### ISSUE TITLE
Django work meta ticket

### ISSUE THREAD

**Issue by Pomax** [mozilla/network#10]
- [Pick X  concrete examples/user stories](https://github.com/mozilla/network/issues/9)
- [Interview current admin users](https://github.com/mozilla/network/issues/11)
- [Check in with MoCo (pmac, tasos)](https://github.com/mozilla/network/issues/13)
- [Research django interface(s)](https://github.com/mozilla/network/issues/12)

**Comment by xmatthewx** [comment]
Please see my comment here: https://github.com/mozilla/network/issues/9#issuecomment-271761646

**Comment by Pomax** [comment]
Apologies for creating the wrong impression: as work around specifically the "clubs" notion that MLN shares with MoCo we needed a place to do some initial work. This is probably not the ideal place, but seems to be the "best" place that we currently have available, without creating a new repo for work that doesn't have any source code associated with it...  we'll be looking at what a more appropriate location for tracking this work is, but the main goal was to get issues written out first so that we could move forward on this.

**Comment by xmatthewx** [comment]
No problem whatsoever. Sorry if my message was curt ... I'm on a crazy schedule here, but I wanted to make sure that people didn't do unnecessary work. This makes sense now. Feel free to use this repo if useful. If you do, maybe we can have a label such as clubs or organizing or infrastructure.

**Comment by kristinashu** [comment]
Cool cool, I've added a "clubs" label to the tickets.

**Comment by kristinashu** [comment]
We have a repo! Moving this over there https://github.com/mozilla/missy-elephant/issues/6
