### ISSUE TITLE
People Partnership logos

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#100]
People page has profiles. Some profiles get a partnership logo. This is different than simple org affiliation. 

@ldecoursy - can us verify which people should get which logos? 

Should we just look to see if a person's org affiliation appears in the [partner list in the spreadsheet](https://docs.google.com/spreadsheets/d/1rwNFjojmnOHkctAIAin9Pd_rxziscGJBSWi-z2S6Bg4/edit#gid=1867971227)? 

 - A person gets a organization logo when they are affiliated with an org that is considered a partner
 - A person doesn't get a logo when they work somewhere that isn't considered a partner
 - A person has zero OR one partner logos. Not two or more.

relates to https://github.com/mozilla/network/issues/33

@hannahkane @sabrinang @taisdesouzalessa @gvn

**Comment by ldecoursy** [comment]
I'd add logos for folks on the "partners" tab here; https://docs.google.com/spreadsheets/d/1rwNFjojmnOHkctAIAin9Pd_rxziscGJBSWi-z2S6Bg4/edit#gid=866621792

Might want @chrislarry33 final approval on that list, though.

**Comment by sabrinang** [comment]
@ldecoursy I started collecting many here: https://drive.google.com/drive/folders/0B4Q8pzCpDS_eUkVRREU3RmlwNlk but many of them I could not find svg versions for and it would be great if you are able to find vector format logos

**Comment by xmatthewx** [comment]
Chatted with @ldecoursy. Here's the scoop: 

 - People in the spreadsheet get a profile when their name is highlighted _bright_ green. True across tabs.
 - People on `Partners` tab also get a logo, BUT only when the new logo column is highlight bright green too. 
 - The Partner list for logos tab will _not_ be put to use right now. Funders from bottom of this tab might appear on About page, but this is TBD by @ldecoursy. 

@sabrinang – I think you can pause your search.

**Comment by gvn** [comment]
@alanmoo FYI ^

**Comment by xmatthewx** [comment]
@sabrinang – we have confirmed people who will get a partner logo on their profile. This is on the Partners tab only. I'm going to assign this ticket to you to gather these logos. This is important, but shouldn't bump your other priorities. 

Let's go for easy wins. Flag hard to find logos in the spreadsheet. Let's get 75% of these. Don't run in circles trying to get 100%. We can gather more post-launch.

**Comment by sabrinang** [comment]
Confirmed partner logos collected here: https://drive.google.com/drive/folders/0B4Q8pzCpDS_ea3NFV1lJVmctaVE?usp=sharing

I collected all the logos but some are .pngs and would prefer .svgs (I'll flag this on spreadsheet)

**Comment by xmatthewx** [comment]
This is done and done. Yay.
