### ISSUE TITLE
Home Page Iteration - merging tickets

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#104]
This is the iteration of the home page that surfaced as a result of tickets #91 and #92.

ACTION ITEMS for "People" and "Projects" components:

- @sabrinang to further explore image approaches, considering the following guidelines:
    - don't develop artwork that is too generic
    - design in an easy way to swap images as needed
    - keep bg neutral so it is dependent on what photo/logo we choose

- Taís to design structure of mobile component and polish desktop component in terms of spacing.

@xmatthewx for this new home page iteration we need Kevin's help in a creating a compelling copy for those new components (please note we will have "Lorem Ipsum" in the "Opportunities" component

cc: @hannahkane @gvn

**Comment by taisdesouzalessa** [comment]
Prototype of new iteration (integrated with the rest of screens):

https://invis.io/ZJ9YTAGEA#/216715355_Home-Page-Opt1

**Comment by taisdesouzalessa** [comment]
Prototype of the mobile version of the new iteration:
https://invis.io/ZKAIKN1MN#/220168109_MOBILE-HomePage

**Comment by sabrinang** [comment]
**Iteration on collage options and tints:**
People Grey Tint/Diagonals
![collages-people](https://cloud.githubusercontent.com/assets/2492510/23679411/b710f90c-033c-11e7-9759-b92798fcec2e.jpg)
People Purple Tint/Diagonals
![collages-people-2](https://cloud.githubusercontent.com/assets/2492510/23679412/b711074e-033c-11e7-8c61-6ebd2f7600e5.jpg)
Project Grey Tint/Circles with subtle Diagonals
![collages-project](https://cloud.githubusercontent.com/assets/2492510/23679414/b7162f58-033c-11e7-9d15-c46e1b56b1f6.jpg)
Project Purple Tint/Circles
![collages-project-2](https://cloud.githubusercontent.com/assets/2492510/23679413/b715c8f6-033c-11e7-9a1c-5bf46bcf330c.png)

**In context: **
<img width="1276" alt="screen shot 2017-03-07 at 1 53 12 pm" src="https://cloud.githubusercontent.com/assets/2492510/23679672/766403da-033d-11e7-8a89-2807ef55e37b.png">

@taisdesouzalessa @xmatthewx I like the grey option as it is more neutral but would love to hear your feedback on collage format etc.

**Comment by xmatthewx** [comment]
Neat! Two boxes, similar but contrasting. 

Do we need the gray? Does it help even the photos out and recede?  

I also prefer the gray over purple. And... I'm curious what it would look like if there was a few different filter colors applied to different people and projects. orangish, purplish, etc. might be totally ugly, but could become fun like candy. 

Either way, I think we're close.

**Comment by xmatthewx** [comment]
@KevZawacki – We've moved people and projects up to the top of the homepage. I think the copy in these two boxes is good. Would you adjust anything?

I wonder if we should say Diverse members, one ~~mission~~ movement. To signal network rather than organization.

**Comment by taisdesouzalessa** [comment]
Those look so nice! I think the grey looks better because it gives the feeling of realism and honesty (these are real people, not people from an image bank), which I think it is important for this project. Although the way you used purple was very nice because it still feels realistic.

I find the diagonal treatment stronger due to the connection with the rest of the site. I also like the idea of filter with colors or even different opacity treatment for different people. It may look a little busy so maybe removing the gaps between the diagonal frames?

**Comment by hannahkane** [comment]
Suggested copy to replace the Lorem Ipsum in the Opportunities section:

Under Fellowships: "At Mozilla, we’re committed to providing research funding, mentorship, and project-based learning opportunities for community leaders."

Under Trainings: "Learn the basics of participation, collaboration, and sharing on community-driven projects. Discover what working open can do for your project, and explore open projects from across the Network."

**Comment by taisdesouzalessa** [comment]
Thanks @hannahkane! Is there any way to reduce the number of characters for Training? It almost fits but ideally it would have more or less the number of characters as Fellowships. If not possible, no problem. Here is a screenshot:
<img width="504" alt="screen shot 2017-03-07 at 5 01 24 pm" src="https://cloud.githubusercontent.com/assets/22157921/23685287/2180fb1e-0358-11e7-9435-d0a0828e6623.png">

**Comment by hannahkane** [comment]
Probably fine to cut the last clause. So, "Learn the basics of participation, collaboration, and sharing on community-driven projects. Discover what working open can do for your project."

**Comment by KevZawacki** [comment]
@xmatthewx I like the look of 'People' moved up!

I prefer "mission" over "movement," but am OK with changing if you feel strongly.

Only other copy edit: removing "awesome." 
So perhaps just: "Meet and connect with Network members."

**Comment by sabrinang** [comment]
Color treatment exploration and reducing spacing on diagonal collage:
![mozilla-network_people-13](https://cloud.githubusercontent.com/assets/2492510/23730489/81cdd266-041c-11e7-8fb8-1a508b6beae5.jpg)
![mozilla-network_projects-14](https://cloud.githubusercontent.com/assets/2492510/23730492/834b5b0e-041c-11e7-9b08-e809797a7db6.jpg)

In context:
![colour-experiment](https://cloud.githubusercontent.com/assets/2492510/23730502/8c473246-041c-11e7-9389-1047b2ce8cf8.jpg)

I don't think it is quite resolved but let me know what you think so far

**Comment by taisdesouzalessa** [comment]
Here is the mockup with the latest copy edits:
https://invis.io/ZJ9YTAGEA#/216715355_Home-Page-Opt1

2 things:
- In the first card "Diverse members, one..." - are we using "mission" or "movement"?
- In the "Other opportunities" section, the CTAs were written by myself. It would be cool if @KevZawacki could take a look at them and see if he thinks they are strong enough and help us with our story, open to any suggestions there.

cc: @xmatthewx @hannahkane

**Comment by xmatthewx** [comment]
@sabrinang – I think I like the mix of color for the people box. Feels less necessary for projects, but maybe good for consistency. What do you think? Should we try a slight opacity on the white box? Good idea, bad idea?

**Comment by xmatthewx** [comment]
@taisdesouzalessa 
 - Kevin says mission, let's go with mission. 
 - Your copy in Leadership Training looks good to me. Fellowships should sound epic. @KevZawacki can help. Or @hannahkane could as she works with team on that page.

**Comment by hannahkane** [comment]
@xmatthewx - not exactly sure what you mean by epic. "Opportunity of a lifetime"? "Go on a journey with us"? "Join our elite corps of Fellows"? I'm guessing those aren't what you mean. :)

How about something a little more descriptive:
We provide research funding, mentorship, and project-based learning opportunities to members working at the intersection of media, science, security, advocacy, and technology.

**Comment by xmatthewx** [comment]
When I read [bios on fellows and their work](https://advocacy.mozilla.org/en-US/open-web-fellows/fellows2016), I see game-changing impact. Fellowship can change their lives and lives of others. I think our description is accurate, but not evocative enough. 

Our prior cohorts might have been a fresh college grad looking for learning opportunities, but (unless I'm mistaken) our current and future cohorts are professionals with big aspiration. I think this is one place where our inclusiveness doesn't emphasize people very early on their professional arc.

**Comment by hannahkane** [comment]
Slight tweak: We provide funding and exciting project-based opportunities to professionals doing game-changing work at the intersection of media, science, security, advocacy, and technology.

**Comment by taisdesouzalessa** [comment]
Home Page has 4 iterations:

1. [Mockup - form in the homepage](https://invis.io/ZJ9YTAGEA#/222853316_Home_Page-V1a)
2. [Mockup - small CTA](https://invis.io/ZJ9YTAGEA#/222853318_Home_Page-V2a)
3. [Mockup - form in the homepage/news in the middle](https://invis.io/ZJ9YTAGEA#/222853317_Home_Page-V1b)
4. [Mockup - small CTA/news in the middle](https://invis.io/ZJ9YTAGEA#/222853319_Home_Page-V2b)

Decision on which one to use is being discussed at #71

**Comment by taisdesouzalessa** [comment]
This is the home page we agreed on:
https://invis.io/ZJ9YTAGEA#/216715355_Home-Page-Opt1

@xmatthewx I discussed the copy in the newsletter box with Hannah following your guidelines and we have this copy as final. What do you think?

Stay Connected
Sign up to receive updates with action opportunities and news from across the network.

Thanks for your word crafting, @hannahkane 

It is ready to build @gvn and @alanmoo. I'll update it in Google Drive shortly. 

cc: @sabrinang

**Comment by taisdesouzalessa** [comment]
Closing this ticket. Discussion for this page is in #141.
