### ISSUE TITLE
Revise Nav and Page framing 

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#106]
We will make a few adjustments to Nav and the way we frame pages based on feedback on the site. 

Steps: 
 1. [ ] Connect with @KevZawacki @hannahkane and maybe @HPaulJohnson to validate plan below 
 2. [ ] Revise copy where needed
 3. [ ] Update comps
 4. [ ] File implementation tickets

 - Home
   - People rise up! Projects too. Offerings relabel --> Opportunities, move down below. 
   - Hero statement: Do we want to iterate on this? Add more fire, urgency? I still like We are Champions. Subhead could evolve to something like: A network of diverse leaders, a movement to tackle critical issues central to the internet. 
 - People 
    - Frame it as a member spotlight. Clarify ambiguity: not all members land here.
 - Programs relabel --> Support
   - Frame this as Mozilla's support for the network
   - In the future: We can examine this page as a single home for Offerings/Upcoming. But that will take some work. Too much for launch. 
 - Projects
   - In the future: We will look at dialing up the Issues and Topics (IoT) as a doorway into Pulse.
   - There's a suggestion to call this Activities to be more inclusive/representative of the variety in Pulse. I'm unsure. Inclined to stick with Projects for now. I think it better fits the goal: invite collaboration from potential leaders.  
 - Campaigns --> REMOVE page. 
   - In the future: Can come back later if needed. Campaign stuff will appear in Pulse and in the News.
 - Upcoming
   - In the future: we will examine this merged with offerings on the support page. Will need to wait to post launch.
 - About
   - Add Issues and Topics (IoT). Useful to keep People/Projects/Support/~~Campaign~~? 

@hannahkane - this single meta ticket seemed like the best place to start with @KevZawacki and @HPaulJohnson. Feel free to migrate toward #95 or individual tickets.

cc @Lottarao

**Comment by hannahkane** [comment]
What do you all think of using a [Google doc](https://docs.google.com/document/d/1-oG6aZJYau7UsKVv76WdKVjWDWg7ffpP9hsKlFTWsYI/edit) to have this discussion asynchronously? @xmatthewx @KevZawacki @HPaulJohnson

**Comment by xmatthewx** [comment]
Good idea. Can we set a deadline? Thurs end of day or Friday noon PT? Then we can decide if we need to meet to finalize things.  Kevin and Paul, I have no idea what your schedules look like these days. We can follow your lead.

**Comment by hannahkane** [comment]
I added a bunch of comments to [the doc](https://docs.google.com/document/d/1-oG6aZJYau7UsKVv76WdKVjWDWg7ffpP9hsKlFTWsYI/edit#) I started. Hope it's useful for @KevZawacki and @HPaulJohnson.

**Comment by HPaulJohnson** [comment]
I can do it by Thursday end of day. Always helpful to have a deadline!

**Comment by KevZawacki** [comment]
Works for me. Reviewing the Google Doc now.

**Comment by hannahkane** [comment]
Closing this ticket, as everything has been ticketed individually.
