### ISSUE TITLE
Add icons to News items

### ISSUE THREAD

**Issue by gvn** [mozilla/network#108]
- [x] Source all icons for current news (SVG or PNG is best)
- [x] Add icons to build

**Comment by sabrinang** [comment]
news media .svg icons are exported to gdrive in this folder: https://drive.google.com/drive/folders/0B4Q8pzCpDS_eSk4xYV80MTZxNk0

**Comment by sabrinang** [comment]
all icons are updated on news with the CMS and are on staging
