### ISSUE TITLE
Implement Fellowships opportunity landing page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/network#111]
Content is [here](https://docs.google.com/document/d/1TPs2OKTtow4rVj8R8n0Lqy7tlP4Q18h3vTMBG6j4yoM/edit#bookmark=id.yo3a3bno0bql). Layout/design should be based on the comparable Internet Health Report landing page.

 - [ ] Mockup
 - [ ] Build

**Comment by hannahkane** [comment]
@gvn @alanmoo @taisdesouzalessa @sabrinang — do you think we need a mockup of this page before we can build it? It should be similar to the Internet Health Report page (#109), but with different copy.

If so, who should I assign this ticket to— @sabrinang or @taisdesouzalessa?

**Comment by gvn** [comment]
I can take a shot at it without a comp.

**Comment by taisdesouzalessa** [comment]
@gvn let me know if you have any questions or need any design support/assets for that.

**Comment by hannahkane** [comment]
Upon further reflection, I think we probably should do a mockup first. There might be some visual distinctions between this page and the Internet Health Report, plus we'll need to identify an image.

**Comment by taisdesouzalessa** [comment]
I will do those mockups, @gvn. It will be straightforward, I think.

**Comment by taisdesouzalessa** [comment]
@hannahkane here is the mockup:

https://invis.io/ZJ9YTAGEA#/222644514_Landing-Page-Fellowships

2 things:
- I couldn't find the logos that will go into the blue box placeholder. Who should I connect with to get the names of the companies or the logos themselves?
- I find the copy is a bit long. If we could reduce it a bit it may be easier to digest. One thing to keep in mind is that we already have some copy in the home page (blurb for the featured item) and that already starts telling the story. Unless the intention is to also send users straight to this page (in which case they will need more context). 

cc: @xmatthewx @sabrinang

**Comment by hannahkane** [comment]
Thanks, @taisdesouzalessa. I'm hoping @auremoser can provide the logos (Aurelia - let me know if I can help gather them). 

It is a little long, but I'm not sure it's too long. @auremoser - what do you think? I could make some suggestions for how to cut it down a bit, without losing any of the important messaging.

**Comment by auremoser** [comment]
I've made a [dropbox here](https://www.dropbox.com/sh/e636nu077yzfl6c/AAB1K-zDi41KYJfTL3xHAJ3Sa?dl=0) with logos! We don't have host organizations at the Science Lab, but I included the Science Lab logo and some partner orgs for the current advocacy fellows.

Please add additional logos @vanessarhinesmith @stephwright  if there are others that we want to highlight in this section of the MLN site (see Taís' [mockup](https://projects.invisionapp.com/share/ZJ9YTAGEA#/screens/222644514_Landing-Page-Fellowships), screenshotted below), we should probably pick 5 or so given the space constraints.

![screen shot 2017-03-08 at 11 16 18 pm](https://cloud.githubusercontent.com/assets/1559703/23735377/4764d4d0-0453-11e7-8fc3-26aa9baa328e.png)

@taisdesouzalessa, for brevity, you might cut:
* The first sentence "A healthy open web community..."
* The first sentence after "Get Involved!"

If that's not enough let me know and I'll cut more.
Thanks!

**Comment by xmatthewx** [comment]
I posted some comments on copy in invision. Some suggestions on bits that could be cut to shorten it overall. Yay fellowships!!

**Comment by sabrinang** [comment]
I mocked up how the logos would look like in between the copy but I was wondering about the phrasing “Here are some of our supporting organizations” paired with showing the Mozilla Science Lab logo (shouldn’t it just be Mozilla if we are showing organizations?) and +1 to removing the sentence before this since mentioning institutional affiliations and showing something from Mozilla seemed odd as well. Logos ordered alphabetically. 

**Left example:** shows logo without Mozilla science lab 
**Right example:** includes Mozilla science lab but I have updated it with new branding to match the site.


<img width="1213" alt="screen shot 2017-03-09 at 3 23 36 pm" src="https://cloud.githubusercontent.com/assets/2492510/23775219/74f936be-04dc-11e7-9fc5-918a60efd861.png">

**Comment by hannahkane** [comment]
No strong opinion on this. I think it's fine to present the Science Lab as "a supporting org"—in this case, specifying the particular branch of the org adds some useful detail. Thanks for the work on updating the branding!

**Comment by hannahkane** [comment]
@taisdesouzalessa or @sabrinang - could you please incorporate Matthew's copy updates from the Invision comments? Then I think we're basically done with this.

**Comment by sabrinang** [comment]
Mockup text updated: https://invis.io/ZJ9YTAGEA#/222644514_Landing-Page-Fellowships

Updates made:
- simplified to "...about the fellows!"
- updated to ”Read more about our current cohorts advancing open data and the open web."
- removed “Fellows maintain either an institutional affiliation of their choosing or are matched with a host organization aligned with Mozilla’s Mission.”
- removed “Our fellowships are designed with variety and flexibility in mind, so the focus area, structure, and location of a fellowship customize on a per-fellow basis. ”
- removed the first sentence "A healthy open web community..." (based on https://github.com/mozilla/network/issues/111#issuecomment-285248662)

**Comment by stephwright** [comment]
Thanks @sabrinang for updating our logo for the new Mozilla branding!  Can we have a hack at it to finesse a bit more as this version loses some of the flow of the logo and identifies a bit more as three separate fonts / items / pieces: image, mozilla logo, words "science lab".  This hadn't made it onto our "to do" list yet but with the launch of the site, we need to jump on that. :)

**Comment by xmatthewx** [comment]
If we use the Science logo, let's use the same one as on the Science site. 

We shouldn't update things to the new brand until we're ready to do that across the board. We don't yet know if/how a graphic can be part of a logo in the new brand.

**Comment by taisdesouzalessa** [comment]
Reopening this issue as it needs some discussion about the copy.

@hannahkane based on your feedback in [InVision](https://invis.io/ZJ9YTAGEA#/222644514_Landing-Page-Fellowships) I have another iteration with the copy:

What if we move the "Get involved" to the CTA box as well?
Mockup: https://invis.io/ZJ9YTAGEA#/223328891_Landing-Page-Fellowships-V2

Let me know what you think and if you agree with the new proposal I can stitch it in the main prototype.

**Comment by taisdesouzalessa** [comment]
Here is the page with the latest revisions:

https://invis.io/ZJ9YTAGEA#/222644514_Landing-Page-Fellowships

Mockup and Sketch files will be updated to reflect change. Closing this issue.

**Comment by sabrinang** [comment]
image for updated logos (with previous science lab branding) here: https://drive.google.com/file/d/0B4Q8pzCpDS_eblphY3BTNEpxaWs/view

![fellowship-partners](https://cloud.githubusercontent.com/assets/2492510/23920545/62141eb2-08b8-11e7-8f7f-50e3d9919d81.jpg)
