### ISSUE TITLE
Image Permissions for Network Site

### ISSUE THREAD

**Issue by sabrinang** [mozilla/network#113]
I collected many photos from various flickr albums or blogs by staff and have used them on the site mainly on the programs and upcoming pages:
![image-in-context2](https://cloud.githubusercontent.com/assets/2492510/23814648/2cf41204-0599-11e7-8cfa-dd7ae8eb8029.jpg)

I made a spreadsheet: https://docs.google.com/a/mozilla.com/spreadsheets/d/1bf9S128z1BkHoHH1MDGj_bZvn1h7Ts1I8SG7BHrvRgk/edit?usp=sharing  to document these images and what I need approval on and  from which individual. Please see the **Approval** column and change it to Yes or No.

Reviewers:
@ldecoursy  
@jenntbeard 
@LauraReynal 
@edrushka 
@vanessarhinesmith 
@KevZawacki

**Comment by edrushka** [comment]
Done! Thanks for checking.

**Comment by jenntbeard** [comment]
Also done, although I made a comment in the sheet. Thank you!

--
Jenn Beard
Gigabit Fund Manager
Mozilla Learning Network
@jenntbeard

**Comment by KevZawacki** [comment]
Thanks, @sabrinang. Updated -- all OK.

**Comment by LauraReynal** [comment]
Thanks Sabrina, one is okay and one is no longer okay. I need to remove some from  Flickr 
Thank you for checking

**Comment by sabrinang** [comment]
Thanks for letting me know @LauraReynal I will not use that photo.

@amirad Is it okay to use your photo https://www.flickr.com/photos/amirad/26515914253/in/album-72157666127395174/ for the Women and Web Literacy thumbnail?
<img width="879" alt="screen shot 2017-03-10 at 1 46 22 pm" src="https://cloud.githubusercontent.com/assets/2492510/23814448/6ac15778-0598-11e7-9671-22f07b91322a.png">

**Comment by amirad** [comment]
Yes, definitely okay @sabrinang

**Comment by xmatthewx** [comment]
This is done.
