### ISSUE TITLE
Add funder logos to About page  

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#114]
@ldecoursy created a list with Jessie Keating (github?) of funders. We will add these logos to the bottom of the about page

Page divider Heading: "Network Supporters" 

 - [x] Alfred P. Sloan Foundation
 - [x] The Helmsley Charitable Trust
 - [x] Ford Foundation
 - [x] National Science Foundation
 - [x] Knight Foundation
 - [x] MacArthur Foundation
 - [x] Open Society Foundations
 - [x] Open Tech Fund
 - [x] Ontario Trillium Foundation
 - [x] C.S. Mott Foundation
 - [x] Institute for Museum and Library Services
 - [x] Susan Crowne Exchange
 - [x] Canadian Internet Registration Authority
 - [x] Chicago Community Trust
 - [x] New York Community Trust
 - [x] The Rockefeller Foundation
 - [x] Siegel Family Endowment
 - [x] Robert R. McCormick Foundation
 - [x] Illinois Science & Energy Foundation
 - [x] Altman Foundation
 - [x] UN Women
 - [x] Irvine Foundation
 - [x] Bill and Melinda Gates Foundation

**Comment by xmatthewx** [comment]
@sabrinang – let's write preferred filetypes and requirements. @ldecoursy can ask Jessie to contact foundations, or maybe get support from Amanda to grab these from the org sits. 

 - Preferred: SVG file
 - PNG or JPG that is at least ___px across. 

Let's mockup page with dividing header "Network Supporters". Include 3-4 logos to convey preferred size to devs. This should happen after your priority projects. Minimal effort. And, let's please not worry about a mockup with all the logos. We have more critical work on our plate. We can make it more attractive if needed after launch.

**Comment by sabrinang** [comment]
Preferred vector files: SVG (EPS is ok if it is available)
If we only have raster files: PNG or JPG that is at least 900px across.

"Network Supporters" Heading and Logos example:
![about-with-funders-example](https://cloud.githubusercontent.com/assets/2492510/23767685/5429cbc4-04be-11e7-8bad-33a20a91c98b.jpg)

**Comment by xmatthewx** [comment]
@ldecoursy @hannahkane – can I trouble you to help nudge this along. thanks! it would be great to land these this week if possible.

**Comment by hannahkane** [comment]
@ldecoursy - let me know how I can help.

**Comment by ldecoursy** [comment]
@xmatthewx Can you clarify if you need them all or just the ones not yet included in the mockup?

**Comment by ldecoursy** [comment]
Adding logo links in this spreadsheet: https://docs.google.com/spreadsheets/d/1rwNFjojmnOHkctAIAin9Pd_rxziscGJBSWi-z2S6Bg4/edit#gid=1867971227

**Comment by xmatthewx** [comment]
@sabrinang if you could check on this. See column H. We probably can't implement this week, but would be good to start populating the prototype.

**Comment by sabrinang** [comment]
@xmatthewx I've added logos from spreadsheet with others and exported them to .jpegs on gdrive here: https://drive.google.com/open?id=0B4Q8pzCpDS_eWHpjdUl0NDJDWDA

Here is a mockup of network supporter logos (with 16px margin each side to give more space between logos):
![about with partner logos](https://cloud.githubusercontent.com/assets/2492510/24431372/59f4ccc2-13d0-11e7-93ef-75f093e6239a.jpg)

**Comment by mmmavis** [comment]
@sabrinang just wanted to double check and see if it was intentional for each big section to have different width. I'm also wondering if there's a Sketch file that I can use as reference?

**Comment by sabrinang** [comment]
@mmmavis Here is the updated page:
![about](https://cloud.githubusercontent.com/assets/2492510/24684278/a4363b16-1959-11e7-8f96-4e9704e82c4b.jpg)

Is it okay if the logos 4 across break the grid?
<img width="995" alt="image" src="https://cloud.githubusercontent.com/assets/2492510/24684284/acde49b6-1959-11e7-8e4c-1f7cbdac99d6.png">

Sketch file has the about screen here: https://drive.google.com/open?id=0B4Q8pzCpDS_eMHVrZXl2VE4yU28

**Comment by mmmavis** [comment]
Hi @ldecoursy I can't seem to find the list of urls to these funders' sites anywhere. Do we just add logos in or we want to also make them hyperlinks? If collecting URLs take time I can add logos to the About page first for now.

**Comment by ldecoursy** [comment]
HI @mmmavis I didn't collect URLs to the funder websites, but Jessie might have that handy (not sure if she's on github).

**Comment by xmatthewx** [comment]
No need for URLs. Let's just run with the logos themselves for now.
