### ISSUE TITLE
Updates to Programs (now Support) page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/network#116]
Rename this page "Support"

Copy edits to hero:

Fellowships, Research and More

Mozilla offers a variety of programs to support network members. Fellowships empowering civic technologists. Laboratories studying emerging tech. Grants supporting web literacy.

 - [x] Update prototype
 - [ ] Update nav label on staging
 - [ ] Update header at top of page, update page copy on staging
 - [ ] Update URL

**Comment by taisdesouzalessa** [comment]
Updated prototype [here](https://invis.io/ZJ9YTAGEA#/216715364_Support).

**Comment by hannahkane** [comment]
Perfect. 

@gvn - I think this is ready for you now. Could be done in conjunction with adding the links in https://github.com/mozilla/network/issues/30#issuecomment-284542996

**Comment by taisdesouzalessa** [comment]
@gvn the new Updated Sketch file is in your dev folder and now it is called "all-desktop-screens.sketch" - please note that some of the pages (like home page - Join the Movement form) are still being discussed and are not 100% final yet.
