### ISSUE TITLE
Images for curated Pulse list

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#117]
Main Pulse ticket:  #38

This ticket is to flag that some of the projects from [this list](https://docs.google.com/spreadsheets/d/1MVOTTxNH4FvyoiBIR--F8HqZYhBvlL2LSKi4XDa1LKo/edit#gid=2088995141) don't have images. Since those are the selected projects for the Network, it would be nice to have images on them to make the page easier to scan.

@xmatthewx

**Comment by sabrinang** [comment]
I can help collect images if needed

**Comment by taisdesouzalessa** [comment]
We had 24 projects from [Kevin's list](https://docs.google.com/a/mozilla.com/spreadsheets/d/1MVOTTxNH4FvyoiBIR--F8HqZYhBvlL2LSKi4XDa1LKo/edit?usp=sharing) but we decided to go only with 9 for this first release (#38) 
@KevZawacki @xmatthewx which 9 ones you would like to feature here? 

@sabrinang will collect images for the Pulse cards that don't have one after those 9 projects are decided.

cc: @hannahkane

**Comment by KevZawacki** [comment]
@taisdesouzalessa Can we do the 9 projects specified [here](https://docs.google.com/spreadsheets/d/1MVOTTxNH4FvyoiBIR--F8HqZYhBvlL2LSKi4XDa1LKo/edit#gid=0), in rows 6, 7 and 8?

**Comment by taisdesouzalessa** [comment]
Prototype updated with 9 projects selected by Kevin: 
https://invis.io/ZJ9YTAGEA#/217251312_Projects-Join-Us-Iteration

@sabrinang there are 6 missing images there.

@xmatthewx Once we have those images, can we update them to Pulse? I could update them but I don't have admin permission.

**Comment by xmatthewx** [comment]
done. handled via pulse.
