### ISSUE TITLE
Research Django interfaces

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network#12]
Do a web search to find popular/viable django interface bolt-ons/etc that make working with Django easier from a user/admin point of view.

Evaluate selected django interface(s) from a UX perspective.

Compare django to wordpress (UI, number of steps to complete a task…)

**Comment by kristinashu** [comment]
We can use the use cases gathered in https://github.com/mozilla/network/issues/9 and see how these might work in django.

**Comment by kristinashu** [comment]
https://getgrav.org/ looks great!

**Comment by Pomax** [comment]
There's also https://www.django-cms.org/en/

**Comment by kristinashu** [comment]
Yes! That's a good looking one.

**Comment by kristinashu** [comment]
Opened in our repo https://github.com/mozilla/missy-elephant/issues/30
