### ISSUE TITLE
Provide CMS training for staff

### ISSUE THREAD

**Issue by hannahkane** [mozilla/network#121]
This might belong in the network-api repo. 

On today's call, I believe we decided to provide a CMS training for staff, perhaps starting with @KevZawacki who will likely be one of the main admins of the site. 

From there, we can learn what works and train other staff admins. @xmatthewx to provide a list of staff members to be trained.

Does this seem like a good plan, @simonwex @taisdesouzalessa @xmatthewx @cadecairos @gideonthomas?

**Comment by alanmoo** [comment]
https://docs.google.com/document/d/1WGWhfUY2mrQQGm-idP137S4CWdcdizL-UXI6DI_2QeU/edit

**Comment by hannahkane** [comment]
Done for now
