### ISSUE TITLE
Changes to About page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/network#130]
Per discussion with @KevZawacki and @xmatthewx, we'd like to make the following content changes.

* Keep intro paragraphs as they are (From "We're building a movement" through to "Now, more than ever, we need a network."
* Replace "The Mozilla Network operates on four levels" section with a section highlighting the five issue areas. 

Section title can be: "The Mozilla Network has identified five Internet health markers:"

And the content can be:

Open Innovation: “Open” means that anyone can publish or invent online without asking for permission, and that the technologies used to run the Web are transparent and understandable.

Digital Inclusion: Everyone deserves equal opportunity to access the Internet, and to use it to improve their lives and societies.

Decentralization: Decentralization means the Internet is controlled by many. It’s millions of devices linked together in an open network. No one actor can own it, control it, or switch it off for everyone.

Privacy and Security: The safety and security of the Internet impacts us all. We should be able to understand what is happening to our data, and have the ability to control how it is used.

Web Literacy: We need everyone to have the skills to read, write and participate in the digital world, so more people can move beyond consuming to actually creating, shaping and defending the Web.

* We can use @flukeout's [illustrations](https://docs.google.com/presentation/d/1oMVDEgzvP919_W3oJiXqZyyXCVxSRl0O1rIro9LRYCA/edit#slide=id.g1ac2e8ecd4_0_37) to accompany the issue area descriptions.

**Comment by hannahkane** [comment]
@taisdesouzalessa and @sabrinang - let me know if this makes sense, and if one of you can mock this up? Thank you!

**Comment by hannahkane** [comment]
@xmatthewx - can you help clarify the priority of the issue illustrations. I assume we'll need to modify them to make them fit with the tone of the site—is that a pre-launch task?

**Comment by sabrinang** [comment]
@hannahkane @taisdesouzalessa I can mock this up

**Comment by sabrinang** [comment]
@flukeout do you have the .ai files for the issue illustraions?

**Comment by flukeout** [comment]
Images are in [the google drive here](https://drive.google.com/drive/folders/0B_CPRh4f3yyqMU1UdWI3ZUU4dFk?usp=sharing)

**Comment by sabrinang** [comment]
![key-issues-integrated](https://cloud.githubusercontent.com/assets/2492510/23865135/e7a0f4c0-07d1-11e7-988d-b0e05302258c.jpg)

Mockup of update changes:
- updated copy to "The Mozilla Network has identified five Internet health markers:"
- modified illustrations to use colours from new palette

**Comment by hannahkane** [comment]
I think these looks great, @sabrinang!

Since the illustration style is fairly different from anything else we have on the site, I'm going to suggest we don't launch with them, but revisit soon after.

@sabrinang - would you mind doing a version without the illustrations so we can file an implementation ticket for now, along with a ticket to follow up soon on the illustrations.

**Comment by sabrinang** [comment]
updated with copy without key issue illustrations:
![about 2x](https://cloud.githubusercontent.com/assets/2492510/23915968/e365d728-08a7-11e7-888d-968dec46a79d.jpg)

**Comment by hannahkane** [comment]
Thanks, @sabrinang. Closing this ticket, and opening an implementation ticket in #153.
