### ISSUE TITLE
Prep a list of Partner to promote on the site

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#14]
We will want to list key partner orgs. Current thinking is that these will show up alongside the people on the people page. Either way, we'll need to...

 - figure out who we list (fellowship host orgs, advocacy partners, grant partners, ??)
   - let's focus on a dozen or so top quality, and plan to grow more later 
 - how we describe them
 - gather logos, links, and basic info

@ldecoursy – is something you could help wrangle? let's discuss next week. 

@taisdesouzalessa – what info should we display? how is it similar/different from [info on people](https://github.com/mozilla/network/issues/5#issuecomment-270502445)

**Comment by xmatthewx** [comment]
@ldecoursy – is this work done content-wise? or represented in the spreadsheet and our other tickets for the people page?

still an open design question: do we feature partners that aren't attached to an individual? like fellowship host orgs? does this happen on the people page? elsewhere?

**Comment by ldecoursy** [comment]
I think the content is covered in other tix for the people page. 

For partners that aren't attached to an individual, one option might be to have partner logos at the bottom of the Programs page - organizations we work with to make those programs happen...

**Comment by xmatthewx** [comment]
Do we have a list of Partners we'd want to include like this? @ldecoursy Any complexity to flag ? Who could help make this list?

@taisdesouzalessa – let's think about placement, but don't put it before other priorities on your list.
   - profile cards on people page?
   - logos at bottom of  people page? about page? programs page?

**Comment by ldecoursy** [comment]
I think the exec team should weigh-in on that list, maybe ad to agenda for the weekly check-in with them this week. 

Could include:
* OWF hosts
* NetGain partners
* Funding partners
* MozFest partners 
* Others 

Just note some individuals from these orgs will be represented on the People page.

**Comment by xmatthewx** [comment]
Hi Lainie. Can you assign individuals to make a list of partners for each of the categories you listed above? We can start with just a list of names and relationship to the org/network. 

Someone (maybe you?) should also make a list of requirements for when a Partner is/isn't listed on the network site.

**Comment by ldecoursy** [comment]
Just set up a call with you to discuss on Monday. We do have partners represented on the people page, so hoping to get clarity on how else they show up.

**Comment by ldecoursy** [comment]
Per discussion with @xmatthewx I'll compile a list of potential partners for now that we can run by Execs as we figure out next steps.

**Comment by hannahkane** [comment]
Can we close this ticket?

**Comment by xmatthewx** [comment]
Yes. Partner logos on profiles are prepared. Funding partners filed elsewhere.
