### ISSUE TITLE
Home Page - revision

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#141]
Here is the home page for discussion:

Desktop:
https://invis.io/ZJ9YTAGEA#/216715355_Home-Page-Opt1

Mobile:
https://invis.io/ZKAIKN1MN#/220168109_MOBILE-HomePage

**Comment by taisdesouzalessa** [comment]
Home Page Iteration - merging tickets #104

**Comment by hannahkane** [comment]
I have no comments on design, because I think it looks awesome.

I just filed a ticket with a [copy change to the tagline](https://github.com/mozilla/network/issues/138). Would be quick to edit that in the prototype as well.

**Comment by taisdesouzalessa** [comment]
IMPORTANT: @gvn @alanmoo - for implementation, please notice that we removed the title "Other Opportunities" ("Get Involved" section) for the mobile version only. With it, the section feel fragmented on mobile and we want to avoid that.

**Comment by sabrinang** [comment]
People and Project collages exported here: https://drive.google.com/drive/folders/0B4Q8pzCpDS_edXF6SFNBNUg3bDQ?usp=sharing
