### ISSUE TITLE
Create a 404 page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/network#143]
Post-launch, let's add a custom 404 page.

**Comment by AkshayGulhane** [comment]
@hannahkane can I pick this up? I would like to contribute! :)

**Comment by hannahkane** [comment]
Hi @AkshayGulhane - thanks so much for your interest! We're not quite ready for contributors yet on this project. Please feel free to check with us soon though! 👍

**Comment by sabrinang** [comment]
Iteration Overview
<img width="1417" alt="image" src="https://cloud.githubusercontent.com/assets/2492510/25250339/102099e4-25ca-11e7-9332-418eb2f91479.png">

Experimenting with emoji illustrations and various layout/copy options to include link back to home or contact us.
![error 404 - iteration 1](https://cloud.githubusercontent.com/assets/2492510/25250366/391dfec2-25ca-11e7-9e69-f3bdf136ae43.jpg)
![error 404 - iteration 2](https://cloud.githubusercontent.com/assets/2492510/25250367/39225206-25ca-11e7-8413-a075a1b74e7a.jpg)
![error 404 - iteration 3](https://cloud.githubusercontent.com/assets/2492510/25250368/39290862-25ca-11e7-8ca2-04d7bb040dd7.jpg)
![error 404 - iteration 4](https://cloud.githubusercontent.com/assets/2492510/25250369/392a96d2-25ca-11e7-84e4-9c03aece8c81.jpg)

@xmatthewx @taisdesouzalessa feedback?

**Comment by xmatthewx** [comment]
this is amazing. i love the first and second one. the 3d motion lines are incredible.

**Comment by xmatthewx** [comment]
you should post this to slack and wake. 

let's remove the page title at the top.

**Comment by taisdesouzalessa** [comment]
@sabrinang - I love those, great job on them! I think the message on the left works best because it is the first thing users should read (options #1 and #2). About the emoji I was wondering if we could have something in between? Not smiling because people are not happy when they find a 404 but also not as heavy as the one with cross eyes . Maybe a sad emoji? Or one that looks lost?

**Comment by xmatthewx** [comment]
@taisdesouzalessa - you could pick this up while Sabrina is away. It's not top priority, but good to nudge along if you have a bit of free time.

**Comment by xmatthewx** [comment]
We estimated just for design. Almost done. Let's reestimate to include engineering.

**Comment by taisdesouzalessa** [comment]
@xmatthewx - sure I can pick this up. Did Sabrina leave you the path of the source files? I can't find them in Google Drive...

**Comment by taisdesouzalessa** [comment]
Talked to Sabrina in Slack and we don't have the source files in Google Drive (they are in her old computer, which is not with her at the moment). We should wait for her to come back to continue this task.

**Comment by xmatthewx** [comment]
@cadecairos says:

 > Since this site is hosted on S3, we can define a page to return on 404s. right now I just have it returning index.html but if we can generate an error.html or something similar I can instruct S3 to use that when we get a request for non-existent resources.

**Comment by sabrinang** [comment]
<img width="1434" alt="copy and emoji iteration" src="https://cloud.githubusercontent.com/assets/2492510/25830074/4d22625c-340f-11e7-94ff-41961c7df26f.png">

Continued iterating on the left aligned text layout with new emoticon + copy pairings.

**Comment by sabrinang** [comment]
@xmatthewx Design reivew?

**Comment by xmatthewx** [comment]
Looks good. Let's go with iteration 7, in color. Copy: 

Uh oh!
Sorry, the page does not exist. 
Contact us or...
`Go to Home Page`

**Comment by sabrinang** [comment]
Updated copy:
<img width="954" alt="error 404" src="https://cloud.githubusercontent.com/assets/2492510/25925563/37630972-359e-11e7-881d-e46aa212dcf2.png">

svg or png asset exported here: https://drive.google.com/drive/u/1/folders/0B4Q8pzCpDS_eTFNsaVpVZlhiY2M

**Comment by xmatthewx** [comment]
@gvn @alanmoo do you have an idea of how we want to approach this? See Cade's [comment above](https://github.com/mozilla/network/issues/143#issuecomment-297445566).  If so, could we label this as help wanted?

**Comment by alanmoo** [comment]
Yup, should just need an error page generated in this repo, as he suggested.

**Comment by sabrinang** [comment]
Thanks for all the feedback! 👍 Closing this ticket and engineering discussions can be continue on https://github.com/mozilla/network/issues/411
