### ISSUE TITLE
CRM form integration

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#15]
For launch, our email sign-up form will ideally feed directly to our CRM. Other integrations (https://github.com/mozilla/network/issues/8) can be added post-launch. 

Let's gather requirements and insights from our advocacy peers. @gvn @arlissc

**Comment by gvn** [comment]
Does the CRM expose a REST API for us to push data to?

**Comment by arlissc** [comment]
@gvn - looking into this, will update shortly.

**Comment by xmatthewx** [comment]
We will use and reuse a short form (email input only) and a longer form (email + a few bits of info) like name, country/city, issue areas of interest. 

It'd be good have a reusable component for the short version. Maybe the long version too.  It definitely would be good to set one of these up early so we can find hiccups before we get closer to launch.

**Comment by gvn** [comment]
Agreed. Hoping I can get endpoint specs soon.

**Comment by xmatthewx** [comment]
cc @ScottDowne

**Comment by ScottDowne** [comment]
@gvn docs for basket: http://basket.readthedocs.io/

**Comment by alanmoo** [comment]
@gvn what's this blocked by?

**Comment by gvn** [comment]
It may not be if the docs linked above are sufficient. I'll unblock for now...

**Comment by gvn** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1329522

**Comment by alanmoo** [comment]
Temporarily blocked by [hatchet configuration](https://github.com/MozillaFoundation/mofo-devops/issues/467)

**Comment by alanmoo** [comment]
Nevermind, going to be posting directly to Basket

**Comment by alanmoo** [comment]
CRM integration itself is done, just a matter of where it's being used. Currently works in the (not yet completely designed?) join us component.
