### ISSUE TITLE
People content issues

### ISSUE THREAD

**Issue by hannahkane** [mozilla/network#150]
The people spreadsheet is in pretty good shape, but needs another round of editing to address the following issues. I added a column "In Django / Notes" which details specifics, but here's a summary:
 - [x] Need to decide what kind of links to allow. Most people offered Twitter and/or LinkedIn, and I suggest we limit links to those two cases. Allowing add'l link types presents some design challenges, and, as I understand it, the purpose is to allow users to connect with one another, not to, for example, show portfolios.
 - [x] Bios are not consistently written. Most are in 3rd person, but some refer to the person by name ("Joe is a programmer"), while others use a pronoun ("He is a programmer"), and others avoid both ("Is a programmer"). They also vary in style, length, and types of details people choose to share. Maybe this is fine??
 - [x] Bio is currently a required field in the CMS, so I wasn't able to add people who don't have a bio. I suggest we change this on the backend, since the mockups show that bios are only displayed on Featured cards. I'll [file a ticket](https://github.com/mozilla/network-api/issues/51) to change this behavior on the backend.
 - [x] MLN Role is required, so in one case I wasn't able to add someone. I think this field *should* be required, so this needs to be fixed in the spreadsheet.
 - [x] Issue areas are required. In a few cases, they weren't included, so I, um, guessed based on their bio. Noted in the "Django / Notes" field in case anyone wants to follow up. I think this field should stay required.
 - [x] Affiliations are required (title/org), so there were a few people I had to leave out. Not sure they should be required, though. Opinions?
 - [x] A handful of people were marked as green, but the "Approved" column wasn't marked. I erred on the side of *not* including people, to be safe. @ldecoursy and @chrislarry33 to advise.
 - [x] In a couple cases, two quotes were given. I chose the one I liked best (!). Noted in the "Django / Notes" field in case anyone wants to follow up.
 - [x] Jargon / Acronyms. I made a judgement call and changed instances of "OWF" to "Open Web Fellows" and "Science Fellow" to "Mozilla Science Fellow," and changed someone's MLN role from "Web Lit / IMLS" to "Web Literacy Partner." Someone might want to go through more carefully to de-jargon.
 - [x] I noted one instance in the spreadsheet where I found the quote to be missing some context.

**Comment by hannahkane** [comment]
@ldecoursy and @chrislarry33 - I'm "assigning" you both to this ticket in case you want to be responsible for it. I realize you might both be too busy to deal with this, so, if you trust me to, I can just make judgement calls on all of this stuff.

The main thing to know, though, is that a handful of "green" people aren't currently in the database b/c various pieces of data are missing. You can find them by scrolling through the new column I added ("In Django / Notes"). In the case where the bio is missing, that's not a blocker. We just need to make that not a required field on the backend, which we will do soon. But in the other cases, I think we actually are missing some necessary info.

**Comment by ldecoursy** [comment]
Thank you @hannahkane! I just added in the missing affiliations and fixed a few that weren't marked "Approved" although they should have been. I definitely +1 not having bios be a blocker since they were always intended to be optional so we don't have them for everyone (and that's also part of why they were inconsistent). I'm not sure how many featured cards with bios we'll have, but I agree we should come up with standards for tense, length, etc. I think it's more than OK for the bio details to vary, though (and since we didn't define that criteria in advance we probably can't avoid that too much).

**Comment by hannahkane** [comment]
Closing this ticket, because we've addressed many of these things in the spreadsheet itself.

Noting that none of the "MLN Advisory" people are going into the database until I get confirmation or an OK from @chrislarry33.
