### ISSUE TITLE
"Join Us" button in Top Nav should go to /join/

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#155]
Currently our "Join Us" button on Top Nav is linking to the hidden form on the same page
![screen-shot-2017-03-14-at-2 05 52-pm](https://cloud.githubusercontent.com/assets/22157921/23922513/eb1f57ba-08bf-11e7-88b5-69a7f86c18f6.png)

**Steps to reproduce:**

- Go to: https://network.mofostaging.net/

- Click on "Join Us" from the top nav

Note: This happens on all pages.

-----

We would like it go to the standalone page: https://network.mofostaging.net/join/

**Comment by gvn** [comment]
This is a launch blocker?

**Comment by xmatthewx** [comment]
Yes. We have the /join page stubbed out already. Any challenges with this?

**Comment by gvn** [comment]
No, just didn't seem like a P0.
