### ISSUE TITLE
Create high-level user journey

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#16]
Here's a quick whiteboard sketch. Fodder for discussion. 

![user-journey](https://cloud.githubusercontent.com/assets/53411/22088059/84a91da8-ddaf-11e6-8978-47791f986778.jpg)

cc @arlissc @taisdesouzalessa @sabrinang @hpauljohnson

**Comment by taisdesouzalessa** [comment]
Here is the doc with additional info @xmatthewx 
<img width="345" alt="screen shot 2017-01-31 at 1 28 06 pm" src="https://cloud.githubusercontent.com/assets/22157921/22485115/3038d416-e7b9-11e6-87c9-c8d968100046.png">

PDF: userjourney.pdf](https://github.com/mozilla/network/files/743200/20170131132351543.pdf)

**Comment by taisdesouzalessa** [comment]
@xmatthewx here is the simplified user flow. There are some parts that are unclear to me so we should sync to refine it.

![simplified-user-flow](https://cloud.githubusercontent.com/assets/22157921/22613470/75e60a9e-ea2d-11e6-9628-fb74fb4aa127.jpg)

**Comment by xmatthewx** [comment]
This is great. Let's discuss at the end of our next stand up to answer your questions and make a few adjustments.

**Comment by taisdesouzalessa** [comment]
@xmatthewx we could discuss this overall experience when we have a meeting to talk about staff feedback. What do you think?

**Comment by xmatthewx** [comment]
thanks @taisdesouzalessa 

Glad to discuss when we chat about feedback. Let's make a couple of small tweaks and then hand this over to the people working on engagement. They can fill out the details. 

 - We can order the entry points. One end likely for existing members (email). The other end likely for new visitors (search). Doesn't need to be scientific, just a spectrum. I don't think we need hard separation between the two groups or more info.
 - Let's add existing member to the top towards on one side, new visitor towards the other
 - I wonder if we should relabel non-member to Site Visitor
 - Remove Pulse and hubs. These are represented by mozilla site & event/partner
 - Remove the notes, bulleted lists on email/segments/offerings.
 - Next to the Input field /Join us button   let's put text `+ Referrer + Page URL + Feature ID` to indicate info we'll capture.

Again. Glad to discuss when we talk about feedback.

**Comment by arlissc** [comment]
@taisdesouzalessa @xmatthewx - just seeing these documents.  Very helpful.  Would like to understand the operational pieces of the data capture mechanisms for the CRM.

**Comment by xmatthewx** [comment]
Hi @arlissc. I don't understand your question. If this is technical about input from the form, let's discuss with Gavin here: https://github.com/mozilla/network/issues/8 and during the tech weekly call on Tuesdays. Beyond email address, we should be capture referring site, page URL, some sort of id to identify the "campaign" featured to gain members (e.g. Health Report 2016, Fellows Mar 2016, ). You can lookto Vojtech and Paul for how we track those sorts of things. If this is not technical, we're meeting tomorrow to talk with Will and 270 about engagement and email. Maybe we can clarify there.

**Comment by taisdesouzalessa** [comment]
Here is the revised User Journey

![simplified-user-journey-revised-v2](https://cloud.githubusercontent.com/assets/22157921/23286258/5e722276-f9eb-11e6-8781-20a5d12fe8f6.jpg)

@xmatthewx I added the "event/partner" after "email" because in my understanding a person who goes to events or is our partner knows more about us (and it is more active) than a regular e-mail subscriber...let me know if I am missing something here.

**Comment by xmatthewx** [comment]
This is excellent. Thanks! A couple of tiny things, and then i think we can call this done for now. I'll share this at a 1pm PT meeting today. Edits would be good before then, but they aren't critical.

Comments here: https://redpen.io/aea43c500e20d86dae

**Comment by taisdesouzalessa** [comment]
Diagram revised:

![simplified-user-journey-revised-v2](https://cloud.githubusercontent.com/assets/22157921/23316060/c5d32e0a-fa7d-11e6-9f53-c8d7c8b20118.jpg)

**Comment by xmatthewx** [comment]
Thanks again. Let's remove the black dotted lines. They draw too much attention. Let's just point to a duplicate of the site. There's a small audience for this diagram ... they can handle it. One other correction in pink. 

Sorry to ask you to do this. I'm having trouble getting typekit to sync on my new computer, otherwise I wouldn't bother you.

![user-journey-revision](https://cloud.githubusercontent.com/assets/53411/23369933/f404448e-fce0-11e6-86a2-9055b14feff0.png)

**Comment by xmatthewx** [comment]
When done, let's drop in our summary deck here: https://docs.google.com/presentation/d/1nLLNCyp1JtrOdiKlFYoBMOa_VqpXFrbxeYRI5PgwB0A/edit#slide=id.g1cfefcff86_0_0

**Comment by taisdesouzalessa** [comment]
Changes applied and added to the summary deck :). 

Closing this ticket.
