### ISSUE TITLE
Copy changes for Support page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/network#160]
Two suggestions:

Change hero to “Fellowships, Trainings and More” to better match the key CTAs we're promoting throughout the site

Change “Mozilla offers a variety of programs to support network members. Fellowships empowering civic technologists. Laboratories studying emerging tech. Grants supporting web literacy.” to “A variety of programs to support network members. Fellowships empowering civic technologists. Trainings to build leadership capacity. Grants supporting web literacy.” Better matches the voice of the other heros, plus aligns with the change suggested above.

@xmatthewx @KevZawacki - thoughts?

**Comment by xmatthewx** [comment]
@taisdesouzalessa  to update mockup and then assign to engineering.

**Comment by taisdesouzalessa** [comment]
Copy Updated:
<img width="892" alt="screen shot 2017-03-16 at 2 11 18 pm" src="https://cloud.githubusercontent.com/assets/22157921/24018719/53e0d9f2-0a52-11e7-8e07-df99cb2686aa.png">

[Comp here ](https://invis.io/ZJ9YTAGEA#/216715364_Support)
