### ISSUE TITLE
Opportunity Landing Pages: CTA should have a form

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#164]
**Issue:**
Our Opportunity landing Pages on staging don't have a form embedded on the CTA area:

<img width="556" alt="screen shot 2017-03-14 at 3 43 56 pm" src="https://cloud.githubusercontent.com/assets/22157921/23925581/1b72162a-08cd-11e7-9105-743a91e773f3.png">

Here are the links to the pages on staging:
- https://network.mofostaging.net/opportunity/fellowships/
- https://network.mofostaging.net/opportunity/training/
- https://network.mofostaging.net/opportunity/internet-health-report/

**Fix**
Those pages should have a form like in the mockups:
- [Fellowships](https://invis.io/ZJ9YTAGEA#/222644514_Landing-Page-Fellowships)
- [Training](https://invis.io/ZJ9YTAGEA#/222644515_Landing-Page-Leadership-Training)
- [Internet Health Report](https://invis.io/ZJ9YTAGEA#/216715361_Landing_Page_Internet_Health)

**Reason:** we want users to have quick access to the forms from these pages. Our goal is to add as little friction as possible to sign up.

This ticket is mentioned in a bigger one related to forms #156

**Comment by xmatthewx** [comment]
@hannahkane – now that we have stable Sign-up (and a focus on sign up, not join) does this change any Landing Page form copy?

**Comment by alanmoo** [comment]
Are all 3 of these forms adding people to the same mailing list?

**Comment by xmatthewx** [comment]
Yes. It's a single list. The CRM should capture the form's origin page. It would also be ideal to capture an ID for category/interest/campaign, but I'm not sure if that's in the plans now or later (cc @arlissc).

Important to note: We plan to have staff create these simple landing pages via the CMS. Authors should have a toggle to include the form or not, and then a couple fields to add the form header and copy. I believe Gavin had some thoughts on how to compose the component so we could inject these strings. 

Make sense? Any questions?

**Comment by alanmoo** [comment]
I spoke to Scott earlier and the ID isn't something that's baked in to Basket right now, so we're going to have to rely on the URL of the submission page.

The rest makes sense, I'm going to build a component that accepts arguments for the text, and when we integrate a CMS we can utilize that.

**Comment by alanmoo** [comment]
@gvn I'd like to get your thoughts on implementing this today based on the way pages are currently composed.

**Comment by gvn** [comment]
I'm actually gonna grab this for the moment. I think we should work out how to add new opportunity pages via the CMS first, so I'm gonna take a shot at that.

**Comment by alanmoo** [comment]
Linking https://github.com/mozilla/coss/issues/98 for reference, just because there are parallels

**Comment by gvn** [comment]
Blocked by #216

**Comment by gvn** [comment]
To clarify this ticket: This is just for refactoring the Signup React component to work in a half-width layout.

**Comment by xmatthewx** [comment]
Half width, and the ability to inject header and text for this particular page. 

Form elements do not change: placeholder, button label, error text, check box ..all stay the same.

**Comment by alanmoo** [comment]
@taisdesouzalessa I just noticed that the images used on the full join-us page are different than the "Thank you" image used on the smaller component. Can the Thank you state be the same image on both?

**Comment by taisdesouzalessa** [comment]
Hey @alanmoo good catch. I forgot to update it I guess, sorry for that. It is supposed to be the green icon. I'll update it and send to you.

**Comment by taisdesouzalessa** [comment]
@alanmoo the file "all-desktop-screens.sketch" in the dev folder is updated to the newest version with the requested icon. You can use the same image as the full join us page ("Thank You" state) - just reduce it to 55% of the original size. 

<img width="423" alt="screen shot 2017-03-28 at 1 25 01 pm" src="https://cloud.githubusercontent.com/assets/22157921/24425770/34550c68-13ba-11e7-9e4a-e3ad5306a6b1.png">

**Comment by alanmoo** [comment]
I've merged these changes in and they're on staging. Can they get a design review?

**Comment by alanmoo** [comment]
Closed by #250
