### ISSUE TITLE
Left alignment bug in Firefox

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#167]
In all hero sections from [staging version](https://network.mofostaging.net/) we have a left alignment bug in Firefox. Here are some screenshots. I believe when we fix those issues for desktop, mobile will be solved as a consequence.

<img width="911" alt="screen shot 2017-03-14 at 4 13 13 pm" src="https://cloud.githubusercontent.com/assets/22157921/23926446/81539ea6-08d1-11e7-9884-7a68cfd8e7d9.png">
<img width="978" alt="screen shot 2017-03-14 at 4 13 25 pm" src="https://cloud.githubusercontent.com/assets/22157921/23926447/815a2c58-08d1-11e7-9321-264c7f8c9349.png">

**Comment by amarlearning** [comment]
@taisdesouzalessa can i take this one ?

**Comment by gvn** [comment]
Hi @amarlearning! Thanks for your offer, but we're not quite ready for contributors yet on this project. Please feel free to check with us soon though! 👍

**Comment by alanmoo** [comment]
This has to do with a combination of the element wrap and the box shadow currently applied to headings. But it's also a difference in how FF and others render elements. If you want any left padding on the text boxes, this will likely happen when it wraps lines. Though I wouldn't say it's necessarily a bad thing; there's something fitting about our branding being about the web/highlighting text and the fact that minor differences like this are the nature of the web.

So, @taisdesouzalessa which would you prefer: No left padding (black edge is basically 2px away from the side of the text) or slight variations between browsers?

**Comment by taisdesouzalessa** [comment]
@alanmoo please correct me if I am wrong. If we remove the left padding this is the final rendering, right?
<img width="969" alt="screen shot 2017-03-14 at 5 00 55 pm" src="https://cloud.githubusercontent.com/assets/22157921/23927621/0cf6720c-08d8-11e7-85da-10fd4d28ed08.png">


If so, I would prefer consistency over the lack of alignment in Firefox. I think the misalignment doesn't work in this case. The feeling we would like to convey with the Network site is trust and I think the lack of alignment can cause some anxiety in users' minds ("is it reliable?"). Also, our [Internet Health](https://www.mozilla.org/en-US/internet-health/) page doesn't have the padding (the hero has but not the rest of the titles). So that would be my preference.

That being said, I find your idea about the nature of the web and the minor differences very interesting. It is a good perspective on that.

Would love to hear other perspectives on that, @hannahkane @xmatthewx @sabrinang

**Comment by gvn** [comment]
For consistency, I'm going to implement per your design above, Taís. 👍
