### ISSUE TITLE
Mobile Typography

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#169]
**Issue:** The mobile typography [on staging](https://network.mofostaging.net/) is not following the mobile specs in [the mockup](https://invis.io/ZKAIKN1MN#/220168109_MOBILE-HomePage) - sizes, line height and spaces. 

NOTE: I am almost sure the mobile on staging is still a WIP so please let me know if it is too soon to file this ticket :).

**Comment by gvn** [comment]
Can you be more specific? Which typography in particular?

**Comment by xmatthewx** [comment]
I recommend that designers & engineers schedule a meeting for Monday to walk through Mobile. To make a plan, some global rules to improve mobile typography, margins. We can keep overrides to a minimum, but some will be required to get heros and homepage components looking awesome.

**Comment by taisdesouzalessa** [comment]
I think it is a great idea. I will need some prep time prior to the meeting to make sure we make the best use of the time together. I will organize the list with only mobile issues so you can focus just on them for this meeting, what do you think?

**Comment by taisdesouzalessa** [comment]
Based on conversation with Gavin, it seems the best way is to have a checklist per page and that will include the mobile typographic styles. Closing this ticket and discussion on typography will be done per page, starting at #233

**Comment by gvn** [comment]
Well, I think we should still approach the typography as a system and adjust the mobile styles more granularly (eg: varying the percentage that they shrink instead of doing all at 75% smaller).

For other design tweaks I think making per-page meta tickets makes sense.

**Comment by taisdesouzalessa** [comment]
Okay then. If we are approaching the typography as a system, do you think the guidelines for mobile I made would help here? Inside the dev folder "Design Assets/_PROJECTS/Mozilla Network Site/dev/all-mobile-screens.sketch" has a page called "Styles" and I have the

**Comment by gvn** [comment]
Are those mobile type sizes all 75% of the desktop sizes, or are they individually resized?

**Comment by xmatthewx** [comment]
For font-size, I'm guessing we will want to reduce large headings, but keep small headings and body copy the same across devices. 16pt should work well for both desktop and mobile. 

Beyond font size, we need to resolve line-height for all these items and margin for a few of them. We should specify those as relative to the item's font-size, so we know everything will translate well.

There might be a few instances where we want to override the system, but let's limit those carefully to the hero and other critical items.

**Comment by gvn** [comment]
Needs further value tweaks. @taisdesouzalessa just let me know when the revised Sketch file is up.

**Comment by taisdesouzalessa** [comment]
@gvn, I have a new Sketch version in our "dev" folder in Google Drive - "all-mobile-screens.sketch". In the page "Styles" there is an artboard called "Typography-Mobile Revised". Please let me know if you have any questions! Thanks.
