### ISSUE TITLE
Mobile - Hero head/subhead space

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#170]
**Issue:** The space between the head and subhead is too tight on mobile for all Mobile hero sections.
 Example:
![spacing-mobile](https://cloud.githubusercontent.com/assets/22157921/23929714/2c7ad304-08e5-11e7-9391-db73e15d3734.png)

**Fix:** To increase the space between elements.

**Comment by gvn** [comment]
Can you specify how many pixels of spacing you want?

**Comment by taisdesouzalessa** [comment]
<img width="331" alt="screen shot 2017-03-20 at 4 23 24 pm" src="https://cloud.githubusercontent.com/assets/22157921/24126101/5a587558-0d89-11e7-8f51-8481fdbbfa25.png">

16px should work (I applied margin-top to the class ".lead-white" in this example).

**Comment by alanmoo** [comment]
FYI: This stems from the headline being set to `display: inline` so that the background highlight appears. Digging into a fix now.
