### ISSUE TITLE
Home Page/ News Page - missing byliner on titles

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#173]
**Issue:** the byliner is missing in the Home Page and the News page.

Example
![byliner-news](https://cloud.githubusercontent.com/assets/22157921/23960697/e95a2346-0965-11e7-8a87-aa913cc40f28.png)

The rule was that if we had the name of the author in Medium we would add it as a byliner. If it was just Mozilla we wouldn't add. This is what I got from our past conversations on that. @xmatthewx @sabrinang @KevZawacki please correct me if I am wrong here :).

**Comment by hannahkane** [comment]
Note: Also applies to the News page itself.

**Comment by gvn** [comment]
I think this info was missing from the spreadsheet when I pulled it.

**Comment by hannahkane** [comment]
@gvn - is it still missing? Does someone need to add them now?

**Comment by gvn** [comment]
I'd suggest that we add them after we hook News up to the CMS, otherwise it's just more data to migrate later and extra work now that will be replaced soon.

**Comment by gvn** [comment]
Related: #206

**Comment by xmatthewx** [comment]
Fine by me as long as @gideonthomas is aware of this for the News content-type model.

**Comment by gideonthomas** [comment]
author has been added to the CMS for News

**Comment by gvn** [comment]
@hannahkane Are you planning to add the authors? Once they're in the CMS I can add them to the front end.

**Comment by hannahkane** [comment]
Sure. I will add them now.

**Comment by hannahkane** [comment]
Where do I add them? I don't see a News module in the admin.

**Comment by gvn** [comment]
@gideonthomas ^ ?
