### ISSUE TITLE
Home: too much margin on 1st News item

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#175]
**Issue:** currently we have a padding of 3rem in our first news item.
<img width="636" alt="screen shot 2017-03-15 at 10 14 51 am" src="https://cloud.githubusercontent.com/assets/22157921/23961548/80e09716-0968-11e7-8ba5-a28d312ee9a6.png">

Is is possible to reduce so it looks more like the width for our gutter? Maybe reduce to 2rem? Example below:
<img width="589" alt="screen shot 2017-03-15 at 10 14 17 am" src="https://cloud.githubusercontent.com/assets/22157921/23961648/d09b8374-0968-11e7-8071-2b0b269b2876.png">

**Comment by alanmoo** [comment]
The padding classes we're using throughout the project are 1.5rem and 3rem (which this is currently set to). I can reduce it to 1.5rem very easily, would that be fine?

**Comment by taisdesouzalessa** [comment]
Sure. 1.5rem left and right padding is good -  it will have the same distance as the previous boxed element (CTA box), adding consistency to the layout. 
![staging](https://cloud.githubusercontent.com/assets/22157921/24527006/33b42d24-1555-11e7-9b03-5122bcde36be.png)

I was wondering it top and bottom can be different, so we keep it consistent with the CTA box. Maybe adding the "px-4" and "py-5" classes?
<img width="1066" alt="screen shot 2017-03-30 at 2 24 25 pm" src="https://cloud.githubusercontent.com/assets/22157921/24527163/deee7622-1555-11e7-9da5-de4efcb060a9.png">

It would be good to have the same behavior in all boxed elements, such as:
<img width="1231" alt="screen shot 2017-03-30 at 2 25 44 pm" src="https://cloud.githubusercontent.com/assets/22157921/24527174/e61d92ca-1555-11e7-8557-fea9d37146a6.png">

I prefer this consistent behavior so we can add some design polish to the page. What do you think?

**Comment by taisdesouzalessa** [comment]
Closing this ticket - this issue is covered in the latest QA tickets
