### ISSUE TITLE
Home: Mobile view - Space above View more news button

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#176]
**Issue:** There is too much space between the last news and the button.

<img width="322" alt="screen shot 2017-03-15 at 10 24 02 am" src="https://cloud.githubusercontent.com/assets/22157921/23962054/1d1a41b2-096a-11e7-876b-f1a58910a013.png">

**Comment by xmatthewx** [comment]
Closing. I believe this is now resolved or at least better.
