### ISSUE TITLE
Support Page:  Mobile - image/text order

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#178]
**Issue:** on mobile we have the following ordering in the [Suport Page](https://network.mofostaging.net/support/):
<img width="298" alt="screen shot 2017-03-15 at 10 37 42 am" src="https://cloud.githubusercontent.com/assets/22157921/23962498/960b8dfa-096b-11e7-8a2d-0ba83a58cb5a.png">

**Fix:** ideally we would have it like [here](https://invis.io/ZKAIKN1MN#/219982565_MOBILE-Programs)

**Comment by hannahkane** [comment]
@xmatthewx notes "We can drop the left-right layout on this page on desktop if it’s an easier fix for now"
