### ISSUE TITLE
Support Page - replace theme photo for Women and Web Literacy

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#179]
There is a new approved photo as per discussion on this issue:
https://github.com/mozilla/network/issues/113

@sabrinang could you add here the path for the new picture once you have the final decision on that?

**Comment by sabrinang** [comment]
https://drive.google.com/file/d/0B4Q8pzCpDS_eVG8xLWlPMlJidE0/view

**Comment by gvn** [comment]
@sabrinang or @taisdesouzalessa Can you prep this image in the same way as the previous one? The aspect ratio is wrong and it doesn't have the shadowing.

Example:

![women-and-web-lit](https://cloud.githubusercontent.com/assets/206379/24123246/f9dbc8d6-0d7b-11e7-81e3-5e79c477dc98.jpg)

**Comment by sabrinang** [comment]
@gvn I have exported all the support page images here (1200x900), I didn't add the dark black gradient to any of the theme images (I thought that was done in CSS?): https://drive.google.com/open?id=0B4Q8pzCpDS_eQUxzOWpWUEhTODQ

**Comment by gvn** [comment]
@sabrinang Can you crop them so they are square? CSS gradient will require refactoring, so I'm fine with you adding that directly to the image so you can have the most control.

**Comment by sabrinang** [comment]
@gvn Here is the image cropped square with gradient: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_ecGpTQVdKeTJqOG8/view?usp=sharing
