### ISSUE TITLE
Add Mozilla teams to this repo

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#18]
@gvn - can we add our usual teams here? Autocomplete won't help with most staff handles. Or... do you want me to move discussion on content somewhere else?

**Comment by gvn** [comment]
What teams do you want added?

**Comment by xmatthewx** [comment]
I wonder if adding `mofo-staffonly` with just `read` permissions will better populate autocomplete without actually open things further. I'm not sure.

**Comment by gvn** [comment]
Hmm, we shall see! I also made you an admin.

**Comment by xmatthewx** [comment]
perfect
