### ISSUE TITLE
Typography: Consider left alignment treatment 

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#180]
Note: this ticket covers a single fix to adjust column width. See comment below. https://github.com/mozilla/network/issues/180#issuecomment-294563495

----

@hannahkane @xmatthewx @sabrinang when we discussed this item we tagged as an engineering bug but I think we should tackle this at design first to see how it feels and move to engineering once we decide on the alignment. What do you think?

**Issue:** some parts of the site have center alignment.

Example:
<img width="886" alt="screen shot 2017-03-15 at 10 49 18 am" src="https://cloud.githubusercontent.com/assets/22157921/23963088/774c5fc8-096d-11e7-938a-89da20577eb5.png">

**Fix:** Consider left alignment - review all the pages that have center alignment and try the left alignment instead.

**Comment by taisdesouzalessa** [comment]
The only part we had the center was in the Support page, so that was an easy design fix.

This is the final result. I recommend to skip one column each side so we don't have a very lengthy line. Besides that, having the white space on the sides adds some visual break.

<img width="509" alt="screen shot 2017-03-16 at 12 56 38 pm" src="https://cloud.githubusercontent.com/assets/22157921/24018076/b1ceec46-0a4f-11e7-8eae-6cc5913d6431.png">

In mobile it is ok for the lines to go full width because of the limited horizontal space - I fing the last too lines a bit funny but they are due the size of the words and the way they break.
<img width="366" alt="screen shot 2017-03-16 at 12 56 46 pm" src="https://cloud.githubusercontent.com/assets/22157921/24018114/d74739a6-0a4f-11e7-8348-595b0f5e4715.png">

Let me know your thoughts on those options.

**Comment by alanmoo** [comment]
FWIW I think this looks a lot better and isn't hard to implement.

**Comment by xmatthewx** [comment]
I think this has been covered by other QA tickets. Reopen if that is not true @taisdesouzalessa

**Comment by taisdesouzalessa** [comment]
Reopening this issue @xmatthewx because there is one tweak to be done.

There is one thing left on this issue: to skip one column left and right so the line length is not that long and the section seems less like a block. 

The purple rectangles indicate the columns offset.

<img width="1270" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/25100921/ecd3f662-2366-11e7-815e-7d20319dd6c8.png">

**Comment by xmatthewx** [comment]
could include #301 as well

**Comment by hannahkane** [comment]
Note: estimate (1) does *not* include #301
