### ISSUE TITLE
Projects Page - Pulse - mockup with 9 projects + links on top + button on the bottom

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#181]
Discussion started on #38.

New mockup, with the tag "Open Innovation" instead of IoT:
https://invis.io/ZJ9YTAGEA#/217251312_Projects-Join-Us-Iteration

IMPORTANT: top links now go to external Pulse page, here are the links:

"Privacy & security" - https://www.mozillapulse.org/issues/online-privacy-and-security

"Mozfest" - https://www.mozillapulse.org/search?keyword=mozfest

"Open Innovation" - https://www.mozillapulse.org/issues/open-innovation

NOTE: now we have only 9 projects being displayed. There has been a discussion on which ones to feature. Please @xmatthewx post here once we have the final word on them. I am closing the other ticket.

@hannahkane is this a p1? Please let me know if I should change the tag.

@gvn @sabrinang

**Comment by gvn** [comment]
All the engineering tasks are done here. @xmatthewx I'm assuming you have the ability to change the featured projects so re-assigning to you.

**Comment by xmatthewx** [comment]
Done!
