### ISSUE TITLE
People Page - Hero sentence break

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#183]
**Issue:** in some screen widths the sentence breaks in a way that leaves "One" separated from "Mission"
<img width="366" alt="screen shot 2017-03-15 at 12 01 10 pm" src="https://cloud.githubusercontent.com/assets/22157921/23966071/4dc572a2-0977-11e7-90be-c3359ffc6222.png">

**Fix:** we were wondering if a `&nbsp;`  would fix this problem.  I tested it in browser and the only breaking point that seems a little weird to me is this one:
<img width="631" alt="screen shot 2017-03-15 at 12 11 05 pm" src="https://cloud.githubusercontent.com/assets/22157921/23966452/a0d47848-0978-11e7-90d1-98f088245b7a.png">

However I think it looks better than the "One" separated from "Mission". Curious to see what others think.

cc: @sabrinang

**Comment by gvn** [comment]
We can add a line break, but bear in mind that the nature of responsive web is that you don't have precision control over typography. People can resize their fonts, override our font choices, and resize their windows which can all change layout. Localization can also create varied layouts.

**Comment by taisdesouzalessa** [comment]
Yeah, I understand what you mean. Good point about localization. Considering all aspects of it I would rather not add the line break because I see the potential of having weird breaks in another languages. How do feel about leaving as is @xmatthewx? I feel the cons are stronger than the pros, given Gavin's points there.

**Comment by alanmoo** [comment]
I think adding a non-breaking space between "One" and "Mission" is a reasonable locale-specific implementation. We're not localizing yet, so at the very least we can make this look good for now and come back to it if there's really an issue with localization.

**Comment by gvn** [comment]
That's fine, but what I'm highlighting is the fundamental problem with trying to have precision control over typographic rendering on the web.

**Comment by xmatthewx** [comment]
No need for precision. No need to figure this out programmatically for text orphans across all headers. Just one localized use of @nbsp; for the second most important header on the site.

**Comment by taisdesouzalessa** [comment]
As @alanmoo mentioned, we can come back to it once we localize it, right? It would be good to see how it looks like in other languages.
