### ISSUE TITLE
Make postcss work x-platform

### ISSUE THREAD

**Issue by gvn** [mozilla/network#19]
Postcss isn't compatible with Windows!

**Comment by mmmavis** [comment]
This issue has been addressed on Pulse. We use the same fix here as well: https://github.com/MozillaFoundation/mofo-standards/issues/30

**Comment by hannahkane** [comment]
Does this need to be resolved pre-launch?

**Comment by gvn** [comment]
Nope!

**Comment by gvn** [comment]
Ok, this may already work on Windows actually. I have autoprefixing set up as a script:

`"autoprefix": "node scripts/autoprefix.js",`

@Pomax can you verify that this project builds on Windows?

**Comment by Pomax** [comment]
This seems to work well, although do we want to rely on a separate script, rather than the pure npm modules solution used in pulse?
