### ISSUE TITLE
QA - Content

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#199]
Document here ("Title: QA focusing on copy & images"):
https://docs.google.com/document/d/1hxZTnqenxZWgUaLHG-RJSRzafSBXuLHSXK-hDCyTk4U/edit#heading=h.xo9crq9ndjf6

**Comment by taisdesouzalessa** [comment]
As the team decide priorities we can file those issues as individual tickets if needed.

**Comment by xmatthewx** [comment]
Thanks for this. There are a ton of things in there. @hannahkane – how do you think we should share with engineers? I don't think we can wait for designers to return. 

@gvn – I'm also curious what you think. The first half of the doc is about copy, the second half has a bunch of style pieces.

**Comment by gvn** [comment]
Yeah, definitely a lot of things in there.

I'd say go ahead and start breaking it into tickets and prioritizing.

**Comment by hannahkane** [comment]
Per conversation in google doc and at stand today: let's get through the existing p1s and p2s, and then revisit this doc. We can either group items into a ticket for each page, or perhaps just do an engineer/designer jam session over vidyo to make decisions in the moment.

**Comment by taisdesouzalessa** [comment]
It seems we are doing the jam on Monday, is that correct?

**Comment by taisdesouzalessa** [comment]
All issues present on this ticket are being addressed on new QA tickets. Closing this issue.
