### ISSUE TITLE
QA - Design

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#200]
Google Docs with design QA:

https://docs.google.com/document/d/1hxZTnqenxZWgUaLHG-RJSRzafSBXuLHSXK-hDCyTk4U/edit#heading=h.6l4n8v79rpjy

**Comment by taisdesouzalessa** [comment]
As we decide priorities we can file those issues as individual tickets if needed.

**Comment by hannahkane** [comment]
Per conversation in google doc and at stand today: let's get through the existing p1s and p2s, and then revisit this doc. We can either group items into a ticket for each page, or perhaps just do an engineer/designer jam session over vidyo to make decisions in the moment.

**Comment by taisdesouzalessa** [comment]
All issues present on this ticket are being addressed on new QA tickets. Closing this issue.
