### ISSUE TITLE
Design tweaks to People cards

### ISSUE THREAD

**Issue by hannahkane** [mozilla/network#201]
- [ ] slants in the featured cards

- [ ] typeface in the quotes have "font-style:italic" instead of using "Nunito Sans Light Italic"

- [x] If it is not possible to break lines through the use of bullet points we may want to rewrite the bullet points in a more descriptive way.

- [ ] @taisdesouzalessa would love to tweak the animation (I am sure this is not a priority, just adding as a reminder).

**Comment by xmatthewx** [comment]
I'm guessing this is covered elsewhere in QA tickets. Reopen if that's not true @taisdesouzalessa
