### ISSUE TITLE
Refactor featured Get Involved home content to use external JSON from Mezzanine

### ISSUE THREAD

**Issue by gvn** [mozilla/network#203]
- [x] Create schema and wire up static JSON in `network`
- [ ] Add new `highlights` model to Mezzanine https://github.com/mozilla/network-api/issues/220
- [ ] Add content to Mezzanine
- [ ] Switch `network` over to use Highlights JSON pulled from `network-api`

**Comment by gvn** [comment]
Blocked by pending API work.

**Comment by xmatthewx** [comment]
We should probably do a new estimate on this to include a means to select featured items outside of the entries themselves.

**Comment by alanmoo** [comment]
Made an epic, this is the first item in it and it is complete, so I'm closing for accurate estimation records.
