### ISSUE TITLE
Add page dividing Headers

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#204]
We have some nice looking headers that might be a bit tricky to implement and will have to wait while we knock out more critical things. In the mean time, 

I'm wondering: Should use a black background that goes full width for now? So we at least divide the page as designed? 

What do you think @sabrinang? 

implemented: 
<img width="800" alt="screen shot 2017-03-20 at 4 27 29 pm" src="https://cloud.githubusercontent.com/assets/53411/24120203/232b76ce-0d8a-11e7-935a-768a9b96cdf8.png">

planned: 
<img width="1044" alt="screen shot 2017-03-20 at 4 24 44 pm" src="https://cloud.githubusercontent.com/assets/53411/24120103/cad85dfc-0d89-11e7-88d6-48b5a9ffc1c2.png">

**Comment by sabrinang** [comment]
Interim solution progress here from @taisdesouzalessa : https://github.com/mozilla/network/pull/101#issuecomment-289585092 

We are going with a black rectangle box for headings and repeatable slanted bg as the divider

**Comment by sabrinang** [comment]
@xmatthewx we can refer to issue #101 , can we close this ticket?

**Comment by xmatthewx** [comment]
Thanks for the update. 101 is pull request. Let's keep this open. It also sounds like that solution is still non-trivial. I think we should consider the 10 second fix in case that doesn't land while we focus on other priorities.

**Comment by xmatthewx** [comment]
Looks like we're good to go with full solution.

**Comment by alanmoo** [comment]
Not quite- we can do the background slants but the box itself presents a bigger challenge, unless the item definitely won't wrap (like the section headings on the home page, I believe)

**Comment by taisdesouzalessa** [comment]
@alanmoo by 

> the box itself presents a bigger challenge

You mean the background box?
<img width="205" alt="screen shot 2017-04-05 at 11 59 54 am" src="https://cloud.githubusercontent.com/assets/22157921/24722043/0fd5097c-19f7-11e7-8f3d-14c186e0dde1.png">

**Comment by alanmoo** [comment]
Yeah, doing the angle on that

**Comment by taisdesouzalessa** [comment]
I talked to @sabrinang a while ago and we both agree that for now a quick solution would be to have a rectangular background, like we have in the "People" page:
<img width="921" alt="screen shot 2017-04-05 at 12 05 22 pm" src="https://cloud.githubusercontent.com/assets/22157921/24722254/edd9520a-19f7-11e7-8208-5d044421a6a3.png">

What do you think?
@xmatthewx  does that work for you?

**Comment by xmatthewx** [comment]
That works for me... IF @alanmoo says this proposal is quick and easy. Otherwise...

IF @taisdesouzalessa's proposal is tricky:  💥Kibosh!💥 We can't put a ton of time in this right now. 

I believe @alanmoo is saying that the black box slant is tricky since some headings might have long strings and require two lines on small screens. We can't predict the padding required.
