### ISSUE TITLE
Simply font sizing adjustments for mobile

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network#213]
We've got a mixin to reduce font size on mobile, but it doesn't affect things like line height because that property is set in pixels for most selectors. We should change that to unit-less values as a basic enhancement, though there are probably other ways to refactor our type code to make it cleaner and more consistent.

**Comment by xmatthewx** [comment]
Closing. I believe this has been covered by other QA tickets. True or false @taisdesouzalessa ?

**Comment by taisdesouzalessa** [comment]
@xmatthewx visually mobile looks good now but I am not sure if @alanmoo's suggestions for enhancement were implemented yet. You ok about closing this ticket, Alan?
