### ISSUE TITLE
Discuss SaaS with Coral

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#217]
The Coral Project has a great tool called Ask that we can use to engage with site visitors. Backend includes a simple form building tool, then embed pulled in via script tag so we can style as we see fit. Lots of great features already in production on major news sites. 

Let's discuss setup with @cadecairos on Monday or Tuesday at tech integrations call. Jeff Nelson from Coral can provide setup support if needed. 

Docs: https://docs.coralproject.net/products/ask/

**Comment by xmatthewx** [comment]
@cadecairos can I assign to you to peek at [documentation](https://docs.coralproject.net/products/ask/#1-setup-aws-instance) and provide estimate on time to setup the platform? Identify any concerns on using this? Jeff Nelson from Coral can provide setup support if needed.

**Comment by cadecairos** [comment]
I just took a quick look at the project and I have some doubts that we should use this. 

We've been moving away from hosting infrastructure on AWS, and it doesn't look like this can be adapted for Heroku without some investment of time. Is there no solution for the forms use-case that we won't have to host ourselves?

I'm not saying setting this up will be difficult at all (the docs look nice), but we should avoid extra maintenance overhead if we can.

**Comment by xmatthewx** [comment]
Alrighty. Maybe we can discuss further at next production team meeting. 

We could see whether Coral could prepare it for heroku deployment. I also wonder if we can just use the Health Report instance that is already set up. Are you supporting that? I also wonder if we could get MoCo to support this –– it's Mozilla software and could be useful for other initiatives (if the admin tool makes sense for use by multiple teams).

**Comment by xmatthewx** [comment]
Simon mentioned that Coral plans to offer SaaS and suggested that we approach them as a client. That would put support and maintenance on their plate, and make the costs transparent. Good idea b/c it supports and helps test their endeavor, and overall it should be cheaper since they know the platform best.

**Comment by xmatthewx** [comment]
@simonwex - let's prepare a paragraph or two on this arrangement.

**Comment by xmatthewx** [comment]
Closing. Currently blocked, but conversation is in motion.
