### ISSUE TITLE
Copy change on sign-up form

### ISSUE THREAD

**Issue by hannahkane** [mozilla/network#222]
Per feedback from Exec team:

- [ ] Change form header to "Get connected" 
- [ ] Change site-wide header button to "Sign Up"
- [ ] Change URL to /sign-up/

**Comment by gvn** [comment]
@hannahkane So, is the button copy supposed to be "Join Us" or "Sign Up"?

**Comment by hannahkane** [comment]
@xmatthewx ^

**Comment by xmatthewx** [comment]
Sorry for the ambiguity. 

Suggestion I heard was that the button at the top of the site be labeled `Get Connected` like the header on the sign up page form. It's an odd pretty odd label. Let's do `Sign Up` to match the form's button. 

@hannahkane @KevZawacki do you agree?


this doesn't seem right: 
<img width="1112" alt="screen shot 2017-03-29 at 11 46 45 am" src="https://cloud.githubusercontent.com/assets/53411/24463698/821f9e48-1475-11e7-9c96-c60ba13df852.png">
 
this seems good:
<img width="1111" alt="screen shot 2017-03-29 at 11 47 17 am" src="https://cloud.githubusercontent.com/assets/53411/24463697/821cc3b2-1475-11e7-8c19-e254ad79aac0.png">

<img width="1116" alt="screen shot 2017-03-29 at 11 49 49 am" src="https://cloud.githubusercontent.com/assets/53411/24463810/d95f997e-1475-11e7-99c8-195d3e11d32a.png">

**Comment by KevZawacki** [comment]
@xmatthewx Agreed, 'sign up' seems better

**Comment by xmatthewx** [comment]
Okay thanks. Updating checklist above so @gvn can proceed.

**Comment by xmatthewx** [comment]
I will do my best to lock this, avoid any more changes until we have actual data from use by real live humans.

**Comment by hannahkane** [comment]
Belated +1 from me
