### ISSUE TITLE
Redesign people box on homepage

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#226]
Let's move toward something that feels like currently spotlighted people, rather than an evergreen collage. 
 - Could be similar to [an earlier design](https://projects.invisionapp.com/share/ZJ9YTAGEA#/screens/221865408), showing 2-4.
 - Could just display name or title
 - Could have context: "Advancing privacy" rather than just members in general

Not require, but nice to have: "See more members like these advancing privacy"

"Amy, CEO at Sprocket Factory"

<img width="1194" alt="screen shot 2017-04-19 at 4 18 51 pm" src="https://cloud.githubusercontent.com/assets/53411/25200324/ef1df772-251b-11e7-947c-a9e9a61cfed2.png">

**Comment by taisdesouzalessa** [comment]
@xmatthewx @hannahkane @sabrinang 

Here are the options for this page:

• [Option 1 LINK](https://invis.io/ZJ9YTAGEA#/226127663_Home_Page-Peoplev1)
In this case I suggest we change the Projects' section too to align with the People's section treatment.

• [Option 2 LINK](https://invis.io/ZJ9YTAGEA#/226127612_Home_Page-Peoplev2b)
For Option 2 I think if we just use "See more members like these advancing privacy" it may give the impression that those members are just related to the issue. To solve that, I suggest we show different issues and members each time the page loads. 
Prototype (reload the page to see members and  issues changing): 
http://www.taislessa.com/mozilla/bkg-image/people-prototype.html

Please let me know your thoughts on those.

**Comment by xmatthewx** [comment]
These look great and are nearly done. Let's discuss at the end of stand up.

**Comment by sabrinang** [comment]
I like the streamlined structure, having less copy on the people and how projects mirror this featured structure in Option 1. This seems more flexible for mobile and maybe this structure avoids having text saved on images themselves and can have the text overlaying it for accessibility purposes.

I also like the concept of showcasing different issues and set of members in Option 2 when the page is reloaded perhaps projects can also be showcasing sets (example: mozfest, games etc.)

**Comment by taisdesouzalessa** [comment]
Thanks for the input here! 

There is a new iteration on this page after I got feedback from Matthew:

https://invis.io/ZJ9YTAGEA#/226387325_Home_Page-Peoplev3

@xmatthewx - I think your suggestion of fading the people behind the box worked well here. It is an elegant solution for showing a variety of people without making the page look busy. 

Let me know your thoughts on it.

**Comment by xmatthewx** [comment]
This is looking great. I propose that we reduce the copy in the box above the button and then share with Mark/Chris for feedback. 

@KevZawacki – what do you think of this phrase above the button?  

![people-featured](https://cloud.githubusercontent.com/assets/53411/24513338/f15e1fb8-153e-11e7-8c38-50e9f9725405.png)

**Comment by KevZawacki** [comment]
@xmatthewx Looks fantastic! Might tighten the copy to: "Meet leaders with a shared mission"

**Comment by xmatthewx** [comment]
Great thanks. 

@taisdesouzalessa – let's draft up a couple of options for how this appears on small screens. Since the box & button will be pushed down, a single row of small photos is probably best. I'm unsure.

**Comment by taisdesouzalessa** [comment]
@xmatthewx here are the mockups, updated:

DESKTOP: https://invis.io/ZJ9YTAGEA#/226387325_Home_Page-Peoplev3

MOBILE: https://invis.io/ZKAIKN1MN#/226606259_MOBILE-HomePage-V3
For mobile, I suggest we just display only 2 cards so the small copy of their roles is still readable.

**Comment by xmatthewx** [comment]
Looks good. Let's see what we hear back from Mark/Chris before we move onto implementation.

**Comment by taisdesouzalessa** [comment]
Based on our conversation today, here are 3 iterations of this screen:

![people-hp](https://cloud.githubusercontent.com/assets/22157921/24677645/57c4ad66-193c-11e7-9cda-70add16d0335.jpg)

Comments:
I prefer the original (1) because it looks more complete to me - the whole last picture is fading and since it is cut on the right side, it gives a sense that there is more to see. The (2) makes me feel weird because we just see half of a person's face and that really bothers me (people tend to look at other people's eyes). The (3) is a bit better but I feel it gets too empty on the right side.

@xmatthewx @sabrinang @hannahkane let me know what you think of those options and what is your preference.

**Comment by xmatthewx** [comment]
I agree with the right edge. Of these 3, I also prefer the original. I do wonder if the left could start at higher opacity and work toward the left edge you have in the original option.

**Comment by hannahkane** [comment]
FWIW, I much prefer the original option.

**Comment by taisdesouzalessa** [comment]
@xmatthewx not sure I understood what you meant. I did 2 iterations based on my understanding. If none of them is what you meant we can sync tomorrow and I can create a new mockup:
![people-hp2](https://cloud.githubusercontent.com/assets/22157921/24682461/b9fecb9e-194e-11e7-84ff-c33c96b3562c.jpg)

**Comment by xmatthewx** [comment]
You did lots of good tests. I think i'm proposing something slightly different. invision live share keeps crashing on me. So i will try this: thumbs up = good, don't change. curious face = something new we might try.  

![people-box-feedback](https://cloud.githubusercontent.com/assets/53411/24718754/25697238-1a05-11e7-90f8-bce4d8ae9fa0.jpg)

note: I like the opacity on the right edge of the original. I'm guessed it's 20% in my note on the mockup. I realize now it's probably higher. I'm not suggesting you change that.

**Comment by taisdesouzalessa** [comment]
@xmatthewx thanks for the diagram. Here is the new version, based on your suggestion:
<img width="1027" alt="screen shot 2017-04-05 at 4 27 32 pm" src="https://cloud.githubusercontent.com/assets/22157921/24731030/6307a0e4-1a1c-11e7-8396-cfb926175d23.png">

I like the fact the last 2 pictures gradually fade, looks nice.

**Comment by xmatthewx** [comment]
if you like it, i like it. good to go.

**Comment by taisdesouzalessa** [comment]
@xmatthewx here is this component together with the latest changes we made in the page:
[DESKTOP](https://invis.io/ZJ9YTAGEA#/227825995_Home-Page-V3)
[MOBILE ](https://invis.io/ZKAIKN1MN#/227826650_MOBILE-HomePage-V3)

Is this feature ready to build (People component only)? Should I create a ticket for engineers?

**Comment by hannahkane** [comment]
Updating estimate based on April 10 estimate that includes new changes from exec team + estimate for both design and engineering.

**Comment by xmatthewx** [comment]
![people-feature-box](https://cloud.githubusercontent.com/assets/53411/24878627/e683525e-1e01-11e7-8fb9-83f545d3ae28.png)

Request is to 1) change header and change button, removing other text; 2) test a fade/crop on both sides. No need to change people cards themselves, unless there are engineering concerns.

**Comment by taisdesouzalessa** [comment]
@xmatthewx I was wondering if you know which people will be featured in this box. For now I will be using placeholders.

**Comment by taisdesouzalessa** [comment]
@xmatthewx here are the iterations on this feature. I had a talk with @gvn and he gave me more context on the technical challenges that the previous solution presented. For these new versions I am using: squared pictures (as we have in the People page - to keep the same proportions) and the copy outside the picture to avoid text being in a fixed height component

V1
<img width="516" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/24887832/e1ba7060-1e13-11e7-837a-c62b3907c52d.png">
I am not sure this version works. I find that left and right fading gives the impression the component is carousel which can be misleading. 

V2
<img width="514" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/24887955/b55f9454-1e14-11e7-9aaa-ad52f9514950.png">

V3
<img width="514" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/24888029/38afdb20-1e15-11e7-82a9-b0f838eb6b0d.png">
The gray in the background highlights the component, making the feature people more prominent and distinctive from the rest of the interface (I think once we give an aesthetic pass later on, we could add some texture in the flat gray background).

**Comment by gvn** [comment]
I'd still like to avoid the text fade, but other than that these options all will work much better with variable content. 👍

**Comment by taisdesouzalessa** [comment]
As per conversation with @xmatthewx here are the revised proposals of the component:

V1: 
<img width="513" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/24925975/e31137f0-1eae-11e7-98df-ea356916d1e1.png">

V2:
<img width="513" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/24926024/0f53a92e-1eaf-11e7-9e44-fdfaa4ff614b.png">

**Comment by taisdesouzalessa** [comment]
@xmatthewx revised versions:

V1 - with fade and tweaks:
<img width="513" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/24931893/eb49968c-1ec3-11e7-9c4b-8860866dbb6a.png">

V2:
<img width="511" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/24931966/4244661a-1ec4-11e7-8542-b87a2f8559f2.png">

**Comment by xmatthewx** [comment]
v2 is approved as our direction over v1. 

New request: 
 - Can we add social links below role? Will be busy, but sends a good signal to visitors and people featured.  
 - Relabel the button to "Meet more Leaders"

**Comment by gvn** [comment]
Can we remove the fade on the role?

**Comment by taisdesouzalessa** [comment]
Here are the options, with some considerations:

V1:
<img width="1026" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/25027936/34e7e9d6-2065-11e7-89fd-eb952ca7a327.png">

V2 (without fade/with social media):
<img width="1027" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/25027955/531607e4-2065-11e7-9d76-0d80721407c6.png">
As Matthew mentioned, I also find it is busy. I think it distracts the audience from the goal of clicking to see more people.

V3 (without fade): 
<img width="1027" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/25027984/985fe536-2065-11e7-843c-1468531f490a.png">

I don't mind the versions without fade but my main worry is that if the titles get too long, they will push the button further down, making it seems lost and out of context. The fade offers the audience only enough glimpse on these people, motivating them to visit the "People" page.

Here is a version with a hypothetical long title:
<img width="1024" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/25028047/42e36d5c-2066-11e7-95ce-f703fe5e3267.png">

That being said, I feel long titles will be uncommon (is this correct?). If this is true I am good without fading. If it is not true, I recommend fading.

**Comment by sabrinang** [comment]
Some thoughts on this @taisdesouzalessa: 
I like the simplicity of having no social icons and it feels more like a glimpse at the network (rather than heavily focusing on who the 4 actually are). I also like the fade to keep text visually consistent to frame the  "meet more leaders" CTA.

**Comment by xmatthewx** [comment]
Including the social icons is important. A) It tells visitors that this site is a place where they can connect with real people, awesome people. B) It tells leaders that we aren't just borrowing their face and title for our benefit, but we are helping to amplify their work, elevating their standing on twitter etc. 

We could mute the social icons a little as medium-to-dark-gray to reduce visual busyness. 

I am fine with or without the fade. I don't see a technical blocker. I also don't think it's critical for design. Uniformity can hamper readability for the sake of aesthetics (consider justified text over ragged right). Various heights on this content adds visual texture that actually catches the eye and pulls it into the content. When I look at V1, I glance across everything and only catch a word or two from all the descriptions. When I look at V2, my eye bounces around and catches a couple words from each person. In both cases, my eye finishes on Meet More, but in the second case I have a better idea of what that button will lead me to find.

**Comment by taisdesouzalessa** [comment]
I haven't thought about the scenario B, thanks for the perspective here, Matthew. I think it is very valid.

I would like to use grey for the icons here so the interface gets cleaner and the primary focus is the button that leads to People's page. I'll do the mockup and post here.

About the fade, I feel that if we are adding the social icons we have to go with the complete information. If users have the opportunity to connect with real people from the home page it makes sense we provide as much info as we can. I would keep an eye for the descriptions though because long ones will push the button "meet more leaders" away from content, which makes the information seem disconnected.

**Comment by taisdesouzalessa** [comment]
Here are the latest iterations for this page.

DESKTOP:
<img width="1025" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/25104168/22d9ee26-2374-11e7-876e-e53f06459a78.png">

MOBILE:
<img width="324" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/25106016/323bae06-237c-11e7-917e-475970a03602.png">

**Comment by mmmavis** [comment]
@xmatthewx how do we decide who to show on the people box on the homepage? If we are filtering by the `featured` flag, what do we do if there are more than 4 featured people in the database? Do we show them all?

@gvn @alanmoo I'm looking at `fetch-json.js` and I'm not sure if the `featured=True` param works at all (for "people" and "news"). It seems like the api doesn't support filtering by `featured` yet?

**Comment by xmatthewx** [comment]
The CMS supports sorting, so you should be able to grab the first 4 entries. Even better if you can grab the first 4 with featured true. 

Featured entries are the big boxes on the People page with more details button. Non-featured people are still served up to the page, smaller boxes. Filtering by featured might be useful, but if you need to do that in the component, probably okay for now.

**Comment by mmmavis** [comment]
@xmatthewx ah I see we are doing client side filtering for the People page now. I'll let @gvn and @alanmoo decide if we need to update the endpoints in `fetch-json.js` then.

**Comment by alanmoo** [comment]
I'd say "client" side filtering is fine for now, since it only happens at build time, not end user render time.
