### ISSUE TITLE
HTML Meta content

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network#229]
When linking to the site in services like Slack, the realization that the Title of the page is still "TODO". So we need that, as well as the following tags:

```
    meta(name=`description`, content=`TODO`)

    meta(property=`og:type`, content=`website`)
    meta(property=`og:site_name`, content=`TODO`)
    meta(property=`og:locale`, content=`en_US`)
    meta(property=`og:url`, content=`TODO`)
    meta(property=`og:title`, content=`TODO`)
```

**Comment by hannahkane** [comment]
@xmatthewx - would you agree this is a p1? Are you able to fill in the blanks here?

**Comment by xmatthewx** [comment]
I'd say it is a P1 add known tags, like title, and hide the rest. Not P1 to supply things like an image for sharing. Can follow up on that later.

**Comment by xmatthewx** [comment]
hardcoding prod URL

**Comment by gvn** [comment]
Also: add URL as an environment var.

**Comment by alanmoo** [comment]
Where are we getting the content for these?

**Comment by xmatthewx** [comment]
description (default) = "Mozilla Network is a global network keeping the internet open and accessible to all." 
site_name = Mozilla Network
title = page title or header
