### ISSUE TITLE
 External Dependencies

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#23]
#This is a list of the projects external dependencies. All are in motion, but could be blockers. We can track risks here.

 Marketing
 - Name of network (impacts design, content, URL) `high`
 - New brand
 - Release of web font
 - Design sign-off
 
Content
 - People content
 - Sign off on program content and links
 - Owners to finalize : Offering CTAs → destination pages
 
 Communications
 - Tell the network this is coming `high`
 - Post sign-up email engagement ready `high`
 
 Tech Services
 - CMS integration `high`
 - Join → CRM integration `high`
 - Medium account connection #24
 - Pulse API
 - End point for contact form (simple mailto desk.com)

**Comment by xmatthewx** [comment]
add or correct things @sabrinang @gvn @taisdesouzalessa

**Comment by hannahkane** [comment]
@xmatthewx - is this ticket still useful? Wondering if we should turn this into actionable items in separate tickets.

**Comment by xmatthewx** [comment]
I think we can close this. There are parallel projects not tracked in github (which feels risky), but those things will now be covered by our weekly with drivers.
