### ISSUE TITLE
Mobile - People page

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#230]
Issue: (1) People's page is broken in Firefox and Safari - iPhone (this issue doesn't happen in the responsive view on desktop browser).

![people-quote](https://cloud.githubusercontent.com/assets/22157921/24381426/2f6cecc6-1305-11e7-882a-de811b77cd09.png)

(2) When we work on fixing that, I was wondering if it is possible to make the featured people (the ones with quotes) to have a picture with full column, like in the mockup:
![people-quote-mockup](https://cloud.githubusercontent.com/assets/22157921/24381432/3820ebf6-1305-11e7-99b8-09a8c9d654ad.png)

InVision [here](https://invis.io/ZKAIKN1MN#/219982117_MOBILE-People)

@hannahkane @xmatthewx I think the fact it is broken is an important issue (1). The item (2) is a nice to have, since it makes it easier to read on mobile due to the amount of information there. Could you help me figure out the priority of this issue for engineering?  Not sure about the milestone you would like to consider for this one.

**Comment by hannahkane** [comment]
Agree that item (1) is a priority. I'll let @xmatthewx decide where it goes within the list of tickets, though, since we can use zenhub to order tickets.

**Comment by xmatthewx** [comment]
These featured people should match the original mobile comps. Feels broken as two columns, even when the text isn't floating off to the side.

**Comment by taisdesouzalessa** [comment]
closing this ticket - issues fixed.
