### ISSUE TITLE
Mobile QA - Home Page

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#233]
As per talk with Gavin here is the QA for mobile - home page. The idea is to do one of those per mobile page. I just focused on what I considered the most important aspects of this page. The visual reference have all the numbers there and you'll see that some appears more than one time because the same instruction is valid for more than one item. 

Typographic mobile styles are included here - more to come. Closed #169. 

@gvn @alanmoo let me know if this format works for you - I will do the other individual pages if you think this is a good format. @hannahkane @xmatthewx @sabrinang open for feedback in terms of process/priorities here.

Visual reference (numbers there matches numbers here): https://invis.io/ZJ9YTAGEA#/225898564_Qa-Mobile-Home-Page

- [ ] 1. Sometimes our padding is 24px, sometimes is 15px. We designed as 15px, if possible can we make it uniform? - issue happens in other pages as well.  **IMPORTANT**

- [ ] 2. Specs: Nunito Sans Light, 16px,  color: #000000;

- [ ] 3. Font size: 22px

- [ ] 4. Font size: 16px

- [ ] 5. Border: 2px - _Valid for all ghost buttons_

- [ ] 6. Font-size: 14px/ button height: 44px (ideally buttons on the pages are 44px in height - the only button smaller than that is the top nav one) - _Valid for all mobile buttons_

- [ ] 7. Nunito Sans Bold, 16px - Also, if possible, apply slating lines as per mockup _Valid for all mobile titles with this same style_

- [ ] 8. padding/margin left and right: 15px instead of 48px

- [ ] 9. font-size: 10px - _Valid for all news items, including the ones in grey_

- [ ] 10. Specs: Nunito Sans Light, 14px - _Valid for all body copy_  **IMPORTANT**

- [ ] 11. Margin-bottom:16px - _Valid for all titles with the same treatment_

- [ ] 12. Distance: 30px

- [ ] 13. Add margin

- [ ] 14. 14px, bold  - _Valid for all text links_

- [ ] 15. Remove this line "Other Opportunities" for mobile only. **IMPORTANT**

- [ ] 16. Font-size: 18px

- [ ] 17. Could we make the sign up button take the whole column? 
<img width="319" alt="screen shot 2017-03-27 at 5 34 55 pm" src="https://cloud.githubusercontent.com/assets/22157921/24383695/60461134-1313-11e7-9f4a-922da616ed0c.png">

**Comment by xmatthewx** [comment]
Let's chat about this during our stand tomorrow.

**Comment by taisdesouzalessa** [comment]
Closing this issue as we are doing a new process of QA.
