### ISSUE TITLE
Adjust News content in CMS

### ISSUE THREAD

**Issue by gvn** [mozilla/network#236]
- [x] Some glyphs are white, which makes them invisible. Gray works well.
- [x] Dates need adjusting. Everything is in 2017 right now.
- [ ] `excerpt` needs to be added for first featured item (currently "Teaching the Web...")

**Comment by gvn** [comment]
`excerpt` is blocked pending adding it to the News schema.

**Comment by hannahkane** [comment]
@KevZawacki - wondering if you can help with this ticket. Let us know if it's not clear what we're asking here.

**Comment by gvn** [comment]
Just for extra clarification, excerpt looks like the first paragraph-ish of an article based on the comps.

**Comment by xmatthewx** [comment]
We'll need an account for @KevZawacki. I don't think he's on this platform yet.  

@KevZawacki – We are ready for you to start adding news items to the site via django. You can ignore the bit about glyphs above.

**Comment by xmatthewx** [comment]
Moving glyphs task to #237 to separate design task from content.

**Comment by KevZawacki** [comment]
@xmatthewx Excellent. I'm not seeing any news curation options in the Pulse admin... where should I be looking?

Separate question: Are we manually creating the glyphs/logos for news outlets? If so, would we need to create a new one each time we feature a story from a new outlet?

**Comment by gideonthomas** [comment]
`excerpt` and Dates are ready to be updated on the CMS

**Comment by xmatthewx** [comment]
@KevZawacki - this is a separate platform. @gideonthomas can you help kevin get on board as an admin?

@KevZawacki – news items should work without an icon if you don't have it. Sabrina can prep new icons as needed, but again that should block posting.

**Comment by gideonthomas** [comment]
@xmatthewx sure thing!

@KevZawacki emailed you about how to access the api. Let me know if you run into any issues or have any questions.

**Comment by gideonthomas** [comment]
@KevZawacki it needs a build for it to show up there. I think @alanmoo might be able to help you with this.

There was also an issue with us accidentally losing the sorted order of "People" . We have gone back to the old interface for the network api so that the ability to sort people is still there. When you click on "people", on the top right corner, you can click on "Change Order" to change the order in which people will appear in the network site. I think @hannahkane tried to sort them in a way that non-featured people were in groups of two so that two non-featured people would show up on a single line. Since this data is lost, would you be able to re-order them accordingly? Apologies for the data loss.

Let me know if you have any questions about that.

**Comment by alanmoo** [comment]
@KevZawacki I'm investigating a build failure right now, I think it may be related. I'll let you know when the changes are reflected.

**Comment by xmatthewx** [comment]
Do we have same ability to sort featured news and opportunities? Will we? Or, are those done by date? Note: news on the news page should always be chronological.

**Comment by gideonthomas** [comment]
news should already be reverse chronological. You should be able to sort people and opportunities for now although once we add the Mezzanine CMS, the UX for it will change (you should still be able to sort it though).

**Comment by xmatthewx** [comment]
Any updates @alanmoo? Things good on your end @KevZawacki?

**Comment by KevZawacki** [comment]
@xmatthewx All good! Adding new content regularly.

**Comment by xmatthewx** [comment]
@chrislarry33 – you should get onboarded to CMS. Kevin can probably help. To update these news items. 

@cadecairos – can you create an account for Chris

**Comment by cadecairos** [comment]
I've created an account for Chris and sent him login details.

**Comment by xmatthewx** [comment]
Closing. This is covered by other tickets.
