### ISSUE TITLE
Revise news box to use same icon color

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#237]
@gvn reports "Some glyphs are white, which makes them invisible. Gray works well."

@sabrinang – ok to assign to you? How would you and @taisdesouzalessa estimate this? I wrote down my vote.

**Comment by sabrinang** [comment]
I separated the white versions in a folder and all are news icons are grey in gdrive: https://drive.google.com/drive/folders/0B4Q8pzCpDS_eSk4xYV80MTZxNk0?usp=sharing
<img width="1310" alt="image" src="https://cloud.githubusercontent.com/assets/2492510/24422192/8ba2db7e-13ad-11e7-845e-513a9a83ed12.png">

**Comment by sabrinang** [comment]
@gvn Do those grey icons work for you? Let me know if you need them exported differently.

**Comment by gvn** [comment]
Those should be fine. I think Kevin is putting in the content.

**Comment by sabrinang** [comment]
@xmatthewx Are there any next steps to this? If not we can close

**Comment by gvn** [comment]
Someone just needs to add them to the CMS.

**Comment by xmatthewx** [comment]
@KevZawacki – as you post news, you can grab icons from [google drive](https://drive.google.com/drive/folders/0B4Q8pzCpDS_eSk4xYV80MTZxNk0?usp=sharing) to upload.

**Comment by KevZawacki** [comment]
Will do -- thanks.

**Comment by xmatthewx** [comment]
There's a bug in this design. This requires an Author/Admin to change the icon when a news item gets bumped from the main box. That seems labor intensive and risky. 

I think we should explore a light color/pattern for that box so we can keep black text and gray icon.

**Comment by sabrinang** [comment]
<img width="1304" alt="featured news item iterations" src="https://cloud.githubusercontent.com/assets/2492510/24635539/bb5857c4-1888-11e7-9eb7-0109b3fcd94f.png">

Iterations to avoid white icon/text:
1 - featured image with news item
2 - featured image with news item with overlap box
3 - no image with grey bg (least preferred option since we use this for CTA boxes and the images bring in some colour and when I tried this with a light colour it looked busy/disconnected)

@xmatthewx feedback?

**Comment by xmatthewx** [comment]
Gray box is a quick, easy fix. Let's do that. 

I don't want to slow down News posts with a need for images. Not yet at least. Let's see if MoCo+MoFo builds a good pool of images and illustrations to go with the new brand later this year.

**Comment by xmatthewx** [comment]
When we revisit design of the site's hero and pull in more brand flavor, we can bring a little color and pattern to this box.
