### ISSUE TITLE
Create a pug-to-mezzanine-template conversion path

### ISSUE THREAD

**Issue by Pomax** [mozilla/network#239]
migrated from https://github.com/mozilla/network-api/issues/86

Either in Django, as standalone script, or even as a CLI, doesn't particularly matter. In the interest of sanity, a standalone python script probably makes the most sense for now.

From @simonwex:
> @Pomax can you add some more detail here so it can be discussed? I'm not quite sure what the tasks are here.

I literally have no idea yet either, never having looked at the network code before. What I suspect, but @gvn will have to confirm, is taking the pug template, rendering to "real" html, replacing the pug tokens (are these plain var names?) with ones that the mezzanine model needs ( which are `page.modelname.varname`) and then judiciously chopping out the parts we don't need due to mezzanine's use of `{% this template extends some base.html file %}`, with the bulk of the static code covered by that base file instead.

**Comment by gvn** [comment]
@Pomax This is the generated Mezzanine template. Can you give me the repo and subdirectory that this should go? I'll make a PR after that...

[index.html.zip](https://github.com/mozilla/network/files/877055/index.html.zip)

**Comment by Pomax** [comment]
We may want to chop this up into more than one file, because there's a lot of static HTML in this that isn't particularly "a block".

That said @cadecairos should be able to tell us which dir in the `network-api` this should go.

**Comment by gvn** [comment]
Chopping into multiple files will complicate this process. 

Can you explain why that would be necessary?

**Comment by Pomax** [comment]
longer-term need if anything about this .html file going to be shared among other templates (e.g. https://github.com/mozilla/coss/blob/mezzanine/templates/pages/pagewithcallout.html relying on https://github.com/mozilla/coss/blob/mezzanine/templates/custombase.html)

**Comment by gvn** [comment]
I believe the approach of just generating this 1 HTML file w/tokens for the Opportunity pages was what we agreed upon in our CMS call.

**Comment by Pomax** [comment]
fair enough, then we can iterate on this in future issues.

**Comment by cadecairos** [comment]
The template paths will be:
`app/networkapi/templates/custombase.html`
`app/networkapi/templates/pages/landingpage.html ` 

we could just combine the templates above into one to make the copy process a bit more simple.

Static assets will go in `/app/networkapi/landingpage/static/` in there we can have `css`,`js`, and `images`

**Comment by Pomax** [comment]
There are some additional tokens we'll need to generate into the template for injecting the live-edit stuff that Mezzanine can do, which I've marked as additional requirement for https://github.com/mozilla/network-api/pull/105. We should find out which tokens we need here, and where in the template they should go.

**Comment by Pomax** [comment]
This particular part of the work has successfully landed.
