### ISSUE TITLE
Build component for Medium articles 

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#24]
Research Medium API and build component. 

These will draw from two blogs managed by @KevZawacki, who can share any account info if needed.

**Comment by gvn** [comment]
@KevZawacki Can you provide me the Medium accounts that we want to pull?

**Comment by KevZawacki** [comment]
@gvn Sure:

https://medium.com/mozilla-internet-citizen

&

https://medium.com/read-write-participate

**Comment by gvn** [comment]
Sounds like we're not going to pull from Medium for launch, but just hardcode the content.

Do we know what content we want to feature? @xmatthewx @KevZawacki

**Comment by xmatthewx** [comment]
Given that this will be a mix of news from different sources, Medium and earned media, I no longer think we should pull from Medium for this. We can add all news in the same way: initially via Github. In the future via CMS. 

I could see adding an automatic feed later, a list of links below featured news. But let's keep that as a post-launch question. 

How's this sound?

**Comment by gvn** [comment]
That sounds good. I was planning on just making it static, but not sure what content to start with.

**Comment by xmatthewx** [comment]
We can probably close this and track static News on Home here: https://github.com/mozilla/network/issues/37#issuecomment-282093722

Related News Page here:  https://github.com/mozilla/network/issues/36#issuecomment-282086760

**Comment by gvn** [comment]
Ah good call.
