### ISSUE TITLE
Craft description for Newsletter preferences page

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#243]
When people sign-up via network site, they double opt-in on a [preferences page](https://www.mozilla.org/en-US/newsletter/existing/cacf9700-d9fc-4d6e-9396-f120ef3093ae/). This page needs a description (140 chars - unsure if this is suggested or a firm limit). All subscribers who update their preferences will also see these preferences.

@KevZawacki @Lottarao – this might already by on your radar. Just tracking here so we don't forget on our end. Let me know if I can help in any way whatsoever.

**Comment by KevZawacki** [comment]
@xmatthewx 

On the [preferences page](https://www.mozilla.org/en-US/newsletter/existing/cacf9700-d9fc-4d6e-9396-f120ef3093ae/), will this replace the "Mozilla Foundation" and/or "Mozilla Learning Network" blurbs?

Either way, some ideas:

**Mozilla Network** 
Regular dispatches on Internet health, from privacy tips and policy news to fellowship opportunities and nearby events.

**Mozilla Network** 
Your guide to the state of the web. Stay posted on developments related to privacy, security, digital inclusion and more. 

**Mozilla Network** 
Your link to the healthy Internet movement. Stay updated on news, events, resources and more.

**Mozilla Network** 
A playbook for digital citizens. Learn about the people and projects working toward a healthy Internet, and how you can get involved. 

**Mozilla Network** 
Sign up for news related to a healthy Internet.

**Comment by xmatthewx** [comment]
I will let @Lottarao @WillatMozFdn @stephaniemcv answer about the lists and copy. I'll just deliver the people 😄

**Comment by stephaniemcv** [comment]
@KevZawacki This will replace "Mozilla Learning Network" as we're sunsetting the monthly newsletter in April and the majority of those subscribers are also on the "Mozilla Foundation" list. 

My vote (for what it's worth!) is: "A playbook for digital citizens. Learn about the people and projects working toward a healthy Internet, and how you can get involved."

**Comment by stephaniemcv** [comment]
No other votes? Do I win by default?! ^_^ Would love to have a decision before we send the leader email on 5/23 however, it's not a blocker to the email send. It just looks lonely.
![2017_05_19_prefcenter_network_nodescrip](https://cloud.githubusercontent.com/assets/11812272/26272810/54de4f28-3cdf-11e7-94ac-5ce4418472a8.jpg)

**Comment by WillatMozFdn** [comment]
I like what you have there Stephanie, only ... is the first sentence necessary?  I think the second sentence is totally perfect just on its own.  "Learn about the people and projects working toward a healthy Internet, and how you can get involved."

@KevZawacki   -- that sound OK to you?

**Comment by KevZawacki** [comment]
@WillatMozFdn Yep, works for me.

**Comment by xmatthewx** [comment]
Great. Let's run with it.

**Comment by stephaniemcv** [comment]
submitted bug to get this changed on basket

**Comment by xmatthewx** [comment]
cool. i'm gonna close this.
