### ISSUE TITLE
Build revised Project page

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#249]
Let's start with an engineering review of [the design](https://github.com/mozilla/network/issues/90). Field questions. Then estimate the work.  After that, I will sort it in the queue. 

Latest comp is here https://github.com/mozilla/network/issues/90#issuecomment-289945507 and in InVision prototype.

**Comment by alanmoo** [comment]
Nothing in the comp jumps out to me as being particularly difficult to build.

**Comment by xmatthewx** [comment]
Cool. Let's do an estimate next time you have another engineer or two on the line. After that, I can sort in the  queue.

**Comment by xmatthewx** [comment]
One note @alanmoo – we will use "Games" as our heading but "game" as the tag to pull projects. Seems like the natural choice, right?
