### ISSUE TITLE
Content for Revised Projects Page

### ISSUE THREAD

**Issue by sabrinang** [mozilla/network#255]
For the revised projects page, there are project topics we showcase and we feature 2 projects from each. The design mockup projects are currently placeholders. It was mentioned on https://github.com/mozilla/network/issues/90#issuecomment-290129522 "Each section will pull in things marked as featured with the related tag or issue. For example /featured=true&tag=games"

@KevZawacki will you be able curate this featured content with Pulse and ensure the tags are defined appropriately? (In Pulse, when you search keywords "game" or "games" / "mozfest" or "mozilla festival" it pulls in different results so I am unsure if tags are influenced the same way.)

![projects-join-us-iteration 2x](https://cloud.githubusercontent.com/assets/2492510/24631082/ed5e0d8c-1873-11e7-97cd-f5886576978f.jpg)

Reference:
Desktop Screen: https://projects.invisionapp.com/d/main#/console/10016110/217251312/preview
Mobile Screen: https://projects.invisionapp.com/d/main#/console/10330313/224241770/preview

Related Issues:
Design: https://github.com/mozilla/network/issues/90
Build: https://github.com/mozilla/network/issues/249

/cc @xmatthewx

**Comment by KevZawacki** [comment]
@sabrinang Yep, I can curate this page. Let me know what precise tags end up corresponding to the four categories, and I'll ensure I use those tags accurately and universally.

**Comment by xmatthewx** [comment]
Issues will use the issue category

Privacy & Security:  https://www.mozillapulse.org/issues/online-privacy-and-security
Open Innovation: https://www.mozillapulse.org/issues/open-innovation

Others will use a tag

Mozfest: https://www.mozillapulse.org/search?keyword=mozfest
Games: https://www.mozillapulse.org/search?keyword=game

While "Games" is natural for the heading, we can use "game" as our tag. Seems to be what more users have input.

**Comment by hannahkane** [comment]
@chrislarry33 will do this. Closing as this isn't where he tracks his work.
