### ISSUE TITLE
Revised Projects + Get Involved component for Home Page

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#256]
**Issue:**
With the new required order ("Get Involved" component right after "People") our Network Home Page looks unbalanced and it doesn't flow very well, which can disorient our users.

**Proposed solution:**
We could add "Projects" inside the "Get Involved" - the rationale behind it is that by going to Pulse, people can contribute with the projects, which is a way to get involved.

Here are the proposed mockups:
[Featured on the left](https://invis.io/ZJ9YTAGEA#/227169847_Home_Page-Proj-Featuredleft)
[Featured on the right](https://invis.io/ZJ9YTAGEA#/227169848_Home_Page-Proj-Featuredright)

The image would be reworked to fit more projects and look more polished if we go with one of those options (I just scaled it for now). 

My questions are:
1. Do you think it makes sense? 
_I find a bit weird the other 3 projects have an action attached to them while the projects are more "see projects", they take the users to a more exploratory than actionable page. Maybe it is something we can solve with copy? Maybe there is another alternative?_
2. Featured project left or right? 
_I think the answer to this question is related to the decision on #237 since those two components will be close._ 
3. Could we remove the "Projects" from home page if we all agree it doesn't fit where it is now? 
_In order to make this decision we need to understand the importance and role of "Projects" on this page_

Curious to see what you think or offer a new perspective to this that I may not be seeing.

@xmatthewx @hannahkane @sabrinang

**Comment by xmatthewx** [comment]
Suggested copy: "Open-source apps. Web literacy curriculum. Guides for fostering gender equality. Discover and collaborate on projects made by and for our Network."

**Comment by taisdesouzalessa** [comment]
Here is a screenshot with new copy and only 3 items applied on this section:
<img width="515" alt="screen shot 2017-04-04 at 1 24 08 pm" src="https://cloud.githubusercontent.com/assets/22157921/24676912/bed8e902-1939-11e7-914d-0dce8049b210.png">

**Comment by xmatthewx** [comment]
I think I dig this. Curious what each of you think @hannahkane @taisdesouzalessa @sabrinang. 

Together with the new people box above, news below, feels really balanced, approachable, and strong to me.

**Comment by hannahkane** [comment]
I definitely think this is a great place to start, and with analytics + member feedback, we'll be able to see what iterations are needed.

@taisdesouzalessa - Let's keep the Fellows CTA since applications are opening this month, and temporarily remove the Leadership Training CTA (we'll bring in back soon!)

**Comment by taisdesouzalessa** [comment]
I agree with the points here about being stronger this way, with less content and also about after when get analytics and member feedback we can iterate more on this component if we see opportunities to improve.

Here is the screenshot following @hannahkane's recommendation:
 
<img width="511" alt="screen shot 2017-04-04 at 3 41 07 pm" src="https://cloud.githubusercontent.com/assets/22157921/24682117/e650ee0e-194c-11e7-8303-8033431752b9.png">

**Comment by xmatthewx** [comment]
Looking good. Let's wait before we move this engineering, see if we can get feedback from Mark/Chris

**Comment by hannahkane** [comment]
Revised estimate (5) based on newest feedback from Mark; includes both design and engineering.

**Comment by xmatthewx** [comment]
![people-feature-box](https://cloud.githubusercontent.com/assets/53411/24878627/e683525e-1e01-11e7-8fb9-83f545d3ae28.png)

**Comment by xmatthewx** [comment]
Forgive the sloppy doodle. Let's a do a mock up that uses Thimble or one of Coral's project. 

@hannah do you mind adding [Ask](https://coralproject.net/products/ask.html) or [Talk](https://coralproject.net/products/talk.html) to Pulse if you have time today? 

Join this project would go directly to the Project's get involved link. 

![get-involved-project](https://cloud.githubusercontent.com/assets/53411/24879836/1e8939ee-1e06-11e7-9aca-ffed503f8a5d.jpeg)

**Comment by taisdesouzalessa** [comment]
@xmatthewx here are the proposals for this component:

V1:
<img width="1024" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/24935439/f5e7371c-1ed6-11e7-9386-d74b465eabdc.png">

V2
<img width="1026" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/24935452/07bc94aa-1ed7-11e7-99e5-0df6279056ec.png">

One question: when user clicks on "Join this Project", would they go to https://thimble.mozilla.org/en-US/ ?

**Comment by xmatthewx** [comment]
Looks good. Is the only difference between v1 and v2 the thumbnail/box treatment? v1 looks nicer to me, but no strong opinions here. 

The Join link would be the contribute link on many projects in Pulse, not the visit link. 

Let's swap in Coral for now. They have a strong contribute page.
 - https://www.mozillapulse.org/entry/216
 - https://coralproject.net/contribute.html

**Comment by taisdesouzalessa** [comment]
The only difference is the box treatment. V1 is my favorite too - the component is more interesting there I think.

Here is Coral applied to V1:

<img width="1026" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/24970332/caeb60dc-1f68-11e7-94b7-394cad330128.png">

**Comment by xmatthewx** [comment]
"Join" link on project will use the Get Involved link from Pulse. Thumbnail should link to "View link" or be static.

**Comment by xmatthewx** [comment]
For this component, we will want to display a specific project rather than the latest featured. (Projects page will continue to pull latest.) 

We can identify project by ID ([api](https://network-pulse-api-staging.herokuapp.com/entries/157/)). We can update this ID initially in Github, but will need to add that as a thing in the CMS eventually.

**Comment by xmatthewx** [comment]
Design in most recent comment above is ready for review by engineers. https://github.com/mozilla/network/issues/256#issuecomment-293647031

Note this requirement: https://github.com/mozilla/network/issues/256#issuecomment-293668330

**Comment by xmatthewx** [comment]
Waht?! That was so fast. It looks great.
