### ISSUE TITLE
Implement Join us component (Home and subpages)

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#26]
Would be good to talk about best way to implement for Optimizely with @vojtechmzl so that staff can edit CTA copy via Optimizely dashboard.

**Comment by xmatthewx** [comment]
Join on subpages will use this interaction: https://github.com/mozilla/network/issues/45

**Comment by gvn** [comment]
Note: Join Us is a React component. Is this going to be problematic with Optimizely? @vojtechmzl ?

**Comment by alanmoo** [comment]
I think I did something with Optimizely and react for the encrypt site last year. It wasn't ideal but I think it worked.

**Comment by gvn** [comment]
I'm guessing it may work on single rendered React components, but subsequent render calls would likely knock out any DOM manipulations by Optimizely since React has its own virtual DOM.

**Comment by gvn** [comment]
Blocked pending redesign of Join Us as a standalone page.

**Comment by gvn** [comment]
Related #46
