### ISSUE TITLE
QA: Opportunities Pages

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#260]
**------TO DO LIST - UPDATED - TO ENGINEERS------**

**[Internet Health](https://network.mofostaging.net/opportunity/internet-health-report/)**

- [x]  Link “your feedback” in the grey box. Link url: https://internethealthreport.org/v01/your-feedback/ **IMPORTANT**

- [x] Link "the report" in the grey box. Link: https://internethealthreport.org/v01/ 

**[Leadership Training](https://network.mofostaging.net/opportunity/training/)**
- [x]  Include start your training button and link to https://mozilla.teachable.com/p/open-leadership-101
<img width="327" alt="screen shot 2017-04-05 at 10 57 40 am" src="https://cloud.githubusercontent.com/assets/22157921/24719363/515f8380-19ee-11e7-8ee6-9d7f86e6b592.png">

- [x] Change class of the font of the first paragraph ("The skills you need...") 
<img width="796" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/25765491/333e8290-31a2-11e7-9703-978b81701f11.png">

**[Fellowships](https://network.mofostaging.net/opportunity/fellowships/)**
- [x]   Link “open data” and “open web” **IMPORTANT**
Open data link: https://science.mozilla.org/programs/fellowships
Open web link: https://advocacy.mozilla.org/en-US/open-web-fellows/fellows2016
<img width="500" alt="screen shot 2017-04-05 at 10 44 14 am" src="https://cloud.githubusercontent.com/assets/22157921/24718860/6de5d57e-19ec-11e7-9034-5b5f2387f77c.png">

**All opportunity pages:**

- [x] Reduce space between Title and first paragraph (removing class "mt-5") of the paragraph works. _NEW REQUEST_
<img width="662" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/25590794/b40dc1cc-2e66-11e7-9075-35dc82455b3c.png">

- [x] Add more padding top/bottom to the grey box (change class from "py-md-4" to " py-md-5":
<img width="1061" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/25591040/d79e7734-2e67-11e7-9ea4-c79ca8c6b7ee.png">

- [x] MOBILE: Add more padding top and bottom in the grey box. Changing class from "py-3" to "py-5" seems to work. 
<img width="610" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/25591480/942f6bdc-2e69-11e7-8508-1aa363af4092.png">

-------------------
**DONE**
Fellowships
- [x]  Replace “Mozilla Science lab” logo  **IMPORTANT**
Image: https://github.com/mozilla/network/issues/111#issuecomment-286546109

- [x]  Form copy should be “Get involved!”/”Calls for applications begin in April of each calendar year. Be among the first to know.” - discussion in [InVision](https://invis.io/ZJ9YTAGEA#/222644514_Landing-Page-Fellowships) **IMPORTANT**
Current copy:
<img width="439" alt="screen shot 2017-04-05 at 10 46 42 am" src="https://cloud.githubusercontent.com/assets/22157921/24718956/c6f083a8-19ec-11e7-8fca-d273db823b8e.png">

- [x] With the change above, the last paragraph won't be necessary - please delete it ("Get involved!/Our fellowship calls for applications begin...") _NEW REQUEST_
<img width="608" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/25590307/df613c2a-2e64-11e7-9cce-20b006202757.png">

**[Leadership Training](https://network.mofostaging.net/opportunity/training/)**
- [x]  Form language should be “Stay Connected”/ "We'll send you updates with opportunities to add valuable skills to your leadership toolkit, and find like-minded people and projects across the Network." Discussion in [InVision](https://invis.io/ZJ9YTAGEA#/222644515_Landing-Page-Leadership-Training)  **IMPORTANT**

- [x] Increase space between paragraph and picture. Maybe add class "mt-4" to "img"?
<img width="479" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/25591677/5b223b02-2e6a-11e7-91d6-309f1a2090b2.png">

**All opportunity pages:**

- [x]  MOBILE: Increase space between last paragraph and grey box 
EXAMPLE - ideal state - bottom (2) spacing could be the same as top (1)? 
![screen-shot-2017-04-05-at-10 59 02-am](https://cloud.githubusercontent.com/assets/22157921/24721070/ff15d5f6-19f3-11e7-8ab7-cb7ecf817bc5.jpg)

Suggestion: add the class "py-5" - let me know if it is a bad idea or if it breaks other parts of the site...
<img width="360" alt="screen shot 2017-04-05 at 2 25 25 pm" src="https://cloud.githubusercontent.com/assets/22157921/24727588/616c9854-1a0b-11e7-995a-a27563a2a41f.png">

- [x]  MOBILE: Grey box should touch footer on mobile (no space between them):
<img width="209" alt="screen shot 2017-04-05 at 10 59 09 am" src="https://cloud.githubusercontent.com/assets/22157921/24721147/3b0225a6-19f4-11e7-984f-9bcb2450ce57.png">

**Comment by taisdesouzalessa** [comment]
@hannahkane - in the "Leadership training" section of this ticket, there is a button "Start Your Training". We don't know where it would link to. Could you help us figure it out? Thanks!

**Comment by hannahkane** [comment]
@taisdesouzalessa - Updated original comment with the link

**Comment by gvn** [comment]
Related: #285

**Comment by gvn** [comment]
I think there's some potential overlap with #268, so marking blocked to avoid merge conflicts.

**Comment by gvn** [comment]
Partially blocked by #285. I think we should try to make the content edits through the CMS once the pages are migrated.

**Comment by taisdesouzalessa** [comment]
Hey @gvn is this ticket still blocked? 

The "Leadership Training" page has the CTA of Fellowships and the first paragraph has another typeface and I was wondering if we could fix that in this heartbeat or if we should wait.

<img width="1151" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/25397295/a793521e-299c-11e7-99ea-ad8406fd7327.png">

**Comment by gvn** [comment]
Yes, we're still waiting for the pages to be migrated to Mezzanine AFAIK.

**Comment by taisdesouzalessa** [comment]
@gvn I reviewed this QA since new things happened since I wrote the first ticket.

I edited old requests and added "NEW REQUEST" label to the new ones so you can rethink the estimate if necessary. This ticket is big - let me know if you would prefer if I break it into smaller tickets.

**Comment by taisdesouzalessa** [comment]
I could do some of those edits myself in the CMS. Reorganized the list - Engineers can focus only in the "TO DO LIST - UPDATED".

**Comment by gvn** [comment]
Need to promote Network API to prod to unblock adding links.
