### ISSUE TITLE
QA: News Page - IMPORTANT

### ISSUE THREAD

**Issue by sabrinang** [mozilla/network#265]
- [x] **Dates are incorrect!** There are many typos with articles labelled 2017 when they should be 2016 (example: "December 2017" should be "December 2016") **IMPORTANT**

- [x] Dates should be ordered from newest at the top to the oldest on the bottom since years (2017, 2016) are displayed in that order **IMPORTANT**
<img width="868" alt="image" src="https://cloud.githubusercontent.com/assets/2492510/24732268/c5de0458-1a24-11e7-9387-190159249490.png">

- [x] https://github.com/mozilla/network/issues/108 & #284 Icons are missing on the page and can be found here: https://drive.google.com/drive/folders/0B4Q8pzCpDS_eSk4xYV80MTZxNk0 **IMPORTANT**

- [x] #284 Austin-American Statesman should be 512Tech since the URL points to 512Tech (for article "Mozilla expands its National Gigabit Project to Austin") **IMPORTANT**

- [ ] Article headings use .h4-medium-black should be 28px **IMPORTANT**

- [ ] If news item does not have an icon, left align text

**Comment by sabrinang** [comment]
related to issue #284

**Comment by gvn** [comment]
@taisdesouzalessa `h4-medium-black` is already 28px for mobile and 32px for desktop. Are you asking for it to be changed to 28px for both?

```scss
.h4-medium-black {
  font-family: Arvo;
  letter-spacing: 0.5px;
  line-height: 1.2;

  @include scaleText(28px, 32px);
}
```

**Comment by taisdesouzalessa** [comment]
The rule for this one is: (22px,28px) - 22px being mobile.
