### ISSUE TITLE
QA: People Page - IMPORTANT

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#266]
- [x] Add quote behind characters and quote seems to be cut on top (see red ellipse) **IMPORTANT**
![quote](https://cloud.githubusercontent.com/assets/22157921/24732647/07343754-1a27-11e7-9e98-6d31add1f01d.jpg)

- [x] Increase space between name and role (quote side). Maybe add the class "mt-2"?
<img width="762" alt="screen shot 2017-04-05 at 5 47 43 pm" src="https://cloud.githubusercontent.com/assets/22157921/24732749/abfad022-1a27-11e7-9e12-002515c3a1e7.png">

- [x] Small gray: line height 1.5  - _I know it affects all the pages too and all it seems fine to me. Let me know if you find some weird case if that change happens._
<img width="357" alt="screen shot 2017-04-05 at 5 10 21 pm" src="https://cloud.githubusercontent.com/assets/22157921/24732762/cd66ea66-1a27-11e7-9fc9-b19fdfae0764.png">
 
- [x] Add a bit more space between top or each card and first line of text (see red rectangles). It seems too tight.
![cards](https://cloud.githubusercontent.com/assets/22157921/24732838/6ed0e3c0-1a28-11e7-9bf9-13d352f9e02b.jpg)

- [x]  in the quotes, let's use “Nunito Sans Light Italic” (instead of using “font-style:italic”)
![italics](https://cloud.githubusercontent.com/assets/22157921/24733047/e239b73c-1a29-11e7-904b-2e9824890be3.jpg)

- [x] Add grey slant

[svg here](https://drive.google.com/open?id=0B3b1KWRwjxtoNWVYbXowajZ3eTQ)
<img width="688" alt="screen shot 2017-04-05 at 5 26 34 pm" src="https://cloud.githubusercontent.com/assets/22157921/24732248/a50232ae-1a24-11e7-8086-819c9d69e634.png">

- [x] Reduce size of "more details" button (we don't want it to compete with main CTA). Changing the font-size and padding seems to do the trick.

<img width="438" alt="screen shot 2017-04-05 at 4 55 27 pm" src="https://cloud.githubusercontent.com/assets/22157921/24732265/c3ae1fce-1a24-11e7-9547-05dd28b987b5.png">

**Comment by alanmoo** [comment]
I'm going to use the built in Bootstrap `btn-sm` class to reduce the size of that button.
