### ISSUE TITLE
QA: Global Issue - text color

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#267]
This issue affects many pages:

- [x] Copy is rendering dark gray in some pages
![gray-copy](https://cloud.githubusercontent.com/assets/22157921/24733408/519ff918-1a2c-11e7-90d5-e1265db499f6.jpg)
It seems the solution for this is in the css of body (currently is set to have a different color than black):
<img width="313" alt="screen shot 2017-04-05 at 6 22 08 pm" src="https://cloud.githubusercontent.com/assets/22157921/24733445/a1285e8a-1a2c-11e7-8f2e-5ae23834b554.png">

- [ ] Other examples of gray copy (those ones are very close to black but not #000000)
<img width="694" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/24733626/a2c850aa-1a2d-11e7-9101-ebd73a6f970b.png">
<img width="692" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/24733642/bb0d246a-1a2d-11e7-853a-1c145f394e47.png">

**Comment by mmmavis** [comment]
@taisdesouzalessa 

- `.h4-light-black`
- `.h4-headingcontract-black`
- `.h5-black`

don't appear in pure black (`#000000`) in the Sketch file. Do we wanna change these as well as body text color to `#000000`?

**Comment by taisdesouzalessa** [comment]
That explains a lot, @mmmavis . I was wondering: "where those values come from?" - and it happens it came from the design files. Yes, every copy should be pure black. Thanks for spotting that and sorry for the wrong values in Sketch!

**Comment by mmmavis** [comment]
@taisdesouzalessa I think this one is simple to fix. Do you wanna take this ticket?

/cc @alanmoo

**Comment by alanmoo** [comment]
Yeah, this might be as simple as removing the color styles and letting them (presumably) inherit black. Give it a shot if you want @taisdesouzalessa.
