### ISSUE TITLE
Implement Featured Offering component (Home)

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#27]
Simple structure for all offerings: Image, Short copy, link to page or URL, campaign ID.  

- [ ] styling

**Comment by xmatthewx** [comment]
Tracking the offering content here: https://github.com/mozilla/network/issues/47

**Comment by gvn** [comment]
From what I gather this is being redesigned. Please let me know if that's incorrect @xmatthewx. Marking blocked for now.

**Comment by gvn** [comment]
Still waiting for design. @taisdesouzalessa can you update here when you have finished?

**Comment by gvn** [comment]
Related #104

**Comment by gvn** [comment]
Closing as dupe of #141
