### ISSUE TITLE
QA: Global Issue - font weight and style 

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#276]
- [ ] Most of our Paragraph Styles are "Nunito Sans Light" or "Nunito Sans Light Italic". They are "regular" on staging or italicized using a css rule instead of using the italic version of the font. Here is the list with fixes:

<img width="322" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/24777769/c51866e6-1adb-11e7-8714-5be9c96c5d90.png">

- [ ] ".lead-white" is also "Nunito Sans Light"

**Comment by gvn** [comment]
Note: Check to see how much weight these additional fonts would add to the page. If it's high, let's try to keep it as-is.

**Comment by taisdesouzalessa** [comment]
Blocked by incoming Zilla.

**Comment by alanmoo** [comment]
Closed as per @taisdesouzalessa
