### ISSUE TITLE
QA: Home Page - IMPORTANT

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#278]
_Including just some items for now since we are currently working on iterations of this page that may change its current structure._

- [ ] Add copy to “Featured box” **IMPORTANT**
<img width="888" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/24778820/810d3da4-1ae1-11e7-8d2f-307980c86bbe.png">

- [x] Font size adjustment - Issue also listed on #265 (article headings use .h4-medium-black should be 28px). I believe if we change it in the News page it would reflect here. **IMPORTANT**

- [ ] Margins adjustment. Follow example of "Network Projects"
<img width="482" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/24779040/8effbe7c-1ae2-11e7-8ad0-34c06764beb6.png">

- [x] “Latest News”/”Get Involved” should have slants/ diagonal lines like comps. Being discussed on #204

**Comment by xmatthewx** [comment]
I suggest that we move this ticket to the backlog, since #290 could impact it (revised design). Engineers could tackle both at once. Sound okay?

**Comment by gvn** [comment]
Featured item copy can be added via CMS.

@taisdesouzalessa I'm unclear on what the padding should be inside the feature box. Right now it's `p-5`.

Can you let me know what [padding level](https://v4-alpha.getbootstrap.com/utilities/spacing/) you'd prefer?

**Comment by taisdesouzalessa** [comment]
@gvn the news box is being reviewed in this ticket: #290 - you can have a better idea of what's coming up in terms of layout. The padding we are following for all contents inside the box is: px-4 and py-5 - the screenshot below will be replaced with a new component but it is valid to illustrate content inside the box.

<img width="1099" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/25097742/9dffea7a-235a-11e7-86f4-5e81de70ef8c.png">
