### ISSUE TITLE
Implement Contact us component (About page)

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#28]
It can use a simple mailto address that goes to desk.com. @ldecoursy can provide the email address.  

Note: this component is less important than others on our list of things to tackle.

@taisdesouzalessa can decide/confirm which page or pages will have this component.

- [x] finish styling
- [x] add links

**Comment by ldecoursy** [comment]
We'll probably want a new email address, that'll be dependent on what we call the network ;) 

Alternatively we might want to link to Discourse - https://forum.learning.mozilla.org/ (can transition to all MLN vs. just learning)

**Comment by xmatthewx** [comment]
Cool. Thanks. Let's go with just an email. Less complicated, especially people who just have a question, but aren't ready for an account.

**Comment by taisdesouzalessa** [comment]
We currently have "Contact Us" component in our "Programs" page and our "About Page".

**Wireframes**
Programs: https://invis.io/ZJ9YTAGEA#/216715364_Programs

About: https://invis.io/ZJ9YTAGEA#/216715351_About

**Comment by gvn** [comment]
@xmatthewx Do we have the email address for this? What Twitter acct are we linking to?

**Comment by ldecoursy** [comment]
Email address may be dependent on final name of the network. Can we put @mozilla twitter for now?

**Comment by xmatthewx** [comment]
Kevin suggested we stick with @mozilla for twitter. Let's hide email link and pull it back when we're ready.

**Comment by taisdesouzalessa** [comment]
For now this component has only Twitter as requested in this thread:

<img width="514" alt="screen shot 2017-02-14 at 4 03 30 pm" src="https://cloud.githubusercontent.com/assets/22157921/22955108/4457db56-f2cf-11e6-8077-ca459e73d048.png">

**Comment by xmatthewx** [comment]
Tracking the question about contact/email triage and staffing in #77. We can open a new ticket when that lands. For now, let's implement with no email/contact link.

**Comment by gvn** [comment]
Blocked my missing visual assets.

**Comment by xmatthewx** [comment]
@sabrinang for visual asset. Or an MVP comp that doesn't require a visual asset.

**Comment by hannahkane** [comment]
Just clarifying that we're closing this because the page currently has a Twitter link. If the engagement team wants to add add'l links, we'll open new tickets.
