### ISSUE TITLE
Content Style Guide

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#280]
Let's agree on our standards. Make a doc. Integrate in CMS if possible. 

- [ ] internet - lower case - see Matthew's comments on #287

- [ ] Use Title Case throughout the website for titles - we will do a pass on that once the site is close to the finalization stage.

- [ ] Change -- to —  (as on About page)

**Comment by KevZawacki** [comment]
@taisdesouzalessa 

As far as I know, we are still using capitalized "Internet."

Yes, let's use em dashes: —, not --

**Comment by alanmoo** [comment]
Does this need changes on the site itself or a styleguide somewhere else?

**Comment by taisdesouzalessa** [comment]
@alanmoo - I see this issue with 2 parts:
1. The live website - it needs a review with those lenses in mind.
2. The new content that will be created by staff via CMS - in this case a styleguide would be super useful (as long as it is simple and easy to scan). Another alternative would be to embed those rules right into the CMS interface as supporting copy.

@xmatthewx @hannahkane do you think we can include part 1 in our next sprint? We could also create a ticket for discussion of the part 2 since it will be a more complicated issue to handle. Any thoughts on it?

**Comment by hannahkane** [comment]
Putting into June 2 milestone so we can discuss during today's planning meeting.

**Comment by gvn** [comment]
I think "Styleguide" is confusing because we have 2 things called style guide already:

1. A Sketch file
2. A built style guide page on the site (this isn't for public consumption, just for dev reference)

Regardless, I don't see this as ready for engineering until instances of copy that needs fixing are identified specifically.

**Comment by taisdesouzalessa** [comment]
@gvn what do you think if we call it "Content Style Guide"? - I've seen this term being used by companies before.

**Comment by xmatthewx** [comment]
I'm going to close this. The site's Editor can establish the rules and make a plan for consistency. We can dig this up when they're on board if needed.
