### ISSUE TITLE
QA: Support Page

### ISSUE THREAD

**Issue by sabrinang** [mozilla/network#282]
- [ ] **Link copy inconsistency** - Let's remove verbs and pronouns. **IMPORTANT**

Examples:
See upcoming events --> upcoming events
See our global research reports --> global research reports
Learn more about our Fellowships --> Fellowships
Read about the Digital Skills Observatory --> Digital Skills Observatory

<img width="1045" alt="image" src="https://cloud.githubusercontent.com/assets/2492510/24812709/1109454e-1b80-11e7-889f-d509a7d5007f.png">

- [ ] **Theme Boxes on Mobile**
The boxes appear really large and we can make them appear 2 images per row
<img width="616" alt="image" src="https://cloud.githubusercontent.com/assets/2492510/24810789/702fcb90-1b78-11e7-8d78-6945410733a4.png">

**Typography**

- [x] H3 with slant divider appears on themes section (related to issue https://github.com/mozilla/network/issues/204)

- [ ] left align h4 copy
<img width="875" alt="image" src="https://cloud.githubusercontent.com/assets/2492510/24811270/2f8c4ce2-1b7a-11e7-8823-9372dae18fc1.png">

**Comment by sabrinang** [comment]
@KevZawacki Do you have any recommendations on the link copy inconsistency on the [support page](https://network.mofostaging.net/support/)?

**Comment by KevZawacki** [comment]
@sabrinang Ooh, good catch!

Let's remove verbs and pronouns. So, "See our global research reports" becomes "Global research reports."
