### ISSUE TITLE
fix icons on news

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#284]
let's remove all white icons currently in the cms. let's also archive in google drive to avoid confusion

**Comment by sabrinang** [comment]
white icon folder is archived, all icons in gdrive folder is grey: https://drive.google.com/drive/folders/0B4Q8pzCpDS_eSk4xYV80MTZxNk0?usp=sharing

**Comment by xmatthewx** [comment]
Do you have access to the CMS? To update current news items? If not, ping Cade on slack to get in there.

**Comment by sabrinang** [comment]
all icons are updated on news with the CMS and are on staging
