### ISSUE TITLE
Migrate the existing landing pages to mezzanine

### ISSUE THREAD

**Issue by Pomax** [mozilla/network#285]
Filed in case we agree this is a thing we want to do.

**Comment by gvn** [comment]
Sounds like this is a thing we want to do. 

@simonwex do you still want to take this?

**Comment by simonwex** [comment]
The content is created on staging.

Waiting on this issue to verify:
https://github.com/MozillaFoundation/mofo-devops/issues/490

@cadecairos do we have a method for moving content to prod?

**Comment by cadecairos** [comment]
Unfortunately there's no automated way to copy content fron staging to production. We will have to duplicate the work on the production cms..

**Comment by gvn** [comment]
So I'm assuming that we're using the production CMS data for `network.mofostaging.net` and `network.mofoprod.net`?

**Comment by Pomax** [comment]
@cadecairos can we not do selective database copy?

**Comment by xmatthewx** [comment]
closing. @alanmoo says this is done. blocked by cloudfront configs. tracked api repo momentarily.
