### ISSUE TITLE
Change opening CTA

### ISSUE THREAD

**Issue by hannahkane** [mozilla/network#287]
"Be a champion of a healthy internet" 
Tagline: "We are a global network keeping the Internet open and accessible to all"

**Comment by taisdesouzalessa** [comment]
@hannahkane I can do a quick test in this opening CTA in desktop and mobile just to make sure it doesn't break anything on design. It will be quick.

**Comment by taisdesouzalessa** [comment]
It seems the words occupy more or less the same space so no concerns from the design standpoint. One thing to consider, though: are we going for title case or sentence case? Internet has to be capitalized (as per #280). What about the other words? 

<img width="1022" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/24881357/625aac8e-1df2-11e7-8bcc-a9fea90dbccd.png">

**Comment by hannahkane** [comment]
Thanks, @taisdesouzalessa.

Updated the original comment to reflect title case.

**Comment by xmatthewx** [comment]
Hi all. Yuliya says they've been using sentence case for their headings. And internet is lowercase with the new brand (just like mozilla). Current mozilla.org style guide for copy says uppercase for Internet, so we will likely see inconsistencies for a while, but we can look toward the future, not the past.

Sentence case headings
Lowercase internet (unless it starts a sentence)

Let's _not_ run around updating everything, just use this moving forward.

**Comment by hannahkane** [comment]
@xmatthewx - I'm fine with your decisions about sentence case and "internet," but why did you assign to me?

**Comment by taisdesouzalessa** [comment]
Thanks for the insights here @xmatthewx I will update the ticket #280 to reflect that as well. 

After the main work is done (I know this should not be a priority at the moment), could we revisit the other pages to make this treatment consistent? I feel it is important as a polished page will evoke more trust from the users.
