### ISSUE TITLE
Hero sign-up button

### ISSUE THREAD

**Issue by hannahkane** [mozilla/network#289]
- [x] Change Sign-up button in Hero to "Get Involved". 
 - [ ] Choose a new color for the button (maybe Orange?)
 - [ ] implement copy and color change
 
**Time boxing for design: 1 hr** (color only, quick test on other pages for conflict)

**Comment by sabrinang** [comment]
![button-explorations](https://cloud.githubusercontent.com/assets/2492510/24931979/4913b522-1ec4-11e7-9287-a56f5f18e223.png)

After exploring some colours, I still prefer the bright yellow as a CTA button since orange clashes with green here and white doesn't really stand out in the UI. This button treatment may also effect the other CTA buttons on the site.

I am unsure about "Get Involved" since on the sign-up page the heading says "Get Connected" and uses sign-up in the language.

@xmatthewx Feedback?

**Comment by xmatthewx** [comment]
I kinda like yellow-3 and white-4. Retro-y. Do you think the style is too different from the rest of the site? Or maybe this a style that can trickle down to other parts later?

**Comment by sabrinang** [comment]
![button-styles](https://cloud.githubusercontent.com/assets/2492510/24982654/5a00c1f8-1f97-11e7-81c5-4d78e3f27ad2.png)

Yeah, the black shadow button 2 is more visually opinionated than the rest of the site since it is quite generic at the moment so the subtle yellow shadow button 1 goes with the site currently. Our buttons can start informing the visual design and other elements of our site though.

**Comment by xmatthewx** [comment]
Let's go with #2 unless we hear something against it in Wake. Have a little fun. I like it. Mark/Chris liked it. You like it?

Feel free to start adding [Latest on Staging] labels on parts of comps that might have legacy content (so you don't have to update Be a Champ just to work on the button). Something like [this](https://cloud.githubusercontent.com/assets/53411/25016727/257fcbf0-204f-11e7-83ca-a0e86db715cb.png).

**Comment by sabrinang** [comment]
<img width="1128" alt="button original vs. alternative" src="https://cloud.githubusercontent.com/assets/2492510/25106464/693727e4-237e-11e7-9aae-9ae5bbefb1c8.png">

I got a variety of feedback on these buttons and we can utilize both in various areas. The black border shadow button can be the primary CTA to draw your eyes towards it and the yellow shadow button can be used elsewhere for CTAs to stand out a bit more from the bg as well. In the example above I believe the CTA is the same though.

### Main CTA Button:

**Border** 
width 2px & color #000000

**Shadow** 
alignment left 4px top 4px  
color #000000 opacity 75%

### CTA Button: 

**Shadow**
alignment left 4px top 4px  
color #D1BE3B

@xmatthewx  design review?

**Comment by xmatthewx** [comment]
We'll need to figure hover and active state. (And can the button click and pop?!)

I wonder if we shouldn't stick to the flat button in other locations, greater contrast between the two types. The other one feels a bit hesitant, incomplete with shadow but no outline.

**Comment by sabrinang** [comment]
<img width="764" alt="image" src="https://cloud.githubusercontent.com/assets/2492510/25149143/45fa13a4-2432-11e7-9267-07da79d2c7fd.png">

### Main CTA Button:

*Border*
width 2px & color #000000

*Shadow*
alignment left 4px top 4px
color #000000

_________________

### Hover Idea
![button-hover-example](https://cloud.githubusercontent.com/assets/2492510/25149188/6945b5f2-2432-11e7-9718-e14730902f29.gif)

The bordered button can animate into the pop out style to 8px and can turn white then active state can be yellow again.

@xmatthewx  thoughts?

**Comment by sabrinang** [comment]
<img width="1289" alt="button overview" src="https://cloud.githubusercontent.com/assets/2492510/25206917/d477523e-251f-11e7-9364-e5cd790c80dd.png">

![button-hover-revised-2](https://cloud.githubusercontent.com/assets/2492510/25206939/fa32b57c-251f-11e7-9c85-068e02b045db.gif)

**Desktop**
We can have the default with 4px shadow and on hover the button comes out more to 8px changing to white background with blue text.

**Mobile**
On mobile, we can have the 4px shadow style but we will need to adjust the padding so the button fits.

**Comment by xmatthewx** [comment]
With all the motion, I don't think we need the color change on text or background. What do you think @sabrinang?

**Comment by alanmoo** [comment]
This is ready pending design confirmation of colors.
![signup](https://cloud.githubusercontent.com/assets/1682681/25250002/fb9ef3a4-25e1-11e7-97be-5dfa25314cb7.gif)

**Comment by alanmoo** [comment]
This is ready, pending color adjustment Gif shows regular size and on a 320px wide screen

![getinvolved](https://cloud.githubusercontent.com/assets/1682681/25251115/33980ad0-25e6-11e7-881b-cab4ebc5508b.gif)

**Comment by sabrinang** [comment]
@xmatthewx I'm fine with the colour change on hover/desktop. The request was to make it pop sooo it's pretty poppy to not miss it. 

If it looks like it's too much, can you help make the call? I think I've been looking at this button too closely lol

**Comment by xmatthewx** [comment]
I think the motion is plenty by itself. If you disagree @sabrinang we can keep the colors. If you don't disagree, let's just do black on yellow. 

⏹ 💥 

@alanmoo – so it's super close to the logo, huh? yikes. i told stakeholders the phrase was too much. let's ship it.

**Comment by alanmoo** [comment]
Only at 320px (though I had to fine tune it). Any phone wider than that is fine though.

**Comment by sabrinang** [comment]
Ok, let's go black on yellow - no colour change.
