### ISSUE TITLE
News box updates

### ISSUE THREAD

**Issue by hannahkane** [mozilla/network#290]
- change title to News & Opinions
- move news above get involved
- use left side for video thumbnail. use a mozfest talk. [design required] [mobile]
- let's consider condensing items on right to more of a bulleted list, so we can list 5-ish things, rather than big font titles of 2-3. 

Estimate includes design and engineering

**Comment by sabrinang** [comment]
Some iterations on video thumbnail:
<img width="1390" alt="image" src="https://cloud.githubusercontent.com/assets/2492510/24887684/825ab568-1e12-11e7-97ee-abed5843ab09.png">

The 3rd iteration feels like it suggests an embedded video which could be misleading cause it isn't but each iteration includes that the media source is youtube so the image may not need treatment at all.

**Comment by sabrinang** [comment]
Right side news listings iterations:
![news-listing](https://cloud.githubusercontent.com/assets/2492510/24920224/5790f052-1e9b-11e7-9674-b3764b9417c7.png)
1 - original
2 - reduced heading size (does not free up much space)
3 - reduced heading size, author removed (may fit 4)
4 - reduced heading size, author + date removed (may fit 4-5)

I don't think bulleted list doesn't help save space and we are using divider lists but removing dividers makes text looked cramped and less scannable. The only way to make more space is hiding content (media outlet, author or date) but I wouldn't recommend it since having less items (like 3 before) keeps the home page focused and people can see more with "view more news".

**Comment by sabrinang** [comment]
@xmatthewx any feedback on the left thumbnail or right list of news items?

**Comment by xmatthewx** [comment]
Looking good. On the right side, option 3 might work. 

For the video, I'm not sure that we need a description. I think we need a play icon over image to indicate that people can click through to a video. We can have engineers place it, rather than photochoppin it every time. 

Right now, since the treatment between left and right is so similar, it looks like the right side might also be videos. I don't think we need the exact treatment. We could drop the Youtube name and icon, and remove the date. 

What do you think?

**Comment by sabrinang** [comment]
@xmatthewx  Iterations with options that have the right side with no authors and video icon/dark gradient included in thumbnails.

![news-listing-v2](https://cloud.githubusercontent.com/assets/2492510/24979802/74adeb28-1f8a-11e7-8508-e9669afdb327.png)

1 - removed media icon/name (youtube) and date
2 - card overlay style with media icon and date
3 - full information with 4 news items on right

1 feels a bit bare compared to the items on the right descriptive items (it makes me wonder a bit why this item doesn’t have those details though) so I prefer the 2 option as it feels balanced with the other items and I think having media icon (youtube) helps hint it is a video from the others and in the future if this left box isn’t a video post the format is still the same for the other news items in the CMS (although these hide the authors).

**Comment by xmatthewx** [comment]
Nice. I also think that Option-2 is good. 

I miss People's names, especially since we aspire to have net members as authors.  What if we did: "September 2016 by Mark Surman" or "Mark Surman · September 2016" one line?

**Comment by sabrinang** [comment]
<img width="1009" alt="image" src="https://cloud.githubusercontent.com/assets/2492510/25023569/29426f9a-204f-11e7-98ba-fb49c8642f6d.png">
Included "by Author Name · Date" on the news and this saves space. Will this effect the other news items in the CMS?

**Comment by xmatthewx** [comment]
> Will this effect the other news items in the CMS?

The CMS won't change. This is just how things get rendered. Engineers might want to update News page to match if it's the same component. That's fine by me. 

What do you think? I think this feature box looks fantastic and ready for review.

**Comment by sabrinang** [comment]
Yeah, I think we can consider how author/date treatments will look across the site - here are some screenshot comparisons:
![author-date-iteration](https://cloud.githubusercontent.com/assets/2492510/25098747/9c4de0de-235e-11e7-870b-11eece3083ac.png)
Overall, reduced margin-bottom to 0.25rem
- original italic-black and small-gray on separate lines
- both small-gray on separate lines
- both small-gray same line with dot separator

On pulse projects, I noticed a [previous version](https://mozilla.github.io/network-pulse/) it had the same line dot treatment but now it has changed to be separate in the [latest version](https://www.mozillapulse.org). What was the main reason for this change? We may want to consider separate lines too incase in the future our author line gets too long as well and to can keep it uniform. 

I think seeing it all next to each other keeping the hierarchy does make it easier to scan and highlights the author/creator but it might get too large for multiple authors... so it depends on if it is important to emphasize the author/creator more or not.

**Comment by sabrinang** [comment]
<img width="1095" alt="image" src="https://cloud.githubusercontent.com/assets/2492510/25146998/cfe29ab2-242a-11e7-9b59-6e49be3b07fd.png">

- title changed to News & Opinions
- items on right list: reduce heading size to h5 
- reduce margin bottom (0.25em) between Author and Date
- white play icon svg: https://drive.google.com/file/d/0B4Q8pzCpDS_edDNQWmxteGJha1E/view for video thumbnails
- move this news section above get involved: https://projects.invisionapp.com/d/main#/console/10016110/229529804/preview

@xmatthewx Design review?

**Comment by xmatthewx** [comment]
Looks perfect. Thanks for the clear summary of changes. 

Devs: in the end, this seem like any other news item + thumbnail + flag as video for icon. For now, we can assume we will only put videos in this prime position (that was the request), hardcode icon overlay. And... let's think about what we'd do later if someone wanted a non-video item with thumbnail.

**Comment by alanmoo** [comment]
Is the image for featured news articles supposed to be in the CMS? There doesn't currently seem to be a field for that.

**Comment by xmatthewx** [comment]
Image is not yet implemented. So, you might build this static to ship it and define new API requirements. Then discuss with CMS team. That seemed to be Gavin's approach.
