### ISSUE TITLE
Consider a minified logo and header on scroll

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#299]
Feedback from mozilla brand team: On some mozilla properties, logo will shrink to [m] icon (like favicon) for a minified header. A stacked logo will then be on one line. Such as:  [m] network.

Please note: I'm adding this to the icebox. We are not ready to design or build this at this time.

**Comment by kristinashu** [comment]
[m] is done and `Network` is no longer relevant. 

<img width="329" alt="screen shot 2017-09-14 at 3 05 42 pm" src="https://user-images.githubusercontent.com/1068783/30457922-34f364e2-995e-11e7-8708-578eefd1cfae.png">
