### ISSUE TITLE
Consider removing Titles from landing page headers

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#300]
Landing pages and other pages with our most minimal header have a small title centered. 

Feedback from brand team: Use open sans. Consider making this left aligned. 

I think we should remove this title. It's redundant with the large page header in content below. The web doesn't usually title it's pages like this.

**Comment by xmatthewx** [comment]
Little About and Project labels don't really add anything to these pages. They're redundant. 

<img width="1114" alt="screen shot 2017-04-17 at 2 36 11 pm" src="https://cloud.githubusercontent.com/assets/53411/25099661/423d02ba-237b-11e7-9aa2-53fe862d7d2a.png">
<img width="1117" alt="screen shot 2017-04-17 at 2 35 59 pm" src="https://cloud.githubusercontent.com/assets/53411/25099660/423701e4-237b-11e7-81f6-19615308863f.png">

**Comment by taisdesouzalessa** [comment]
hey @xmatthewx I would recommend to keep the title of the page on the top for some reasons:

- Our menu in desktop has the mobile behavior (it is hidden inside the hamburger), which doesn't allow us to provide context for the users about the page they are in. Usually exposed menus allow that, like in this example below. It is clear for the user that they are in the "design" session (design is highlighted in the menu).

<img width="1133" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/25398188/e18e5c54-299f-11e7-9d91-00ae033753a5.png">

- I assume that the entry point won't be the home page in all cases (I may be wrong). If users enter in the website using a direct url, the title helps them to understand where they are in the site.

- Once users scroll, they can still see the title, which decreases their cognitive load
<img width="1200" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/25398372/9e3536d4-29a0-11e7-9b05-9fa1bfee8b47.png">

I agree with your point of having some redundancies in the page (like in the screenshots you had there). However I think removing the titles will cause more harm than good.

Curious to see what you and others think :).

cc: @sabrinang

**Comment by xmatthewx** [comment]
That's true. Sites almost always indicate the current page in the nav. 

On many or most websites, once a user scrolls down, they no longer see the nav or the you-are-here indicator. Apps that use a hamburger + nav tray do not typically include a title at the top of the view once the tray is closed. They let the content speak for itself. 

When users scroll to the top of our pages again, they see a large headline that names the page. I think this is sufficient to locate them before the pop open the nav. I'm not convinced this is a problem.

**Comment by taisdesouzalessa** [comment]
@xmatthewx I see what you mean there about the headline. I have a few more points to make and I also would like to understand better where you are coming from. How about we schedule some time and talk about this issue?

**Comment by xmatthewx** [comment]
I discussed with @taisdesouzalessa. I'm going to move this into the icebox. We can revisit later if it seems useful.

**Comment by alanmoo** [comment]
Related to #582

**Comment by gvn** [comment]
Header titles have gone away as part of the nav refactor.
