### ISSUE TITLE
Left align footer content

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#301]
Feedback from Brand team: Mozilla is moving to left aligned footer content. 

As we've seen throughout the site, left aligned is our default alignment. We use centered sparingly, only for buttons and short headers in boxes on images.

**Comment by hannahkane** [comment]
Can we move this ticket to the mofo-bootstrap or mofo-design repo, and discuss in the context of all mofo web properties?

**Comment by xmatthewx** [comment]
works for me.

**Comment by hannahkane** [comment]
https://github.com/MozillaFoundation/Design/issues/233
