### ISSUE TITLE
Link to learn about Internet Health

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#307]
How do visitors learn more about a _healthy internet_ and what that term means? Can we offer a link somewhere visible but not too obtrusive?

The answer could be a text link after "We are a global network..." that says "Learn about Internet Health." Or, perhaps we need a simple bar below the people feature that says: "What's a Healthy? Learn more..."

Let's propose a few options with quick, unrefined mockups.

**Comment by xmatthewx** [comment]
@hannahkane – can I add this to the current heartbeat if we keep it design, no dev? Or is that always poor form? How do we properly handle emergent bugs and other issues?

**Comment by hannahkane** [comment]
No hard and fast rule on this, though people have strong opinions. One good rule of thumb is that if we put this in, we have to remove something with the same story point value.

**Comment by xmatthewx** [comment]
Okay. I'll put it in this milestone, but keep it in the backlog. We did drop the ticket that prompted this, though that estimation was zero or null.

**Comment by xmatthewx** [comment]
Closing. We now have a link in hero intro text and more info on the about page.
