### ISSUE TITLE
Update landing template to make "signup" an optional block

### ISSUE THREAD

**Issue by gvn** [mozilla/network#309]
Requires boolean from: https://github.com/mozilla/network-api/issues/118

**Comment by alanmoo** [comment]
The field is now optional, so we should be able to simply check if it exists before rendering it (and if not, do something else).

**Comment by xmatthewx** [comment]
@taisdesouzalessa to mock up a landing page without a sign up form.

**Comment by xmatthewx** [comment]
scope for estimation
 - [ ] mock of page without sign up form (column width)
 - [ ] update template (requires a check for null )
 - [ ] cms documentation for authors

**Comment by taisdesouzalessa** [comment]
Here is the mockup for this page, in case we don't have a form field on the right:
https://invis.io/ZJ9YTAGEA#/230741183_Landing-Page-1-Column-Template

I suggest we use a 8 column layout, center aligned (skip 2 columns on the left).

Let me know your thoughts on it.
