### ISSUE TITLE
Implement Upcoming page

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#31]
Note. We will want staff to be able to edit this page content. We should probably discuss pros/cons of components before implement that instead of html content.

UX may still be a work in progress. 

- [x] finish styling
- [x] add images

**Comment by taisdesouzalessa** [comment]
Wireframe of Upcoming page: https://invis.io/ZJ9YTAGEA#/216715367_Upcoming

**Comment by xmatthewx** [comment]
Depends on https://github.com/mozilla/network/issues/57

**Comment by taisdesouzalessa** [comment]
@xmatthewx here is the page. Please take a look at that and let me know your feedback in InVision.

https://invis.io/ZJ9YTAGEA#/216715367_Upcoming

cc: @sabrinang

**Comment by xmatthewx** [comment]
Looks great. Added some comments on copy in invision. 

We will need to grab images for each item. Yikes. And, let's decide with @gvn that it's okay if we launch without images. This page can survive without.

I filed a ticket to gather images (https://github.com/mozilla/network/issues/67). Please don't hesitate to mention program people to gather some options for you. Let's distribute the work so you can focus on more critical things.

**Comment by gvn** [comment]
Looks like images might have been removed from the comp? Either way, I'd be fine with launching without images. 👍

**Comment by taisdesouzalessa** [comment]
The comp has just placeholders for now (solid color squares) because I am focusing on building the structure to pass it on to build. 

I would highly recommend we launch with images to make this page more exciting on launch, to take opportunity of the momentum when the network sees it for the first time. 

I think we can find more generic images for launch in case we don't hear from all program people and we can replace them as we receive better ones from staff. I agree with you @xmatthewx to focus on critical things first but I think we can focus on finding those images after the critical work is done, what do you think?

**Comment by sabrinang** [comment]
These content dependent images are gathered on issue https://github.com/mozilla/network/issues/67

Some feedback to consider is the location or label of "recent" at the bottom of the upcoming page especially if it gets long. I understand the purpose of archiving/noting things that has happened but I think this page is framed for future things to expect to get involved with and people may not expect to find past things in "upcoming".

**Comment by gvn** [comment]
Blocked by review in #67

**Comment by xmatthewx** [comment]
Calling this unblocked. New images look good here: https://github.com/mozilla/network/issues/67#issuecomment-284091011

**Comment by gvn** [comment]
@xmatthewx This pages is landed, but the links are placeholder URLs. Do we have the URLs for all the items?

**Comment by gvn** [comment]
@hannahkane ^

**Comment by hannahkane** [comment]
- [ ] DSO Research: http://mozillafoundation.github.io/digital-skills-observatory/
 - [ ] MozFest Call for Proposals: https://mozillafestival.org/
 - [ ] SRCCON: https://srccon.org/
 - [ ] Open Web Fellows announced: https://advocacy.mozilla.org/en-US/open-web-fellows/fellows2016
 - [ ] Internet Health Report: https://internethealthreport.org/v01/
 - [ ] MozFest: https://mozillafestival.org/
 - [ ] Open Web Fellows application open: https://advocacy.mozilla.org/en-US/open-web-fellows/fellows2016

Recent:
 - [ ] Education Innovation Showcase - @omnignorant, is there something we can link to about this event in the "Recent events" section of the Network site, other than the expired Eventbrite page? Did we blog about it, or is there a video or photo collection or something?

**Comment by gvn** [comment]
@hannahkane @xmatthewx 

Just a reminder that we're still missing a "Education Innovation Showcase" link. Any thoughts? Should I just remove the placeholder link?

**Comment by xmatthewx** [comment]
I think that Robert is on PTO. We could use this for now: https://www.meetup.com/edtechaustin/events/236879127/

**Comment by gvn** [comment]
We're also missing links for:

- Gigabit grant applications open
- Gigabit grants announced
- The Glass Room

**Comment by hannahkane** [comment]
Sorry, didn't see those.

Link to both Gigabit items would be the same: https://learning.mozilla.org/en-US/gigabit/apply
The Glass Room: https://theglassroomnyc.org/
