### ISSUE TITLE
One image from Pulse doesn't load

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#318]
Curious: The [Internet Health Report in Pulse](https://www.mozillapulse.org/entry/12 ) has an image, but that image doesn't load on the network site's [projects page](https://network.mofostaging.net/projects/) for some reason. 

Happen for you too @alanmoo? A bug?

**Comment by alanmoo** [comment]
Hmmm yeah I'll have to look into that.

**Comment by alanmoo** [comment]
@pomax @cadecairos looks like that entry has a `thumbnail` key but not `thumbnail_url`. Which should I be using from now on?

**Comment by Pomax** [comment]
`thumbnail`

**Comment by alanmoo** [comment]
Probably; I think I just used `thumbnail_url` for the network site. This is probably a simple switch.

**Comment by Pomax** [comment]
we kept it in the network-pulse-api until we'd switched over the client, so I'll file an issue to remove it properly now

**Comment by Pomax** [comment]
or I already did and it's https://github.com/mozilla/network-pulse-api/issues/108 and we just need to do it. Yes
