### ISSUE TITLE
Design Primary (Open Menu) Navigation

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#32]
Navigation will follow a mobile nav paradigm, becoming more common on desktop. 

@taisdesouzalessa – we should list basic specs on layout and behavior. For example, does it always fill the whole screen, regardless of screen size?

**Comment by taisdesouzalessa** [comment]
Wireframe of Primary navigation: https://invis.io/ZJ9YTAGEA#/216715933_Menu-Expanded

I will think about behaviour and post it here later on

**Comment by taisdesouzalessa** [comment]
The menu should take the whole screen so users can focus on their next step of the journey. Plus, it looks cleaner. @sabrinang will style the menu. 

In terms of interaction, we could make it animate - moving from top to bottom or to fade (as this example here: https://www.ideo.com/us/). The animation will depend on our decision over the "join us" interaction (#45) - I would like to keep the animation styles consistent through the page.

**Comment by sabrinang** [comment]
Here are some menu variations:

1) left aligned with secondary column of footer links and logo and cta
2) centre align and logo
3) menu without logo or cta with Home link included

<img width="1189" alt="screen shot 2017-02-17 at 1 51 11 pm" src="https://cloud.githubusercontent.com/assets/2492510/23084638/2ce56ef2-f518-11e6-8663-b5be6450673b.png">

1, do we want to include the call-to-action on the menu? 
       - depending on the “join us” interaction, we need to think about how this works when the menu is open

1 & 2, do we want to keep the logo on the menu? 
	- is it obvious that the logo also goes home? if not, we can include “home” item like v3

3, this keeps it simple, surfaces links higher with "home" included

All versions, when the user scrolls it should scroll the menu itself and not the page beneath.

**Comment by sabrinang** [comment]
Another thing to think about is if we want to surface footer links here on the menu, we should decide which or how many should be surfaced here without making it too busy.

**Comment by xmatthewx** [comment]
Nice options. 
 - 👍 to explicit Home item, no logo. Good thinking.
 - 👍 to no Join button. Adds complexity and redundancy.
 - 👍 to footer links, but let's remove legal/privacy as you hinted.
 - 👍 I vote for left aligned. I could be swayed, but I think it's easier to read. I also like how you've treated footer links on this option.

**Comment by sabrinang** [comment]
Updated with feedback: 
      - no logo, no cta
      - simplified to twitter, chat, email, donate footer links 
      - left aligned
      - current page is 100% white bold
      - hover state is yellow bold, black underline
<img width="1125" alt="screen shot 2017-02-17 at 4 37 47 pm" src="https://cloud.githubusercontent.com/assets/2492510/23088241/76ec95e0-f52f-11e6-8b65-b1cb0504843b.png">


mockups are on the same navigation .sketch file on the "Navigation (Menu Open)" page: https://drive.google.com/file/d/0B4Q8pzCpDS_eQy1SMnhJNG1sODQ/view

Design review? @xmatthewx

**Comment by taisdesouzalessa** [comment]
Menu in the prototype: https://invis.io/ZJ9YTAGEA#/216715355_Home-Page-Opt1 
IMPORTANT: no hover stater applied there, just the overall look and feel. I LOVE it, Sabrina :).

**Comment by xmatthewx** [comment]
👍
