### ISSUE TITLE
CTA Phrase Inconsistencies

### ISSUE THREAD

**Issue by sabrinang** [mozilla/network#322]
On ticket #289, it is mentioned to change “Sign-up” button in Hero to "Get Involved" but in a previous ticket #222 we wanted to change site-wide header button to "Sign Up” and I was wondering how this affects the other buttons on the site. I'm feeling uncertain which was the final decision and the intention that determines what language we use. Beyond this button we also have other potential inconsistencies on the site if these CTAs need to align.

### Variation in Phrase
**Main CTA Button**
-  “Sign Up” to “Get Involved” according to #289

**CTA Buttons**
- Does the main CTA button and other buttons link to the same place? If so, does this language change apply to all the CTA buttons to become “Get Involved”?
    - Example: these buttons are seen on the “Get Connected” component on home page and form on landing pages

**Barn Raising Page**  cc/ @taisdesouzalessa 
- “Join the Network” button should this be “Get Involved” instead?

**Sign Up page**
    - URL: https://network.mofostaging.net/sign-up/
    - “Join the Movement” heading on green header
    - “Get Connected” main heading on page
    - “Sign Up” button and body copy
    - Should this page be called “Get Involved” now?

![potential-areas-of-inconsistencies](https://cloud.githubusercontent.com/assets/2492510/25108572/93a4f698-238b-11e7-91ea-dffe86dc8e3f.png)

**Comment by xmatthewx** [comment]
I believe this is all resolved now or filed elsewhere. @hannahkane can you confirm?

**Comment by hannahkane** [comment]
There are still inconsistencies. Despite a decision to change the button text to SIGN UP, the signup page still has an H1 reading "Get Connected", the CTA boxes all over the site use different language, and the barn raising page used "Join the Network."

I'm not sure we actually need all of these to be consistent though. Using different language can keep  content from being repetitive, especially when there's only a short distance between the H1 and the button (as on the sign up page and the CTA boxes). In the context of the barn raising, "Join the Network" feels like an appropriate CTA.

@jessevondoom - thoughts?

**Comment by kristinashu** [comment]
Now that the barn raising message is gone and other updates have been made, I believe this has been fix. But please reopen ticket if you disagree. 

<img width="973" alt="screen shot 2017-09-14 at 2 57 50 pm" src="https://user-images.githubusercontent.com/1068783/30457716-51f57cd4-995d-11e7-8c69-d2b2025de4a5.png">
<img width="1153" alt="screen shot 2017-09-14 at 2 58 11 pm" src="https://user-images.githubusercontent.com/1068783/30457715-51f04bec-995d-11e7-931d-729a3a726ed8.png">
