### ISSUE TITLE
Prep analytics for first-visit Welcome view

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#325]
During member preview, we'll have a Welcome message presented as a full site takeover. There's risk of losing visitors. 

We'll want to track a few things. Here's first stab. Needs refinement. 

 - [x] Source: if these people arrive via our preview engagement emails, we should know that. Add a source attribute to those links.  
 - [x] View: We should track Welcome views as [virtual page views](https://developers.google.com/analytics/devguides/collection/analyticsjs/single-page-applications#tracking_virtual_pageviews).
 - [x] Event: Welcome view offers 2 buttons and 2 links to proceed. We should track these as events.
 - [x] Bounce: There's high risk people will bounce. We need to track that, make sure it isn't happening too often for the 2500 people engaged via email.

**Comment by xmatthewx** [comment]
more info in #412

**Comment by alanmoo** [comment]
The buttons on the splash page now trigger events, this is live on production.

**Comment by gvn** [comment]
I'm not sure who controls the welcome email, but they'll need to append a query string. @vojtechmzl can you provide what that should be?

**Comment by gvn** [comment]
"Source: if these people arrive via our preview engagement emails, we should know that. Add a source attribute to those links."

^ Is blocked by query string and then delivering that query string to whoever controls the emails (@xmatthewx – can you assign that person?).

**Comment by hannahkane** [comment]
Adding @stephaniemcv who I believe has the keys to the welcome email.

**Comment by xmatthewx** [comment]
I believe this is all done! Including source attribute for visits via email. Closing. Reopen if needed.
