### ISSUE TITLE
CMS-ify the left column "Latest from the Network"

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network#328]
Blocked by https://github.com/mozilla/network-api/issues/133

**Comment by xmatthewx** [comment]
@hannahkane – this Latest Video feature and the similar [Get Involved Project](https://github.com/mozilla/network/issues/567) item are two CMS things somewhat dependent on Editorial strategy. Should it always be a video? Should it always be a project? Do we handle these as unique snowflakes or extend the general news and highlights models?

My gut tells me we should land other Mezz stuff, then figure out [homepage admin approach](https://github.com/mozilla/network/issues/562), and then tackle these two items. But that's just a hunch.

**Comment by xmatthewx** [comment]
@alanmoo - should we have an epic for all these content-to-mezz tickets?

**Comment by hannahkane** [comment]
@xmatthewx - I'm not sure if it matters if it's always a video. The image on the homepage is just an image with a link, right?

**Comment by alanmoo** [comment]
We have a admin panel flag for news articles indicating if they're a video, so that we can handle them differently in the front end (show the play button over the image, make it a link to the video or possibly embed the video; I don't believe we've gotten that far yet though)

**Comment by xmatthewx** [comment]
This probably requires a conversation to unblock. Some tech discussion required with @gvn @Pomax @xmatthewx.  @alanmoo to schedule.

**Comment by xmatthewx** [comment]
Note: the left or primary featured item on news may not always be a video. We should be able to identify if it is a video in the CMS, apply play overlay accordingly.

**Comment by alanmoo** [comment]
This isn't really relevant anymore with the current "Homepage admin" approach
