### ISSUE TITLE
Update Welcome message

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#329]
Updated TODOs for engineers:

 - [ ] Update paragraph that begins "If you see yourself as part of this movement..." with "If you see yourself as part of this movement – or a part of Mozilla's community – we want your feedback, your ideas, and your help building this site. This is a barn raising." [no links needed]
 - [ ] In last para, replace "mid-2017" with "the coming months"

**Comment by hannahkane** [comment]
estimate assumes this is literally just adding links

**Comment by hannahkane** [comment]
OK, we don't have pages for "name the network" or "help us build the site", so I'm going to make a call and say we should remove those CTAs. 

I think we can remove the whole paragraph. The paragraph before flows nicely into the paragraph that follow.

We do need an update to the last paragraph. Rather than saying "mid-2017" let's say, "the coming months."

Updating original comment and moving to engineering.

**Comment by xmatthewx** [comment]
Hannah, as this was authored by Mark, I propose we either run this by Jesse, or that we remove the links but keep the paragraph. 

> If you see yourself as part of this movement – or a part of Mozilla's community – we invite you to ~~name the network and~~ help us build this site [remove link or link to feedback form]. This is a barn raising.

👍 to "the coming months"

**Comment by hannahkane** [comment]
@Lottarao is running this by Mark

**Comment by xmatthewx** [comment]
@jessevondoom – we should resolve this before email goes out to network. Two links go to nowhere 😢 

Any update @Lottarao?

**Comment by jessevondoom** [comment]
Let's not kill the paragraph entirely as it provides the barn raising context, but I think edits are a good idea. +1 to the "coming months" change — let's go ahead and make that change. 

I like @xmatthewx's suggested edits to the paragraphs but I worry that keeping the "invitation" framing without a specific call to action may sound like lip service. Let's try something along the lines of:

"If you see yourself as part of this movement – or a part of Mozilla's community – we want your feedback, your ideas, and your help building this site. This is a barn raising."

Feel like specifically mentioning "feedback" ties to the ask for feedback at the top of each page, and the "we want your ideas/help" framing will work with the email engagement stuff. Yeah?

**Comment by hannahkane** [comment]
Works for me.

@gvn - assigning this to you. The first comment is updated to reflect the final decision.
