### ISSUE TITLE
Implement People page

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#33]
Depends on Profile Component #25

**Comment by gvn** [comment]
Data: https://docs.google.com/spreadsheets/d/1rwNFjojmnOHkctAIAin9Pd_rxziscGJBSWi-z2S6Bg4/edit#gid=866621792

**Comment by xmatthewx** [comment]
@gvn - 

two notes, in case you have questions: 
 - some members have an affiliation with a partner org. You will see to two people in comp that have a logo below their pic. Fine to extend the height of the card. https://projects.invisionapp.com/share/ZJ9YTAGEA#/screens/216715363
 - some cards are featured. these have a big quote AND have a button to transition to more info. simple transition (fade?) is fine. mvp.

**Comment by alanmoo** [comment]
@xmatthewx How do we determine featured cards? Do we look for a specific piece of data on that user (like a pull quote?) or a flag on the person that gets set?

**Comment by alanmoo** [comment]
Scratch that, I see a "featured" boolean in the schema.

**Comment by sabrinang** [comment]
People headshot images: https://github.com/mozilla/network/issues/67#issuecomment-284075743

**Comment by alanmoo** [comment]
Can I get some guidance on the featured people cards? Just expanding the content to 12 column feels a bit...poorly spaced.

<img width="1156" alt="image" src="https://cloud.githubusercontent.com/assets/1682681/23628345/f8d62e40-0281-11e7-9ce3-1b8a43efd336.png">

**Comment by alanmoo** [comment]
Also, is it OK to assume that the order of these people (specifically where the "featured") ones fall will be predetermined? Or should I build logic to divy up the placement of "featured" people?

**Comment by gvn** [comment]
@xmatthewx See q's above ^

**Comment by taisdesouzalessa** [comment]
Hey @alanmoo, I can answer the first question you had about being poorly spaced. The "featured" cards will have more info (3 bullet points on one side and a quote on the other side). So all the white space will be filled in with bullet points or the quote (depending on the side of the card the user is in).

Example:
<img width="976" alt="screen shot 2017-03-06 at 1 07 48 pm" src="https://cloud.githubusercontent.com/assets/22157921/23629846/d1bb1320-026d-11e7-8898-567a4c9fb4a7.png">

Prototype: https://projects.invisionapp.com/share/ZJ9YTAGEA#/screens/216715363
If you click on Hera Hussain's "more details" you can see how the interaction in action.

**Comment by xmatthewx** [comment]
I remember discussing sorting, but seems to have slipped through the cracks. @ldecoursy is our best single source for an opinion. Can we add a column to the spreadsheet? @alanmoo feel free to comment in spreadsheet if questions pop up on this content.

Featured people should have a quote and more info in spreadsheet. If they don't have that, they don't get featured. 

Lastly, we want to emphasize members, not staff. Don't put staff toward the top. Hide some staff if it feels like we have too many. 

cc @hannahkane

**Comment by ldecoursy** [comment]
Actually I'm going to defer to @KevZawacki - my understanding is that editorial would drive who we might feature at the top of the page. So depending on what projects and news are being featured, we might adjust who appears at the top of the People page to reflect that work. 

Kevin, I'm happy to go over this with you if you can share the latest launch ed cal.

**Comment by KevZawacki** [comment]
@ldecoursy That makes sense. I can curate 'People' the same way I curate 'Projects.'

Is there a spreadsheet that lists out all 'People' who will be available to feature?

**Comment by xmatthewx** [comment]
People are listed in various tabs here: https://docs.google.com/spreadsheets/d/1rwNFjojmnOHkctAIAin9Pd_rxziscGJBSWi-z2S6Bg4/edit#gid=866621792

Feel free to add a column to indicate things, maybe as high, med, low? We'll probably want some flexibility beyond editorial to balance things by member type, region, age, 'has partner logo', 'has quote'. Once you can do this via a CMS and preview, it'll be easier.

Bright green indicates approval. You can ignore other entries.

**Comment by alanmoo** [comment]
This is done, I created a follow up ticket for filling out the CMS. #146.

Any other bugs/issues with people page should be opened in a new ticket.
