### ISSUE TITLE
Featured person button has extra space above it

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network#332]
Looks like this change https://github.com/mozilla/network/blame/master/source/js/components/people/people.scss#L14 causes the following extra space above it. (Firefox Developer Edition)
<img width="193" alt="screenshot 2017-04-20 17 29 12" src="https://cloud.githubusercontent.com/assets/1682681/25253434/ecccaee0-25ee-11e7-994c-28b86cfb2371.png">

@taisdesouzalessa the "btn-sm" font size is 14px, which Bootstrap expects its small buttons to be, so that the padding and margins are consistent. If we up those buttons to 14px from 12, this works fine. Otherwise we need to rework...something about that button to make it not put off space above it.

**Comment by taisdesouzalessa** [comment]
@alanmoo - tested 14px locally and it works great. Let's use 14px then. 
Thank you for the context and attention to detail :).

**Comment by taisdesouzalessa** [comment]
@alanmoo I could do this change in a new branch and push it here for you to review if you want. I already did the change locally anyways. Let me know.

**Comment by alanmoo** [comment]
Using "btn-sm" and getting rid of the font size line? Sure, I'll review it in the morning.
