### ISSUE TITLE
font-weight for buttons and <a> is bolder than it should be

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network#335]
### Reference: Common weight name mapping 
https://developer.mozilla.org/en/docs/Web/CSS/font-weight?v=example

## From mockup
we should be using `bold`(`font-weight: 700`)  for button text AND anchors/links

<img width="506" alt="screen shot 2017-04-20 at 8 10 11 pm" src="https://cloud.githubusercontent.com/assets/2896608/25261114/7dacb192-2605-11e7-8653-bc737daec2e6.png">

---

## In code...
it is set to `900` (`Black (Heavy)`)

**On Chrome/Firefox there is barely any diff between font-weight `700` and `900`**

<img width="904" alt="screen shot 2017-04-20 at 8 15 05 pm" src="https://cloud.githubusercontent.com/assets/2896608/25261304/41425634-2606-11e7-86e5-d2babee8c3eb.png">

**While on Safari...**

<img width="879" alt="screen shot 2017-04-20 at 8 14 01 pm" src="https://cloud.githubusercontent.com/assets/2896608/25261234/fefb5bcc-2605-11e7-82dd-9d416a7f3edc.png">

**Comment by taisdesouzalessa** [comment]
@hannahkane do you think we could add this issue to our queue? Not sure about the priority in comparison with other issues but it would be nice to get a fix for it.

**Comment by hannahkane** [comment]
@taisdesouzalessa - will you bring this up at stand today? I think this can be a team decision.

**Comment by taisdesouzalessa** [comment]
Yes, I can do that! Thanks, Hannah.
