### ISSUE TITLE
Implement Campaign page

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#34]
Design of this page should be discussed to identify MVP version. 

@HPaulJohnson will discuss what campaigns should populate this page with the advocacy team.

**Comment by taisdesouzalessa** [comment]
Wireframe of Campaign page: https://invis.io/ZJ9YTAGEA#/216715353_Campaigns

**Comment by xmatthewx** [comment]
Depends on https://github.com/mozilla/network/issues/56

**Comment by taisdesouzalessa** [comment]
Page comp here: https://invis.io/ZJ9YTAGEA#/216715353_Campaigns

**Comment by xmatthewx** [comment]
depends on https://github.com/mozilla/network/issues/56

**Comment by xmatthewx** [comment]
Closing. Will reopen after we plan iteration based on feedback.
