### ISSUE TITLE
QA - Projects Page

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#340]
Summary by @xmatthewx: 
 - [ ] Project thumb and title should link to entry in Pulse (1)
 - [ ] Fix heading hierarchy as described in (2) below
 - [ ] Add "Discover much more..." as in mockup under (3) below. No need to add sign-up form.
 - [ ] Add space on mobile between each category and its 1st project (4)

In addition: 
 - [ ] Change categories to be our 5 issues. (drop games and mozfest). Tais and Hannah will provide copy. 

------- 
Original comment: 

Since the last changes on this page's structure we didn't have a QA. This ticket is to cover that.

- [ ] 1.  In the "Projects" page, the right side projects are not clickable. For instance, users can't click on "The Internet Health Report" or "The Glass Room". We have to add the links for all of them - could we add the links in both image and title? If not possible, in the title is the preference. The link should go to individual cards in Pulse. For instance, "The Internet health Report" should go to here: https://www.mozillapulse.org/entry/12. "The Glass Room" to here: https://www.mozillapulse.org/entry/15
<img width="1187" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/25460107/a49e9262-2a96-11e7-8b8e-7daa4c8f03fe.png">

- [ ] 2. Currently the projects for each section have the title with size h4 and we should have it as h5. It is important because the hierarchy is broken on mobile of we don't have it as h5

**STAGED VERSION:**
<img width="1190" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/25360076/8026474a-28fc-11e7-9948-2057ad39cfe4.png">

**DESIRED STATE:**
The solution is to implement the same classes as we have in the home page (People box) - "h5-black" and "my-2"
<img width="1199" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/25360138/c8f05f10-28fc-11e7-90e6-29024270b5ba.png">

- [ ] 3. The staged solution doesn't have the closing text ("Discover much more...") 
<img width="699" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/25589922/42125d6a-2e63-11e7-8136-81a075350672.png">

- [ ] 4. MOBILE: Increase space between category links and the following image.
<img width="321" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/25360840/bc44c4a6-28ff-11e7-9079-7b04dee62784.png">

adding the class "mb-5" seems to work
<img width="359" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/25360867/e7e36252-28ff-11e7-9be3-319f8ff51ae3.png">

**Comment by xmatthewx** [comment]
This all looks good. We don't need to add the sign-up form to this page. It's got plenty of actions for users. 

To summarize: 
 - [ ] Project thumb and title should link to entry in Pulse (1)
 - [ ] Fix heading hierarchy as described in (2) above
 - [ ] Add "Discover much more..." as in mockup under (3) above. No need to add sign-up form.
 - [ ] Add space on mobile between each category and its 1st project (4)

**Comment by xmatthewx** [comment]
Since a project can have multiple issues attached, there will be duplicates. For now, we can ask admins to check and fix, but we should add some logic now or later.

**Comment by taisdesouzalessa** [comment]
Here is the copy for the remaining 3 issues:

DIGITAL INCLUSION: Projects, articles and tools that promote an open and inclusive internet. 
DECENTRALIZATION: A healthy internet needs the collaboration of all of us: big/small businesses and individuals from around the world. 
WEB LITERACY: Everyday Internet users should be able to shape their own Internet experience. These projects empower people to shape the web.

New comp for reference:
https://invis.io/ZJ9YTAGEA#/217251312_Projects-Join-Us-Iteration

@hannahkane could you please review this copy? Feel free to change them as you see fit.

**Comment by hannahkane** [comment]
@taisdesouzalessa - here are my suggested edits.

If you think these are good, please move to the "Ready for engineering" column.

DIGITAL INCLUSION: Projects, articles and tools that promote an open and inclusive internet.
DECENTRALIZATION: Projects that help ensure that the internet is controlled by many, rather than just a handful of global technology giants.
WEB LITERACY: Projects that empower people to shape their own internet experience.

**Comment by taisdesouzalessa** [comment]
Those work great, thanks!

Here is the comp with updated copy:
https://invis.io/ZJ9YTAGEA#/217251312_Projects-Join-Us-Iteration
