### ISSUE TITLE
QA - page headers

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#341]
Issue: currently our headers titles are not aligned to the left and some of them are very chunky. Our intent with the initial design was to make those headers short so the content below it could be displayed as much as possible ("show, don't tell").

![headers](https://cloud.githubusercontent.com/assets/22157921/25362298/ebe2c75a-2907-11e7-9d3d-015916643a3f.jpg)

- [ ] 1. Please align copy to the left and allow 6 columns for both title and sub. I achieved that by removing the classes highlighted with a purple box - maybe it is not the best solution, the Engineers would know it better :).
<img width="663" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/25362342/26b48d82-2908-11e7-9ac1-f36fe2776d76.png">

**Comment by alanmoo** [comment]
This looks like it contradicts work done for https://github.com/mozilla/network/issues/268

**Comment by taisdesouzalessa** [comment]
Hey @alanmoo in #268 the ask was to skip one column (left and right) in order to narrow the content of specific pages: "Sign Up", "About", "News" and "Opportunities". Those changes didn't apply to hero (green part on the top of the page) of any page.
