### ISSUE TITLE
User jouney: from website to first e-mail

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#344]
**Issue:**
Once our audience decide to sign up to our mailing list, they will receive an e-mail about our news and offers. Ideally, the e-mails would match the expectations they had when they clicked the "Sign Up" button. The challenge we have is that - at this moment - all the users will be sent to the same e-mail list even though their expectations differ from page to page.

Here is a diagram that illustrates the situation:
<img width="967" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/25407682/1a6248cc-29c0-11e7-9a41-41c1dddabc56.png">

**Proposed solution**
One way to tackle this issue at the website level is to have a standard message close to the sign up button that explains to the audience that they will receive news about internet health, blended with others. I am not sure how we would do it since the CMS allows the editors to choose the copy they want. It is something we will have to think about.

**Comment by xmatthewx** [comment]
@jessevondoom - The Salesforce CRM is very limited at this stage. SIgn-up, and you get an email with double opt-in on a very confusing page (#207). 

We'll track pages that pull people into our list (fellowships vs mozfest) as raw URL (rather than friendly label), but users will get the same generic email reply. Staff should be able to get a report of people who join related to their programs, but will this be instant? Monthly?

This isn't critical for the launch next week, but is a thing we should look at soon. We should decide if we need a design solution as @taisdesouzalessa suggests b/c the tech will come too slowly.

**Comment by xmatthewx** [comment]
We can roll this over to the next heartbeat. Probably requires a real-time discussion. We could turn off the feature for authors to customize the sign-up copy, or only allow them to add a short statement to the standard form.

**Comment by xmatthewx** [comment]
This sprint we will hold a cross-team conversation on constraints and goals.

**Comment by taisdesouzalessa** [comment]
Having a conversation in #503 with Stephanie to have a more detailed view of the current experience - it would be useful to have the complete diagram handy for our cross-team meeting.

**Comment by taisdesouzalessa** [comment]
Hey team, @stephaniemcv  helped me figure out the missing pieces of the current journey (from website to e-mail...yay! Thanks, Stephanie). This is a snapshot of the journey as is now. RedPen: https://redpen.io/ws99a7bd530a91b791
![double-opt-in](https://user-images.githubusercontent.com/22157921/27109992-0c5fe6be-505b-11e7-971f-12b79b7edafb.jpg)

By looking at this diagram, some elements stood out to me:
1. As we discussed before, there is an opportunity to align expectations in our website copy with what happens once users receive their first e-mail.
2.  If they are already subscribed to any Mozilla or Firefox mailing list, it seems they receive the Pulse e-mail. I think there is an opportunity of alignment in this flow.
3. If they are already subscribed to the Mozilla Leadership Network mailing list there are currently no mechanism in place to let them know they are already registered. People may forget they registered so I think there is an opportunity improve this flow as well.

@xmatthewx @hannahkane @jessevondoom

**Comment by hannahkane** [comment]
@taisdesouzalessa will schedule a follow-up meeting to discuss with @jessevondoom @xmatthewx @stephaniemcv, etc.

**Comment by taisdesouzalessa** [comment]
Booked a 30min meeting next Friday (July  14th).

**Comment by taisdesouzalessa** [comment]
Here is the click through of the experience showed on the map earlier in this thread. I feel it is less confusing now, let me know what you think, ok? I'll attach it to our meeting agenda.
https://docs.google.com/a/mozilla.com/presentation/d/1tdxC1aqiJsEWC-k5ekQZpS1lbGJThZiNWtcnMfvH9L8/edit?usp=sharing

@jessevondoom @hannahkane @stephaniemcv @sabrinang @xmatthewx

**Comment by xmatthewx** [comment]
Great conversation today. Thanks @taisdesouzalessa for the insightful deck. And thanks @stephaniemcv for all the expert info. 

Next steps? I think we close this ticket after we open two new ones: 
 - [ ] explore sign-up scenarios and welcome messages
 - [ ] refine existing forms and language on the site for more clarity

Anything else?

**Comment by stephaniemcv** [comment]
Here is the deck I mentioned: <a href="https://docs.google.com/a/mozilla.com/presentation/d/1xH8c1ItRqHCmOpGE481IG7FX6VfYrk8uGl8PlIaVBlI/edit?usp=sharing">The Need for Improved Audience Segmentation</a>

**Comment by hannahkane** [comment]
@xmatthewx - how are #585 and #586?

**Comment by kristinashu** [comment]
@xmatthewx can we close this ticket?

**Comment by xmatthewx** [comment]
Closing. Follow up filed elsewhere as Hannah commented above.
