### ISSUE TITLE
Improve score on the SSL observatory

### ISSUE THREAD

**Issue by cadecairos** [mozilla/network#346]
We currently score an F.

we should add a Content Security Policy - which we'll need to do using a meta tag, since this is hosted on S3.

I'll need to look a bit more into the other headers (HSTS, X-Content-Type-Options, X-XSS-Protection)

**Comment by hannahkane** [comment]
Noting we have a ticket for the CSP meta tag (#390)

@cadecairos - can you please file add'l tickets as needed? Thanks!

**Comment by cadecairos** [comment]
At this time, we'll only be able to implement the CSP header in #390, because S3 powered websites lack the ability to add HTTP headers. I'm working on getting access to a new AWS feature called Lambda@Edge that will let me write middleware code which can add Headers to Cloudfront responses on the fly.

**Comment by alanmoo** [comment]
@cadecairos Any update on this?

**Comment by cadecairos** [comment]
We've added a CSP meta tag - but that's all we can do right now. Unfortunately, the observatory doesn't pick up on these tags though so we don't get a score boost.

I have not heard back from Amazon about Lambda@edge

**Comment by xmatthewx** [comment]
tracking in #504
