### ISSUE TITLE
Finalize About page

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#35]
- [x] finish styling
- [x] add links
- [x] add images (or remove blue) (blue in build is where they're missing)

**Comment by taisdesouzalessa** [comment]
Mockup here: https://invis.io/ZJ9YTAGEA#/216715351_About

Still have to work some details with Sabrina such as: "Join Us" with arrow or not/ color of top nav/color of "About Us" in the top nav.

**Comment by gvn** [comment]
Is there an up to date sketch file?

**Comment by taisdesouzalessa** [comment]
Hey @gvn just added the updated file in the dev folder - name of the file: "all-wireframes-ui.sketch". Home Page (Home Page - hero opt 3) and About Us (About) comps are there with the correct spacings.  The About Us page may have some changes - discussing the addition of some buttons or text links with Matthew but the main structure is there. 

NOTE: we updated one little thing in the "styles" sheet. The H5 now have line height of 24px now.

**Comment by sabrinang** [comment]
I think in the first two paragraphs we should work in linking some of these pages: 
https://www.mozilla.org/en-US/mission/
https://www.mozilla.org/en-US/about/manifesto/
https://www.mozilla.org/en-US/internet-health/

to help contextualize and ground the "movement" or "mission" explanation we are describing to our audience. This would be an opportunity to tie the network to the work of the wider Mozilla org (related #73).

**Comment by xmatthewx** [comment]
> I think in the first two paragraphs we should work in linking some of these pages

Agreed. Let's hold off on this until we consolidate feedback and make a plan for iteration. Seems like we also might want a few words on the issues. We can loop in Kevin after we've formed our opinion.

**Comment by xmatthewx** [comment]
Let's build what we have in comp. We can update copy later.
