### ISSUE TITLE
Revised IA 

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#352]
Description:
The Network website has evolved a lot since we first start building it. In order to discuss about metrics and what success looks like I think it is important we have an overview of the site through its IA. In this way we can see the relationship between pages, the external links and other items that can guide our discussion and at the same time allow us to see all the pages' content in one place.

Here is [the link](https://invis.io/ZJ9YTAGEA#/230975900_IA-Network-V2) for the revised IA. Feel free to add comments on InVision. 

Preview below.
![ia-network-v2 2x](https://cloud.githubusercontent.com/assets/22157921/25460448/639f4dcc-2a98-11e7-9fe0-dbb7a3042f96.jpg)

**Comment by taisdesouzalessa** [comment]
From this exercise some questions came to mind:

1. The "Get Involved" button in this page links to the page itself. I question if we should exclude the button from this page (less distractions, more chances users will fill the form)
<img width="1154" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/25460010/138c5804-2a96-11e7-8583-570b36c7e257.png">

2. In the "Projects" page, the right side projects don't have any links attached to it. For instance, users can't click on "The Internet Health Report" or "The Glass Room". Was this intentional or we need to fix it and add the links?
<img width="1187" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/25460107/a49e9262-2a96-11e7-8b8e-7daa4c8f03fe.png">

@xmatthewx @hannahkane @sabrinang @gvn @alanmoo - curious to hear your thoughts on those.

**Comment by alanmoo** [comment]
Both points make sense, go ahead and open up tickets for them individually.

**Comment by hannahkane** [comment]
Closing, but @taisdesouzalessa will keep the maintenance of the IA map as a personal TODO
