### ISSUE TITLE
Consolidate env methodologies

### ISSUE THREAD

**Issue by gvn** [mozilla/network#353]
Currently we're using both a standard `.env` and also a JSON based system (see `/env`).

We should consolidate to just use the standard `.env`.

**Comment by gvn** [comment]
Related #350

**Comment by alanmoo** [comment]
Ah I searched for a sample.env file before approving #350 but since it wasn't there I assumed the repo didn't use env vars.

**Comment by gvn** [comment]
No worries. I'm going to put a `defaults.env` in as part of this work.
