### ISSUE TITLE
Project page enhancements

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#357]
Project page will be central to the member preview. Members will be invited to add a project to pulse (directly, or to a google form). 

Two updates: 
 - Change categories to 5 issues. We now have more quality projects, can drop games and mozfest, add other 3 issues. 
 - And link from Project thumb/title to the project on Pulse.

**Comment by xmatthewx** [comment]
@taisdesouzalessa – Can you craft draft phrase for the 3 new issues? Get feedback from Hannah?

**Comment by taisdesouzalessa** [comment]
@xmatthewx you mean the sentences that go after each title? For instance: "Privacy and Security: **Tools, tips, apps and more for staying safe online.**" - Yep I can do that and add to the mockup.

**Comment by xmatthewx** [comment]
Duplicate. Tracking in #340. 

@taisdesouzalessa - you can add copy in that thread.
