### ISSUE TITLE
Simplify Profiles. Add link to interviews

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#359]
We would like to simplify the design and implementation of featured profiles on the people page. 

These were designed when we still didn't have strong sense of the content. They're good, but can be stronger.

On large, featured cards:
  - [x] Remove More button and diagonal lines
  - [x] Keep quote. Add basic info to front like smaller cards
  - [x] Drop bio field altogether. 
  - [x] Move large quote mark up and left. something like left: -0.06em; top: -0.035em; 

On all cards:
 - [ ] add a link to "Read Interview" (required DB field)

Also good to do: 
 - [ ] confirm analytics are setup on story engine site

@taisdesouzalessa will add more polish to this, but here's a rough mockup: 

<img width="1170" alt="screen shot 2017-04-27 at 2 49 52 pm" src="https://cloud.githubusercontent.com/assets/53411/25506711/eeb43dc2-2b75-11e7-993f-4dea31f3a564.png">

**Comment by taisdesouzalessa** [comment]
Hey @xmatthewx, once I started doing some design studies on those cards I felt that adding a "Read Interview" in the small cards makes this page seem very busy. Also, it makes sense that only big cards have "Read Interview" so we have something more to offer in the featured cards than only an extra quote. So I take back what I what I said about having the link in all the cards.

There are 2 proposals:

PROPOSAL 1
Desktop
<img width="1024" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/25508842/9d83ba56-2b69-11e7-9309-d300a4dd5ca0.png">
Mobile:
<img width="317" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/25508860/b561904e-2b69-11e7-80f6-41c23335e7ac.png">

PROPOSAL 2 
Desktop
<img width="1023" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/25508913/06a09bda-2b6a-11e7-944d-912cc2127ddf.png">

Mobile
<img width="320" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/25508938/261fff5a-2b6a-11e7-879e-8cd461b73caf.png">

I find the proposal number 2 seems more clean and balanced. What do you think?

cc: @sabrinang

**Comment by xmatthewx** [comment]
👍 on proposal 2 and big cards only. Quote signifies we have an interview.

**Comment by taisdesouzalessa** [comment]
1 exception for this rule: "Karolina Andersdotter" has a quote but no interview. In this case we shouldn't have the "read interview" link on the bottom -or- we make "Karolina" a small card and add another person that has interview as featured.

**Comment by gvn** [comment]
Partially blocked by https://github.com/mozilla/network-api/issues/168
