### ISSUE TITLE
Implement News page

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#36]
This page is linked from button below News on the homepage. Not in the primary Nav menu, but should sit at /news. 

Note. We will want staff to be able to edit this page content. We should probably discuss pros/cons of components before we implement that instead of html content.

Kevin has identified earned media that populate this page. @taisdesouzalessa can share copy for implementation.

**Comment by taisdesouzalessa** [comment]
Wireframe of News page: https://invis.io/ZJ9YTAGEA#/216715362_News

[List made by Kevin ](https://docs.google.com/a/mozilla.com/spreadsheets/d/1UsnRgCYYLsQJvicJGKHgn3TU7dfwZ3icn9PaAzxtrmg/edit?usp=sharing)

**Comment by taisdesouzalessa** [comment]
Mockup of New Page: https://invis.io/ZJ9YTAGEA#/216715362_News

**Comment by taisdesouzalessa** [comment]
Are we adding the whole news list made by Kevin? I was just wondering how long this list will be to see if we should have a "load more" button or display the list in full. Also, depending on the size of the list, maybe we could add a search feature?

**Comment by xmatthewx** [comment]
I think the list will remain short. Maybe 2 dozen things per year? We can revisit page design later, after the page is bursting with content. Curious what @KevZawacki thinks.

**Comment by KevZawacki** [comment]
@xmatthewx I would say 10-12 items per year. Allows us to be selective and showcase only the top-tier placements.

**Comment by gvn** [comment]
Do we know what items we want to launch with?

**Comment by xmatthewx** [comment]
Link to Kevin's spreadsheet is in comment above. https://github.com/mozilla/network/issues/36#issuecomment-276243591
