### ISSUE TITLE
Implement News component (Home)

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#37]
The homepage includes a section of News. 

News includes 4 items
 - 2 medium blog posts written by us
 - 2 earned medium items

This will be updated regularly by editorial staff (@KevZawacki). Medium could be pulled in via API, but all 4 items will have the same presentation, labeled with the publication. So, they could also be manually added just like the earned media. 

Let's aim for simplicity.

cc @sabrinang @taisdesouzalessa 

May or may not depend on: https://github.com/mozilla/network/issues/24

**Comment by taisdesouzalessa** [comment]
Current state of news in the home page in this wireframe: https://invis.io/ZJ9YTAGEA#/216715355_Home-Page-Opt1

I will connect with Sabrina to see how we will style this section.

**Comment by KevZawacki** [comment]
@taisdesouzalessa @xmatthewx Looks great! One suggestion: Can we style it so news stories and Medium blogs have distinct presentation? At the moment, the New Statesmen story looks like it might be a Medium blog.

**Comment by xmatthewx** [comment]
For medium, we should probably name the blog, not medium, which could help. 

 - [Medium icon] Mozilla's Read, Write, Participate
 - [Mozilla icon] Mozilla Blog
 - [Newstatesman icon] Newstatesman
 - [CNBC icon] CNBC

Another idea – we could also add a by line if helpful. When it's by us, we could say "By Mark Surman, Mozilla".

**Comment by xmatthewx** [comment]
Please note: for design, let's not attempt to use logos. A simple, square favicons + publication's name in text will do the job well. I fear that we will introduce unnecessary complexity if we attempt to use logos. Most publications should have a nice, high-res icon for use on device home screens, easy for us to access.

**Comment by taisdesouzalessa** [comment]
@xmatthewx @KevZawacki 

Here is how this section is looking like, we did the modifications based on your comments:
<img width="781" alt="screen shot 2017-02-06 at 4 37 40 pm" src="https://cloud.githubusercontent.com/assets/22157921/22672779/d896a766-ec8a-11e6-94b4-b9e2bb062f29.png">

Here is the full page: https://invis.io/ZJ9YTAGEA#/216715355_Home-Page-Opt1

cc: @sabrinang

**Comment by xmatthewx** [comment]
Treatment of stories looks good. 

@sabrinang mentioned using a bold color block behind item on the left. I think that would be much more inline with the brand and the site's style. I don't think we need complexity of a photo with an overlay.

**Comment by taisdesouzalessa** [comment]
Bold color block implemented: https://invis.io/ZJ9YTAGEA#/216715355_Home-Page-Opt1
The color may change depending on decision on the theme colors of the site. Removing the tag design from here.

**Comment by gvn** [comment]
Do we have initial content approved for launch?

**Comment by sabrinang** [comment]
Medium / Earned media feature tab has 4 yellow rows selected by Kevin:
https://docs.google.com/spreadsheets/d/1UsnRgCYYLsQJvicJGKHgn3TU7dfwZ3icn9PaAzxtrmg/edit#gid=2020397576
