### ISSUE TITLE
Add Upcoming to CMS?

### ISSUE THREAD

**Issue by gvn** [mozilla/network#373]
Right now the Upcoming page is still using static JSON.

Do we want to add the Upcoming model to the CMS?

**Comment by gvn** [comment]
@xmatthewx ^

**Comment by xmatthewx** [comment]
I don't think we should do that right now. This page makes less sense now that we have a mature set of Get Involved features.

**Comment by gvn** [comment]
Should we leave this ticket open and Icebox it, or is that page going away?

**Comment by xmatthewx** [comment]
Let's icebox. Wait and see.

**Comment by xmatthewx** [comment]
tracking in #551
