### ISSUE TITLE
Shrink logo to [m] on small screens

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#379]
**Issue:**
Currently our users that are viewing the site from iPhone 4 or 5 see the website as displayed below:

<img width="716" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/25643834/cc7f76b0-2f56-11e7-8f28-2c4d0605d823.png">

As you can see there, the logo and CTA "Get Involved" are too close.

**Proposed solution:**
We could use just the "M" for mobile view, as seen in https://www.mozilla.org/en-US/

<img width="357" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/25643890/20276a70-2f57-11e7-92c8-a67a8047d277.png">

**Comment by taisdesouzalessa** [comment]
Asked Yuliya in Slack and we are good to use the logo as in "mozilla.org", yay! I'll give this an estimate of 1 for design and I assume it is +1 for engineers? @gvn @alanmoo feel free to add more points to the estimate.

cc: @hannahkane

**Comment by xmatthewx** [comment]
@hannahkane @gvn @alanmoo @mmmavis  – we should confirm estimate on this. Moving to top of backlog if someone has bandwidth. Requires file prep by a designer first.

**Comment by alanmoo** [comment]
Can we use the file from mozilla.org?

**Comment by taisdesouzalessa** [comment]
The Network site's logo is a little bit bigger than mozilla.org's logo. I recommend we use an "m" with the same height as our Network site logo. I can save it as svg.

**Comment by taisdesouzalessa** [comment]
Here is the SVG file for the "m" (I optimized the original svg to decrease file size): https://drive.google.com/a/mozilla.com/file/d/0B3b1KWRwjxtoelFqOFFFa01rVEk/view?usp=sharing

The current height of the full version of the logo is 28px. We should keep it the same for the short "m" version.
