### ISSUE TITLE
Tweak line height in headings (all pages other than home)

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#381]
Line height should be increased so that highlight always has space between lines. 

Example:
<img width="650" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/25677331/6d3fa0b8-2ffa-11e7-8ea5-b33cc4ba0c54.png">

**Comment by taisdesouzalessa** [comment]
@gvn this issue seems like a minor tweak in the css: ".h1-white" class. I could change it locally here and push it to GitHub for review. What do you think?

**Comment by gvn** [comment]
Sure! Feel free to make PRs whenever you like!
