### ISSUE TITLE
Add CSP Meta tag

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network#390]
@cadecairos Any more details required?

**Comment by cadecairos** [comment]
Handy Firefox addon helps you generate CSP for a site: https://addons.mozilla.org/en-US/firefox/addon/laboratory-by-mozilla/

**Comment by gvn** [comment]
@cadecairos Is there any particular standard we have at this point for our policies?

**Comment by cadecairos** [comment]
I'd just say avoid inline code, data URIs for JS, and use https for all resources that aren't 'self' (so localdev works)

I should write a guide for implementing CSP.

**Comment by cadecairos** [comment]
Also, no eval 😁
