### ISSUE TITLE
add contribute.json

### ISSUE THREAD

**Issue by cadecairos** [mozilla/network#391]
> contribute.json is a text file placed within the root directory of a website that describes what it is, where its source exists, what technologies it uses, and how to reach support and contribute. contribute.json is a Mozilla standard used to describe all active Mozilla websites and projects. 

https://wiki.mozilla.org/Security/Guidelines/Web_Security#contribute.json

**Comment by acabunoc** [comment]
I did _not_ know this was a standard! Interesting...

**Comment by alanmoo** [comment]
Where does this get used?

**Comment by cadecairos** [comment]
If a bug is ever filed in BZ, they use it to track down people who can address the issues.
