### ISSUE TITLE
People Page - social media icons bug

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#394]
Featured Cards have Social Media  icons (LinkedIn and Twitter) but the links don't work when clicked on DESKTOP view - they work on MOBILE view though.
GIF showing the issue:
![bug-people-desktop](https://cloud.githubusercontent.com/assets/22157921/25817068/0c31fa16-33db-11e7-83a9-0baf1ae596f1.gif)

**Comment by taisdesouzalessa** [comment]
@hannahkane here is the ticked for the People Page bug

**Comment by xmatthewx** [comment]
icons for what? social?  I haven't checked, but it's possible interview links are ready, bjut just need some urls in the cms.

**Comment by taisdesouzalessa** [comment]
Social icons. I edited the ticket to add some clarity.

**Comment by gvn** [comment]
Interview links may not have been added to the CMS yet, but the functionality to display them is in the code.
