### ISSUE TITLE
Home Page headline

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#40]
Currently we have 3 options of home page headlines. Copy deck [here ](https://docs.google.com/a/mozilla.com/document/d/1MDfeLsJimZm6glqOQENv-aOe_XOTgT-j0H-NJo39FXs/edit?usp=sharing)

1. **Where Technology Meets Humanity**
We believe a healthy Internet and healthy society are deeply entwined. Join the network.

2. **For Those Who Believe the Internet is Worth Protecting**
The Mozilla Network is a diverse coalition fighting for a healthy web.

3. **We Are Champions of a Healthy Internet**
The Mozilla Networks brings together diverse leaders of all types. Join its ranks.

Just flagging we have 3 options so we can choose one in the future for the release. The CTA should change depending on the chosen headline:

1. **Join the Mozilla Network**
Community. Training. Funding. What you need to build a healthy web.

2. and 3. **Join Our Ranks** 
Access to bright minds, passionate community and invaluable resources.

Wireframes (use keyboard side arrows to navigate through the 3 options):
https://invis.io/ZJ9YTAGEA#/216715779_Home-Page-Opt1_-2-

cc: @xmatthewx @KevZawacki

**Comment by xmatthewx** [comment]
For launch, let's plan to use "We are champions..." as the default unless we learn something while meeting with staff. We can test the other two. 

@sabrinang – I noticed that one design (with the colorful buildings) uses "Where Tech meets Humanity" with a shortened secondary heading. Let's correct that if it's accidental so we stick with official copy.

**Comment by xmatthewx** [comment]
I think we can close this. Reopen a new ticket when we're ready for testing.
