### ISSUE TITLE
Graphic for soft-launch email

### ISSUE THREAD

**Issue by hannahkane** [mozilla/network#403]
We don't necessarily need to do this, but if there's time, it might be nice to include an image in the email that's going out to soft-launch the site. Final copy TK.

**Comment by sabrinang** [comment]
Is there more details on how this email is built or sent? Can we have a template like this (similar to some of the recent mozilla emails sent out):
![email example](https://cloud.githubusercontent.com/assets/2492510/25875014/395b6794-34ca-11e7-8091-7e7e5e790158.png)

Would we want the image in graphic to have any copy on it? Also, if there is any copy known for this email that can help inform the image let me know.

I'll continue iterating on the image itself.

**Comment by hannahkane** [comment]
@stephaniemcv - can you please advise on what we can do in terms of the template for the Network emails? See @sabrinang's questions above. Thanks!

**Comment by stephaniemcv** [comment]
@sabrinang the email is being sent from our Salesforce Marketing Cloud Platform. 

We can do something similar, here's more details about the current template.
Body Font: Geneva, Tahoma, Verdana, sans-serif;
Body Font color: #555555
Title Font color: #464646
Body Button & Link color: #0c99d5 (we could make the case to change the button color, but text links can't change)
Background color: #e1e1e1 (can't change it) 

There are two choices for images, a hero image that would need to be 640px width or a single column image that would need to be 250px width. 

My only flag is that this style of email is more geared toward newsletter type content (different content blocks), which I'm not sure if that's what this first email is. But I haven't seen finalized content to make a good recommendation. Finalized copy should be dropped in or linked into this [RASCI](https://docs.google.com/document/d/1tF1QFDSBJ9U4tv6Es8_tpDp-EiZREB1XKSBvKuaLZQM/edit?usp=sharing)

**Comment by hannahkane** [comment]
Thanks, @stephaniemcv.

Good point re: this isn't exactly a newsletter. Maybe I've confused this issue by asking for a graphic.

I just put the nearly-final copy into the [RASCI doc](https://docs.google.com/document/d/1tF1QFDSBJ9U4tv6Es8_tpDp-EiZREB1XKSBvKuaLZQM/edit). Would love your recommendation about the best way to treat this from a design perspective.

**Comment by sabrinang** [comment]
Ideas for email (hero or column image):
![email-examples](https://cloud.githubusercontent.com/assets/2492510/25968421/487c328a-3646-11e7-8624-f7524d8c7b60.png)
Body Font: Can we change to another sans-serif such as [Nunito Sans](https://fonts.google.com/specimen/Nunito+Sans)? I know e-mail type is very particular.
Body Font color: #000000
Title Font color: #000000
Body Button: #FFED00 (yellow)
Link color: #0c99d5 (text links can't change)
Background color: #e1e1e1 (can't change)

Thank you for the RACI doc and image reference. I have taken some language from the email copy in some image ideas:
<img width="1273" alt="email image ideas" src="https://cloud.githubusercontent.com/assets/2492510/25969562/36024fb4-364a-11e7-81f4-9286068f8c00.png">



@stephaniemcv You flagged that this style of email is more geared toward newsletter type content, how does a email for non-newletter content look like and are the templates different?

**Comment by hannahkane** [comment]
I really love the hero version, @sabrinang. I think it does a nice of conveying the people-focus, and doesn't seem too newsletter-y to me.

Curious what others think, though. Perhaps @Lottarao will want to weigh in?

**Comment by stephaniemcv** [comment]
I am also a fan of the hero version. 

I was referring more to the style of separate content blocks, that's more used in newsletters so different articles have their own section. What you've put together looks great for non-newsletter content!

**Comment by WillatMozFdn** [comment]
Big fan of the hero version over here too ... the hexagon just isn't doing it for me.  :-) 

One note -- if you want to use a different font, that's highly discouraged under our new template guidelines.  You could ask Michele (who heads up the LCM team) for an exception to that rule, but ... I think you'd have to have a really really good reason....

**Comment by sabrinang** [comment]
Thank you all for the feedback and using the original Geneva typeface sounds good to adhere to template guidelines:
![network email](https://cloud.githubusercontent.com/assets/2492510/26012710/4dd30c08-370a-11e7-89b8-0e269e2c6a54.png)
Body Font: Geneva, Tahoma, Verdana, sans-serif;
Body Font color: #000000
Title Font color: #000000
Body Button: #FFED00 (yellow)
Link color: #0c99d5 (text links can't change)
Background color: #e1e1e1 (can't change)

@stephaniemcv Here is the image on gdrive here: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eUzl5cVJOb0k3WWM/view?usp=sharing
Updated logo available here: https://mozilla.ninja/our-logo/

**Comment by hannahkane** [comment]
Nice, @sabrinang!

I'm going to close this issue.
