### ISSUE TITLE
Add link from Profile to Project

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#410]
Most of the People profiled on the site will have a project in pulse. We should design and build a link from the profile card to projects. Maybe something like.... Working on: project title as link

**Comment by xmatthewx** [comment]
@sabrinang this could be a good ticket for you. Light exploration of a couple of options.

**Comment by sabrinang** [comment]
![project links](https://user-images.githubusercontent.com/2492510/26892248-818ae00e-4b6c-11e7-8d53-d236b54000f5.jpg)
1 - have a link to a list of members projects (near see interview link in feature card)
   - this can surface a large list of projects within pulse but doesn't surface any content at a glance on people page itself
  - it may be useful to surface number of projects a member has from pulse (easier to maintain)

or

2 - in the members description section we can add a list of projects they are working on   
 - this can provide some context of projects they are working on at a glance but this list can get long if not curated (example: if they have 5+ projects)
 - each project can link directly to the project in pulse (or the project itself)

**Comment by xmatthewx** [comment]
This is great. I think both options make sense, depending on what we can do technically (we can't do option 1 yet, but hope to have that at some point). I like the Titles in Option 2.

This might be done design-wise. What do you think?

Next, we have to figure out if we want to implement a quick simple feature (type info in CMS), or if we want to wait until the tech can do this stuff more automatically. 

Let's keep this open and see how related work shapes up.

**Comment by sabrinang** [comment]
Option 2 project links list with proposed layout in issue #430
![proposed project links](https://user-images.githubusercontent.com/2492510/27110339-744a8f2a-505d-11e7-82f5-4ec353483baf.png)

**Comment by xmatthewx** [comment]
This is good. I'm think we can call this done, file an engineering ticket to implement, but keep it in the backlog to sort and figure out where this sits on the priority list. 

@sabrinang – what do you think?

**Comment by sabrinang** [comment]
@xmatthewx Sounds good to me. Closing this ticket and filed implementation ticket here https://github.com/mozilla/network/issues/520
