### ISSUE TITLE
Build 404 Page

### ISSUE THREAD

**Issue by sabrinang** [mozilla/network#411]
**Mockup**
![error 404](https://cloud.githubusercontent.com/assets/2492510/26011422/e3c5e53c-3705-11e7-9d2a-9f00b3871e4d.jpg)
.sketch file on gdrive updated: https://drive.google.com/a/mozilla.com/file/d/0B3b1KWRwjxtoVW5TeTVfM2VDYlk/view?usp=sharing

**Copy**
Title: Uh oh!
Subtitle: Sorry, the page does not exist.
Body copy: Contact us or...
Button: `Go to Home Page`

**Graphic** 
.svg or .png asset exported here: https://drive.google.com/drive/u/1/folders/0B4Q8pzCpDS_eTFNsaVpVZlhiY2M

**Related Issue**
More context on design on issue: https://github.com/mozilla/network/issues/143

**Comment by gvn** [comment]
@sabrinang @xmatthewx – What is the URL for "Contact us"?

**Comment by sabrinang** [comment]
<img width="1502" alt="image" src="https://cloud.githubusercontent.com/assets/2492510/26463501/5a9cb752-4139-11e7-9be3-036bc76bc56b.png">

I would use the same as this section so I believe twitter is what we are using as a contact point but @hannahkane mentioned we have an email network@mozillafoundation.org that goes to a google group.
