### ISSUE TITLE
Analytics: identify mvp events to track

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#412]
TASK:
identify 10 or less simple events to track in the Network site. Matthew and I discussed those events and I'll prepare a list based on that conversation and post it here. 

Conversation started on #64

**Comment by taisdesouzalessa** [comment]
Hey @xmatthewx - could you please take a look at the spreadsheet and see if those categories are clear enough for our purposes? 

I never labeled things into GA so I am relying on your expertise here :). Feel free to edit the spreadsheet as you see fit. 

https://docs.google.com/a/mozilla.com/spreadsheets/d/1x-CP_HYaAs3oRv2cjbSFu8w5Z938E4cyHQ3hvh17c6c/edit?usp=sharing

**Comment by xmatthewx** [comment]
Thanks @taisdesouzalessa. I created a [new tab](https://docs.google.com/spreadsheets/d/1x-CP_HYaAs3oRv2cjbSFu8w5Z938E4cyHQ3hvh17c6c/edit#gid=779058050) to consolidate our events actions into a shorter set of categories. 

@vojtechmzl - How are our names and labels? @stephaniemcv do you know about event tracking in google analytics?

Events in GA are fairly convoluted and unintuitive. For example, categories organize assessment, but actions with same name are counted across categories. Events are also limited/throttled. Is this list a good place to start?

**Comment by taisdesouzalessa** [comment]
Love the consolidated view, Matthew. Simple and easy to understand. Thanks for organizing them!

**Comment by vojtechmzl** [comment]
These look great! The only one I'd suggest to add is someone clicking on the Signup button and possibly where that click happened. This would help indicate intent to sign up, which in comparison with the event that tracks form submissions could help us get a sense of form attrition. The labeling is otherwise clear. Let me know if there is anything I can do to support the deployment of these.

**Comment by xmatthewx** [comment]
Excellent. Yep, thanks. Closing. Filed new ticket for implementation.
