### ISSUE TITLE
Kevin is the best (doube--dashes)

### ISSUE THREAD

**Issue by flukeout** [mozilla/network#416]
On the About Us page. Look at all -- those -- double dashes. With spaces around them.

* Please use ``&mdash;`` in the markup, and ditch the spaces around them.

![image](https://cloud.githubusercontent.com/assets/25212/26076060/5cd9c002-396c-11e7-904d-985ce136e03a.png)

cc @KevZawacki 

![image](https://cloud.githubusercontent.com/assets/25212/26076114/8002c4c0-396c-11e7-8853-644dd9599bd6.png)

![image](https://cloud.githubusercontent.com/assets/25212/26076125/85adc44c-396c-11e7-9dc7-82a3c7e49ac8.png)

Just -- wow.

**Comment by KevZawacki** [comment]
Humiliating. Will "em it" going forward, as they say. At least I didn't use tildes.

**Comment by flukeout** [comment]
Also, remove spaces around mdash from the quote here...

![image](https://cloud.githubusercontent.com/assets/25212/26080425/6b6257ce-397b-11e7-9974-208cf8db0e50.png)

On people page.

**Comment by xmatthewx** [comment]
> Also, remove spaces around mdash

This content will be entered via CMS by more and more staff. Design/Devs won't be able to track and correct all of it.

**Comment by KevZawacki** [comment]
@xmatthewx Happy to do dash style updates, if it's helpful. Do I have access to webpage content via the Network API I use for news curation?

**Comment by xmatthewx** [comment]
@KevZawacki you can access news, people profiles, get involved items. for pages, only the ones linked from get involved are editable at this time.

**Comment by KevZawacki** [comment]
Got it. I've just amended dashes / spacing for Kylee, Karolina, Alex, Mmaki and Achintya quotes. 

I *think* that's all I can do at this time. Let me know if I can help further.

**Comment by xmatthewx** [comment]
Thanks @KevZawacki you're the best. I'm going to retitle this issue accordingly.

**Comment by KevZawacki** [comment]
@xmatthewx Issue bookmarked.

**Comment by flukeout** [comment]
<img width="532" alt="image" src="https://cloud.githubusercontent.com/assets/25212/26128484/6f1f6cb4-3a41-11e7-88d9-4baf9a681c13.png">

**Comment by KevZawacki** [comment]
@flukeout is a [legend](https://youtu.be/q7Sj4uHp0s4?t=2m28s).
