### ISSUE TITLE
QA > Don't hard-code the Menu label into the .svg image

### ISSUE THREAD

**Issue by flukeout** [mozilla/network#418]
The hamburger has the word menu in the SVG, which will be hard to localize...

![image](https://cloud.githubusercontent.com/assets/25212/26076718/85bb3c24-396e-11e7-9fce-2c215ee6d37c.png)

**Comment by gvn** [comment]
I think our plan for localization is to just remove the `MENU` label.

**Comment by kristinashu** [comment]
Closing since this has a `won't fix` tag.
