### ISSUE TITLE
QA > Link Supporter Org Logos

### ISSUE THREAD

**Issue by flukeout** [mozilla/network#419]
At the bottom of the About page there are a bunch of logos, I think they should be clickable...

![image](https://cloud.githubusercontent.com/assets/25212/26077504/1acd165a-3971-11e7-82d4-f6243c39f712.png)

**Comment by hannahkane** [comment]
This was intentional. We don't want people to leave.

**Comment by hannahkane** [comment]
Sorry, just saw that @xmatthewx Iceboxed it. Matthew - can you advise whether you want to do this?

**Comment by hannahkane** [comment]
From @sabrinang and @taisdesouzalessa - should we make them look less clickable?

**Comment by xmatthewx** [comment]
Let's not worry about this until someone outside of MoFo says "hey, moar click please". We've got bigger fish to fry 🐟 🦈  🔥  🍽

**Comment by gvn** [comment]
In that case, can we close this? @xmatthewx
