### ISSUE TITLE
CMS Requirements

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#42]
Network site requires a CMS so that content can remain fresh and move as quickly as our programs. 

This issue recaptures previous conversations. It offers high level info for planning, not all the nitty gritty details for implementation. 

**Next steps**: 
1) engineering review of details
2) engineering proposal with estimation 

### Summary

The CMS needs to manage specific content types pulled into the site. It does not need to manage the entire site. See images below.

### User/Author Requirements
 - Updates by a half dozen staff members (a mix of Comms, Program, Design) 
 - Can require comfort with HTML
 - Can require adherence to style guide and documented patterns (e.g. html for an image and caption)
 - Can require review by an editor or peer
 - Cannot require production support

### Content Requirements
 - Enable staff to edit key info pages
   - These include Programs, About, Upcoming and other _specific pages with unstructured content_
 - Enable staff to create a new subpage with
   - a custom slug (e.g. /programs/custom-slug)
   - fields: Title, Subhead, CRM ID, Body (Markdown or HTML)
   - author option: Standard Join form with custom heading and subhead
 - Enable staff to add a new "Offering" featured on homepage
   - fields: heading, subhead, link URL, image, CRM ID
   - author options: sort order, future publish date,  
   - note: should be compatible with Optimizely integration on frontend to manage test content
 - Enable staff to add a new member "Profile"
   - fields: name, city, country, relationship (staff, board, advisory, ...), image, linkedin url, twitter, ...
   - author option: sort order
   - note: This is a gallery of representative members with official relationship to the network. Page may link to a directory, but this is not a directory.
 - Enable staff to add a new "Campaign" or "Earned media" item
   - Similar to the "Offering" content type. A few fields, no unstructured html content.
   - Note: These two content types could initially be managed on an unstructured page to simplify initial build. They are less critical than other CMS requirements. 

### Future Requirements
 - Translations
   - We will want the ability to translate key info pages

### Non Requirements

The cost to manage the entire site or integrate all content into the CMS, such as content that will change very infrequently, is likely greater than the cost to make updates via Github or with engineering help. These things could be added later as needs become evident. They should not slow development of core requirements.

Things out of scope:
 - Management of UI localization
 - Management of the site navigation
 - Management of content on structured pages. E.g. Intro text on the People page, or headings between sections of the homepage. 
 - Management of structured content within unstructured pages (e.g. embedded things)
 - Management of members
 - Management of blog posts

### Reference

![home](https://cloud.githubusercontent.com/assets/53411/22452697/1e3ba1a2-e747-11e6-8d5b-b508806103d9.png)

![page](https://cloud.githubusercontent.com/assets/53411/22452752/9806c840-e747-11e6-922c-962dff2a1fed.png)

**Comment by simonwex** [comment]
Question for you, @xmatthewx: is this part supposed to be CMS, or CRM:
![image](https://cloud.githubusercontent.com/assets/25260/22807358/5c17854a-eedb-11e6-8c79-3e192fa4c6d7.png)

**Comment by xmatthewx** [comment]
The idea here: When authoring a page in CMS, you could specify to include the join form or not. The form itself would not be managed by the CMS. The CMS could allow you to specify strings to inject a header/subhead, but that's not MVP. Form can remain generic.

**Comment by xmatthewx** [comment]
As you dig into this work, I think there are a few things we need to document and review with designers:

 - **A detailed write up of the content requirements.** Could be a strawperson API. 
 - **A global look at the admin requirements.** On content items, we'll need control of things like future publish date, expiration date, sort order. We should also have a state that includes draft, pending review, published, archived. We'll need user levels and privileges. This is not obviously not trivial. This requirements are a higher priority than many others things.
 - **A look forward at how this grows.** We'll need a core set of staff creating pages today, but not long after, we'll want to enable other trusted individuals to create a `Page` as well. (e.g. Fellow creates a landing page for their initiative; Partner creates a landing page for their campaign or whitepaper). 

### Measure twice, cut once. 📐 😃 

A few thoughts below on "Pages" to consider. _This list is opinionated_. Let's discuss, debate, correct, and document a shared set of guidelines to help us set good expectations and stay on track.  

 - **Page content** Beyond our meta-fields, page content should be unstructured. We don't need to worry about specialized templates and should prioritize access and flexibility. 
   - There are **two pages types**: `Primary pages`; other `Pages`.
   - We will have a **limited set of bespoke aka `Primary pages`** that can be handled differently than the rest. Some `Primary pages` (home, people) will pull in content. Their content should be otherwise stable and edited via github for now. A few other `Primary pages` (programs, upcoming), can be crafted with support from designers/devs, updated carefully by trained Editors. There will be very few of these bespoke `Primary pages`. We could create an Admin option to turn off wysiwyg on bespoke pages. Otherwise, let's not invest our CMS energy on these `Primary pages`. 
   - **All other `Pages` will be kept simple** (e.g. [Health report landing](https://projects.invisionapp.com/share/ZJ9YTAGEA#/screens/216715361)) so they can be created by non-technical staff. We will offer documentation on crafting effective and nice looking pages. A join form can be inserted, with little options for authors.  
   - If a **proposed page is specialized**, it either should be high value to justify bespoke support (NSF challenge landing), or it should be a common content-type handled elsewhere (pulse, teachable, github project, medium, planet, etc) for those specific needs. If it's not high value or highly repeatable, it should be simplified.

Any clarifying questions? Let's find time to discuss over vidyo and then pull the conversation back here.

**Comment by xmatthewx** [comment]
cms standup pad: https://public.etherpad-mozilla.org/p/cms-stand

**Comment by gideonthomas** [comment]
cc @cadecairos @gideonthomas to make this issue easier to find

**Comment by kristinashu** [comment]
Great ticket! cc @a-kilroy @Pomax

**Comment by alanmoo** [comment]
I believe this is no longer needed, as we've done the work. Feel free to re-open if you disagree.
