### ISSUE TITLE
QA > "Curious of..." sounds weird, change to "Curious about..."

### ISSUE THREAD

**Issue by flukeout** [mozilla/network#420]
In the we'd love to hear from you section, it sounds a bit strange and I think its a fringe usage to pair "of" with "curious"...

![image](https://cloud.githubusercontent.com/assets/25212/26077563/5d81bf50-3971-11e7-9e6e-2a84ca524c30.png)

cc @KevZawacki what do you think about this one -- I'm curious of your thoughts.

**Comment by KevZawacki** [comment]
@flukeout Good catch. Should definitely be "curious **about**"

**Comment by xmatthewx** [comment]
@taisdesouzalessa - interested in taking on this small copy change? not a huge priority, but a chance to practice your git skills.

**Comment by kristinashu** [comment]
This has been updated https://network.mofostaging.net/get-involved/
