### ISSUE TITLE
QA > Extremely faint underline on hovered items in Main Menu

### ISSUE THREAD

**Issue by flukeout** [mozilla/network#421]
It's pretty hard to see the underlines when you hover the items...

![image](https://cloud.githubusercontent.com/assets/25212/26077621/89a0ee58-3971-11e7-946a-2869d4ac258b.png)

Consider removing the underline or making it brighter? cc @taisdesouzalessa @sabrinang

**Comment by hannahkane** [comment]
won't fix. :)

@flukeout - if you're upset, talk to @taisdesouzalessa and @sabrinang
