### ISSUE TITLE
QA > Missing "BBC" logo on a story on the news page.

### ISSUE THREAD

**Issue by flukeout** [mozilla/network#422]
At the top of https://network.mofoprod.net/news/ there are two stories credited to the BBC, the first one is missing the logo...

![image](https://cloud.githubusercontent.com/assets/25212/26077992/e1c3dd60-3972-11e7-9fd5-ae0f68a4fe8b.png)

**Comment by xmatthewx** [comment]
cc @KevZawacki possible author

**Comment by KevZawacki** [comment]
Thanks for the heads up! Looks like someone beat me to the fix. Let me know if I can help further.
