### ISSUE TITLE
QA > Hover state on email signup button is barely noticeable.

### ISSUE THREAD

**Issue by flukeout** [mozilla/network#425]
I'd increase the contrast between the normal and hovered states...

![image](https://cloud.githubusercontent.com/assets/25212/26079554/06b76574-3978-11e7-9bcd-d777ffb2af8e.png)

**Comment by hannahkane** [comment]
estimate is just design

**Comment by gvn** [comment]
@taisdesouzalessa If you want to come up with a darker color value for hover I can tweak this pretty easily.

**Comment by taisdesouzalessa** [comment]
@gvn here is the hex code for the button hover state: `#e7c121` - I connected with Kristina and Sabrina to make sure we are all aligned on it.

Here are the demos of it in action:
![signup-yellow3](https://user-images.githubusercontent.com/22157921/31636553-c640a182-b27f-11e7-8bc6-025f48ebd3cb.gif)
![signup-yellow4](https://user-images.githubusercontent.com/22157921/31636555-c83ba856-b27f-11e7-9d47-9d0ed7a35d3c.gif)

Tks!

**Comment by taisdesouzalessa** [comment]
It looks great @gvn! Closing this issue.
