### ISSUE TITLE
QA > All caps links are a bit hard to read

### ISSUE THREAD

**Issue by flukeout** [mozilla/network#427]
I think buttons are OK being all caps, but some of these links are harder to read than they need to be I think, case in point on the Support Page...

![image](https://cloud.githubusercontent.com/assets/25212/26080075/d18f0166-3979-11e7-9a36-04cd191e769f.png)

**Comment by taisdesouzalessa** [comment]
Hey @flukeout thanks for your feedback here. I agree that the all caps have the potential to slow down the reading a bit. However, I don't think it is a big issue for those links. I don't see it complicating the usability of the page. 

Just to add some context here, we decide to make the links as all caps to make it easier to scan as some of the pages are very heavy in content. 

I discussed this ticket with @sabrinang and we decided to leave them as all caps for now and if we see any problems surfacing with users in the future related to that, we may change it. Do you have any concern, from your perspective?

**Comment by flukeout** [comment]
👍
