### ISSUE TITLE
QA > Make "Theme" images a bit more clickable...

### ISSUE THREAD

**Issue by flukeout** [mozilla/network#428]
These don't really look clickable compared to the other things on the site like the links and buttons. We could improve this by adding some kind of navigation indicator (graphic / icon) or adding a hover state maybe?

![image](https://cloud.githubusercontent.com/assets/25212/26080126/044f3026-397a-11e7-9cb5-bbfe64df4ade.png)

**Comment by hannahkane** [comment]
@xmatthewx @jessevondoom - is it likely we're going to keep themes for the long-term?

**Comment by xmatthewx** [comment]
Not likely to keep them as currently designed. Likely move to a page that introduces the Issues and these themes.
