### ISSUE TITLE
CRM & Offerings follow-up

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#43]
When people Join the network via a specific offerings, will program staff be notified? How will they track, follow up, and engage? 

Background: One of our featured offerings will be a Training, a mini DIY experience distilled by @zee-moz from the open leadership training series. The site will leverage this offering to encourage site visitors to join the network, adding their email to our CRM. 

Questions: @arlissc – how will @zee-moz know that a new person joined via this offering? Can program staff craft an auto-reply related to their offering? Will these program staff have access to the CRM to contact these individuals or the group of all?

Next step: Let's figure out the short-term and long-term limits to this engagement so we can plan accordingly.

cc @HPaulJohnson @ldecoursy

**Comment by zee-moz** [comment]
To follow up on this issue, the mini-DIY leadership training experience has a "next steps" section that can serve as a way to route people to different opportunities. What links and information should be there? We could send people to a form with options, like : send me info about applying to Mozfest, the latest advocacy campaign, fellowship opportunities, Clubs, Groups, etc. Or we could include lineks to landing pages with for those events.

**Comment by xmatthewx** [comment]
Hey @arlissc can you take a look at this thread and questions above?

**Comment by xmatthewx** [comment]
Meeting with @WillatMozFdn and 270 to discuss engagement plans. Includes @acabunoc @Melechuga. One among us will report back.

**Comment by arlissc** [comment]
@xmatthewx - great, looking forward to hearing what is decided.

**Comment by xmatthewx** [comment]
@arlissc – I will move this ticket forward to this week. Take a look at questions from me and from @zee-moz above. Maybe you have more enough now to share?

cc @hannahkane

**Comment by WillatMozFdn** [comment]
For now, given that "interest areas" (as an overall framework) is a larger and more long-term infosys and CRM project involving MoCo as well ... we need to assume that the Network and its email program will launch WITHOUT the ability for subscribers to specify interest areas.  I'm not saying that we shouldn't be thinking about it, of course, but we (MoFo) can't act unilaterally on this one without MoCo, because we share the same email signup and CRM/data design processes. Figuring out how interest areas work is definitely not going be resolved in Q1.

**Comment by hannahkane** [comment]
@WillatMozFdn - will we be able to track from which page the user signed up? That could be a good proxy for gauging interest areas.

**Comment by WillatMozFdn** [comment]
Yes -- every new email address that comes into our system has a "source
URL" field so we know what page drove the signup.

 - W

**Comment by xmatthewx** [comment]
@arlissc – would it be good to give program staff an example report they can get from CRM?

**Comment by arlissc** [comment]
@xmatthewx - I have a sample report I use.  Let me clean it up and I'll share.

**Comment by xmatthewx** [comment]
@arlissc - it would be great to see a sample report. i'm going to close this ticket though, as this work has continued elsewhere.
