### ISSUE TITLE
Enable gzip compression on server

### ISSUE THREAD

**Issue by gvn** [mozilla/network#434]
(@cadecairos let me know if you'd prefer this filed in devops.)

Per audit:

**Enable gzip compression (6)**
Compressing the following resources with gzip could reduce their transfer size by about two thirds (~288 KB):
network.mofoprod.net/
could save ~8.8 KB
main.compiled.css
could save ~147 KB
fira.css
could save ~4.8 KB
css
could save ~2.2 KB
css
could save ~228 B
main.compiled.js
could save ~124 KB

**Comment by cadecairos** [comment]
gzip is now enabled if the client indicates support

**Comment by gvn** [comment]
Confirmed: gzip is enabled on prod.
