### ISSUE TITLE
Make it easier to close the nav menu

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network#437]
Right now the only way to close the navigation menu is by clicking the X. At the very least, the `esc` key should also work, perhaps clicking (far) outside any of the links should also close it. Let's keep accessibility in mind.

**Comment by gvn** [comment]
Closing with escape makes sense to me, but closing based on clicking an arbitrary area doesn't.

**Comment by alanmoo** [comment]
Given the current style, that's reasonable.
