### ISSUE TITLE
QA > Staging: Top Nav button label

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#447]
**Issue:**
Currently on staging our top nav button has an updated copy: "Sign Up"
<img width="1143" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/26271113/7fd15528-3cb6-11e7-9955-c236c69dab0b.png">

The new copy is updated on all pages except on the 2 opportunities pages, which still have the old label "Get Involved":

https://network.mofostaging.net/opportunity/fellowships/
<img width="1160" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/26271097/4e2308f0-3cb6-11e7-9fa7-dc9b038e9285.png">

https://network.mofostaging.net/opportunity/training/
<img width="1180" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/26271106/6a5d94ae-3cb6-11e7-8602-ced48f570ce7.png">

Flagging here before those changes are pushed to prod.

cc: @hannahkane @xmatthewx @alanmoo

**Comment by alanmoo** [comment]
Content from the opportunity pages is in the CMS. I'm not sure if these are actually supposed to be changed, but they can be without assistance from dev.

**Comment by xmatthewx** [comment]
@alanmoo – I believe she's referring to the site's header component... big yellow button at top right.

**Comment by alanmoo** [comment]
Ah, good point, that makes more sense

**Comment by alanmoo** [comment]
I think that wasn't explicitly part of the request from @jessevondoom. Jesse, can you clarify?

**Comment by jessevondoom** [comment]
Yeah I'm less concerned with general "get involved" headers throughout the site, but if we can update the button itself so it's consistent I think that'd be best.

**Comment by taisdesouzalessa** [comment]
I meant the button @alanmoo. Sorry for the confusion, I should have highlighted it in the interface :). I think it is important to keep consistency here from the users' perspective: across all the website the users see "sign up" on the top then suddenly in the opportunities pages they see another label in the button. It is misleading as it can make them think this button is new and it will take them elsewhere.
