### ISSUE TITLE
"member preview" panel and survey preamble tweaks

### ISSUE THREAD

**Issue by hannahkane** [mozilla/network#448]
from @jessevondoom:

**Issue**
There’s concern that we need to do more to communicate the iterative/collaborative nature of the Network site. Right now we’re framing that as the site being “in progress” or a preview. We’ll move away from that framing as the network starts to feel more ownership of the site, but for now there are some ways we can make the the in-progress/feedback process more obvious.

**Suggested solution**
There’s a three-step fix that hopefully doesn’t require a ton of work:

1. The feedback panel on the top of the site (“Welcome to our member preview. We look forward to your feedback.”) is fairly subtle. If we make it stand out more we hopefully remind people that this is a collaborative building process and invite more feedback. 
2. Can we change the text in the feedback panel to: “Welcome to our member preview. It’s a work in progress and we invite your feedback.”
3. ~~Lastly, let’s reiterate that message before the survey form: “Mozilla is a part of a movement to keep the Internet healthy and wants to help it grow. This site is part of our effort to do that. It’s a work in progress, and your feedback makes a real difference. We look forward to hearing your perspective.”~~

**Comment by alanmoo** [comment]
I can take care of 2 and 3 myself rather quickly, though 1 requires a designer, all of which are out today. @xmatthewx thoughts?

**Comment by hannahkane** [comment]
Just noting that the survey itself is going to be changed, and already has a [different preamble](https://docs.google.com/document/d/1xVeaN_DbOMSLO74rKIT-ISOO20MmEcOuxrAH-RWlRCY/edit#). Probably best not to start on 3 just yet.

**Comment by jessevondoom** [comment]
@alanmoo #1 can be a lower priority — the "in progress" language gets at what we want and we can even wait to tweak the style until we're looking at new hero styles. No rush there.

@hannahkane Awesome. Let's just disregard #3 then — my bigger concern was making sure it had some context/preamble in place before we push out to network leaders and the already-reviewed preamble sounds like the way to go. Thanks for flagging that.
