### ISSUE TITLE
Change main page hero copy

### ISSUE THREAD

**Issue by hannahkane** [mozilla/network#449]
from @jessevondoom:

**Issue**
We introduce the phrase “healthy internet” on the main page but don’t define Internet health or tie back to the Internet Health Report. Defining the network in terms of Internet health is a main goal of the organization in 2017 so we need to make more of an explicit connection going forward. 

**Suggested solution**
This will be a central theme as we design for the next major iteration of the site but for now I think we can make a lot of impact with a pretty minor copy change in the Network site main page hero:

_Current:_
“We are a global network keeping the internet open and accessible to all.”

_Change to:_
“The Internet is an ecosystem billions depend on. [https://internethealthreport.org/v01/about/](It’s health influences everyone it touches.) We are a global network keeping the Internet open, healthy, and accessible to all.”

Borrowed the new copy (edited down) from the Internet Health Report site about page for consistency.

**Comment by hannahkane** [comment]
I like the copy edit! Are we sure we want to link to another site in the hero of our homepage?

**Comment by xmatthewx** [comment]
We could add the following from that health report about page to the middle of this site's about page. And then link there. 

> The Internet is an ecosystem. A living entity that billions of people depend on for knowledge, livelihood, self-expression, love…. The health of this system relies on – and influences – everyone it touches. Signs of poor health in any part impacts the whole. We’re all connected.

> How healthy is our Internet? How might we understand and diagnose it? 

This would go above the 5 issues, under a new heading "Internet Health" or "A healthy internet"

**Comment by jessevondoom** [comment]
@xmatthewx I think that's a great idea. To @hannahkane's point: it'd be a lot cleaner/better to link to the local about page. Hadn't thought of that, even though it feels obvious now that you mention it. Rad!

**Comment by alanmoo** [comment]
So we still want the home page header to be updated, right? But we also want content added to the about page?

**Comment by xmatthewx** [comment]
Yes. That's correct. I've reviewed Alan's local update to the About page. Looks good. Let's get that on staging for a final thumbs up. 

@alanmoo – I'll take look at intro text and link now. More soon...

**Comment by xmatthewx** [comment]
I think the new intro is a bit too long for fleeting eyeballs. I propose a revision below. I think it maintains the spirit. 

<img width="840" alt="screen shot 2017-05-22 at 6 38 03 pm" src="https://cloud.githubusercontent.com/assets/53411/26331255/f50b6518-3f1d-11e7-9f99-a7d6b3465fa1.png">

<img width="839" alt="screen shot 2017-05-22 at 6 45 38 pm" src="https://cloud.githubusercontent.com/assets/53411/26331447/e1dc36b0-3f1e-11e7-87c3-35d7ea5b2cfe.png">

I think the second sentence gives a hint of of what we mean by healthy internet. 

> Billions of people depend on a healthy internet. Our network helps keep this ecosystem open, secure, and accessible to all.

**Comment by hannahkane** [comment]
@jessevondoom is traveling, but I got an OK from him to ship @xmatthewx's suggestion above.

@alanmoo - do you got this?
