### ISSUE TITLE
Implement a "Thank You" state

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#46]
Design a "Thank You" page after user input their e-mail in the form field.

**Comment by taisdesouzalessa** [comment]
@xmatthewx here is the flow of the "Thank You" page
![thank-you-demo](https://cloud.githubusercontent.com/assets/22157921/22669048/e04a9728-ec77-11e6-87bd-fe6e8d824af5.gif)

I think we can refine the copy a bit more (I just quickly created one).

Here is the page in InVision for feedback: https://invis.io/ZJ9YTAGEA#/217738531_Thank-You

cc: @sabrinang

**Comment by sabrinang** [comment]
From doing some mockups for the interstitial pages, I think it would be great if we can keep users on the current page they are on. Since the dedicated thank you page just seems like short copy and share buttons, I think we can fit that in the same space the form occupies... so this will still provide the same value to the user (confirmation feedback that it was successfully submitted and the options to share).

Example:
<img width="1335" alt="screen shot 2017-02-09 at 3 19 39 pm" src="https://cloud.githubusercontent.com/assets/2492510/22807329/32da2ff2-eedb-11e6-8790-c704fc5096f3.png">

**Comment by taisdesouzalessa** [comment]
I think it is a great idea! I vote for integrating the "Thank you" message on the other pages as well. 

My only feedback would be to add one button for sharing as a dropdown so users can choose from there - 4 buttons displayed at the same time may be overwhelming and compete with our other buttons in other pages.

**Comment by xmatthewx** [comment]
Cool. Integrated "Thank you" makes a ton of sense. 

Let's remove the social for now. We _will_ want it later ... but for a soft launch .... I'm unsure if we want people to share this right away. Let's take a little pressure off ourselves right now, add it back when we're ready.

**Comment by taisdesouzalessa** [comment]
I'll integrate in "thank you" in the mockup to test it and share here.

**Comment by sabrinang** [comment]
@gvn Are there any implementation or testing issues if it is not a separate page? Let me know if this approach works

**Comment by gvn** [comment]
I think it should work as a separate page.

**Comment by taisdesouzalessa** [comment]
Here is how the integrated "Thank you" page feels like. I think it looks nice and seamless.  It is working on the prototype (home page only). Here are the gifs:

TOP CTA:

![thank-you-top](https://cloud.githubusercontent.com/assets/22157921/22956985/385505d0-f2da-11e6-9d68-f481858163d3.gif)


-------

MIDDLE CTA:

![thank-you-center](https://cloud.githubusercontent.com/assets/22157921/22956986/399ea77a-f2da-11e6-9967-1e1e22a7f83b.gif)


Nice to have: a different illustration for the "Thank You" state.

@gvn @sabrinang @xmatthewx

**Comment by gvn** [comment]
Looks good!

**Comment by taisdesouzalessa** [comment]
@xmatthewx let us know how you feel about this interaction.

**Comment by gvn** [comment]
@xmatthewx Is this approved for implementation?

**Comment by xmatthewx** [comment]
This is ready for the Health Report Page and form on the middle of home page.

**Comment by gvn** [comment]
Blocked pending redesign of Join Us as a standalone page.

**Comment by xmatthewx** [comment]
For the homepage form and the standalone join page, this pattern should still work. we can stub it out if we want, add specific content when ready.

**Comment by gvn** [comment]
Is the design approved?

**Comment by gvn** [comment]
This is functionally working, but needs some styling.

**Comment by taisdesouzalessa** [comment]
@gvn please correct me if I am wrong but it seems that after all the changes we made the embedded Thank you will occur only in these 3 pages, right?
- https://invis.io/ZJ9YTAGEA#/216715361_Landing_Page_Internet_Health
- https://invis.io/ZJ9YTAGEA#/222644514_Landing-Page-Fellowships
- https://invis.io/ZJ9YTAGEA#/222644515_Landing-Page-Leadership-Training

I can do the styling for those ^ to you and attach it here.

---

There will be another Thank You state, this time in the standalone page:
https://invis.io/ZJ9YTAGEA#/222863031_Join-The-Movement
We don't know what this page's content will be yet. But I imagine a very simple Thank You in the same style as the page, just changing content. At least for MVP.

**Comment by taisdesouzalessa** [comment]
@gvn here is the styling (the same for all of the 3 Landing Pages):
https://invis.io/ZJ9YTAGEA#/223042054_LandingPage-Internet-Health-Thankyou

Illustration is still a placeholder. Will update the Google Drive.

**Comment by gvn** [comment]
@taisdesouzalessa @alanmoo is working on this ticket. @alanmoo FYI ^

**Comment by taisdesouzalessa** [comment]
Alright! Sorry for that  and thanks for tagging him! @alanmoo let me know if you have any question
