### ISSUE TITLE
Add link to health report on about page

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#461]
Below the five issues on the about page, we should have a statement and link, something like "Learn more about this and join us in writing the Internet Health report." (link to https://internethealthreport.org)

**Comment by hannahkane** [comment]
I think @xmatthewx's copy is good minus the extraneous "To" at the beginning. So: Learn more about this and join us in writing the Internet Health report.

Wondering if it should link directly to the [report](https://internethealthreport.org/v01/) or to the [landing page](https://network.mofoprod.net/opportunity/internet-health-report/). I think the former.

@jessevondoom - does this sound alright to you?

**Comment by jessevondoom** [comment]
Yes on both counts. I think pushing people directly to the IHR is correct here, and I like the more active phrasing without the "to."
