### ISSUE TITLE
Add routing rules to local server

### ISSUE THREAD

**Issue by gvn** [mozilla/network#462]
Try to get parity between S3 and our local dev server so that we can hit 404 pages, landing pages, etc.

If possible, share a common rule set / config.

Nice to have: An ENV var to point to location of Mezzanine server (for routing to locally running landing pages).

Related: #411

**Comment by hannahkane** [comment]
pending decisions about merging repos, removing from milestone

**Comment by alanmoo** [comment]
Closing as per @gvn
