### ISSUE TITLE
Prepare 3+ "offerings" for launch

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#47]
The site will feature 3 "offerings" to visitors, doorways to engagement, something we provide of value to network members. 

We have identified 4 [leading options](https://docs.google.com/presentation/d/14aNtuq-5JTvJxgY4csD418Wis13VRMCMxCRWbmAdIg4/edit#slide=id.p) among our [upcoming 2017 highlights](https://docs.google.com/spreadsheets/d/1UsnRgCYYLsQJvicJGKHgn3TU7dfwZ3icn9PaAzxtrmg/edit#gid=2090555237).

Offerings were evaluated based on ability to:
* Help tell story of network
* Provide a mix of offering types, with high/low engagement
* Viability 
* Goal: turn quality visitors into members via diverse options

Options for launch include: 
 - contribute to internet health report
 - view fellow cohort and express interest in future fellowships
 - take mini-leadership training
 - become an encryption champion

Each offering requires a feature card for the homepage (image, copy, url) and a landing page with join form. 

We've started conversations with an owner for each of the 4 most viable offerings.

**Comment by xmatthewx** [comment]
- [ ] training https://github.com/mozilla/network/issues/21
 - [ ] health report https://github.com/mozilla/network/issues/29
 - [ ] encryption champ ([white board](https://docs.google.com/presentation/d/14aNtuq-5JTvJxgY4csD418Wis13VRMCMxCRWbmAdIg4/edit#slide=id.g1a7cea6c72_0_0))
 - [ ] fellows ([white board](https://docs.google.com/presentation/d/14aNtuq-5JTvJxgY4csD418Wis13VRMCMxCRWbmAdIg4/edit#slide=id.g1a7cea6c72_0_30))

**Comment by xmatthewx** [comment]
bumping to next milestone

**Comment by hannahkane** [comment]
Closing this because it's duped by individual tickets.
