### ISSUE TITLE
Add link to healthcheck to show diff from master

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network#472]
To make the deployment process smoother, let's add a link to the healthcheck page (even if it's a string we have to copy/paste) that brings you to a github page that shows a list of commits as a diff between what's on production and what's been merged into master.

For example: https://github.com/mozilla/network/compare/0d1fefe578093c7291e0b60ac06bd158b0296847...master

**Comment by gvn** [comment]
If you have just the latest commit hash for a build (`git rev-parse HEAD`), then you can only see what's been committed to `master` after it using that link scheme. That's not super useful.

For what we want, I think we need the commit hash of the previous deploy, which is going to be trickier. I'm assuming we'd have to tap into an API on Jenkins to get it (which may require key storage). Once we have it then we can diff between the last deploy hash and the current deploy hash, like so:

https://github.com/mozilla/network/compare/422235c399dc4378cbd60d745509b3227855cfd7...98d2e091106980bbcc8bbfbe5a4e0cf0e41164d7

@cadecairos : Do you know if Jenkins makes this available?

**Comment by cadecairos** [comment]
I'll investigate what we can do with jenkins.

**Comment by cadecairos** [comment]
We can grab the last git commit id from this endpoint: https://jenkins.mofoprod.net/job/Network%20(production)/lastBuild/api/json

The response object will have the commit id at `resp.changeSet.items[0].commitId`

There's also a some other info about the build there that might be handy, if you care to have a look and see. (commit message, author, etc)

**Comment by gvn** [comment]
Oh, sweet. Thanks @cadecairos !

**Comment by alanmoo** [comment]
>If you have just the latest commit hash for a build (git rev-parse HEAD), then you can only see what's been committed to master after it using that link scheme. That's not very useful. I'm assuming we want more of a change log, not what's "missing".

I guess I was thinking you'd be able to click the link on production and see what's coming from staging next (since `staging == master`). Would the route we're going then mean we'd have a link to click on the staging healthcheck that shows what's different from production?

**Comment by gvn** [comment]
I'm already working on the changelog approach, but I can add the "upcoming" commits link in there too if it's useful.

**Comment by gvn** [comment]
Here's an example of a new healthcheck:

```
commit f6d9350fda718ef553257ca0ac6e44b1cb309b88
Author: gavin lazar suntop <gavin@gsuntop.com>
Date:   Mon Jun 5 09:41:02 2017 -0700

    adding github issue template (#484)


PULSE_API_DOMAIN: network-pulse-api-production.herokuapp.com
PULSE_DOMAIN: www.mozillapulse.org
NETWORK_API_DOMAIN: network.mofoprod.net
VIRTUAL_ROOT: /
TARGET_DOMAIN: network.mofostaging.net

Changelog:

https://github.com/mozilla/network/compare/0d1fefe578093c7291e0b60ac06bd158b0296847...f6d9350fda718ef553257ca0ac6e44b1cb309b88


Commits since this deploy:

https://github.com/mozilla/network/compare/0d1fefe578093c7291e0b60ac06bd158b0296847...master
```

**Comment by alanmoo** [comment]
Yeah, the main driver of this ticket was we want to be able to see what's changed from production to staging so that we can more easily QA before deploying to production.
