### ISSUE TITLE
Posters for Board Meeting 

### ISSUE THREAD

**Issue by sabrinang** [mozilla/network#473]
After discussing with @Lottarao, there are 5 posters that need to be made by Friday June 2 to meet the print deadline. 

The first poster is complete by @cassiemc as reference:
<img width="884" alt="image" src="https://cloud.githubusercontent.com/assets/2492510/26648884/c16a02be-45f8-11e7-9c80-dbc8851136e1.png">

Since Cassie is working in the evening, we need to discuss with Mark about his vision he has in mind for the other four posters before then and the content is in progress here: https://docs.google.com/document/d/1ApQKzMdjsGh0QoaS5rRNA2dtYAaUih__s9Gz4CZ_vz4/edit#heading=h.qwb3pf55word

- [x] Poster 1 - Fuel the Movement **DONE**
- [ ] Poster 2 - People in the Network
- [ ] Poster 3 - Network By Numbers
- [ ] Poster 4 - Network Projects
- [ ] Poster 5 - Press Clippings

The dimensions should be the same as the first poster and check with Mark is he still wants them all horizontal. I won't be able to get design template files from Cassie until Thursday evening.

Example board slide aesthetic: https://docs.google.com/presentation/d/1aj7KzxOW_Q1M3UbXOFXPtkGPla-wUiiIXDL7vQMF1Zo/edit#slide=id.g225e5b57b2_0_83

@xmatthewx @jessevondoom

**Comment by sabrinang** [comment]
cc/ @hannahkane

**Comment by flukeout** [comment]
Some sizing updates. Each of the walls between the windows is 8 feet wide. And we've got nearly 15 feet on each of the walls that are to the sides of the entrance...

![image](https://cloud.githubusercontent.com/assets/25212/26653189/2bd6c12e-4607-11e7-9dfa-06fe5dee1a33.png)

**Comment by xmatthewx** [comment]
You might ping Jordan and Lotta to figure out where and how they've printed these in the past. So you can choose paper size.

**Comment by sabrinang** [comment]
The indesign document for posters last year were: 
<img width="475" alt="image" src="https://cloud.githubusercontent.com/assets/2492510/26657454/c73f3428-4618-11e7-89dc-5f9ae1cb9bff.png">

**Comment by sabrinang** [comment]
In the process of laying out draft content:
<img width="1263" alt="image" src="https://cloud.githubusercontent.com/assets/2492510/26660366/7cf2edf6-462c-11e7-860c-853224bbace3.png">
Working from this [gdrive folder](https://drive.google.com/open?id=0B4Q8pzCpDS_eUlJOZEtFclpmQUE) I'll collect higher res images/fix dimensions and continue tomorrow

**Comment by xmatthewx** [comment]
@ldecoursy - can you confirm that these are on track content-wise? Let's correct course before she starts to refine the details. 

Nice speedy work @sabrinang! Thanks for jumping in.

**Comment by ldecoursy** [comment]
@xmatthewx Those are the ones! Just changed "Press Clippings" to "Headlines." All poster content is now final at https://docs.google.com/document/d/1ApQKzMdjsGh0QoaS5rRNA2dtYAaUih__s9Gz4CZ_vz4/edit#heading=h.qwb3pf55word 

Thanks all!

**Comment by sabrinang** [comment]
Progress on redpen: https://redpen.io/p/fr3c44ab88b23c8d2d
<img width="1300" alt="image" src="https://cloud.githubusercontent.com/assets/2492510/26698284/3817f3ea-46ca-11e7-9759-e3fc42c1be73.png">

**Comment by sabrinang** [comment]
I will have the posters accessible to be used in slide deck or if other posters need to be made and printed together (check with @jessevondoom if he is making a poster of the network site)

Notes/Feedback from meeting:

@ldecoursy Will help to figure out who is taking this to print to hand off to and figure out time of cut off. Lainie will also assist reducing copy where possible and provide a screencap for headlines.

- **All Posters:** remove all white boxes on upper right with lots of copy (content is cover insides and doesn't flow well on poster) 
- **People:** make speech bubbles more integrated somehow (but staggered layout has good rhythm) 
- **Network by Numbers:** adjust colour scheme of audience diagram (try alternating colours and lighten to increase contrast legibility)
- **Network by Numbers:** highlight projected 1m circle on diagram and connect to "progress" description or small type description
- **Network by Numbers:** reorder to 1) Objective 2) Key result 3) progress so it reads in order
- **Fuel the Movement:** feels darker overall and can lighten palette to match others and include line art textures. Also, can try playing around with xplane black bg to lighten poster overall

**Comment by ldecoursy** [comment]
Thanks @sabrinang!

I think we'll just need the funnel image with the key from the Network by Numbers poster for the board slides (which have a white background)

Phia is going to take it to print. She's contacting the printer now to find out what our hard deadline is tomorrow. 

Attching the updated screencap for the top middle press clipping here. 
![screen shot 2017-06-01 at 4 54 32 pm](https://cloud.githubusercontent.com/assets/4885898/26700387/284b8690-46eb-11e7-9653-fc9ad1f68818.png)

**Comment by ldecoursy** [comment]
**Production details**

- Email file by Friday, June 2 at 12pm PT—>Phia can arrange for pick up
- Once files are ready, email to usa5177@fedex.com and cc Phia
- Files should be in pdf format

**Comment by ldecoursy** [comment]
@sabrinang Just pinged you in the content doc - # for supporters should be 1.7 instead of 2.7

**Comment by jessevondoom** [comment]
@sabrinang Here's [copy for the Network site poster](https://docs.google.com/document/d/15w8slemGqRwfwxV6Mygv7hYeA3gci_XWbVLU6gK5dvc/edit#). Very basic/simple and can edit down as you need.

**Comment by sabrinang** [comment]
@ldecoursy I updated changes from the feedback as well as the number 1.7 (thanks for flagging). Can you or @Lottarao please review the posters specifically Fuel the Movement since I lightened the xplane deck and realized some sections looked different than @cassiemc 's version. I may not have the latest design file of the xplane deck and I didn't receive them to export. (If there is an update deck .ai/.pdf file please supply)

Does Phia know the confirmed dimensions of these posters for the printer? 

I will export .pdfs tomorrow morning for print. I'll get to @jessevondoom 's poster tomorrow morning as well.  

Redpen is updated: https://redpen.io/p/fr3c44ab88b23c8d2d
<img width="1181" alt="image" src="https://cloud.githubusercontent.com/assets/2492510/26708063/33e17f56-46fe-11e7-85b0-122a8f8ff2d2.png">

.ai file here: https://drive.google.com/file/d/0B4Q8pzCpDS_eNEFQQUVLWFp3eVU/view
source gdrive folder here: https://drive.google.com/drive/folders/0B4Q8pzCpDS_eUlJOZEtFclpmQUE?usp=sharing

**Comment by ldecoursy** [comment]
Thanks @sabrinang!

I'm checking with Phia on dimensions, but we should also check with Jordan if he's done them in the past. 

I don't have the xplane design file but pinged Lotta. I think the order of the slides in the latest version of the Fuel the Movement poster are incorrect. Also not sure that white background is translating - it's a bit hard to read. the flow and background treatment are better aligned with the other posters which is great. Might be good to keep that but with the black slides (I think the colorful lines pop on the black and are actually easier to see/read).

**Comment by ldecoursy** [comment]
Let's go 24x36" for the posters.

**Comment by sabrinang** [comment]
@jessevondoom Can you review the site poster on redpen? https://redpen.io/vg98ed08fd8451bc66
<img width="1005" alt="image" src="https://cloud.githubusercontent.com/assets/2492510/26733649/5470bfc6-4770-11e7-87d6-02e6ada1bc78.png">

**Comment by jessevondoom** [comment]
@sabrinang Network site poster looks great. Only thing I caught was a stupid extra comma in the copy I wrote (too quickly) yesterday. Could you remove the comma in the main paragraph to the left in "turning people taking their first steps on the open web into activists, and..." — sorry! Otherwise I think this is good to go unless @xmatthewx or @hannahkane have any copy suggestions.

**Comment by jessevondoom** [comment]
@sabrinang I lied. Could we change the "Storytelling" header either to "Storytelling and Engagement" if both fit, or just "Engagement" if not? Want the takeaway to be that we're working with people, not just talking to them.

**Comment by hannahkane** [comment]
No copy changes from me. Looks good!

**Comment by jessevondoom** [comment]
@sabrinang New paragraph copy for Storytelling + Participation:

A network is more than a collection of nodes. We’re driving engagement through storytelling about people, projects, and opportunities — how they all relate to one another and to the key issues of Internet Health. We’re focused on impact and connections, bringing people together and giving them the resources and support needed to fuel this movement.

**Comment by jessevondoom** [comment]
Really solid edit to the last sentence from @xmatthewx if we still have time to make changes:
"We’re focused on impact through connections. We bring people together to collaborate, giving them the resources and support they need to fuel this movement and create a more healthy internet."

**Comment by sabrinang** [comment]
.pdf (24x36" - 0.125" bleed): https://drive.google.com/drive/folders/0B4Q8pzCpDS_eYzBkMGpwcUk1WU0?usp=sharing
Updated redpen with changes and new dimensions: https://redpen.io/p/fr3c44ab88b23c8d2d

Sorry for the delay it took foreverrr to export + upload the large file. In contact with Phia coordinating this to take it to print.
