### ISSUE TITLE
Explore merging network-api into network repo

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network#475]
In an effort to improve the development and deployment processes, let's create a new branch for this project and see how difficult it is to integrate the two repos, and analyze any possible issues with such a setup in the future.

**Comment by xmatthewx** [comment]
deliverables
 - [ ] list goals, pros / cons
 - [ ] experiment on a branch (time box: X hrs)
 - [ ] develop plan & approach

**Comment by alanmoo** [comment]
@gvn to experiment with building to django static files directory, key question is how we can access html files stored there using various routing setups.

**Comment by gvn** [comment]
Etherpad from our meeting: https://public.etherpad-mozilla.org/p/network-merge

**Comment by alanmoo** [comment]
Work that is determined here will continue as issues to be created in #583

**Comment by alanmoo** [comment]
Update: We can't improve our Observatory score while we're hosting pages on AWS. So we need to do this in a way that makes django serve the static pages. Once we've done that, HSTS can be enabled and we can switch over to network.mozilla.org.

What do we need to determine in our call on Thursday based on this information? @cadecairos @Pomax @gvn

**Comment by gvn** [comment]
Cool. That's definitely something I already wanted to do and one of the pieces I needed a hand with. I basically need a folder within `network-api` to use as a build target for all the assets currently being built into `/dest` in `network`.

**Comment by xmatthewx** [comment]
Meeting done. Agreement all around. Yay.
