### ISSUE TITLE
Research CMS authored subpages

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#477]
Prototype:
https://taisslessa.github.io/simple-model-ui-v4/index.html

Tasks
 - Re-enable subpages in local builds of mezzanine
 - Surface usability concerns and constraints for authors
    - Test multiple sub-pages (i.e. `Opportunities->Fellows->sub-page a/b/c`) and ability to add side navigation of sibling pages
    - Verify ability to force use of specific subpage templates when using a "mini-site" template
    - Verify ability to inherit from parent templates (so the main site navigation can be a single component reused across pages)
 - Identify design constraints that will impact #445 

Deliverables
 - [x] File implementation ticket
 - [ ] Iterate on design based on findings

Nice to have (not mvp): 
 - learn more about permissions
 - learn more about how we might handle a page header image

**Comment by Pomax** [comment]
It's been a while, so in the interest of having enough information in the issue for anyone to jump on it, what do we mean with "subpages in Mezzanine"? Are we talking purely the `Pages` system, where we currently have a (quasi-)locked and then subpages to that, with the intent to allow sub-subpages, sub-sub-subpages, etc.?

<img width="667" alt="screen shot 2017-07-06 at 12 48 11 pm" src="https://user-images.githubusercontent.com/177243/27930022-0699ad9a-624a-11e7-9e6e-5d0bf80bb605.png">

**Comment by xmatthewx** [comment]
That original comment was composed while talking with Alan, Tais, and Gavin. Sorry for the missing context. You more or less got it. 

The idea: a staff author can create an Opportunity page like Leadership Training and then create sub-pages under that, such as an FAQ. On the front-end, we could then generate a [simple nav element](https://redpen.io/wh681ba02d54215838) to browse this small set of pages.

Authors would _not_ be able to create new top-level pages like /opportunities/. And I don't think we'd need a third level for them below. Two levels should give plenty of flexibility.  

So this ticket is to explore what Mezzanine does out of the box. Consider how we might constrain authors. Surface any concerns for this plan and any new design constraints.

We can discuss at the end of stand if this isn't clear yet.

**Comment by alanmoo** [comment]
Do these mini sites all show up at `/opportunities/{mini-site-name}/{child-page}`?

**Comment by alanmoo** [comment]
I've updated the original post with more specific tasks that will enable us to make a proper assessment of the proposed design.

**Comment by xmatthewx** [comment]
@alanmoo to comment on next steps. Maybe close this and open a follow up.

**Comment by alanmoo** [comment]
I've added this to an Epic and also populated that epic with what I see as the main steps of it.
