### ISSUE TITLE
Add Page for Tech Policy Fellows 

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#482]
Add a simple page via CMS with bios for tech policy fellows. 

 - Page title: Tech Policy Fellows 2017
 - [Content](https://docs.google.com/document/d/1N8SZRaWtD5S3IV_FSaSq4v2Gz30wrT0wTDwQRARW4t8/edit) (draft – pending final review)
 - Photos [link coming soon]

Accountable: @corizarek

@hannahkane – can you drive or delegate this? Message me with any questions.

**Comment by hannahkane** [comment]
Sure. I can build this page when the content is final. It's going to look a lot like the Network50 page I think (but shorter!)

@corizarek - can you please let me know when the content is final?

**Comment by hannahkane** [comment]
Closing. This is done. More photos can be added as they are available.
