### ISSUE TITLE
Add email address to site

### ISSUE THREAD

**Issue by hannahkane** [mozilla/network#486]
- [ ] 1. Add "EMAIL" as a line item under TWITTER on the "We'd love to hear from you" section of /about. It should be a mailto: pointing to network@mozillafoundation.org
 - [ ] 2. Add "Email" as the second item in the footer, to the right of Twitter 
 - [ ] 3. Add "Email" as the second item in nav menu footer, below Twitter

**Comment by xmatthewx** [comment]
- [ ] Add "Email" as the second item in nav menu footer, below Twitter

**Comment by taisdesouzalessa** [comment]
Here are the screenshots and the sketch file that contains the e-mail icon.
1. The e-mail link (pointing to network@mozillafoundation.org)beside the Twitter link. The distance between the links is 30px (I kept it the same as our bootstrap gutter default). This component exists in 2 pages: [About](https://network.mofoprod.net/about/) and [Get Involved](https://network.mofoprod.net/get-involved/)
<img width="790" alt="image" src="https://user-images.githubusercontent.com/22157921/27451793-31704886-5745-11e7-93bc-9fc9da730570.png">
2. E-mail in the footer:
<img width="890" alt="image" src="https://user-images.githubusercontent.com/22157921/27451972-c488b0e0-5745-11e7-85d9-d332f7168d17.png">

SVG - we have it in [mofo-boostrap](https://mozilla.github.io/mofo-bootstrap/demo/)

Sketch file: 
[footer-network.sketch.zip](https://github.com/mozilla/network/files/1095944/footer-network.sketch.zip)

3. Screenshot of email as a second item in nav menu:
<img width="986" alt="image" src="https://user-images.githubusercontent.com/22157921/27452286-e91d4e06-5746-11e7-933f-508ec6365fcf.png">
