### ISSUE TITLE
Gather requirements for Optimizely

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#49]

**Comment by gvn** [comment]
@vojtechmzl Can you provide more information on what we'll need to do for Optimizely?

**Comment by vojtechmzl** [comment]
Hey @gvn, all we need to do to implement Optimizely is to insert the following tag right after the opening <head> tag on every page of the site.

`<script src="https://cdn.optimizely.com/js/206878104.js"></script>`

The rest of the set up for individual experiments will be done through the Optimizely dashboard.

Let me know if you have any questions

**Comment by gvn** [comment]
@vojtechmzl I dropped that script into our staging site. Can you confirm that it does what you need?

https://network.mofostaging.net/

Thanks!

**Comment by gvn** [comment]
Confirmed working via chat w. @vojtechmzl

**Comment by xmatthewx** [comment]
That's rad that this is in place already.
