### ISSUE TITLE
Explore Navigation Bar Design

### ISSUE THREAD

**Issue by sabrinang** [mozilla/network#492]
Continuing from the work on https://github.com/mozilla/network/issues/60#issuecomment-303482641 , explore how this navigation would work on various pages as well as consider how this will work with new artwork.

<img width="1172" alt="nav hero options" src="https://cloud.githubusercontent.com/assets/2492510/26368234/e70ce6c0-3fa5-11e7-8716-660c6a298aab.png">

Related Issues:
#426 menu icon position
#493 hero artwork

**Comment by xmatthewx** [comment]
@taisdesouzalessa @sabrinang let's estimate this and hero artwork task

**Comment by sabrinang** [comment]
<img width="535" alt="image" src="https://user-images.githubusercontent.com/2492510/26988464-61a9b21c-4d04-11e7-98da-e446387080d0.png">



example of animation (but refer to design above):
![nav-example](https://user-images.githubusercontent.com/2492510/26950413-5ef5b316-4c52-11e7-9b75-ab9b4e860df8.gif)

- scope technical challenges

**Comment by xmatthewx** [comment]
This is done design-wise, yes? If so, let's file an implementation ticket and connect with the hero implementation ticket.

**Comment by xmatthewx** [comment]
closing. yay. implementation continues in #524
