### ISSUE TITLE
Hero Artwork

### ISSUE THREAD

**Issue by sabrinang** [mozilla/network#493]
Continuing from the [explorations](https://docs.google.com/presentation/d/1QEfeQ4LEg8p9UXigdnp4zzgLTpuoje2d4qR5De30xs8/edit#slide=id.g1e305061e7_0_0) we did for board slides, we can start exporting assets and implementing some of this artwork.

<img width="1057" alt="image" src="https://user-images.githubusercontent.com/2492510/26845186-88341c58-4aaa-11e7-9bca-458caf5ecde9.png">

Related design issue: Explore Navigation Bar Design https://github.com/mozilla/network/issues/492

**Comment by sabrinang** [comment]
<img width="1219" alt="example" src="https://user-images.githubusercontent.com/2492510/27096886-5a632aee-5027-11e7-963d-4770c65922e2.png">
4 corner gradient, repeating pattern and image (transparent at the sides) in the center with background-blend-mode: overlay

@gvn does this work to assemble in css if i supply the main image + repeating pattern?

**Comment by gvn** [comment]
The pattern and hero image composite should work. I'm not sure about the gradient being CSS generated. I think it'll have to be 4 radial gradients, which I've never tried, but let's give it a shot!

**Comment by sabrinang** [comment]
image and background are in gdrive here: https://drive.google.com/open?id=0B4Q8pzCpDS_eRERhbllweWhsSXc

**Comment by xmatthewx** [comment]
Yay. Looks great. I believe we want a new implementation ticket. We can estimate during grooming tomorrow.

**Comment by xmatthewx** [comment]
Done! Implementation continues in #523.
