### ISSUE TITLE
Network builds fail sometimes on "dest/_images" creation

### ISSUE THREAD

**Issue by cadecairos** [mozilla/network#499]
`cp: cannot create directory 'dest/_images': No such file or directory`

**Comment by cadecairos** [comment]
Example: https://jenkins.mofoprod.net/job/Network%20(staging)/236/console

**Comment by gvn** [comment]
Do you know if this is still happening?

**Comment by gvn** [comment]
Closing, but feel free to re-open if this comes up again.
