### ISSUE TITLE
Gather content for People page

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#5]
The site will have a page dedicated to showing the amazing people and partnerships at the heart of this network. Shipping that page will require us to gather a bunch of images and links. We need your help! 

Design is a work in progress. Things we know now about this page: 
 - Goal: The page should inspire visitors. They should think "these people are awesome" and "I belong here"
 - This is not a directory. We might have a directory some day. That day is not today. This page can link there or draw from there when that day arrives. 
 - This page should include a mix of Staff, Board members, Advisory members. Recognized members when we're ready. 
 - Ideally this page will also include logos of partner orgs. Any chance we have a list somewhere of all the orgs we consider a partner? 

This Github issue could open a pandora's box. Let's not do that. Let's choose simplicity. Let's inspire people.

**Comment by xmatthewx** [comment]
Profiles include: 
 - Required
   - Name
   - Quality picture
   - Relationship: Staff, Advisory, Board, etc.
 - Should include
   - Link to twitter and/or linkedin
 - Could include (might not all fit)
   - 5 issue interest area(s)
   - Location
   - Org role, affiliation
   - Tweet length text on contribution to internet health and/or the network
   - Quote

Profile of a partner org would be similar with a few adjustments.

**Comment by OpenMatt** [comment]
@xmatthewx 
* We have completed our initial pass on this here: 
https://docs.google.com/presentation/d/1dBNsFQ-z4FCUGo3x91MofjE6fyNP0Y6Xzx4iGaOHSn0/edit#slide=id.g1aaae356c5_0_0

* Can you review and tell us whether this meets your needs? 
* We will be adding additional people to this deck as we go -- but this should be a good selection for launch. Let us know what you think. 
* There's a link to a high-res version of each photo included in the speaker notes for each slide

**Comment by OpenMatt** [comment]
cc @prefontaine

**Comment by xmatthewx** [comment]
@taisdesouzalessa – the deck linked above has people who have approved our use of their image and info. You'll find a link to quality photo in the speaker notes.

**Comment by prefontaine** [comment]
Oh actually... I have to update those photo links. They were just ones we
pulled from the web. I'll do that right now.

**Comment by xmatthewx** [comment]
@prefontaine - if those images are in google drive with fairly easy to interpret file names ... i don't think you need to copy-pasta a bunch links to this deck.

**Comment by prefontaine** [comment]
It's okay. All done! Note that my practice is to put full-sized approved
images in the open on their StoryEngine page. Easier than being in a drive.

**Comment by OpenMatt** [comment]
@xmatthewx can you let us know what more do you need from us to close this ticket?

**Comment by xmatthewx** [comment]
Can we invite @ldecoursy and Rizwan to our Tuesday meeting? We close lose threads and clarify next steps.

**Comment by OpenMatt** [comment]
sure perfect idea! done.

**Comment by OpenMatt** [comment]
also @xmatthewx : I think this ticket is now redundant, and this work will get done here:
https://github.com/mozilla/network/issues/6

Let me know if you agree, and I'll close this one?

**Comment by ldecoursy** [comment]
Let's talk in the call about whether or not these are two separate requirements (quote database and people tracking spreadsheet ;) or if we should combine.

**Comment by ldecoursy** [comment]
Starting to highlight folks in green that we have info and approvals from across member categories: https://docs.google.com/spreadsheets/d/1rwNFjojmnOHkctAIAin9Pd_rxziscGJBSWi-z2S6Bg4/edit#gid=866621792

**Comment by xmatthewx** [comment]
@taisdesouzalessa @sabrinang - there is real info for 10 or so people you can start to use. see tabs for different relationships.

**Comment by OpenMatt** [comment]
* Met Feb 7 with @xmatthewx @prefontaine @openmatt
* next step: @openmatt + @prefontaine check in on site design later this week. 

Staging site links:
https://mozilla.github.io/network/
https://projects.invisionapp.com/share/ZJ9YTAGEA

**Comment by OpenMatt** [comment]
See design iterations here also: https://github.com/mozilla/network/issues/39

**Comment by xmatthewx** [comment]
@OpenMatt & @prefontaine – design is updated in [prototype](https://projects.invisionapp.com/share/ZJ9YTAGEA#/screens/216715363), looin' nice. Feel free to share feedback https://github.com/mozilla/network/issues/39#issuecomment-278825333

Note: tags to filter by issue are MVP. Down the line, we'd like to have filters for region, role in network, etc. 

Question: did you have a chance to shorten some of the quotes? It's not critical now, just curious so we know whether to gather updates later.

**Comment by xmatthewx** [comment]
@prefontaine @OpenMatt @ldecoursy   – we should probably think about sort order, and who to feature with a larger card and quote ([see design](https://projects.invisionapp.com/share/ZJ9YTAGEA#/screens/216715363)). Layout is flexible. We can feature one out of three, or fewer. 

cc @taisdesouzalessa @sabrinang

**Comment by prefontaine** [comment]
Okay I've added/edited some more short quotes and will continue adding more
today.

**Comment by xmatthewx** [comment]
I think we can call this done. Work is ongoing, but we should file specific tickets as needed to track new people and changes to the existing bunch.

**Comment by prefontaine** [comment]
Yes. I'm about to post a bunch of new interviews so will update the
spreadsheet. If you have gaps in any particular area please let me know and
I'll focus on those.

**Comment by xmatthewx** [comment]
@hannahkane – it might be good to have your eyes on the mix of people we have ready to feature. A new perspective. Green = member approved to use info
