### ISSUE TITLE
User Journey - double opt-in

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#503]
Task: track the current website to e-mail user journey with screenshots and validate with email team to make sure we are aware of all scenarios and use cases. This documentation will help us in the discussion we will have cross team (#344)

Current user journey:
![user-journey-email](https://user-images.githubusercontent.com/22157921/26948971-12bb8de0-4c4d-11e7-9b5a-72fd2fd9ff74.png)

**Comment by taisdesouzalessa** [comment]
@stephaniemcv I don't think we've met yet, so...first things first: nice to meet you :). 
My name is Taís and I am a UX/UI designer for Mozilla Foundation.

I heard you are the person who could help me figure out the gaps I am having in the Network journey in terms of e-mail. What I am trying to capture in the above diagram is the users' point of view: in which order they receive e-mail communication from us and what type of first e-mail they receive, depending if they are a new user, a user already registered in the Leadership Network mailing list or a user registered in other mailing list that is not Leadership Network.

Could you help me to figure this out? Any insight you have would be super helpful :). 

My questions are:
1. Are the journeys number 1 and 2 accurate?
2. What happens if a user is already registered in on of our mailing lists (but not the Leadership Network) - as shown is the journey number 3?
3. Besides the user types I pointed above (1, 2 and 3) is there any other I am missing?

**Comment by stephaniemcv** [comment]
Hey Taís, great to meet you!

1. Journey 1 is accurate. Journey 2  and 3 should be switched. If they are already registered to the Mozilla Leadership Network list and try to re-signup, nothing happens.
2. If they are already registered in any Mozilla mailing lists, they only get the Welcome email. They don't have to confirm the double-opt in again.
3. Hmm, I think this covers the main scenarios. If you're interested in some weird edge cases I can also give you those.

**Comment by taisdesouzalessa** [comment]
@stephaniemcv thank you so much for your guidance here. Now things are more clear to me :)
I am interested in the edge cases as well, could you let me know what happens? I am also interested to know the frequency they happen, if you have this info.
Let me know if you would prefer to do this over Vidyo.

**Comment by taisdesouzalessa** [comment]
Here is the updated journey. Please let me know if I am missing something, Stephanie.
![double-opt-in](https://user-images.githubusercontent.com/22157921/27058497-8160805c-4f86-11e7-91fa-418717503917.jpg)

**Comment by stephaniemcv** [comment]
Aww, I get an error message when I click on the link. "The image cannot be displayed because it contains errors."

**Comment by taisdesouzalessa** [comment]
Oh, that's no good. Here is a link: https://redpen.io/ws99a7bd530a91b791

I would recommend you zoom out in your browser to see the whole diagram (I kept it as a big image so we can see that's written in the e-mails).

**Comment by stephaniemcv** [comment]
Thanks! It looks good. Do you think we need to call out on flow 2 that it is registered to either Mozilla or Firefox list in the past?

Edge cases that I've seen tend to be around manually importing email address (example: if they were collected on paper at an event). The flow is then dependent upon how recently the emails were collected, relatively recently and we've sent them through flow 2. Older email collections have gotten a custom email reminding people when they signed up and letting them know how to opt-out if they want to.  Frequency is not very often.

**Comment by taisdesouzalessa** [comment]
Hey Stephanie. Thank you so much for your reply and for the edge cases. Super super helpful.

> Do you think we need to call out on flow 2 that it is registered to either Mozilla or Firefox list in the past?
Absolutely! I'll update the chart above to reflect that.
