### ISSUE TITLE
Request network.mozilla.org for the Network site

### ISSUE THREAD

**Issue by jessevondoom** [mozilla/network#504]
We need a permanent URL for the Network site and the preferred location is **network.mozilla.org** — per @cadecairos this involves a MoCo security review before they'll transfer the DNS. So let's start the ball rolling on that and we can create additional issues should we need to make fixes after their review.

**Comment by alanmoo** [comment]
Is our Jenkins setup going to be a problem with this? Would it be better if we wait until we get everything static on Mezzanine?

**Comment by cadecairos** [comment]
They're generally alright with CSP included via meta tag

**Comment by cadecairos** [comment]
Filed: https://bugzilla.mozilla.org/show_bug.cgi?id=1372971

**Comment by alanmoo** [comment]
🎉 we're live
