### ISSUE TITLE
Update homepage featured content

### ISSUE THREAD

**Issue by hannahkane** [mozilla/network#505]
The homepage content needs to be refreshed.

## Latest from the Network
 - I marked the recent articles about online protection and net neutrality as featured. (Sorry I didn't think to do this before the recent database push to prod.) I wanted to mark the Aadhaar post as featured, but noticed it was behind a paywall, so decided against it. (Thoughts?)
- The primary feature is Zeynep's video from Mozfest. Can we replace that with something more recent? Perhaps this [Global Sprint wrap-up post](https://medium.com/read-write-participate/48-hours-devoted-to-a-healthier-internet-c3e1d03cf5aa) or the [Tech Policy Fellows blog post](https://blog.mozilla.org/blog/2017/06/08/increasing-momentum-around-tech-policy/)?

## Get Involved
- What do folks think of replacing the Global Sprint with a Pulse entry about the MozFest call for proposals? (We'd have to file that as a Pulse project, but I think that makes sense.)
- Do we need to update the [Fellowships landing page](https://network.mofoprod.net/opportunity/fellowships/) with info about the Tech Policy Fellows? 
- I think we likely want to keep the Internet Health Report item as is, but do we want to update the landing page to reference the considerit project, since that is an active way for people to participate right now?

@jessevondoom @xmatthewx - thoughts?

**Comment by xmatthewx** [comment]
> Sorry I didn't think to do this before the recent database push to prod

I think we need to push to prod more often while content depends on that. Maybe we set a schedule rather than as needed. 

> noticed it was behind a paywall

😢 😭 

> ...video from Mozfest. Can we replace that...

Is there another video we could feature? Republica Internet Health clinic?

> reference the considerit project

👍

**Comment by jessevondoom** [comment]
LATEST
Republica video sounds good to me, but I think we should get the Tech Policy Fellows post into that section as well if possible. Maybe push it up into the top 3 stories to the right of the video? 

GET INVOLVED
Pushing people to the considerit page on IHR sounds perfect and the Mozfest CFP is great as the main feature in that Get involved section. 

FELLOWSHIPS PAGE
Let's go ahead and add tech policy with a link to the Tech Policy Fellows page in that "Read more..." sentence on the Fellowships page. We may want to revisit that page soon to go into more depth on those programs. But that's a separate issue.

**Comment by hannahkane** [comment]
### Done
 * Added Tech Policy Fellows post to featured News items. (not visible yet)
 * Added a Mozfest CFP entry to Pulse. 
 * Asked Sam and Solana in an email about adding a link to the considerit page. I'd want to use their language.
 * Added link to Tech Policy page from [Fellowships page](https://network.mofoprod.net/opportunity/fellowships/)

### Follow-up tickets:
 * [Replace featured video in "Latest News"](https://github.com/mozilla/network/issues/509)
 * [Replace featured item in "Get Involved"](https://github.com/mozilla/network/issues/510)

### Questions:
 * The Tech Policy Blog post is the only News item from the Mozilla Blog. All of the others are from external sources or our Medium collections. Wondering if that was an intentional editorial decision?
* Once the Global Sprint is replaced in the Get Involved section, there will be no reference to it on the homepage. Is that desired?
* Do we need to add any new partner logos to the [Fellowships page](https://network.mofoprod.net/opportunity/fellowships/)? Are the Tech Policy fellows embedded anywhere, or supported by other partners?

**Comment by hannahkane** [comment]
Closing this.
