### ISSUE TITLE
Update "Upcoming" content

### ISSUE THREAD

**Issue by hannahkane** [mozilla/network#506]
The [Upcoming page](https://network.mofoprod.net/programs/upcoming/) of the Network site needs a few updates

Suggestions (to be refined by @jessevondoom before implementation starts):
- [x] Move Mozfest Call for Proposals item up to main section (it's currently in "Recent") and indicate that the call is open until August 1
- [x] Add "NSF Wireless Innovation for a Networked Society Challenges submissions open"; date: June 15; suggested blurb: "A total of $2 million in prize money is available for wireless solutions that get people online after disasters or that connect communities lacking reliable Internet access." Suggested link text: "Learn more about the challenges"; url: https://wirelesschallenge.mozilla.org/
- [x] Update "Gigabit grant applications open" and "Gigabit grants announced" section with dates, and new cities (maybe @jenntbeard can help provide updated copy?)
- [x] Add Global Sprint to "Recent" section (need copy)
- [x] Add Hive Chicago Buzz to "Recent" section (need copy)
- [ ] I think there are probably some additional events we can add to the list. @jessevondoom to advise.

**Comment by jenntbeard** [comment]
The correct dates for the Gigabit grants can be found here - https://learning.mozilla.org/en-US/gigabit/apply.

Updated copy should read: Innovators in the gigabit cities of Austin, Chattanooga, Eugene (OR), Lafayette (LA) and Kansas City can seek support for projects that leverage next-generation Internet.

**Comment by xmatthewx** [comment]
@hannahkane – should we add this to next week or the next heartbeat. seems valuable for engagement. can we assign you?

aside: if we still think this page gives visitors a valuable snapshot to understand the network and engage (cc @jessevondoom), we should migrate this content to mezzanine. or, is this view better as a curated list of opportunities posted to Pulse?

**Comment by jessevondoom** [comment]
I think moving this into mezzanine is probably the best way to go for now. It'll allow easier editorial control until we figure out how we're handling various time-sensitive opportunities. (I do think there's a big role for Pulse here, just probably a few conversations we need to have first.)

**Comment by hannahkane** [comment]
Filed a PR for these changes in the meantime, but, agreed, moving this to Mezzanine would be rad.
