### ISSUE TITLE
Unblock CMS adding Get Involved content

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#507]
Currently, the CMS manages News & People, but not Get Involved features on homepage. I paused this integration because of some questions that emerged just as @jessevondoom was joining the team.

It's time to discuss and set this work in motion.

My straw-person proposal: 
 1. We create a simple model, no schmancy intelligence (title, body, link string & url, thumbnail). 
 1. We add a feature control for `Homepage Get Involved` where Editor can select items for the specific feature spots, primary and secondary. This is different than how we handle News currently (toggling feature on/off within each entry), but feels like the proper approach. 
 1. "See more projects" button could remain in presentation layer for now or be added to the feature control.
 1. We don't connect Pulse at this time. Editor adds that content manually rather than picking a project. We wait to learn more about editorial plans before investing in that complexity.

Does this seem right? @jessevondoom @alanmoo @gvn @hannahkane

**Comment by gvn** [comment]
This sounds good to me. I think leaving the model simple and highly adaptable makes a lot of sense.

**Comment by jessevondoom** [comment]
Seems like a perfect short-term approach, especially appreciate the flexibility it affords.

**Comment by xmatthewx** [comment]
Great. I'm going to close this. Gavin, we can continue work in #203 or file something new if that's easier.
