### ISSUE TITLE
Run `npm run build` on production api with a debounce

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network#508]
Related to #475 , update the Jenkins build URL we hit in the django signals for model changes (as env var).

Edit to clarify:
When users make changes on network.mofoprod.net/admin, the changes should be reflected on production after a short debounce time.

**Comment by alanmoo** [comment]
cc @gvn @Pomax

**Comment by Pomax** [comment]
it's been a few days, what was this going to achieve for us?

**Comment by gvn** [comment]
Regular builds run on production will ensure that the non landing page content stays up to date.

**Comment by Pomax** [comment]
does that mean continuous building (a la crontab) with debouncing to  make sure we don't build more often than once every X minutes, or signal-based building (e.g. when master updates) but with debounce to make sure only that we still only build once every X minutes at most?

**Comment by gvn** [comment]
Ideally we should run a build whenever content gets updated in Mezzanine.

If that's not possible, then it should be run on an interval.

**Comment by cadecairos** [comment]
We don't need to build every X minutes. 

We already have the code to run builds when API data is changed - that's how we update staging. all we need to do is update the Jenkins build URL we hit (Via ENV var) in the django signals for model changes.

**Comment by Pomax** [comment]
cool, update the issue comment with that

**Comment by cadecairos** [comment]
alright, I created a [new Jenkins job](https://jenkins.mofoprod.net/view/PROD/job/Update Network Frontend) that grabs the commit ID artifact from the last successful production build and builds and deploys it again.

The build trigger URL on production is now pointing there.

**Comment by cadecairos** [comment]
Also, builds are debounced for 2 minutes, and throttled to happen no sooner than 5 minutes apart

**Comment by Pomax** [comment]
v.nice -- does that mean we can close this?

**Comment by alanmoo** [comment]
Yes, I verified it worked yesterday.
