### ISSUE TITLE
Replaced featured item in "Latest from the Network" section

### ISSUE THREAD

**Issue by hannahkane** [mozilla/network#509]
Please replace the video of Zeynep with this [YT video](https://www.youtube.com/watch?v=dRDz_1a8vqQ) of the Republica Internet Health Clinic event.

Copy:
Visit the Internet Health Clinic
by Mozilla
June 2017

**Comment by hannahkane** [comment]
@gvn - would it be disruptive to add this to the current sprint?

**Comment by gvn** [comment]
No, that should be fine, but we'll need design to make a new image.

**Comment by hannahkane** [comment]
In that case - @sabrinang - same question. Would it be disruptive to put this into the current sprint?

**Comment by sabrinang** [comment]
I can take this on @hannahkane

**Comment by hannahkane** [comment]
rad. thanks, both!

**Comment by sabrinang** [comment]
Video screencap on gdrive here: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_ea1p0T0o3OTFnNlU/view?usp=sharing

Preview
<img width="1112" alt="preview" src="https://user-images.githubusercontent.com/2492510/26996677-b55e9548-4d28-11e7-8d55-9cae894b47dc.png">
