### ISSUE TITLE
Run Quality testing scripts

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#51]
About two weeks before we expect to launch, we should build out scripts. Scripts should be fairly self-explanatory, so a contributor could complete a test with minimal support. 

We had a good process for Webmaker. Let's rinse and repeat. Ours will be a bit simpler since there are many fewer interactive features. https://github.com/mozilla/webmaker-core/wiki/Webmaker-Quality-Testing

@hannahkane – it might be worth documenting this process on mofo.build. Suggestions for improvement welcome!

**Comment by hannahkane** [comment]
Added a [page to mofo.build](https://mofo.build/quality-assurance-processes/), though it just refers to the Webmaker QA ticket as an example, because it's so thorough and clear.

**Comment by taisdesouzalessa** [comment]
Moving this task to March, after the page is built. Does it make sense? Should we have those scripts ready for the member preview (March 15-April 15)? @xmatthewx @hannahkane

**Comment by hannahkane** [comment]
Makes sense to me.

**Comment by hannahkane** [comment]
@taisdesouzalessa, what do you think of this for a QA checklist?

## Interaction
- [ ] Nav pop-over
- [ ] Nav from homepage features 
- [ ] External links

## Technical
- [ ] Join CRM integration
- [ ] Analytics firing

## Content
- [ ] Pulse loading
- [ ] People well sorted and featured
- [ ] Images
- [ ] Copy edit (typos, grammar)

## Platform/browser check for responsiveness and layout/elements weirdness
- [ ] Tablet
- [ ] Mobile
- [ ] FF (latest version)
- [ ] Chrome (latest version)
- [ ] Safari (latest version)
- [ ] IE (latest version)

**Comment by taisdesouzalessa** [comment]
@hannahkane I think it looks great. Most of the things are covered. I was wondering if we should add a Design category (or maybe it is inside "Content") with

- [ ] Favicon
- [ ] Accuracy to comps (not in a pixel perfect manner, just to check major visual issues)

Do you think it is useful? Or are those implied in some of the categories above?

Also, do you usually do 404 pages? We don't have any comp for that but maybe we could have a message and leave top menu and footer so users can reorient themselves in case they get lost?

For browser checking, is the latest version usually enough, based on your experience with our audience? I would assume that the audience usually updates their browser to the latest version, but I would like to learn from you so I can apply to other cases as well.

**Comment by hannahkane** [comment]
Great suggestions, @taisdesouzalessa. I updated the comment with your design additions. Feel free to edit my comment if you think of more (because github lets you do that!)

Also filed a ticket for the 404 page. Good call on that, though I don't think we need it before launch.

**Comment by xmatthewx** [comment]
link to our doc from today's staging review: https://docs.google.com/document/d/17R9uJM103VRcvAy20_fg4DgdOi5pAwqkSM8b8Y15H_o/edit#

**Comment by taisdesouzalessa** [comment]
@xmatthewx here is the doc with the copy/images differences between mockups and the staging version (we used staging version because the latest changes are already there). 

We also compared mockups with tickets and found some pictures that should be updated in the mockups (labeled as DESIGN)

https://docs.google.com/a/mozilla.com/document/d/1hxZTnqenxZWgUaLHG-RJSRzafSBXuLHSXK-hDCyTk4U/edit?usp=sharing

**Comment by taisdesouzalessa** [comment]
@hannahkane I linked the individual tickets I filed based on QA that Sabrina and I worked on on Thursday and Friday. We attempted to do some triage adding the label "Important" on Google Docs. Feel free to move the label around and change priorities as you see fit.

We did a more granular QA on those docs.

cc: @xmatthewx

**Comment by hannahkane** [comment]
@xmatthewx - given the detailed doc @taisdesouzalessa prepared, do you think we can close this ticket?

**Comment by taisdesouzalessa** [comment]
@hannahkane the docs I created with Sabrina address only part of the design and content checklist (the ones that have a ticket in front of them: #199 and #200). I think this list here covers a broader range, including crossbrowser, analytics and so on. I see them more like complementary than exclusive. Do you think it gets confusing this way?

**Comment by hannahkane** [comment]
Ah, right. OK, we'll keep it open. Hoping to close #199 and #200, once everything in those docs is ticketed.

**Comment by hannahkane** [comment]
I think we can close this. Feel free to reopen if anyone disagrees.
