### ISSUE TITLE
Iterate UI based on new hero design

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#514]
Ideally we find some small enhancements we can make in the short-term... small flourishes with nice visual impact. I recommend we take a look at Kristina's work on Internet Health site. Some nice elements we might pull in.

**Comment by sabrinang** [comment]
I'll be collecting UI examples in a gslide: https://docs.google.com/a/mozilla.com/presentation/d/1DRNAWJwn55JMAf1v6tZRWN4JiXWt9KplIGAycfMr1yg/edit?usp=sharing

**Comment by xmatthewx** [comment]
@sabrinang will get busy with Mozfest things next week. I think we should consider pulling in @kristinashu to look at this as well as alignment with Pulse and Internet Health Report site.

**Comment by kristinashu** [comment]
I'm closing this ticket given the larger alignment work that is happening https://github.com/mozilla/network/issues/582
