### ISSUE TITLE
Add dependency freshness badges

### ISSUE THREAD

**Issue by gvn** [mozilla/network#516]

**Comment by alanmoo** [comment]
Like these? 
![cxo2to8lwsm53earxedz0yiacwrgosa2cduj8vnrjiqqkxmrhpbyqjuhbhezkrv4](https://user-images.githubusercontent.com/1682681/27151162-b7d32620-5117-11e7-95d7-b997a6bb46a9.jpg)

**Comment by gvn** [comment]
Yes, exactly.
