### ISSUE TITLE
Refine member "roles" in profiles for clarity

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#521]
We need plain language to describe Roles of members in the network. Current phrasing on People page is inconsistent and sometimes totally unclear for non-insiders. 

Examples: 
 - Digital Skills Observatory contributor
 - HiveNYC 
 - Mozilla Reps

Here's a doc to discuss better [role phrasing](https://docs.google.com/document/d/1oweBXa785-WKAOZVmjAEkrwcVxJHLO2GieWIEOhzYYc/edit#) and build consistency.

**Comment by xmatthewx** [comment]
@hannahkane I'd love your help with this. @jessevondoom feel free to drop in any guidance.

**Comment by hannahkane** [comment]
Added more comments. I think we're really close. Maybe @jessevondoom can bring us home!

**Comment by hannahkane** [comment]
OK, we've resolved all of the issues in the doc, and we have a working proposal. 

How to close this out?

I'll file a ticket to update the current People profiles, and then I think this lands on Sydette's desk for ongoing adherence / modification. I'll share the doc with her w/ a little backstory.
