### ISSUE TITLE
Implement new hero artwork

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#523]
Design in #493

**Comment by gvn** [comment]
A couple options from pairing with @sabrinang earlier:

<img width="1905" alt="screen shot 2017-06-15 at 3 46 10 pm" src="https://user-images.githubusercontent.com/206379/27205042-51f86dc0-51e3-11e7-91cc-ed0b290f44a9.png">
<img width="1913" alt="screen shot 2017-06-15 at 3 55 14 pm" src="https://user-images.githubusercontent.com/206379/27205043-51f8f092-51e3-11e7-96ca-0ec04c54802b.png">

**Comment by sabrinang** [comment]
I exported cropped jpgs in the google drive folder: https://drive.google.com/open?id=0B4Q8pzCpDS_eRERhbllweWhsSXc

I also lightened the shadows so the people are not as dark.

**Comment by sabrinang** [comment]
@gvn I modified the image so the edges don't fade to white but a continuation of the beige background so when blend mode overlay is applied it shows. I made a repeating background tile to use on subpages. I included a dark line version which we can use first (and included a backup white line version that uses a .png though). Colour hex for gradients are on this reference image:
![ref](https://user-images.githubusercontent.com/2492510/28044486-80a2a23c-658c-11e7-9c25-8ac5e86aac2b.jpg)

**Attached Images**
![hero_cropped 2x](https://user-images.githubusercontent.com/2492510/28044583-1ddf85ba-658d-11e7-8dc2-cac6504cf43c.jpg)
![hero_cropped_bg 2x](https://user-images.githubusercontent.com/2492510/28044584-1fb4e3da-658d-11e7-8885-210f3c082eb5.jpg)
![network-lines-bg](https://user-images.githubusercontent.com/2492510/28044589-23d0b462-658d-11e7-808a-28d742a03e6e.jpg)
![network-lines-bg-white](https://user-images.githubusercontent.com/2492510/28044592-25cc2b70-658d-11e7-9e93-ca7d7ad7f8ec.png)

.sketch file here if you need to reference the layers: https://drive.google.com/file/d/0B4Q8pzCpDS_eaDJfUzJrTUJ6dEE/view

Let me know if you need anything else :)
