### ISSUE TITLE
Change header and blurb on /news

### ISSUE THREAD

**Issue by hannahkane** [mozilla/network#528]
We changed the header of the corresponding section of the homepage to "Latest from the Network," so now it doesn't match the header on the /news page, which reads "In the News."

![screen shot 2017-06-16 at 2 23 37 pm](https://user-images.githubusercontent.com/8389648/27245286-6cfe13b0-529f-11e7-8f44-02dff58dac8c.png)

![screen shot 2017-06-16 at 2 23 23 pm](https://user-images.githubusercontent.com/8389648/27245288-6eba075e-529f-11e7-8329-33e2be07ae3d.png)

@xmatthewx - was this already discussed? I think we should change the header of the /news page to "Latest from the Network" and perhaps change the hero blurb to "Browse articles, blog posts, interviews and op-eds covering the efforts of Mozilla Network members."

cc @jessevondoom

**Comment by xmatthewx** [comment]
Good call @hannahkane. Longterm, we can address with #539. But short-term this sounds right. 

For blurb, how about:  "Stories by and about members and their initiatives."

**Comment by gvn** [comment]
@taisdesouzalessa #559 is landed, can we close this ticket?

**Comment by taisdesouzalessa** [comment]
Of course, @gvn. Closing :).
