### ISSUE TITLE
Define Feature content requirements & eval process

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#53]
We have identified a few dozen offerings among our [upcoming 2017 highlights](https://docs.google.com/spreadsheets/d/1UsnRgCYYLsQJvicJGKHgn3TU7dfwZ3icn9PaAzxtrmg/edit#gid=2090555237). Some of these will be featured on the site in 2017. Goal: turn quality visitors into members via diverse options.

We need to:
 - clarify the requirements and refine the evaluation rubric. 
 - involve more staff in the info gathering and proposal process

[Spreadsheet](https://docs.google.com/spreadsheets/d/1UsnRgCYYLsQJvicJGKHgn3TU7dfwZ3icn9PaAzxtrmg/edit#gid=2090555237) shows some rough ideas on how to evaluate:
* Help tell story of network?
* Provide a mix of offering types, with high/low engagement?
* Viable? High confidence? 
* etc

Next step after this: Get new items in the queue

**Comment by xmatthewx** [comment]
Work is in progress: https://docs.google.com/presentation/d/1rHH2nKm4pRVlEEsWEyeTcja3Ex0PEANyYLZzP4uVxUU/edit#slide=id.g20e1d0ac8d_0_39

@hannahkane @KevZawacki - I assigned a few content types to you [see initials in deck]. Task is to build a description slide on that type, and a requirements slide. Some of these can be shorter and simpler than Offerings.

**Comment by KevZawacki** [comment]
@xmatthewx Slides/requirement built for 'Upcoming' and 'News.'

**Comment by hannahkane** [comment]
@xmatthewx - what's the next step on this ticket? The deck is done, right?

**Comment by xmatthewx** [comment]
Closing. This is largely done. Handed over to appropriate people.
