### ISSUE TITLE
Capture organic traffic on landing pages

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#540]
We get some good organic traffic from Medium to our landing pages, but they're pretty much a dead end right now. 

How can we capture some of these eyeballs?
 - "hello, this is the network" footer
 - you might also be interested in News, Projects, or Get Involved 
 - etc...

cc @taisdesouzalessa @sabrinang

**Comment by taisdesouzalessa** [comment]
I think this is very important, particularly for the Landing Pages that are Opportunity pages.

If we take a look at the Analytics report for the network 50, for instance (1 month period) we can see that 94.2% of sessions drop off after that, which seems very high. This page seems to have been receiving more traffic than the homepage (correct me if I am wrong, but I think our home page is represented by the "/" which means we had 77 sessions vs 691 in the Network 50):

<img width="1148" alt="image" src="https://user-images.githubusercontent.com/22157921/27968813-74b0d08e-62fd-11e7-95d4-0af27eb447d8.png">

**Comment by xmatthewx** [comment]
Yep. We posted a medium article that got a bunch of organic traffic to that page. THose page pull people to sign up, but not back into the site itself. Something to consider for sure.

**Comment by taisdesouzalessa** [comment]
@xmatthewx let me know in which milestone you would like to tackle this issue. For now, I am moving to the 28th.  Feel free to change it as you see fits.

**Comment by xmatthewx** [comment]
Also worth thinking about if a mini-site needs the same or different callout to the network. Does it include or hide the sign-up button at top of site? cc @kristinashu

**Comment by taisdesouzalessa** [comment]
Related to #690 - REMINDER: the solution chosen here will affect not only 1-column templates but also other opportunities pages: multi-page and 2 columns.

**Comment by xmatthewx** [comment]
Closing. Work on a footer continues in #760.
