### ISSUE TITLE
Add link on form for info on 5 issues

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#547]
When people submit an entry to Pulse, we offer 5 issue categories. Would be useful to link to more info on Internet Health and the 5 issues. 

> Check any key [Internet Health issue](https://network.mofoprod.net/about/) that relates to your project.

Link: https://network.mofoprod.net/about#internet-health

Note: anchor needs to be added to the site's page

<img width="604" alt="screen shot 2017-07-06 at 2 34 37 pm" src="https://user-images.githubusercontent.com/53411/27927033-6a3876a2-6258-11e7-9d11-c6ff85f5513d.png">

cc @hannahkane

**Comment by Pomax** [comment]
This got misfiled, refiled as https://github.com/mozilla/network-pulse/issues/599
