### ISSUE TITLE
Move 'Upcoming' content to Mezzanine

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#551]
Worth discussing: should this be the same content-type as the Get Involved home page features? Upcoming things seem like to move to that featured space. 

Get Involved highlights model here: #518

New Upcoming content here: #506 

cc @jessevondoom @hannahkane

**Comment by alanmoo** [comment]
These sections seem awfully similar, but I don't think I'm in the position to make the call. Will the items in "Get Involved" always be items that also appear in "Upcoming"? If so, how do we want them to "expire"? We could start with these being manual moves and work in date logic later on, but we first need to decide if they are in fact the same thing. Seems like a question for Sydette? What's her github handle?

**Comment by hannahkane** [comment]
My two cents:

As they currently are, I think these content types are similar but different. :) They are similar in terms of the metadata, but different in terms of purpose.

The "Upcoming" content is date-focused, and aims to get the user to do something. The "Get Involved/Highlights" features on the homepage are not necessarily tied to a date, and are more about increasing awareness of our offerings (@taisdesouzalessa articulated this well during the site planning meeting today).

Another key difference: the "Upcoming" items almost always (always?) point to an external site, whereas we've mostly kept the "Get Involved/Highlights" content within the site.  We've already established a precedent of sending people away from the site on the homepage with the "Latest" section, but I'm not sure that's something we really want to encourage.

I don't personally have a strong opinion on this. If we decide to use a shared model, I'd suggest we go with a date-based/action-oriented approach.

**Comment by alanmoo** [comment]
I'm fine keeping them as separate models; I haven't yet seen an argument for making them the same model. @Pomax do you have any thoughts?

**Comment by xmatthewx** [comment]
Seems like decision is decided here: https://github.com/mozilla/network/issues/574#issuecomment-316266364

**Comment by gvn** [comment]
I believe this is good to close! 🎉
