### ISSUE TITLE
Read the "Mozilla Leadership Network: stories+early learnings" and summarize the findings

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#557]
- [x] Read [this report](https://drive.google.com/a/mozilla.com/file/d/0B3b1KWRwjxtoZHdtdkp4Nmt1X2M/view?usp=sharing)

- [x] Summarize the findings. The goal of this exercise is to better understand the audience described there and come up with an easy to digest summary of the main ideas we saw there.

**Comment by sabrinang** [comment]
We are document for insights and findings in this gdoc: https://docs.google.com/document/d/1kM2KGgRCLtPt8eJ8CwOEAMaCo9WZ59Obne77H29z5dw/edit?ts=59601b98

**Comment by taisdesouzalessa** [comment]
Closing this issue since the finding report was delivered. We can reference this report after we dive deep in the persona research.
