### ISSUE TITLE
Prep 3+ items for campaign page

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#56]
@HPaulJohnson – let's identify 3 or so items for launch. We'll need title, intro words, image, and link. Nothing crazy fancy. Maybe assign to Jordan/Natalie/Becca to pick and pull this together?  

Page: https://projects.invisionapp.com/share/ZJ9YTAGEA#/screens/216715353

For launch, layout might be simpler like: https://projects.invisionapp.com/share/ZJ9YTAGEA#/screens/216715367

cc @taisdesouzalessa

**Comment by xmatthewx** [comment]
@HPaulJohnson & @KevZawacki – any feedback on the Campaigns page? https://projects.invisionapp.com/share/ZJ9YTAGEA#/screens/216715353

How do you feel about the items featured, the images, and copy. Any complexity in linking out from here to somewhere awesome?

**Comment by KevZawacki** [comment]
@xmatthewx Presentation and featured items look great! Plus, we have solid sites we can link out to for each one. 

Very small nitpicks about the copy -- but perhaps something we can fix at a later date?

**Comment by xmatthewx** [comment]
From conversation with MoCo and @HPaulJohnson yesterday, it seems like we need to reframe things a bit. I'll let Paul lead on this, but as I saw it, we should frame each item as part of a bigger campaign effort. And maybe... invite people to view and share items as a champion of the cause.

**Comment by xmatthewx** [comment]
Pending further discussion. Based on feedback from staff and execs. We will likely look at ways to integrate this content in with News, Projects, Upcoming, rather than a standalone page.

**Comment by hannahkane** [comment]
Closing for now. Will reopen if needed later.
