### ISSUE TITLE
Dashboard with all data related to our users

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#560]
**Description:**
The data we have about our audience and staff insights related to the Network is spread in many documents and places. This situation was a bit challenging for design, who had to constantly remember where the data was in order to access it for design research. The proposed solution for that was to create a dashboard, with links pointing to all the places data lives.

Here is the link to the dashboard: 
https://docs.google.com/spreadsheets/d/1Y-PSaKUPTfpUe1aZB-l2SPDoZ2NmHUlWGi3Qbkr03F0/edit?usp=sharing

**Comment by taisdesouzalessa** [comment]
We talked to 270 Strategies about this model and received the following feeback from Caroline: 
1. It seems like there is some color coordination with the lines and types, but I'm not 100% sure what it means. I would recommend making that clearer. Maybe something at the top that associates the type with a color and defines each type so it's easy to scan through and in something you're looking for.
2. The descriptions of each section are the most important piece for me here since I don't know what all of these data points are or how they are collected. I would assume at least some people coming to this dashboard won't be aware of all the different pieces and will likely go off the descriptions too, so I would recommend making them clear and pretty detailed. 
3. On that point, I think most of these are pretty good - but I'm not sure what Feedback and Survey Analysis Plan is - which Survey? It's also light blue and doesn't have a type making it harder to categorize. 
4. Lastly, what is the plan for updating this?  Will it be shared out so people can add to it? How do we make sure it stays evergreen? **@hannahkane and Taís will keep an eye for updates on Mozilla's side and 270 Strategies will update the board as well.**

It is important to notice that the data analysis will come from 270 Strategies. 

Feedback pieces from 1 to 3 still have to be integrated into the dashboard.

**Comment by hannahkane** [comment]
@taisdesouzalessa - anything in particular you want to do on this during this sprint?

**Comment by taisdesouzalessa** [comment]
@hannahkane I don't think so. Probably next one I can take a look at it and integrate Caroline's feedback? I've been focused on personas for this sprint because it seems a higher priority. Let me know if I am mistaken.

**Comment by hannahkane** [comment]
agreed! It's been removed from the milestone. Thanks!

**Comment by taisdesouzalessa** [comment]
@hannahkane do you think we should close this issue? I will keep this dashboard for my personal use (and extend it) but I am not sure if we are using this as an artifact to share with others and if we should keep this issue open, what do you think?

**Comment by hannahkane** [comment]
I think we can close. Thanks, @taisdesouzalessa.
