### ISSUE TITLE
Make "Get Involved" page CMS editable

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network#563]
Need to discuss if this is evergreen content or structured.

cc @xmatthewx

**Comment by xmatthewx** [comment]
@jessevondoom what do you think? If it was same effort to build either way, which would you choose? Right now, this is fairly stable content, probably fine as a page though wysiwyg could break layout. Better edited as html.

**Comment by jessevondoom** [comment]
I think we can view this as evergreen for now. I still feel it's the wrong place for the themes section but don't have a strong feel for where the right place actually is. So my gut instinct is to say it's stable now, we won't have massive changes soon, and we have more pressing sections to rethink/re-engineer. 

All that's to say that if we leave it as evergreen HTML for the moment I think that would be a-okay.
