### ISSUE TITLE
Network Personas Project: benchmarks 

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#568]
- [ ] Collect benchmarks for inspiration and guidance of best practices related to personas. 
- [ ] Create an initial template persona card. 
- [ ] Test that template against an actual story from StoryEngine and iterate.

We had a meeting with Christine and she brought up some other points we could use in a template such as:
- [ ] Level of familiarity with technology.
- [ ] Level of familiarity with Mozilla. 

And one other thing we should consider:
- ~~[ ] What do we want them to do? What is our ask? How do we expect them to use the website?~~ <-- I feel this question is now answered in the [strategy docs](https://docs.google.com/a/mozilla.com/document/d/13waxxLxbfWo4qBI6ZsakEI1nXCBfA6ZTPnaMk3PIIPE/edit?usp=sharing), do you agree with that @hannahkane @xmatthewx?

@kristinashu @flukeout I broke up this task in some steps here, feel free to create new tickets for each or edit this ticket as you see fit, ok?

**Comment by taisdesouzalessa** [comment]
- This is the draft report of the Conscious Choosers Segmentation that Venetia Tay shared with me:
https://drive.google.com/file/d/0B2wvfBjG7Mb1S1VKblFBVUlzRk0/view 

- This is the CoSS research shared by Kristina (personas on slide 37): 
https://docs.google.com/presentation/d/1V5nJbZxgJPnW3Ggz5Jz1iid22kOlo-9R6RGHZO1LGJo/edit#slide=id.g1b0c1f5c61_0_62

- Science personas https://drive.google.com/a/mozilla.com/file/d/0B2irLVDJivhLb1pSZEdLUXdtaFE/view?usp=sharing

**Comment by hannahkane** [comment]
@taisdesouzalessa - to your question in the first comment - I think the strategy docs are the place where we should answer that question, yes. Would be good to explicitly reference user personas in those docs, once we have them. cc @jessevondoom

**Comment by jessevondoom** [comment]
Yeah +1 to @hannahkane's answer and I'll go a step further: developing those personas is an important part of the overall strategy, so we need to carve out space for this work in the larger mofo digital strategy and standardize our personas across projects. (And have them reference back to the network strategy user types in the enchilada doc.)

**Comment by taisdesouzalessa** [comment]
@flukeout @kristinashu we estimated 8 points for this task. Feel free to change it if you feel it is not accurate ok?

**Comment by xmatthewx** [comment]
@flukeout - let us know if you have any questions or progress to share. @prefontaine offered to share some examples but might be traveling right now. We could also reach out to her colleague via email.

**Comment by prefontaine** [comment]
I am traveling :) but checking email and happy to help out. Can you send draft template and I'll comment or see if any examples would be helpful? Also a link to strategy if not in Git thread.

**Comment by flukeout** [comment]
I've been trying to find some real-life benchmarks and so far have, got a couple of things..

**Mailchimp**
They have a very open design culture, I'm trying to find more places like this. 
* [Persona Posters](https://creative.mailchimp.com/persona-posters/?_ga=2.62911401.403422251.1500666092-1943156118.1486685847)
* [Persona photos flickr album](https://www.flickr.com/photos/jasontravis/sets/72157603258446753/)
  * Really cool visual way to present personas along with items in their life, done by one of the Mailchimp designers.

**CodePen**
Codepen did a redesign recently, and as part of that process created some personas.
* [CodePen Personas PDF](http://codepen.seesparkbox.com/assets/CodePen-Personas.pdf)

**Persona Design Resources**
* http://opendesignkit.org/methods/personas/
  * They also have some real-life examples linked at the bottom

To be continued...

**Comment by prefontaine** [comment]
Hi All. I've shared some examples and a proposed process to get most out of StoryEngine. @taisdesouzalessa is reviewing first. (@taisdesouzalessa please let me know if any questions)

**Comment by taisdesouzalessa** [comment]
Hey @prefontaine, I just took a look at it and added one note of one thing I thought it was missing. @jessevondoom @hannahkane @xmatthewx the doc is here: https://docs.google.com/a/mozilla.com/document/d/1Yw4gmD_8Bi6-ZSVPQtE-5o_V43qMO0NPwVHeljgAGbk/edit?usp=sharing

**Comment by taisdesouzalessa** [comment]
Had a meeting with Luke and Kristina to discuss findings through StoryEngine and get feedback/insights on pieces we are adding to the template. Meeting documented **[here]**(https://docs.google.com/a/mozilla.com/document/d/1XX19SI2GnV6dPEA8RXw6ZOXUS7RqD3K6nz6gMfXOQQo/edit?usp=sharing)

Next step: Kristina and Luke to figure out which categories belong to the template. Once they have that Taís will start filling in the template with current insights from StoryEngine and for the missing pieces, figuring out with others on how to get the info/or making assumptions together with the team. <-- does that seem correct to you @flukeout and @kristinashu?

**Comment by xmatthewx** [comment]
Thanks @kristinashu @flukeout for your input on benchmarks and this template. I suggest that we hand your work over to @taisdesouzalessa to lead on the template and first draft persona. Her discovery work is done-ish and she's got bandwidth to build a template and first draft. You two have _plenty_ on your plates. Make sense? She's also got lots of insight from her research on how the template can respond to our strategy docs, fill gaps, and challenge assumptions. @taisdesouzalessa can lead on this and look to you two for feedback, brainstorming, etc. Let's chat on slack if there's any questions.

**Comment by kristinashu** [comment]
That would be great, thank you! Sorry I didn't get to do much.

**Comment by xmatthewx** [comment]
@taisdesouzalessa – is this ticket still useful? want to bump it to next heartbeat?

**Comment by taisdesouzalessa** [comment]
It will be useful again once we move from draft to template stage. I'll bump it.

**Comment by taisdesouzalessa** [comment]
IBM example (I found it very interesting):
<img width="1422" alt="image" src="https://user-images.githubusercontent.com/22157921/29682466-efe2b500-88bf-11e7-8a2a-b4c01728737a.png">

Closeup:
https://cdn-images-1.medium.com/max/2000/1*QinXmcsZoxEWAY5X9Ft3uA.jpeg

**Comment by jessevondoom** [comment]
@taisdesouzalessa This is really great. I could see something like this, with some added lines/brackets above denoting their network group affiliations, conscious chooser stuff, etc. Very cool!

**Comment by xmatthewx** [comment]
@taisdesouzalessa can we close this benchmarks issue?
