### ISSUE TITLE
Add content to Upcoming page comp

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#57]
Our Upcoming page shows a snapshot of the upcoming milestones key to the network and to conveying its story. 

We need to gather/create content for 6-12 items for launch. Prospects identified in [this spreadsheet](https://docs.google.com/spreadsheets/d/1UsnRgCYYLsQJvicJGKHgn3TU7dfwZ3icn9PaAzxtrmg/edit#gid=2090555237)

Each item requires an image, title, link, and short description

See https://github.com/mozilla/network/issues/7 for prior discussion on some specifics.

**Comment by KevZawacki** [comment]
@xmatthewx Happy to start writing these up. Have we settled on which ones?

**Comment by xmatthewx** [comment]
You're the editor in chief! Maybe when we talk with Chris on Monday, we can hijack a few minutes to flag some priority items from his perspective. Lainie can probably help identify owners of these items to provide us with the details. 

Maybe start with the ones that jump out as obviously bigly and relevant to many across the network? I flagged a few from my naive perspective in [Column C](https://docs.google.com/spreadsheets/d/1UsnRgCYYLsQJvicJGKHgn3TU7dfwZ3icn9PaAzxtrmg/edit#gid=2090555237).

**Comment by KevZawacki** [comment]
I've written up eight possible entries [here](https://docs.google.com/document/d/1MDfeLsJimZm6glqOQENv-aOe_XOTgT-j0H-NJo39FXs/edit#bookmark=id.fgy6dwlfaki9) (beneath "ENTRIES"). 

@xmatthewx On Monday, we can check with CLaw to see if they feel right.

**Comment by xmatthewx** [comment]
Thanks @KevZawacki. This all looks great from where I sit. (I knew we wanted to sneak another topic into our meeting earlier. But couldn't recall this. Drats.)

@taisdesouzalessa – we can add this content to the upcoming page when there's a moment. After, I'll run it by Chris & Co. for feedback. I think we'll get a stronger reaction from the page, than in a gdoc.

**Comment by xmatthewx** [comment]
done! we can edit bits later if needed.
