### ISSUE TITLE
Review member interviews, write main points in sticky notes and do an affinity diagram per group

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#570]
**Description of the process:** reading member interviews from Story Engine and writing sticky notes with main info in order to organize clusters of personas.
- [x] 1. Start with 1 group so @flukeout and @kristinashu can see what type of info we can currently get with StoryEngine
- [x] 2. Do a simple test to see if the grouping of characteristics is working
- [x] 3.  Open this group to feedback so we can do a team refinement - include Christine on that
- [x] 4. Repeat steps 1 to 3 to other Personas

Comparison chart with clusters that surfaced:
https://docs.google.com/a/mozilla.com/spreadsheets/d/1KBQp7LSNfsxfV0sView2gorJooY93QBwDMXGN-nih9E/edit?usp=sharing

Spreadsheet [here](https://docs.google.com/a/mozilla.com/spreadsheets/d/18T_uclwqj-c5_FDhw2sgppnaskHurI7r2IPiD3WN8Rw/edit?usp=sharing)

**Comment by taisdesouzalessa** [comment]
Hey team. Starting with the assumption that people related to Open Leadership, Fellows, Open Science and Study Group Leads would have common interests to form a persona,  I read 6 stories from StoryEngine and found patterns that will inform our first Persona template. The temporary name of this Persona is "Persona #1". Any ideas for a better name?

Please take a look at this board to see the patters that emerged: https://invis.io/98CV7XETM#/246777597_Persona--1-From-Story-Engine

Feedback is welcome. The more voices we have here, the better.
@xmatthewx @hannahkane @jessevondoom @prefontaine @paulfzenke @sabrinang

**Comment by taisdesouzalessa** [comment]
And this is a little test I did to see if this Persona #1 has universal characteristics that accurately represent a big group of people. Further validation/testing will be required over time but this was a quick way I found to do a validation for now.

We can find as a group other ways we can test this Persona's characteristics. Let me know if have any ideas :).

https://docs.google.com/a/mozilla.com/document/d/1vJ1MJoiKGXNPO65ZANNAnTOHAUphZIzeHBRFraXU1XM/edit?usp=sharing

**Comment by taisdesouzalessa** [comment]
Team, here is the affinity diagram for Persona number 2. Starting with the assumption that people that belong to 3 groups (Mozilla Club Regional Coordinator, Mozilla Club Captain and DSO) have common characteristics, I read 5 stories from StoryEngine and found patterns that will inform our next persona template.

https://invis.io/U5D1948NF#/248618764_Persona--2-From-Story-Engine 

Please take a look and comment there if you agree with those clusters or if you would change anything.

**Comment by xmatthewx** [comment]
Excellent. Which group would this be in the [draft groups](https://docs.google.com/a/mozilla.com/document/d/1rJJOC_qvFulL9sFlhs02MXRSpCQRoAGaXg6PISvFA60/edit?usp=sharing)?

**Comment by taisdesouzalessa** [comment]
I need some help to figure out the group of this one...I added the information of the clusters (from persona 1 and persona 2) side by side to facilitate comparison [here](https://docs.google.com/a/mozilla.com/spreadsheets/d/1KBQp7LSNfsxfV0sView2gorJooY93QBwDMXGN-nih9E/edit?usp=sharing).

I feel this is a new category: volunteers who are taking initiative in the movement. They are clearly leaders and they are very close to the communities they serve. They are super engaged with us. 

Wondering what are your feelings about this group and where it would fit, @xmatthewx.

**Comment by taisdesouzalessa** [comment]
• Persona number 3 affinity diagram here: https://invis.io/KZD34QXJ8#/249159992_Board-Persona3-
• They relate to: The Uber Teacher (Leader)
• Included them in the side by side [comparison chart](https://docs.google.com/a/mozilla.com/spreadsheets/d/1KBQp7LSNfsxfV0sView2gorJooY93QBwDMXGN-nih9E/edit?usp=sharing)
• I feel that after all the available personas in StoryEngine are clustered I will need to go back to this side by side chart and diagrams to surface similarities and differences between groups. It is a non-linear process.

**Comment by taisdesouzalessa** [comment]
• Persona number 4 affinity diagram: https://invis.io/AFD5HXX9N#/249859135_Persona_-4_-_From_Story_Engine
• I am not sure if they relate to "The Wonk" or "The Influencer". I think both groups are interested in bigger changes in the society that are deeply aligned with our agenda and also they have a big power/influence on these areas. I wonder if you think a distinction is necessary here... @xmatthewx @hannahkane @prefontaine @flukeout @sabrinang @kristinashu any thoughts about it? :).
• Included them in the side by side [comparison chart](https://docs.google.com/a/mozilla.com/spreadsheets/d/1KBQp7LSNfsxfV0sView2gorJooY93QBwDMXGN-nih9E/edit?usp=sharing)

**Comment by taisdesouzalessa** [comment]
Hi all! After investigating the information from Story Engine, getting feedback from different people about ways the information would make sense and comparing data against our Persona Groups Draft Doc I think there is a way to divide the leaders in only 3 groups (instead of the initial 4 we had in our Persona Groups Draft). Some observations:

1. It is important to notice that none of this groups feel they are fighting for the "Internet Health". They are fighting for issues that we, as Mozilla, consider part of the "Internet Health". They are deeply aligned with us in principles but don't use all the same words as we use.
2. I found that many characteristics and motivations of "The Wonk" and "The Influencer" matched when I clustered the data. Also, "The Professional" and "The Uber Teacher" as well (we had big groups of researchers, educators and some journalists). 
3. There is a third category that have very unique motivations and characteristics. I feel they fit into the "Action-taker" group but I feel they are leaders as well.

Please take a look at the main characteristics of each group and let me know if it makes sense to you. 

https://docs.google.com/spreadsheets/d/1KBQp7LSNfsxfV0sView2gorJooY93QBwDMXGN-nih9E/edit?usp=sharing#gid=1706648975

@xmatthewx @jessevondoom @hannahkane

**Comment by hannahkane** [comment]
I like the idea of simplifying and combining into a smaller number of personas, if the data supports it, and if there's still enough distinction to be useful to us. Can we perhaps test out these three personas with something coming up on our roadmap - perhaps the revised About page?

**Comment by xmatthewx** [comment]
Let's schedule some time to chat about all of this. 

Keep in mind that our data is incomplete, reflective of past work but not a comprehensive in terms of future aspirations. We should look to story engine to help bring our personas to life, but let the strategy direct give shape to our audience and future research.

**Comment by taisdesouzalessa** [comment]
Sure, let me know what time works best for you both and I can book a meeting.

**Comment by taisdesouzalessa** [comment]
I'll discuss those groups with Matthew in the next days but the bulk of this work is done. I may just need to tweak it. I'll close it once the discussion happens.

**Comment by taisdesouzalessa** [comment]
I'll close this ticket since @xmatthewx and I are already aligned on the groups. The work inside each group is being tracked on #714 - does that sound good to you all? If not, please let me know and I reopen this ticket.
