### ISSUE TITLE
Decide if "Upcoming" content and "Get Involved" on homepage are same model

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network#574]
This is what inspired turning #551 into an Epic

Matthew:

>Should this be the same content-type as the Get Involved home page features? Upcoming things seem like to move to that featured space.
>
>Get Involved highlights model here: #518
>
>New Upcoming content here: #506

Alan:
>These sections seem awfully similar, but I don't think I'm in the position to make the call. Will the items in "Get Involved" always be items that also appear in "Upcoming"? If so, how do we want them to "expire"? We could start with these being manual moves and work in date logic later on, but we first need to decide if they are in fact the same thing. @sydette may be able to provide some insight.

**Comment by alanmoo** [comment]
@sydette test

**Comment by Sydette** [comment]
Get Involved should be direct action items. Upcoming can include anniversaries, important dates, announcement of other projects opening. Ideally we'll be  surfacing events and happenings from the Network into upcoming as a circuit to pulse as well as non Mozilla events that impact IH .

**Comment by alanmoo** [comment]
Ok, so it sounds like they should be different models. Unless anyone has objections by the time @pomax and @gvn start tomorrow, let's go with that to keep this moving.

**Comment by gvn** [comment]
In that case, this is the schema for Upcoming:

https://github.com/mozilla/network/blob/master/source/json/upcoming.schema.json
