### ISSUE TITLE
Pull "Upcoming" content from Mezzanine to front end

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network#576]
Looking at the code, I'm guessing it won't be too hard to switch the source of content on the upcoming page from the hardcoded JSON to being pulled from Mezzanine, is that correct @gvn?

**Comment by gvn** [comment]
This is basically the same LOE as Highlights. As I recall @xmatthewx thought this section might be going away or changing, but I'm fine with migrating it as it's the last hardcoded JSON "model".

**Comment by alanmoo** [comment]
Good to know. And yeah, it may change, as to be determined in https://github.com/mozilla/network/issues/574

**Comment by alanmoo** [comment]
Some data is now live: https://network.mozilla.org/api/milestones/

For displaying dates: If start and end date are the same, just show that date.
If it's the first and last of the month, show just the month name.

**Comment by gvn** [comment]
Are we renaming Upcoming to Milestones? @alanmoo @xmatthewx

**Comment by alanmoo** [comment]
Not the front end page itself. But we needed a better word to refer to the items on those pages, and milestones seemed to fit.

**Comment by xmatthewx** [comment]
@alanmoo pointed out that "past upcomings" is very awkward. 🙄

**Comment by gvn** [comment]
To fully verify we'll need to do a prod push of `network-api` first.

**Comment by gvn** [comment]
@xmatthewx Can you verify this looks correct?

https://network.mofostaging.net/programs/upcoming/

**Comment by xmatthewx** [comment]
👍
