### ISSUE TITLE
Decide how primary news item will be identified for homepage

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network#577]
Currently, the news articles in the right column of the homepage show up based on the most recent "featured" items from the "news" section of the admin. We probably don't want the primary item (on the left side of the homepage under "Latest from the Network") to rotate out that quickly, so we need a way to identify that separate from the existing "featured" flag.

Long term, it would be best to simply have a homepage model/view from which we can choose the specific item, but to start we probably need to do it within the News model.

Thoughts @pomax @xmatthewx?

**Comment by xmatthewx** [comment]
Here's a quick demo of an admin interface. Clunky MVP. The drop-downs would get unwieldy, but if they options are sorted reverse chronological, it can get us through the next few months. 

<img width="897" alt="screen shot 2017-07-19 at 2 45 55 pm" src="https://user-images.githubusercontent.com/53411/28386004-328e46e2-6c98-11e7-9576-034350452880.png">

**Comment by alanmoo** [comment]
My instinct is to start this model for the "super-featured" news article, and then slowly add to it over time. One thing this doesn't give us @xmatthewx is a history of which news items were previously featured on the homepage. Do we need that though?

**Comment by xmatthewx** [comment]
We need a News archive, but I don't think we need an archive of what's been featured. Analytics will capture enough history if that was ever needed internally. Curious what @Sydette @jessevondoom think.

**Comment by xmatthewx** [comment]
We can run with current number, change later if needed.
