### ISSUE TITLE
Update front end to use designated news item in left column on homepage

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network#579]
I believe this is separate work from #656 because the featured news item is still currently hard-coded.

The News items have an "isVideo" flag- this work should not only pull in the appropriate news item, but if it's a video, the video button overlay should appear as it does on the current version of the home page.

I can't recall if long-term we're going to want the video to play inline, but that's a topic for another issue.

**Comment by xmatthewx** [comment]
is this ticket necessary @gvn? or captured in the bigger homepage admin effort?

**Comment by gvn** [comment]
I think it's captured. 🎉
