### ISSUE TITLE
Enable HSTS on site

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network#580]
As recommended by security team, so that we can use a Mozilla domain.

**Comment by cadecairos** [comment]
We can't do this, since the static parts of the site are hosted on S3.

we can either serve it all using Django, or wait until I get us access to Lambda functions for Cloudfront requests, where I'll be able to add these kind of security headers on the fly.

**Comment by cadecairos** [comment]
I take back all that I said. Lambda@edge was released yesterday!

We can make use of it in the short term to boost our scores on the observatory.

**Comment by alanmoo** [comment]
@cadecairos can we close this?

**Comment by cadecairos** [comment]
yes!
