### ISSUE TITLE
Merge network and network-api repos

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network#583]
- [ ] move some of the api-deploy-specific files from the server root directory into the real root dir:
  - procfile
  - appveyor CI file
  - travis yml file
- [ ] figure out how to selectively trigger CI for "network" and "API" sides of things based on which dirs a PR touches (for efficiently determining that we might actually want sibling dirs "client" and "server" so we can tell inside of which dir a PR makes changes)

Etherpad: https://public.etherpad-mozilla.org/p/unity

**Comment by alanmoo** [comment]
@cadecairos Is this epic up to date or can we close some of the sub-tasks?

**Comment by cadecairos** [comment]
# UNITY IS LIVE ON PRODUCTION

**Comment by xmatthewx** [comment]
@alanmoo – wanna close this?
