### ISSUE TITLE
Relatioships between StoryEngine and Other Docs

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#587]
Analyze the relationships between emerging personas from Story Engine, the [Enchilada doc](https://docs.google.com/document/d/13VHN6xazlMTWyuwMe_ivjwpy_CGLd8jGaOlKnLSFJJ0/edit?usp=sharing), Mark's [X-Plane deck](https://drive.google.com/a/mozilla.com/file/d/0B1dIaWlgfRdIVnM5Nm00OW9YVWc/view?usp=sharing), [Jesse's strategy](https://docs.google.com/a/mozilla.com/document/d/13waxxLxbfWo4qBI6ZsakEI1nXCBfA6ZTPnaMk3PIIPE/edit?usp=sharing) docs and Venetia's [Counscious Choosers](https://drive.google.com/a/mozilla.com/file/d/0B2wvfBjG7Mb1S1VKblFBVUlzRk0/view?usp=sharing) draft research

Deliverable: some sort of mapping/report that shows the relationships <-- @jessevondoom please feel free to edit here more details of the deliverable you are expecting, ok?

**Comment by xmatthewx** [comment]
If possible, a visual map would be useful to help us get to simplicity.  Better reference than a big report ... if it's possible.

**Comment by jessevondoom** [comment]
Yeah agreed. We mostly need a way to examine the overlap between the various groups and standardize our language. Ultimately what I'd love is something visual (per @xmatthewx) that can show the relationship between enchilada groups, conscious choosers, and the personas/persona groups we define. 

The enchilada already does a decent job of showing who belongs in each category but ties them to Mozilla-specific roles and with no mapping to conscious choosers. So essentially we're looking for something that helps us map personas to the MoFo and MoCo categories — that will help us understand who to target when we're pulling traffic from MoCo (assuming many conscious choosers' journeys start there) and how to grow each of the various Network member types once they're on MoFo sites.

Can be as simple as a Venn diagram or area chart we'll add persona names to later — we've got the deep dive reports already...just looking for a rosetta stone right now.

**Comment by taisdesouzalessa** [comment]
Thanks for the clarity on the expected deliverable Matthew and Jesse! 
Based on the conversation I had with Matthew a while ago, we decided it would be good if I shared the process while I study all this data. 

I finished the study of the relationship between Xplane and StoryEngine and I am sharing the process in this doc. The final deliverable is TBD and it will be together with all the others. I'll package all in a nice way but I wanted to share the doc while still in draft for feedback, questions.

Please comment there, add people to see it, etc. https://docs.google.com/document/d/1tG3FCKMliquYlasp7u7m-_6gGvGD-Zj4h2r5g5CIvxQ/edit?usp=sharing

cc: @xmatthewx @jessevondoom @hannahkane

**Comment by taisdesouzalessa** [comment]
Hey team,

Here are the diagrams:
https://invis.io/A5CQB4NXU#/245312112_Xplane-Storyengine
https://invis.io/M7CQBC8QX#/245312837_Enchilada-StoryEngine-ConsciousChoosers

The full study is here:
https://docs.google.com/a/mozilla.com/document/d/1tG3FCKMliquYlasp7u7m-_6gGvGD-Zj4h2r5g5CIvxQ/edit?usp=sharing

@paulfzenke we were wondering if we could have your eyes on this issue since you have a bunch of knowledge about the Network. It would be great if you could add your thoughts in the study and diagram :). Let me know if you want to chat to add more context. We can schedule a call.

@jessevondoom @xmatthewx @hannahkane @sabrinang @prefontaine please let me know what you think. Any insights/feedback/blind spots/gaps? The more perspectives, the better. Feel free to edit the doc too if you want.

**Comment by prefontaine** [comment]
Thanks! Just copying Alecia.

**Comment by taisdesouzalessa** [comment]
Sorry @prefontaine I forgot :( Does Alecia have a GitHub handle? Or should I copy her via e-mail?

**Comment by prefontaine** [comment]
@ankuhl

**Comment by hannahkane** [comment]
Really enjoyed reading this, @taisdesouzalessa. Great, detailed research and analysis.

**Comment by taisdesouzalessa** [comment]
Closing this issue because the deliverables were delivered! In case there are revisions, I can open it again in the future.
