### ISSUE TITLE
QA > Full size Pattern on Subpages (About Page)

### ISSUE THREAD

**Issue by sabrinang** [mozilla/network#594]
For pages with narrow hero sections like the about page, we can keep the original size of the pattern. Currently it shrinks and it is faint:
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/2492510/28444802-9753d9ac-6d74-11e7-8eed-4848ac66316f.png">

We can make it full size to look like this:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/2492510/28444905-32146f06-6d75-11e7-8e2d-ba0ba48e145b.png">

**Comment by xmatthewx** [comment]
Ah, the minified header. @gvn – cc'ing just to put it on your radar.

**Comment by xmatthewx** [comment]
R+ 👍 Good to promote.
