### ISSUE TITLE
Set up build target for static assets

### ISSUE THREAD

**Issue by gvn** [mozilla/network#595]
In combining `network` and `network-api` I'm trying to build a bundle of static assets into a folder inside of `network-api` (what's currently being built into `/dest` on `network` and then hosted on S3).

There's a folder that already has some static assets in `network-api`: `app/networkapi/static/` but it is served to `/static/...` on the front end.

I'm hoping to be able to serve this "dest" bundle at the root on the front end, but I'm not sure exactly how to do that.

Is there a way that we can create a folder inside `network-api` that will be reachable at the root on the client?

**Comment by gvn** [comment]
@gideonthomas @Pomax @cadecairos  – Any thoughts?

**Comment by alanmoo** [comment]
@arush0311 maybe you have some thoughts too?

**Comment by gideonthomas** [comment]
I might be missing context for this, but you should simply be able to use WhiteNoise to  serve the static build from any directory you want: http://whitenoise.evans.io/en/stable/base.html#WhiteNoise.add_files

**Comment by Pomax** [comment]
@gideonthomas we would like to serve all the "network" pages from its own dir, similar to how in Express you can say `express.static('/client/dist')` + `express.static('/static/')` and get seemless static hosting from multiple directories.

**Comment by gideonthomas** [comment]
Hmm, do you want to serve the `/client/dist/` dir from the root url and `/static/` from say `/static/*`? If so, I think you can just set `WHITENOISE_ROOT`(http://whitenoise.evans.io/en/stable/django.html#WHITENOISE_ROOT) to point to `/client/dist/` so that it would serve your built client from the root url. From what I understand, `WHITENOISE_ROOT` should override the `STATIC_URL` setting specifically for `/client/dist` in this case.

**Comment by Pomax** [comment]
this almost worked, but we needed whitenoise 4 (currently 4.0b2) to be able to rely on automatic index.html resolution for dirs. Not sure why the author of white noise didn't add it way back when, but it get added 21 days ago, and it solves a lot of problems!

**Comment by arush0311** [comment]
just a thought, but why dont we put it on s3 like uploads? wouldnt work in development though.. there is also this if we want https://github.com/matannoam/pypugjs

**Comment by alanmoo** [comment]
@arush0311 The static pages are currently on S3, we're trying to move everything to django so it can be our one server for all the pages to reduce complexity and enable us to move towards a purely CMS driven site. This is part of the work related to #583

**Comment by arush0311** [comment]
No I am saying use s3 as we use with media.. this would replace whitenoise

**Comment by gvn** [comment]
@Pomax and I worked this out this morning.

Here's how we got it to work: https://github.com/mozilla/network-api/commit/aca1eefb0ce2e5e3a6278e29002c1ac61487ab50
