### ISSUE TITLE
Hero link only visible on hover

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#596]
Homepage Hero contains a link on "healthy internet" in secondary text, but link is only visible on hover. While maybe not a technical bug, it's important to fix. 

<img width="958" alt="screen shot 2017-07-24 at 3 50 24 pm" src="https://user-images.githubusercontent.com/53411/28541666-d7450f48-7087-11e7-914b-0797e2d2cdb3.png">

@sabrinang @taisdesouzalessa what was the design spec?

**Comment by sabrinang** [comment]
We can include a blue underline to indicate that it is a link. 
<img width="1273" alt="image" src="https://user-images.githubusercontent.com/2492510/28592808-fe4969f6-713e-11e7-99e4-ef7fa105ab63.png">

On hover, it can look like our other hover links in navy blue (#4383bf).
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/2492510/28593069-ff8e66c6-713f-11e7-8075-3bc16d768a9e.png">

**Comment by xmatthewx** [comment]
R+ 💥
