### ISSUE TITLE
Replace email signup copy

### ISSUE THREAD

**Issue by jessevondoom** [mozilla/network#597]
We need to change the copy that accompanies the email sign-up form on the Network site. There are variations of it on the following pages:
https://network.mofoprod.net/
https://network.mofoprod.net/sign-up/
https://network.mofoprod.net/opportunity/fellowships/

New copy:

TITLE: Connect to the movement
COPY: Mozilla will periodically update you about important people, projects and opportunities in our Network, so you can connect yourself to the Movement for Internet health.

**Comment by alanmoo** [comment]
This is all stored in django: https://network.mofoprod.net/admin/landingpage/signup/
Each of those instances of the signup component may be used by different pages - it's what the `Signup` field of the `Page` model uses. So we can create a new Signup widget and point all of the pages at that.

This does open a question though- will pages ever have different signup CTAs? Or will they only change if they're signing up for a different mailing list?

**Comment by jessevondoom** [comment]
It's probably all one unified CTA until 2018 at the earliest. Until we shift from explicit lists to Salesforce "interests" we'll just put everyone into the new Network list. After we make that change we'd add different interests and different CTAs and different interests. 

...but that's a little ways off.

**Comment by jessevondoom** [comment]
Okay. Changed the copy in django. Only issue is that "Connect to the movement" is a significantly longer string than "Get connected" so I just kept it there — the copy is enough to give context to the movement and what they're connecting to.

**Comment by alanmoo** [comment]
In that case, should we take away general permissions that allow creating new Signup Widgets, and remove the existing ones from the database? That way new pages can only use the default widget or not use one at all.

**Comment by xmatthewx** [comment]
I don't think we need to disable that feature. It's not super obvious and isn't likely to be used by others outside of this circle. Let's wait and see if we need or others misuse it.
