### ISSUE TITLE
Gather quotes to activate the info

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#6]
The site will be fairly lean in terms of text content, but where we do have it, we can make it better with a nice quote. 

Useful quotes might include: 
 - importance of internet health
 - awesomeness of the network
 - role of network in internet health
 - urgency of privacy and security
 - awesomeness of our events
 - transformative-ness of our fellowships, grants, & trainings
 - impact of our campaigns
 - innovation of our member projects
 - energy in member collaborations

cc @KevZawacki @prefontaine @sabrinang

**Comment by prefontaine** [comment]
This slipped through cracks. On it!

**Comment by OpenMatt** [comment]
@ldecoursy started a spreadsheet for this content here: https://docs.google.com/spreadsheets/d/1rwNFjojmnOHkctAIAin9Pd_rxziscGJBSWi-z2S6Bg4/edit#gid=866621792

We can migrate from our slide deck into that spreadsheet when we're ready.

**Comment by prefontaine** [comment]
Too funny. I had also just started a spreadsheet:  
https://docs.google.com/spreadsheets/d/1qqeQuepHt2JWHEpLdAmcS66afHYCG9TFSnmHiFrym_8

I'll go take a look and use that one instead. I had not gotten very far in terms of content. Just set up the data structure to make it easy to export later.

**Comment by OpenMatt** [comment]
Still waiting to get the template finalized from Matthew.

**Comment by OpenMatt** [comment]
Let's use this as the single source of spreadsheet truth:
https://docs.google.com/spreadsheets/d/1rwNFjojmnOHkctAIAin9Pd_rxziscGJBSWi-z2S6Bg4/edit#gid=866621792

@prefontaine is all your data from the other spreadsheet ported over?

**Comment by OpenMatt** [comment]
This is the correct spreadsheet to use: https://docs.google.com/spreadsheets/d/1rwNFjojmnOHkctAIAin9Pd_rxziscGJBSWi-z2S6Bg4/edit#gid=866621792

**Comment by xmatthewx** [comment]
I think we can close this. And track the info #5.

**Comment by OpenMatt** [comment]
great!
