### ISSUE TITLE
Update Opportunity templates to support subtree navigation, if present

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network#619]
To close this ticket, multipage navigation should be implemented to the point of [Phase 1](https://redpen.io/wh681ba02d54215838).

Any page that's a child of "Opportunities" which has its own children (and those children pages themselves) should show the side navigation.

Note that the first item in the nav list is the parent, but it's styled to be identical to the children pages.

Also, pages that have the signup component will look a little strange due to the 2 columns next to the navigation, the guidance for now is simply "don't do that" so that these mini-site pages are single column + nav.

**Comment by gvn** [comment]
@arush0311 (or maybe @alanmoo ) – What are the `page` object properties to access the subpages in the opportunity template?

I'm assuming its something along the lines of `page.landingpage.SOMETHING`?

**Comment by arush0311** [comment]
@gvn I think its a `page_branch` variable. http://mezzanine.jupo.org/docs/content-architecture.html#page-menus

**Comment by gvn** [comment]
@taisdesouzalessa Can you point me to the Sketch file for this?

**Comment by taisdesouzalessa** [comment]
Hey @gvn I had a prototype for the latest version but it is broken now (my guess is that the css was updated and I have to relink now)
Here is the prototype - please see it at 320 [mobile] and 1280 [desktop]
https://taisslessa.github.io/simple-model-ui-v4/index.html

I could either:  fix the now broken prototype (it is the most accurate representation of the final state) or make updates to the Sketch file (some little changes happened that were only reflected in the prototype). Which one is more useful to you? I could do any of those by end of the day tomorrow if it works for you.

**Comment by gvn** [comment]
It's definitely most useful for me to have a Sketch file. 👍

**Comment by taisdesouzalessa** [comment]
@gvn here is the link to the Sketch file: https://drive.google.com/a/mozilla.com/file/d/0B3b1KWRwjxtoa093cVU5REhxdlU/view?usp=sharing

Prototype updated (you can also see it in mobile view - >376 - to check mobile behavior): https://taisslessa.github.io/simple-model-ui-v4/index.html

**Comment by gvn** [comment]
I'm trying to figure out if there's a boolean I can access outside of the `page_menu` function that will indicate whether or not a page has children or not. I need this to adjust the template layout and hide the side navigation for standalone pages.

Any ideas @arush0311 @alanmoo ?

**Comment by alanmoo** [comment]
`page.has_children` in a template tag should do it, no?
http://mezzanine.jupo.org/docs/content-architecture.html#menu-variables

**Comment by gvn** [comment]
That only works in the scope of the `page_menu` function itself. I need to access it outside of `page_menu`, which is the problem.

**Comment by gvn** [comment]
@Pomax do you know if there's a boolean (or some other indicator) that a page has a child in this template? `source/pug/views/opportunity.pug`

Is the `page` object a custom object, or does it have a documented API?
