### ISSUE TITLE
Decouple people on homepage from people page in CMS

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#625]
Currently, Editor orders the people featured on homepage by changing the order of people on the people page.
 - Editor might want different order, and more importantly...
 - The nature of big and small profiles on people page limits ordering, and essentially blocks Editor from freely featuring people on the homepage.

**Comment by alanmoo** [comment]
This feels like the work being described by the epic as a whole, and not a specific task. I'd suggest we close it, sound good?
