### ISSUE TITLE
Replace "Mozfest call for proposals" on homepage

### ISSUE THREAD

**Issue by hannahkane** [mozilla/network#629]
The call for proposals is over. What should we put in that spot—Mozfest tickets? 

cc @Sydette @jessevondoom

**Comment by xmatthewx** [comment]
We can fallback to the Open Leadership training while we search for and prep new content.

**Comment by jessevondoom** [comment]
Agreed. think that's the right call for now.

**Comment by hannahkane** [comment]
@alanmoo @gvn - is the Open Leadership Training homepage blurb still available somewhere, or do we need to rewrite it?

@xmatthewx @jessevondoom - I'm going to change the signup form on the Leadership Training page to be the default, as per earlier decision.

**Comment by alanmoo** [comment]
Was the blurb something that was hard-coded on a page at some point? If so we can pull it out of the commit history if need be.

**Comment by hannahkane** [comment]
@alanmoo - yeah, I think so. Because it wasn't CMS-ified.

**Comment by alanmoo** [comment]
https://github.com/mozilla/network/blob/8f4635a521d28b1c71241a73fe2fdeae5f49b122/source/json/highlights.json ?

**Comment by hannahkane** [comment]
Hmm...I don't see the Open Leadership Training in the history. Maybe we never had it?

I can pull together content from previously closed tickets. @alanmoo - should I file a PR for this myself? It's not editable via CMS yet, right?

**Comment by alanmoo** [comment]
https://network.mozilla.org/admin/highlights/highlight/

**Comment by hannahkane** [comment]
Oh, awesome. Thanks, @alanmoo.

@Sydette - would you be up for adding a new Highlight about the [Leadership Training](https://network.mozilla.org/opportunity/training/) using the link Alan posted in the comment above? The items will need to be re-ordered so that the Mozfest one is last and "falls off" the homepage.

Let me know if that doesn't make sense.

**Comment by xmatthewx** [comment]
Draft content from comp. Maybe useful?

<img width="516" alt="screen shot 2017-08-03 at 4 03 43 pm" src="https://user-images.githubusercontent.com/53411/28941244-6c0b6430-7865-11e7-8e05-ad39e1c1c02e.png">

**Comment by xmatthewx** [comment]
We should huddle up early next week to do this.

**Comment by hannahkane** [comment]
as per discussion with @Sydette in Slack, I'm going to make the Open Leadership training the featured highlight on the "Get Involved" section of the homepage. 

cc @acabunoc ^

**Comment by acabunoc** [comment]
yes please, thank you! Let me know if you need anything from the open leadership team

Also, I'd still love to see Mark's video somewhere on the site: https://www.youtube.com/watch?v=quKdaqlR_9w

**Comment by xmatthewx** [comment]
Started talk about video limitations in #191. I'll give it a bump.

**Comment by hannahkane** [comment]
Closing.
