### ISSUE TITLE
Path bug in package.json

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network#63]
Just discovered this bug in the [NSF site repo](https://github.com/mozilla/nsf-challenge/pull/18).

We should use recursive directory tree traversal for tasks like build, watch, and test.

**Comment by hannahkane** [comment]
@mmmavis - how urgent is this? Wondering if I can put it in a post-softlaunch milestone?

**Comment by mmmavis** [comment]
Seems like this has already been taken care of. 👏
