### ISSUE TITLE
Draft persona in a doc

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#632]
This ticked is a place to add the drafts. 
The plan is to have 1 here, gather feedback and use the revisions to inform the next drafts.

**Comment by taisdesouzalessa** [comment]
Team, here is the first draft of the first persona...yay! In the top of the doc, I added some quick notes based on research about best practices on personas. It would be nice to use those as lenses for the feedback round.

Please feel free to edit this persona if you feel there are opportunities to be clearer or more compelling. Just please keep in mind to not create new facts that are not represented in the board. 

If you think something important is missing and you want to place new facts, just change the color/style of those new facts so it is clear that it is an assumption that we should test once we use this persona. Assumptions are okay as long as we know where they are so we can test them.

https://docs.google.com/a/mozilla.com/document/d/1s4QODpZTrQEO4Xe93GXPNh3WGOFx1XwywkIpo3hepn8/edit?usp=sharing

Thanks to @flukeout and @kristinashu, which benchmarks and insights helped to inform this first draft. Please edit/add comments if you think something is missing.

@sabrinang @jessevondoom @hannahkane @xmatthewx @prefontaine @paulfzenke

**Comment by xmatthewx** [comment]
This is so excellent on many levels @taisdesouzalessa! Having this draft will make it much easier to figure out the full system.  

I think you've done a great job of grounding this in a realistic individual while keeping it abstract enough to describe a broad group. Maybe obvious, but definitely not easy.

One suggestion: On the Gains and Pains, I think it's important to focus on things in their experience _outside_ of Mozilla and the Network. You've done this very well with the Gains, identify things they get from the Network for their work life. While we should address the Pains that come _within_ Mozilla, the Network itself should address Pains for people at home/work/play. So in this case: Her peers resist her efforts to share data, making it harder to collaborate with others, slowing down her work. I almost feel like the challenges and opportunities for joining and participation could be a separate section. Maybe a few bullets under Engagement?

**Comment by taisdesouzalessa** [comment]
Based on the latest feedback from @xmatthewx @prefontaine @jessevondoom and @kristinashu and also after thinking and regrouping the information, here are the drafts of the first 2 leaders personas:

https://docs.google.com/a/mozilla.com/document/d/1s4QODpZTrQEO4Xe93GXPNh3WGOFx1XwywkIpo3hepn8/edit?usp=sharing

I am using now "I" statements because I feel it is easier to empathize with a story in the first person. I read a [very nice article](https://medium.com/@indiyoung/describing-personas-af992e3fc527) from Indi Young that encouraged this approach.  Also, inspired by that I opted for using gender neutral names and omitting location and age for personas because I don't feel it is essential for our design needs. Open to debate, always :).

As I mentioned, I merged The Wonk + The Influencer. Also The Professional + The Uber Teacher. The reason being was that I couldn't find strong enough differentiation in the data we currently have to justify the division in terms of their motivations (represented by "Key beliefs & motivators"). We can talk further about that if there are any disagreements. 

Please let me know what you think. I am currently working on the 3rd persona (Leaders) and I'll post it here tomorrow. 

Next step: add the information to posters. I can use the doc above as placeholder and we can evolve the copy and groups as the discussion evolves. It would be nice to have something visual soon even though that means it will change in terms of information.

**Comment by taisdesouzalessa** [comment]
This thread is getting too long. After the things we discussed here and my talk with Matthew there were revisions so I am starting a new clean ticket with the latest revisions :). Closing this.
