### ISSUE TITLE
Define draft persona groups

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#635]
**Goal** 
 - draft persona groups
 - identify if there are some missing audience types not covered by Enchilada Doc. 

**Description**
We did a brainstorm in Google docs and it resulted in the [Strawperson list of Persona Groups](https://docs.google.com/a/mozilla.com/document/d/1rJJOC_qvFulL9sFlhs02MXRSpCQRoAGaXg6PISvFA60/edit?usp=sharing)
 
**Next steps**
Refine this doc and validate info based on user research (starting from what we have in StoryEngine)

**Comment by xmatthewx** [comment]
I think we can call this done. Groups might change as we learn more, but a draft is done. 

@taisdesouzalessa - let's remember to follow up with the people I asked for feedback. I requested input by next Wednesday.
