### ISSUE TITLE
Console errors in Chrome

### ISSUE THREAD

**Issue by gvn** [mozilla/network#636]
I'm seeing a couple of console errors in Chrome:

`Failed to set referrer policy: The value 'same-origin' is not one of 'no-referrer', 'no-referrer-when-downgrade', 'origin', 'origin-when-cross-origin', or 'unsafe-url'. The referrer policy has been left unchanged.`

`Error parsing header X-XSS-Protection: 1, mode=block: expected semicolon at character position 2. The default protections will be applied.`

I think this is because of some of the newly added HTTP response headers. @cadecairos any thoughts?

**Comment by cadecairos** [comment]
Chrime doesn't support the same-origin directive for referrer-policy,  but they're [working on it](https://bugs.chromium.org/p/chromium/issues/detail?id=627968)

The X-XSS-Protection header appears to have a typo.  I'll look at that tomorrow

**Comment by cadecairos** [comment]
This doesn't appear to be a problem anymore.
