### ISSUE TITLE
Audit and brainstorm ideas on how to align sites

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network#640]
From https://github.com/mozilla/network/issues/582

Audit and brainstorm ideas on how to align Network site, Pulse, Health report. Looking at streamlining UX + UI elements and linking sites together.

**Comment by kristinashu** [comment]
Added content in this slide deck https://docs.google.com/a/mozilla.com/presentation/d/1R1r4RCfoxKYAPVZerAPItJk1JZuALrc5jWm0t1QMijU/edit?usp=sharing

**Comment by kristinashu** [comment]
cc @xmatthewx

**Comment by xmatthewx** [comment]
Good progress. Will continue in next sprint.

**Comment by kristinashu** [comment]
Pressing pause on this and will continue the work week of Sept 4.

**Comment by kristinashu** [comment]
Initial brainstorming and audit is done. I will close this and open up new tickets after our kickoff https://github.com/mozilla/network/issues/751
