### ISSUE TITLE
refine the user groups

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network#646]
@Pomax commented on [Mon Jul 24 2017](https://github.com/mozilla/network-api/issues/259)

right now we have admin and staff, and a defunct pulse-related group. We should probably extend that a bit into
- staff (no special permissions?)
- admin (all perms)
- editor (editing rights on all objects)
  - [xyz] editor (editing rights on specific objects)

---

@arush0311 commented on [Fri Jul 28 2017](https://github.com/mozilla/network-api/issues/259#issuecomment-318711291)

Do we have to create a migration or do that manually?

**Comment by xmatthewx** [comment]
**Author** (MVP)
 - can create & publish "content" such as Pages
 - cannot edit "content" by other Authors
 - can create "data" such as People
 - cannot publish or feature "data"

**Moderator** (Nice to have)
 - all Author permissions
 - can publish or feature "data"
 - nice to have
   - can unpublish "content" or "data" by other Authors
   - cannot edit "content" or "data" by other Authors

**Editor** (MVP) 
 - all Moderator permissions
 - full publish and edit privileges on all content types, including content by other Authors

**Admin**
 - all Editor privileges
 - full user management

**Staff** (Nice to have)
 - Good to know who is staff
 - No special privileges

**Comment by alanmoo** [comment]
I think these might be overly specific based on what Mezzanine gives us out of the box- most things break down into "Can add, can edit, can delete". And unfortunately, "can add" doesn't mean they can edit the page they just added unless they can edit everything in a category.

**Comment by xmatthewx** [comment]
I wonder if Django's "create" privilege assumes "edit own content", for users who don't have "edit" privilege. 

Either way, I guess for now we can create an Authors group who can only create "content" (Pages), not "data" used elsewhere on the site.

**Comment by alanmoo** [comment]
Implemented permissions on production
