### ISSUE TITLE
Define process for choosing featured people, projects, etc

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#65]
- People profiles will come from fellowships, advisory group, recognized members. From this pool, who curates the list of people featured?
 - Projects will be posted by program staff, fellows, etc, to Pulse. From this pool, who curates the Featured items on the site? How do staff nominate items?
 - News is posted to Medium. Featured content is curated by Kevin. 
 - Campaigns are managed by Advocacy team. Paul can curate content from the team and the network to feature on the site. 

cc @ldecoursy

**Comment by hannahkane** [comment]
@xmatthewx - I added what I could to the deck.

**Comment by hannahkane** [comment]
duped by #53
