### ISSUE TITLE
Add logging for templating errors

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network#652]
@Pomax commented on [Mon Jul 17 2017](https://github.com/mozilla/network-api/issues/246)

We've been bitten by template errors silently breaking things when `DEBUG=False`, we need to find a way to enable logging of template errors so that when things break, they at least do not break silently.

---

@arush0311 commented on [Mon Jul 31 2017](https://github.com/mozilla/network-api/issues/246#issuecomment-319152523)

Can i take this?

**Comment by Pomax** [comment]
are we still planning to do something with this issue or should we close it until we run into it again?

**Comment by alanmoo** [comment]
Staging should have `DEBUG=False` so we know things break when they get to staging, not between staging and prod. Other than that, I'd say let's close this until we run into it again going from local to staging.
