### ISSUE TITLE
Create Homepage admin

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network#659]
Something like this:
<img width="897" alt="screen shot 2017-07-19 at 2 45 55 pm" src="https://user-images.githubusercontent.com/53411/28386004-328e46e2-6c98-11e7-9576-034350452880.png">

**Comment by xmatthewx** [comment]
We might add ability for user to sort drop down by alphabetical, default to reverse chronological.

If can't label first item different, we'll help help text to container.

**Comment by xmatthewx** [comment]
@gideonthomas – just a quick note to say that the mockup above was a quick comp that seemed like the easiest thing to land using django/mezzanine patterns. Feel free to adjust for MVP. In the future, we'll want to improve the interface, but for now we're just focused on landing basic functionality. Make sense?

**Comment by gideonthomas** [comment]
@xmatthewx sounds good. It should be fairly straightforward to develop in a way that is extensible so I'll do that

**Comment by xmatthewx** [comment]
@gideonthomas here's what I see. @alanmoo was playing with my permissions so we could test user stuff, so that might be the reason.  

![image](https://user-images.githubusercontent.com/53411/30226006-7d6e2cd6-94a2-11e7-89f9-41541abb57c7.png)

 - is there a way to make this a single thing and remove "save and add another"

**Comment by alanmoo** [comment]
Hmm, I see that too. We're both superuser on staging, so it's not a permissions thing.

**Comment by gideonthomas** [comment]
ugh, I think it's csp. will remove the save and add another link.

**Comment by gideonthomas** [comment]
@xmatthewx should be fixed now.

**Comment by xmatthewx** [comment]
We reviewed. Agreed this was good to merge to production. 
 - @alanmoo - please only allow top users to access this
 - @gvn - try and break it as you work on frontend

**Comment by hannahkane** [comment]
Might be useful to better align the language used - e.g. where it says "Network Leaders" maybe it could say in parentheses ("People") to match the module name in the CMS.
