### ISSUE TITLE
Gather content dependent visuals for network upcoming, offerings and media

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#67]
The new site will have a few places where we need an image to support info about a specific program. An example is the [Upcoming](https://invis.io/ZJ9YTAGEA#/216715367_Upcoming) page.

Staff – if you've been asked to find an image. Please provide a few options. Images need to be large, not tiny. Feel free to link or upload. Photo or illustration is fine. We can use a big bold logo on background for things like Glassroom and SRCCON. 

### Upcoming
https://docs.google.com/document/d/1MDfeLsJimZm6glqOQENv-aOe_XOTgT-j0H-NJo39FXs/edit#bookmark=id.fgy6dwlfaki9

 - [ ] Education Innovation Showcase
 - [x] Digital Skills Observatory (DSO) research published 
 - [x] MozFest call for proposals
 - [x] SRCCON
 - [x] Open Web Fellows announced
 - [x] Internet Health Report
 - [x] MozFest
 - [x] Open Web Fellows applications open
 - [x] Gigabit grant applications open
 - [x] Gigabit grants announced 
 - [x] The Glass Room 2.0

### Homepage 3 Offers?
Refer to green highlights? https://docs.google.com/spreadsheets/d/1UsnRgCYYLsQJvicJGKHgn3TU7dfwZ3icn9PaAzxtrmg/edit#gid=2090555237
- [ ] Internet Health Report
- [ ] OWF 2016>2017
- [ ] Encryption Campaign
- [ ] Glass Room 1.0
- [ ] Open Leadership Training

### Earned Media Icons (b/w vectors) #36 
Refer to the yellow highlights: https://docs.google.com/spreadsheets/d/1UsnRgCYYLsQJvicJGKHgn3TU7dfwZ3icn9PaAzxtrmg/edit#gid=2020397576

- [x] Medium
- [x] CNBC
- [x] The New Statesman
- [x] MIT Technology Review
- [x] New York Times
- [x] ~~Fast Company~~ FastCo Design
- [x] NPR
- [x] El Pais
- [x] Consumer Reports
- [x] CNET
- [x] EU Observer
- [x] The Register
- [x] Mashable
- [x] Engadget
- [x] WIRED Germany
- [x] Times of India
- [x] ~~Austin-American Statesman~~ 512 Tech
- [x] Lifehacker
- [x] NPR
- [x] CBC
- [x] CNN
- [ ] Default icon when icon is not available

### No Image / Empty State?
If we don't have an image available for the content we can try to find a stock image if not:
- [ ] colour block with pattern system

### People Page #33 
Refer to spreadsheet of approved people with partners: https://docs.google.com/spreadsheets/d/1rwNFjojmnOHkctAIAin9Pd_rxziscGJBSWi-z2S6Bg4/edit#gid=866621792
- [x] export partner logo svg
- [x] people photos

**Comment by xmatthewx** [comment]
whoops. duplicate of #66. feel free to close this ... and I still encourage us to flag program people to gather options. i'm glad to help identify people.

**Comment by xmatthewx** [comment]
feel free to rename and edit list @sabrinang

**Comment by sabrinang** [comment]
Are all the highlighted pieces signed off so we can collect the content dependent visuals?

**Comment by sabrinang** [comment]
earned media icons exported in folder: https://drive.google.com/drive/folders/0B4Q8pzCpDS_eSk4xYV80MTZxNk0?usp=sharing

**Comment by sabrinang** [comment]
Preview of collected visuals so far which consists of a mixture of photgraphy from us, stock photography, illustrations and logos: <img width="596" alt="screen shot 2017-02-22 at 10 58 55 am" src="https://cloud.githubusercontent.com/assets/2492510/23227493/fb2826be-f8ed-11e6-8f67-e23e67602b85.png">

Our site mainly uses two formats 1:1 (squared) 3:4 (rectangle) depending on context and screen size. I am currently testing photoshop actions for sizes and adjusting photography tone so we can export in batches.

**Comment by sabrinang** [comment]
![upcoming](https://cloud.githubusercontent.com/assets/2492510/23314009/dcbf8d2e-fa74-11e6-8020-5e8341432997.jpg)
@xmatthewx  Photo review? and do you know who I can ask or where I can find photos from the [Education Innovation Showcase](https://www.eventbrite.com/e/education-innovation-showcase-tickets-30495213003#)?

**Comment by xmatthewx** [comment]
Most look great! You can talk to Robert for Hive Austin. Talk to Lindsey for Gigabit an image that screams next-generation internet would be great. You can ask Vanessa for something better than the headless people on Fellowships. @sabrinang

**Comment by sabrinang** [comment]
I reached out to programs people via email separately and waiting for responses

**Comment by sabrinang** [comment]
People photos are gathered from the [spreadsheet](https://docs.google.com/spreadsheets/d/1rwNFjojmnOHkctAIAin9Pd_rxziscGJBSWi-z2S6Bg4/edit#gid=866621792) and exported 900x900 optimized .jpegs here: https://drive.google.com/drive/folders/0B4Q8pzCpDS_eUzFlYnZ0TGpOUG8?usp=sharing

<img width="1184" alt="screen shot 2017-03-03 at 1 30 53 pm" src="https://cloud.githubusercontent.com/assets/2492510/23569725/b47dc0d2-0015-11e7-92c1-7bd674c29658.png">

**Comment by sabrinang** [comment]
Upcoming photos are updated with 2 fellows photos (from Vanessa/Aurelia), a gigabit photo (from Jenn/Lindsey), I used edTech austin for the education innovation showcase (since I have not heard back from Robert).
![upcoming-update](https://cloud.githubusercontent.com/assets/2492510/23571709/8e960fbe-001f-11e7-9f96-7b051eebb917.jpg)

Upcoming photos exported 1200x900 optimized .jpegs on gdrive here: https://drive.google.com/drive/folders/0B4Q8pzCpDS_eb2lkMVNMX1Zxa3c

**Comment by sabrinang** [comment]
news media .svg icons are exported to gdrive in this folder: https://drive.google.com/drive/folders/0B4Q8pzCpDS_eSk4xYV80MTZxNk0

<img width="950" alt="screen shot 2017-03-07 at 4 31 34 pm" src="https://cloud.githubusercontent.com/assets/2492510/23684423/9333abf8-0353-11e7-95f5-036a01ea9276.png">
