### ISSUE TITLE
Limit Highlights that show on homepage to first 3

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network#673]
It looks like the "Get Involved" section on the homepage will show everything that the API returns. We should either update the API to return 3 by default, support a `count` param and update the front-end to use that, or make the template only display the first 3.

@pomax @gvn thoughts? Maybe @arush0311 could implement?

**Comment by xmatthewx** [comment]
@alanmoo - can you verify and close this if good to go?

**Comment by hannahkane** [comment]
I still see the fourth item on the homepage.

**Comment by gvn** [comment]
On staging or prod?

**Comment by hannahkane** [comment]
Staging. Sorry, I'm an idiot. :)

**Comment by alanmoo** [comment]
I still see the fourth item on production, not staging.

**Comment by hannahkane** [comment]
Dammit. Sorry, yes, I also see the fourth item on production (despite my earlier comment). So I'm assuming this just hasn't been pushed to prod yet? If so, please disregard.

**Comment by gvn** [comment]
Yeah, I've been treating this column as verifying on staging before pushing to prod. We may want to consider another verification on prod column prior to close, but I don't know if that might be excessive...

**Comment by hannahkane** [comment]
Yeah, sorry, that's my understanding of that column, too. I just temporarily forgot, and made things super confusing.

I do feel like a final verification step is valuable, though it doesn't necessarily need to be reflected on the board. It could/should be part of the Review.
