### ISSUE TITLE
Add CSP Header in Django

### ISSUE THREAD

**Issue by cadecairos** [mozilla/network#679]
Unity has removed the need for CloudFront, and so we don't need to use Lambda@edge to add security headers.

We should add these in using a python module in the Django project.

**Comment by cadecairos** [comment]
possibly: https://github.com/mozilla/django-csp

**Comment by Pomax** [comment]
Reading through http://django-csp.readthedocs.io/en/latest/configuration.html this looks like we should be able to use this.
