### ISSUE TITLE
Fix broken healthcheck

### ISSUE THREAD

**Issue by gvn** [mozilla/network#683]
Healthcheck "Change Sets" and "Latest Deployed Commit" are broken now because Unity isn't deployed with Jenkins anymore.

**Comment by alanmoo** [comment]
This probably doesn't need to be very complicated anymore, right? Just a comparison of 2 branches of something?

**Comment by gvn** [comment]
I think it's about the same level of complexity. We just need the commit hashes brought in from Heroku instead of Jenkins.

Essentially this XHR request needs to be refactored:

https://github.com/mozilla/network/blob/master/scripts/build-healthcheck.js#L64
