### ISSUE TITLE
Pull in latest changes from network-api

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network#686]
It looks like the network-api repo was not merged in from its latest commit point. There are a few commits that aren't reflected in the code of this repo (I'm looking at the actual lines of code in various files, not the commits- I know those won't show up in history).

Looks like https://github.com/mozilla/network-api/commit/795b6ed08b7e3398798d7ceb7e5317dc4b9bb0e9 and forward weren't moved over

**Comment by cadecairos** [comment]
This was completed in #694
