### ISSUE TITLE
Opportunity page - 1 column template

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#690]
**Description** 
We have been seeing some cases in which staff needs to insert a big amount of content in 1-page opportunity pages. Example: https://network.mozilla.org/opportunity/network-50/

That makes the left column very long which causes a hard user experience for readers of the page. 

I was wondering if there is any way we could have a 1-column template that integrates the email box to the body of the content. That would also require a narrower column for the copy.

<img width="674" alt="image" src="https://user-images.githubusercontent.com/22157921/29643934-3e5ed496-8827-11e7-9746-bb74b2ac3b72.png">

This page would be needed in this specific scenario:
the author needs the email box and the multi-page template with sidebar (the one that is in progress) doesn't attend their needs because their content fits on one page. 

**Question** 
I am not sure if you think this is a valuable item to spend time on (do we see this scenario happening frequently?) and I am not sure about the complexity of building a new template so I am throwing this ticket here for thoughts. I think Sabrina had a nice 1 column template designed (better than the one that I quickly mocked up here)

@hannahkane @xmatthewx @alanmoo @sabrinang

**Comment by hannahkane** [comment]
This feels important to me. I think we already have a couple examples where it would be nice - Network50, but also MITI, and pages where we've made a single column might benefit from having the sign-up widget (e.g. The Tech Policy Fellows page).

**Comment by alanmoo** [comment]
This makes sense to me. Would the widget always be at the bottom like on this comp?

**Comment by xmatthewx** [comment]
👍 on this. In the very early days, we wanted to keep the join box from falling too low on the page, because we thought this would be a critical pathway to build membership. Times have changed. 

I think we can move to display this as a footer in many-to-most scenarios. Crazy idea: what if we default to footer, but given author option for sidebar display? Too much complexity to maintain?

**Comment by taisdesouzalessa** [comment]
I was wondering if we could give editors the flexibility of adding this box at any point they want in the text (kind of a widget in wordpress) and choose the desired location. The image below is an illustration of the idea, not that I feel that it should be exactly like that.

<img width="619" alt="image" src="https://user-images.githubusercontent.com/22157921/29835640-7979eea6-8ca7-11e7-9a54-1e0fbc33e9f0.png">

I think it would be nice to give that flexibility to editors as I can see the needs seem to be varying a lot, depending on the content. I feel the content should shape the page and not the opposite.

I don't know about how much it would cost us in terms of time for such flexibility, so I would be happy to hear the engineers thoughts.

However, if we think that in the majority of scenarios the users will want to have this is the bottom of the page, I think it is ok if we make this default, as @xmatthewx suggested. I don't know what is coming up in terms of this type of page and its uses.

**Comment by xmatthewx** [comment]
We won't be able to create full widget flexibility right now. Let's default to the bottom. If we can also retain the sidebar as a checkbox option without too much tech overhead, awesome.

**Comment by taisdesouzalessa** [comment]
Sure, I am cool with that!

**Comment by alanmoo** [comment]
Unfortunately I don't think we can easily implement something quite like that @taisdesouzalessa. Mezzanine is based more around a quantity of fixed templates than free-form layout. We'd be better off creating a second template that has that layout if the element is desired.

**Comment by taisdesouzalessa** [comment]
As discussed in the stand-up today, while I work on this ticket I should also work on #540 since they are related to the same set of pages.

Matthew's suggestion: maybe have a blurb of copy in the footer explaining that this project is part of a bigger thing: the Network and add an invitation for people to explore the site. Could be a footer or on the top of the page. - @xmatthewx let me know if accurately represented your thoughts here. Feel free to edit them.

**Comment by xmatthewx** [comment]
Looks good. I think we can open an engineering ticket to move the form now. True? Or is there more to figure out with that?

**Comment by taisdesouzalessa** [comment]
In my understanding, I thought the next step was to think about a mockup to accommodate this form in the bottom + a solution to invited people to explore the network more (another box, a blurb of copy...). Those 2 pieces could be done in separate stages as well if you think it it better.

**Comment by xmatthewx** [comment]
I guess that I see moving the form down as a quick and easy fix to something that feels a bit broken. 

Thinking about a blurb is going to take a bit of design exploration, an enhancement that's a little less urgent.  Does it sit on top of the footer? Do we always show it or only when the form is not shown? 

Feel free to push back though if you see this differently.

**Comment by taisdesouzalessa** [comment]
Yep, I agree with you that moving the form down is an easy fix. 

The blurb or whatever other solution we choose would take a bit of design thinking. If you think it is less urgent, let's just move the form down for now. Is that what you meant? If we are just moving the form, I guess we don't need a mockup for it, unless the Engineers would like one.

**Comment by xmatthewx** [comment]
Filed a new implementation ticket #754
