### ISSUE TITLE
Allow sign-up widgets to pull from any newsletter

### ISSUE THREAD

**Issue by hannahkane** [mozilla/network#691]
We have one use case where we want to add a sign-up widget to a page, but the the user should not be signing up for the main Mozilla Network newsletter. Instead it's a TBD newsletter that's being created.

This ticket is for the technical work of allowing CMS admins to specify a particular newsletter per sign-up widget.

Pending product conversation with @xmatthewx

**Comment by hannahkane** [comment]
Grooming notes: 
 - Add field to sign-up widget model for path for newsletter name
 - Limit the admins who can create a new sign-up form (we have an interest in keeping each newsletter-specific sign-up form consistent)
 - Don't need to validate that newsletter isn't used twice; will just trust people to follow the rules

**Comment by hannahkane** [comment]
Just noting a UX challenge this opens up - every page has the "SIGN UP" button in the header that lets users sign up for the Mozilla Network newsletter. This is potentially quite confusing on pages with a different newsletter sign-up widget.

**Comment by xmatthewx** [comment]
I'd like to pause this, push back on the need to service unique snowflakes while we're still trying to get the core services running optimally.

**Comment by hannahkane** [comment]
@xmatthewx - OK. How do you want to address the immediate need for MITI?

**Comment by xmatthewx** [comment]
I added this to our agenda to discuss with Jesse. We can loop back here after.

**Comment by alanmoo** [comment]
Did we come to a decision on this last week?

**Comment by xmatthewx** [comment]
I believe we said we'd allow this lone exception, with the expectation that this will become part of the main list in the future, distinguished as an interest. It can be engineered with that in mind.

**Comment by xmatthewx** [comment]
@alanmoo - who can confirm this? should we hit up Steph?

**Comment by alanmoo** [comment]
In my time off this managed to get onto production, but it's working as expected.
