### ISSUE TITLE
Identify key 2017 moments

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#7]
The site will include a list of the biggest moments planned for 2017. The list should be limited to 6 items, ten max.

Goal: Each item should be show off what makes the network awesome. Exemplify how we uniquely foster change in the world. This is not an events calendar. Not a comprehensive list. Signal, not noise. We can link out to a public g-cal for that if we want. 

Likely on the list: MozFest, global sprint, call for new fellows, next release of internet health report. 

We'll need rough dates (month or season) and a tweet length description, framed on it's role in the network and how it impacts internet health. 

cc @ldecoursy @KevZawacki @sabrinang

**Comment by KevZawacki** [comment]
Also thinking: Maker Party. 

And perhaps Gigabit applications / a select, finite Advocacy campaign.

**Comment by ldecoursy** [comment]
I'd put a (maybe) next to Maker Party for 2017. 

Agree with adding an advocacy campaign, or perhaps Glass Room 2.0 (however not sure on timing yet). 

Perhaps also the Mozilla/NSF Innovation Challenge, or other grantmaking announcement/moment.

**Comment by ldecoursy** [comment]
Thoughts on whether we'd highlight the call for fellows apps, or the announcement of the fellows? Could go either way - former highlights the opportunity, latter tells a story of the partner host orgs, the individuals and the projects they're pursuing.

**Comment by xmatthewx** [comment]
Perfect. All these suggestions feel like the right altitude to me. Worth noting that in addition to this list, key moments will be reinforced by features on the homepage with related calls to action.

**Comment by xmatthewx** [comment]
@ldecoursy if you could help us identify ballpark dates, that'd be great. 

@KevZawacki – if you could draft a description or two for known moments (like MozFest), we could then ask others to follow your lead. In the edit, we'll probably need to edit for uniformity. 

@sabrinang – next week, a draft design might help guide Kevin. I'm thinking simple: 
 - `thumbnail`
 - `title` example: MozFest
 - `subhead` example:  A festival of workshops, talks, and hacking 
 - `one-liner` example:  Mozfest brings together awesome people ... new relationships, new plans, new fuel, ... to blah de blah healthy internet.
 - `Timing` example: More info and call for proposals: Early Summer.

**Comment by KevZawacki** [comment]
@xmatthewx Certainly. Two examples [here](https://docs.google.com/document/d/1MDfeLsJimZm6glqOQENv-aOe_XOTgT-j0H-NJo39FXs/edit#bookmark=id.fgy6dwlfaki9). Let me know how I can help further.

**Comment by ldecoursy** [comment]
Here's what I have so far - I put some asks out for specific dates and will update this comment accordingly. 

* Global Sprint - June 2017
* Call for fellows - Summer 2017
* NSF WINS Innovation Challenge applications due- Spring 2017 (I think)
* Gigabit applications due - July 2017
* Advocacy campaign - _TBD_
* Glass Room 2.0  - _TBD Q2?_

**Comment by xmatthewx** [comment]
Discussion can continue in this thread. Moving items to here for organizing and prioritization: https://docs.google.com/a/mozilla.com/spreadsheets/d/1UsnRgCYYLsQJvicJGKHgn3TU7dfwZ3icn9PaAzxtrmg/edit?usp=sharing

**Comment by xmatthewx** [comment]
Work continues in https://github.com/mozilla/network/issues/57
