### ISSUE TITLE
Identify featured projects for launch

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#70]
Currently, featured items on Pulse are picked by yours truly without much rigor. We should look at items and pick 3 for homepage and 9-18 for the projects page. Using a similar rubric that we hacked together for offerings. 

We should avoid Mozilla things and focus on stuff by the network. I think MozFest talks are an exception to that rule, though I would choose image and copy to emphasize the person.

@KevZawacki – how should we do this? Async. On a call? Anyone else you think should join us on the task?

**Comment by KevZawacki** [comment]
@xmatthewx We can collaborate asynchronously, in a spreadsheet.

I think the most important characteristic is accessibility: Is it clear what the project is and why it exists?

I've highlighted Pulse projects that meet that criteria **[here](https://docs.google.com/a/mozilla.com/spreadsheets/d/1MVOTTxNH4FvyoiBIR--F8HqZYhBvlL2LSKi4XDa1LKo/edit?usp=sharing
)**. Feel free to add / subtract. We can tinker with their eventual arrangement in the second tab. 

@Lottarao and @HPaulJohnson may want to weigh in, too.

**Comment by xmatthewx** [comment]
@KevZawacki – I've [featured](http://mozilla.github.io/network-pulse/) the Zeynep Tufekc talk you posted to Pulse now that we have an image. Looking good. 

I'd like to suggest that we remove the second half of this item title, and do the same for other entries. The Algorithmic Spiral of Silence ~~| Zeynep Tufekci at MozFest~~

I think the descriptions are short enough that we don't need a subhead. If you do think we need subheads, I'd like to design it as a distinct field.

**Comment by KevZawacki** [comment]
@xmatthewx Lookin' fresh!

Agreed that we can do without the subhead.

**Comment by xmatthewx** [comment]
Thanks @KevZawacki. I'll will flag your suggests as featured after we launch new Pulse this week. 😄
