### ISSUE TITLE
Google Analytics not displaying data after July 27th

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#703]
**Issue:** It seems GA is not collecting data after July 27th:
<img width="668" alt="image" src="https://user-images.githubusercontent.com/22157921/29797287-12e251ac-8c0b-11e7-9632-2351bced3be2.png">

Talked to @alanmoo about the issue and he suspects that it may be related to the way the filters are set up, since that’s probably the day we switched domains. His guess is the data is there but we are not being able to see it.

Could you please take a look at this issue for us, @cadecairos?

Thanks!

**Comment by cadecairos** [comment]
I've updated the GA filter for production, it was set to `mofoprod.net`
