### ISSUE TITLE
Opportunity page

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#708]
**Description:**
The layout of the opportunity pages (ex: [https://network.mozilla.org/opportunity/internet-health-report/](https://network.mozilla.org/opportunity/internet-health-report/)) is not as expected in the live page. 

Mainly, everything is pushed to the right and the grey box is narrower than usual.

Here is the screenshot of the mockup for comparison (this is what the page looked like before the change - mockup is outdated but you can see the columns had same width and that the first column would align with Mozilla's logo:

<img width="493" alt="image" src="https://user-images.githubusercontent.com/22157921/29934538-72c044d6-8e30-11e7-9b9d-d85ad3ced357.png">

**Comment by gvn** [comment]
Should be fixed now!
