### ISSUE TITLE
Add page for OWF, Science, Media Fellows

### ISSUE THREAD

**Issue by auremoser** [mozilla/network#715]
Taking a layout model from #482, let me know if I should change the format here.

cc/ @jessevondoom @xmatthewx @hannahkane @community-impact

### Context
I'd like to announce our Open Web Fellows and Science Fellows on our affiliate sites (see [#654](https://github.com/mozilla/science.mozilla.org/issues/654) for Science Website, [#381](https://github.com/mozilla/advocacy.mozilla.org/issues/381) for Advocacy Website). I think this ideally should also propogate on the Network Site, and not sure what the best place for that given the current Network Site IA.

### Plan

Ideally, I think this could just be a duplicate page to the [Tech Policy Fellows Landing Page](https://network.mozilla.org/opportunity/2017-tech-policy-fellows/) with the fellows names listed, and links to their twitter bios. To that end, I've attached bios, with links to their twitters and photos as a zip below.

**OWF**
[2017-owf-bios.txt](https://github.com/mozilla/network/files/1278205/2017-owf-bios.txt)
[owf-imgs.zip](https://github.com/mozilla/network/files/1278159/owf-imgs.zip)

**Science (defined on the network site as "open data"**)
[2017-science-bios.txt](https://github.com/mozilla/network/files/1278224/2017-science-bios.txt)
[science-imgs.zip](https://github.com/mozilla/network/files/1278225/2017-science-imgs.zip)

**Media**
cc/ @brettgaylor 

AND we could continue to link to the respective [Science](https://science.mozilla.org/programs/fellowships/fellows) and [Advocacy](https://advocacy.mozilla.org/en-US/open-web-fellows/fellows2016) fellows' pages, as they do on the main [fellows' landing page](https://network.mozilla.org/opportunity/fellowships/) on the network site.

### Deadline

As with the other site updates, I'd love to wrap this by **Friday of this week (9/8/17)** or **Monday (9/11/17)** of next week so I can write blog announcements celebrating the fellows in a timely manner (prior to their onboarding at the end of September.

**Comment by xmatthewx** [comment]
Thanks @auremoser. Do you have access to the CMS? If not, let's get you on there. We will gladly provide support on any aspect of this, but are eager to set you free. 

As an early staff user, we'd welcome any feedback. A CMS comes with natural limitations, but we're glad to iron out wrinkles where it is easy and useful.

**Comment by xmatthewx** [comment]
cc @taisdesouzalessa – no work here for you at this point. Just making sure you witness discussion for any future UX considerations.

**Comment by auremoser** [comment]
Nope, I don't think I'm on the CMS @xmatthewx , feel free to set me up and I'll update things according to your instructions.

Thank you!

**Comment by hannahkane** [comment]
Thanks, @auremoser. My two cents:
 - I think eventually all of the Fellowships content should live on the Network site, including bios as well as the program overviews and application instructions
 - Ideally, we won't maintain the same content in multiple places
 - My understanding is the reason we built the Tech Policy page was because that program didn't already have its own site. Any press release or blogs we published needed to point to _something_. Since the Open Web and Science fellows have sites, I'm not sure there's a need to build and maintain a page on the Network site as well. Blog posts/press releases can point to the relevant pages on Advocacy/Science (where there's already a more comprehensive set of information about the programs) and we can promote those blog posts on the Network site homepage.

**Comment by auremoser** [comment]
O.k. cool, thanks @hannahkane , in that case, I will proceed with updating the Advocacy and Science sites.

There's still a question of where the Media Art fellows will be featured cc/ @brettgaylor 

Let me know if we should close this issue then?

**Comment by brettgaylor** [comment]
Maybe I should just make 'em a page on Network site?

In fact that's probably the way to go, since I'd also like to host a call for proposals for remaining grants there...

**Comment by hannahkane** [comment]
Just to clarify, I'm not the decider on this. Maybe @jessevondoom is?

**Comment by jessevondoom** [comment]
So chiming in with my 2¢ — I think it's fine to update the science/advocacy sites, but we'll have to move these things over eventually. So let's make sure we save the bios and photos you collected here for when we're ready to start moving everyone over. 

And yeah let's hook up a site for the Media fellows on the Network site now.

**Comment by community-impact** [comment]
Hi all, sorry I haven't responded earlier. This is my first time collaborating on GitHub, but now I have my bearings. I know that centralizing communication about fellowships is a big priority this year that @rizwan have been thinking about a lot. As such, is there any way we might be able to post the new fellows's bios all in one place, like [this page](https://network.mozilla.org/opportunity/fellowships/)  using the format of the TPF page for now until we port the info to the new site? I know the OWF, Science, and Media bios will all be in the same format.

**Comment by alanmoo** [comment]
Anyone with authorship permissions on the network site certainly could do that; We've got some long-term plans to improve that page creation process to be a bit more seamless based on Pulse profiles but we're not there yet. If someone were to take the time to build out a page like you describe, it likely wouldn't be work that's easily re-purposable into the new style once we're ready for it, so I'd hesitate to recommend someone spend the time to do that unless they think it's really worth it.

**Comment by hannahkane** [comment]
Quick update: @community-impact, @jessevondoom and I are meeting on Wednesday to hash out plans for the Fellowships' presence on the Network site moving forward.

**Comment by hannahkane** [comment]
I think we can close this, given plans/tickets for a robust Q4 pan-Fellowships presence on the site. 

Unless...is there an urgent interim need we need to fill?

**Comment by alanmoo** [comment]
It can always be reopened if there is.
