### ISSUE TITLE
Draft Persona Cards (designed)

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#719]
**Description:**
Design personas cards in a way that makes the personas easy to understand at a glance and to use.

**Comment by taisdesouzalessa** [comment]
Hey team, 

I did a draft of the structure I think it would for the personas' cards. Please take a look and let me know what you think of the structure. A layer of refinement (adding colors, illustrations, adjusting all the spaces) will be done later on. I just wanted to put this out there as soon as possible to collect some feedback :)

https://drive.google.com/a/mozilla.com/file/d/0B3b1KWRwjxtoVjNCa3RVU2U5bXc/view?usp=sharing

1. The information may change as we move to rounds of iterations.
2. I feel it is a bit text heavy...I tried my best to shorten the sentences. I will need help with the copy to make it more concise and better written. I really wanted those cards be easy to digest...not sure it is still quite there yet.

@xmatthewx @hannahkane @jessevondoom @prefontaint please let me know what you think of those templates.

**Comment by taisdesouzalessa** [comment]
Later on, it would be cool to have a comparison poster, like this:
<img width="1422" alt="image" src="https://user-images.githubusercontent.com/22157921/29682466-efe2b500-88bf-11e7-8a2a-b4c01728737a.png">

- for a poster like that I would recommend we get nuggets of information of those cards (the most important info) and put them all together in one poster.

**Comment by xmatthewx** [comment]
This is excellent @taisdesouzalessa! Well done. Great progress.  

Let's check in off Github about the best way to manage a round of wordsmithing and then feedback from others. I have a few thoughts. 

This is exciting. I think I see the light at the end of the tunnel!

**Comment by taisdesouzalessa** [comment]
@xmatthewx sure, I would love guidance on how we could organize a round of feedback, let's connect on it. Also, we could discuss how to fill in the info of the personas we don't have info from StoryEngine. I am super excited to see progress as well!

**Comment by taisdesouzalessa** [comment]
In terms of illustration, I was thinking about doing something in this style (names are gender neutral so I am trying to do the same with the illustration):
<img width="935" alt="image" src="https://user-images.githubusercontent.com/22157921/30139827-25e0e374-9325-11e7-99ee-7b7e623d8f23.png">

-----
I am currently gathering feedback from the designers in the Vancouver office in terms of the design of the cards and the illustration. I also would love to hear the thoughts of you all before I move on to the next illustrations.

**Comment by taisdesouzalessa** [comment]
Got feedback from designers and reiterated on the "Selby, the System Changer" illustration and also on the card itself. Besides it, I designed "Indigo, the Influencer". The copy will change and I will work on final alignments once we have the final copy. For now, here is how the cards look like. I'll be working on the other illustrations and posting here as I move on. Any feedback?

https://redpen.io/qm44b7dc608f93efb8

**Comment by taisdesouzalessa** [comment]
Also did a quick study to see how the different colors can work together once we do posters that require personas side by side:

<img width="865" alt="image" src="https://user-images.githubusercontent.com/22157921/30571164-b24db746-9c9a-11e7-9b62-7633305a7b66.png">

**Comment by taisdesouzalessa** [comment]
@xmatthewx @jessevondoom let me know if you have any feedback on these illustrations.

**Comment by taisdesouzalessa** [comment]
All the illustrations are done - they are on RedPen for feedback:
https://redpen.io/p/jz5de052b28bb0c3ea

And here is the card template, I will adjust all the alignments and spacings once we have the final copy:
front: https://redpen.io/ned710f0c483fa0339
back: https://redpen.io/wq55c43f9c3ec2d0c7

**Comment by xmatthewx** [comment]
these are so great! i think we can probably close this issue. there might be some feedback from other staff on the iconography, but we can iterate on that later.
