### ISSUE TITLE
Make CMS changes work

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network#722]
Sydette made some updates on Friday but the site didn't update/rebuild. (Though the API shows the new data). Let's figure out why that didn't happen automatically.

**Comment by cadecairos** [comment]
It looks like something in the front-end build is broken for the current version of network that we have deployed. It fails in the `build-healthcheck.js` step.

This appears to be fixed on master though.

**Comment by cadecairos** [comment]
aha: https://github.com/mozilla/network/commit/a40c57bf3f3d10c8fa6f76b653d09ab4966469ed

**Comment by cadecairos** [comment]
@alanmoo This should be fixed now, can we confirm this somehow?

**Comment by alanmoo** [comment]
Yes. I just updated the "People" ordering so Gideon and Chrystian appear next to each other. We should see that appear shortly if everything's working correctly. (Right now they're on different rows and the page looks a little broken)
