### ISSUE TITLE
CMS: Opportunity Pages (enhancement) - background color boxes + arrows for links

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#731]
**We have 2 issues to tackle on this issue:** 
1. Add background colors to make boxes. In case we want to highlight some information and differentiate it from the rest of the text. One example is the "Upcoming Events" section in the MITI page:
<img width="480" alt="image" src="https://user-images.githubusercontent.com/22157921/29834166-d7d894ca-8ca2-11e7-84bb-f1b3f2e7cf3c.png">

2. Links in our website (when isolated, not embedded in the middle of a sentence) are all caps and have the →.

For now, Taís will add a tutorial in our [Author's Doc](https://docs.google.com/a/mozilla.com/document/d/1WGWhfUY2mrQQGm-idP137S4CWdcdizL-UXI6DI_2QeU/edit?usp=sharing) so authors can add it themselves. In the future, if the need arises, we can implement those features in the CMS.

@alanmoo @hannahkane @xmatthewx please let me know if I wrote this ticket accurately. This was my understanding of what we decided to do - feel free o edit it as you see fit.

**Comment by alanmoo** [comment]
1. Can you describe when and where these boxes might be used? It looks to me like there isn't a specific pattern, so that's the kind of thing that's hard to codify into the template. If there is some sort of "aside" element that we want to be part of a specific template, we can work towards that. But for a simple box in the middle of some content, I don't believe that's something we'd want to address behind the scenes.

2. Is this a need or a problem that currently exists?

**Comment by xmatthewx** [comment]
I suggest we table this for now. Keep it in the backlog as a potential enhancement. Revisit when we have a bit more capacity and more authors creating pages. For now, I recommend we lean on tips and tricks gathered in the cms author guide doc.  

If the links+arrows prove to be a blocker to creating content, then we can file that as a separate ticket.

**Comment by taisdesouzalessa** [comment]
@alanmoo and @xmatthewx I think we are all aligned here, that is why I had added this comment at the beginning of the thread:

> For now, Taís will add a tutorial in our Author's Doc so authors can add it themselves. In the future, if the need arises, we can implement those features in the CMS.

Sorry if it was not clear that no action will be taken on the Engineering side. I should have been more explicit :).

**Comment by taisdesouzalessa** [comment]
Team, I think I won't add the first item to the doc because it is too complicated (we have to have a class copied from the website and change the source code in the editor). If somebody needs a box like that, I can tweak the code and build it for them in the CMS manually as necessary. 

Let me know if any of you disagree with that, ok?

**Comment by xmatthewx** [comment]
Your note was totally clear Tais. 

Most of our authors are comfortable with editing html and css. It's fine to have a use-at-your-own-risk tips at the bottom of that doc (if you can show example rather than instructions for copying things from source AND if it doesn't take more than a few minutes)

**Comment by taisdesouzalessa** [comment]
Cool! thanks for the context about the author's html expertise, Matthew. I may share in the "Design Tips" section then.

**Comment by taisdesouzalessa** [comment]
Items added to the document. Closing this issue.
