### ISSUE TITLE
Add links to footer

### ISSUE THREAD

**Issue by gvn** [mozilla/network#74]
@xmatthewx Do we know the various links for the footer?

**Comment by xmatthewx** [comment]
@taisdesouzalessa - do you have a list of the footer links in your IA diagram? Can you link from here to that? Rough doc is fine, just for our internal use.

**Comment by taisdesouzalessa** [comment]
Sure, this is the ticket: #41

**Comment by gvn** [comment]
That ticket just links Email to "desk.com", which is a landing page. 

Do we have a more specific URL?

**Comment by gvn** [comment]
I've added the URLs indicated in #41. Still missing code of conduct and email link. Marking blocked.

**Comment by xmatthewx** [comment]
We can hide/remove missing links. Add them if and when we've got them. I suggest we close this. 

Tracking:
 - Participation guidelines: https://github.com/mozilla/network/issues/87 
 - Email address for contact: https://github.com/mozilla/network/issues/79

**Comment by gvn** [comment]
Ok, commenting them out for now.
