### ISSUE TITLE
Changing order of people in admin isn't working

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network#742]
When I attempt to sort at https://network.mozilla.org/admin/people/person/sort/, I get a 403 on dropping the person in a new spot. 

`POST XHR https://network.mozilla.org/admin/people/person/sort/do-sorting/10/[HTTP/1.1 403 Forbidden 274ms] `

**Comment by alanmoo** [comment]
STR: Attempt to put Gideon and Chrystian next to each other on the list, as they shouldn't be a single item between two featured items anyway.

**Comment by gideonthomas** [comment]
@alanmoo, which account are you using? alanm or alan?

**Comment by alanmoo** [comment]
alan, a superuser.

**Comment by gideonthomas** [comment]
interesting...I'm able to sort people fine as a superuser but if I remove superuser status, I get the 403.

**Comment by alanmoo** [comment]
Can you rearrange it so that yours and Chrystian are next to each other?

**Comment by gideonthomas** [comment]
I can try

**Comment by gideonthomas** [comment]
Oh wait what? I'm getting the 403 now too

**Comment by cadecairos** [comment]
This looks like a possible CSP issue 

![2017-09-13 09_41_44-settings](https://user-images.githubusercontent.com/438003/30380555-ec883c56-9867-11e7-922d-48a65e56dbee.png)

**Comment by gideonthomas** [comment]
@cadecairos I see those CSP errors on practically every page though. I feel like there might be a permission issue.

**Comment by gideonthomas** [comment]
Yep, confirmed! That script that it is not loading is needed to set the csrf token on the ajax request. So we get back a 403 with the payload saying CSRF validation failed.

**Comment by gideonthomas** [comment]
Fixed
