### ISSUE TITLE
Gather metrics on existing homepage performance

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network#747]
So that we can compare them once #656 has landed and determine the impact if we implement this across the site.

**Comment by gvn** [comment]
Here are some reports from Lighthouse and dev tools:

[perf.zip](https://github.com/mozilla/network/files/1296805/perf.zip)

**Comment by cadecairos** [comment]
here's the latest data from pingdom's page speed check: https://screenshots.firefox.com/rXq0CSLRkWe5VVwG/my.pingdom.com

**Comment by alanmoo** [comment]
We never did a follow up on this, I'm curios- how does the performance compare now that we've got XHR everywhere?

**Comment by cadecairos** [comment]
Here's some data, but it looks like it's only 1 or 2 week's worth
![](https://screenshots.firefoxusercontent.com/images/112a2623-502a-410e-95a0-e3349d0cd8db.png)

**Comment by alanmoo** [comment]
But we don't have anything to compare it to anymore? I'm curious about the overall impact of this move to XHR.
