### ISSUE TITLE
Improve deployment process

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network#749]
### What problem(s) are we trying to solve?
* Making changes to the network site is error-prone.
  * There's a circular dependency in which the front end being built is dependent on the API being spun up, but that doesn't happen till the front end gets built.
  *  Deploying changes is error prone- sometimes rebuilds fail silently on content updates
  * Production/Master branch setup is unlike our other projects, and it's helpful to have the same dev/deploy process as much as possible.

We need to solve these, keeping in mind that Mezzanine templating...isn't great or easy

([original etherpad](https://public.etherpad-mozilla.org/p/cms-chat))

**Comment by alanmoo** [comment]
Before closing this we're going to need to turn off the "rebuild on model change" script @cadecairos

**Comment by cadecairos** [comment]
@alanmoo is this something we want now? I can disable it via config, and I can rip out the signals altogether.

**Comment by gvn** [comment]
Should be safe to turn off now that all the CMS driven components are pulling via XHR on prod.

**Comment by cadecairos** [comment]
filed #798 - I think I might leave that for next week, and just disable the build via config for now

**Comment by cadecairos** [comment]
The model signals will now bail early, as I've unset the config vars they rely on.

**Comment by alanmoo** [comment]
Closing epic, final issue has a PR open.
