### ISSUE TITLE
Opening the Menu is delayed in FF

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network#753]
There is a long delay between clicking on the menu icon and the menu actually opening. It is quick in Chrome, Safari and mobile but slow on my FF. This is annoying because I then end up clicking the icon twice which eventually opens and then closes the menu right after. 

I am on FF 55.0.3 for mac OS 10.12.6. But although @taisdesouzalessa has the same version of FF, she does not have this problem...

**Comment by gvn** [comment]
I have the same FF and OSX versions and also experiencing this delay.

**Comment by gvn** [comment]
I think this may be resolved now. I'm at least not noticing it in FF 57. Can you try again?

**Comment by kristinashu** [comment]
Yup, seems good in FF 56 too!
