### ISSUE TITLE
Restyle form as full width on Opportunity pages

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#754]
Our CMS Authored Opportunity pages allow an author to include a sign-up form. This was original designed as a sidebar on wide screens. Intentions were good, but the 2-column is not working. It's poor for content, and problematic with new multipage subnav. 

Task: 
 - [x] Make the sign-up form full width below page content, using the same style as the form on the homepage. 
 - [x] Allow the content above to be full width (as currently styled when no form is included).

Mockup: 

<img width="674" alt="image" src="https://user-images.githubusercontent.com/22157921/29643934-3e5ed496-8827-11e7-9746-bb74b2ac3b72.png">

Originally discussed with @taisdesouzalessa in #690

**Comment by xmatthewx** [comment]
@gvn assigning this to you in case you have time after wrapping up homepage admin project, so the queue isn't empty. i'm not sure that's the right practice, but i'll be out next week.

**Comment by taisdesouzalessa** [comment]
Opened a ticket with the QA here: #813. Ideally our content should occupy only 8 out of the 12 columns if the screen is greater than 991px (got this number from the current live staging site - I would assume it is one of our media query breakpoints?).

**Comment by taisdesouzalessa** [comment]
Verified on staging - closing!
