### ISSUE TITLE
Add footer to opportunity pages to give context

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#760]
Our CMS Authored Pages will have diverse audiences often arriving via external links. They might understand the Page's content, but not have any context on the site or the foundation's work. 

Let's explore a simple footer for these Pages, with a few words, that sits on top of the site's footer. It should be unobtrusive, helpful for curious visitors, but not pulling attention from the content above. 

 1. [x] design a quick option or two (time boxed to 2 hrs)
 1. [x] craft copy, considered for differing CMS authored pages
 1. [x] handover for implementation

**Comment by taisdesouzalessa** [comment]
Here are the designs:
V1: https://redpen.io/nr130b89723c14315c
V2: https://redpen.io/xm82d3c74067a81783

**Comment by xmatthewx** [comment]
Great work! Dropped in a couple of comments. Should be a quick iteration before we can pass this along.

**Comment by taisdesouzalessa** [comment]
Hey Matthew,

Based on your feedback, here is the new iteration. It works with or without the e-mail form. 
With email form: https://redpen.io/ch39b557e752ef992b
Without email form: https://redpen.io/jw7d43562ff23cae22

I think the e-mail form and the blurb of copy have different purposes so they can co-exist on a page. Maybe the copy on the blurb could be a little bit more explicit (that we are taking the users to the home page) so it doesn't sound too much like the copy on the e-mail form? I think that would solve the problem you pointed out in RedPen. Something aligned with: "Want to learn more about our movement? Check our home page".

**Comment by xmatthewx** [comment]
Looks great!! It feels a bit like it's part of the page content (and by that author), rather than part of the site. Maybe that's okay though?? 

What do you think @jessevondoom? This page footer would appear at the bottom of any cms authored opportunity page (likely to have a good chunk of traffic via outside links).

**Comment by taisdesouzalessa** [comment]
Mockups were updated with "See more" and added a "." after the link, as requested. Links are the same as posted earlier in [this thread](https://github.com/mozilla/network/issues/760#issuecomment-329898863)

In my opinion, it is ok that the blurb looks like part of the content. The reason being is that I think it is more likely the users will click to see more content if it is integrated with the copy they are already reading. Also, the blurb is related to the content above ("this is part of a movement...") so to me it makes sense they are visually related.

**Comment by xmatthewx** [comment]
I'm going to call this ready for implementation. @taisdesouzalessa – can you file an implementation ticket with artwork? no rush. we can stick it in the backlog of the next milestone.

**Comment by taisdesouzalessa** [comment]
Implementation ticket here: #787
