### ISSUE TITLE
4 network leaders

### ISSUE THREAD

**Issue by gvn** [mozilla/network#761]
For the Homepage model there should be 4 leaders instead of 3.

**Comment by gvn** [comment]
This is working, but ideally we should cap it at 4.

**Comment by alanmoo** [comment]
Why cap it? If the design changes in the future, we should be able to easily add people, and the ability to add/delete people from the homepage is already managed by django permissions.

**Comment by gvn** [comment]
We could always remove the cap later. If people add more (or less) than 4 it'll look weird as it stands today.

**Comment by alanmoo** [comment]
Permissions are set such that only superusers can add more items to the different sets. Good enough?

**Comment by gvn** [comment]
Sure
