### ISSUE TITLE
Create process and channels for feedback post-launch

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/network#77]
We'll want to have a streamlined way to collect feedback post-launch. 

* Bugs filed in Github (this repo or a different one)?
* Google form with guided questions or Coral's Ask tool?

This information will be helpful especially as we begin outreach to existing members.

**Comment by ldecoursy** [comment]
@samanthaburton Is this something your team might be able to help with? 

Essentially need some guided questions to collect feedback from our current active/engaged audiences, as they'll be the first folks we reach out to with a "preview" of the site for soft launch.

**Comment by samanthaburton** [comment]
Yes! Capacity will depend mostly on the timeline you're working on, but it could fit quite nicely into the network strength work Paul is leading w/Abdoul's support. Claw asked them to reach out to you/Matthew/Kevin re: syncing that work with the network site launch, and I think this is a great example of how those two pieces of work line up! 

I don't think Paul or Abdoul are on GitHub yet, so you could ping them via email & see if this is something they'd have capacity to support (ideally, in the context of the network strength work). 

Sound good?

**Comment by ldecoursy** [comment]
Will do! Thanks @samanthaburton

**Comment by xmatthewx** [comment]
@paulfzenke – can you lend a hand with this?

**Comment by paulfzenke** [comment]
@samanthaburton Thanks Sam! Yes, I created a new MoFo-specific GH account during on-boarding. You can find me here at @paulfzenke. 

@xmatthewx I would be happy to talk more about this -- perhaps on Friday during our meeting? I'll add some additional time (15 mins) to the invite and will update the agenda. Please let me know if there is anything you would like me to review before our discussion. Thanks!

**Comment by xmatthewx** [comment]
This work is being led by 270 and tracked elsewhere. Closing it here.
