### ISSUE TITLE
Implement little footer in Opportunity pages

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#787]
Implement footer in Opportunity pages. We want to provide more context to users that land straight into those pages and also encourage them to explore more of the website (so we hopefully can drop the high bounce rates we are seeing on those pages):

Mockup:
With e-mail form: https://redpen.io/ch39b557e752ef992b
Without e-mail form: https://redpen.io/jw7d43562ff23cae22
This footer should be present in both cases: with or without the email form.

Sketch file:
https://drive.google.com/a/mozilla.com/file/d/0B3b1KWRwjxtoUFBFbGw4Z0xtLW8/view?usp=sharing

Icon in svg:
[internet-health-icon.svg.zip](https://github.com/mozilla/network/files/1330474/internet-health-icon.svg.zip)

**Comment by gvn** [comment]
@taisdesouzalessa What does "See more" link to?

**Comment by taisdesouzalessa** [comment]
to the home page @gvn. I should have included in the ticket. Sorry for that!

**Comment by taisdesouzalessa** [comment]
The QA for this little footer is included here: Opportunity pages - QA #813. Narrower column with offset (visuals included in the screenshot posted there).

**Comment by taisdesouzalessa** [comment]
Talked to Matthew about the tweak above and we will let it go for now, since we have other stuff we want to implement. I may give a stab at fixing it and sending a PR for review but if I am not able to, we can do this tweak later on (when things are slower), since this is not a major UX problem.
