### ISSUE TITLE
Contact Us: Prep for visitor questions

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#79]
The website should have a way for visitors to contact us with questions. We'll include Twitter @mozilla and can also include an email address. Emails could be directed to Desk.com, but I'm unsure of our status with that platform and who would triage those messages. 

@Lottarao – can I assign this to you?

We won't include an email/contact us link until we sort this out. 

This is related to post-launch channels for feedback, but that could be handled with a google form regardless of this: https://github.com/mozilla/network/issues/77

**Comment by xmatthewx** [comment]
Hi Lotta. Do we have a catch-all email address that people can write with questions about the Network? I suggest we flag this as a staffing need. As the site becomes a central home, we'll need someone on point to triage, capture and answer FAQs, and relay the rest to staff as needed. 

If this isn't you and your team, let's figure out with Angela/Chris/Ashley how else we might handle this.

**Comment by xmatthewx** [comment]
@hannahkane - is this ticket still useful? should we open a new one with specific tasks? do we have a better link for contact that we should now add to the site?

**Comment by hannahkane** [comment]
We have an email address - network@mozillafoundation.org that we should add to the "We'd love to hear from you" section of /about, as well as the footer. I'll file a follow up for that. I don't think we need to do any more prep for visitor questions. We have a living doc with messaging where we can store FAQs, and a Slack channel to discuss responses.
