### ISSUE TITLE
Iterate Hero design

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#791]
Jesse suggests that we condense the hero in general, as well as the “Become a champion…” header. The goal is to move timely up higher.

**Comment by taisdesouzalessa** [comment]
Here are the options. Please note these mockups address the issue #792 as well:
V1: https://redpen.io/zu1240c7415e6b471d
V2: https://redpen.io/kg25c75eefb6dca199
V3: https://redpen.io/hm1ba4bf10e2ea0f05

I also did a quick mockup (not pixel perfect, just for preview purposes) of how it would look like after Kristina's work on UI alignment.
V1: https://redpen.io/gc46cd021f98ba9c80
V2:https://redpen.io/qo022c3d3d4be883c6
V3: https://redpen.io/fy49d0e4f5510bbddc

**Comment by taisdesouzalessa** [comment]
One thing to notice is that with the top banner removal, all the page will move to the top a bit. Currently, looking at the analytics (period: May 1 to Oct 1), the majority of people who see this page, see it in a browser height of 900px (desktop). Without the banner, this is what they would see (I also added the smallest desktop height included in the top 10):
<img width="602" alt="image" src="https://user-images.githubusercontent.com/22157921/31103302-08397172-a78b-11e7-8187-b58b904c40c8.png">

I think that just removing the banner, adding the news right after the hero section and the small copy blurb for each news would already fix the issue of making the News section more visible without too much work. 

The mockups I posted above are closely related to the UI alignment Kristina is working on so if we choose one of the options above we should maybe consider to do it together with that work?

Any thoughts, @kristinashu @xmatthewx @gvn ?

**Comment by kristinashu** [comment]
Nice! I've added a few comments in redpen. I would love it if we could hold off on the banner updates and just start with moving news up and adding the news descriptions since the banner updates would be introducing new styles which will make alignment work more difficult.

**Comment by xmatthewx** [comment]
Agreed. Thanks @taisdesouzalessa.  Let's hand this over to @kristinashu to recommend small adjustments that we can land alongside the other alignment work – rather than doing this with the other homepage rebalancing. I will switch epics. @kristinashu feel free to refile if useful.

I do think we can shrink vertical space a bunch by adjusting font-size, paragraph spacing, text layout ... without introducing new visual patterns.

**Comment by kristinashu** [comment]
I suggest we start by updating both fonts (title and intro text) to Zilla and do the nav updates (bringing the menu items out of the hamburger). Once that is done, we can see how the banner feels. I worry reducing the banner height will make the site look busy and over crowded, but lets wait and see!

**Comment by taisdesouzalessa** [comment]
Agree with @kristinashu here. 

I would love to test those font updates in my local environment first because Zilla is smaller than Arvo and it will affect the design of all of our pages. We will have to tweak spacings through the whole system (Kristina and I could collaborate on it). To be safe, we should definitely test locally first...

**Comment by kristinashu** [comment]
For sure. Linking this ticket to https://github.com/mozilla/network/issues/303.

**Comment by xmatthewx** [comment]
> We will have to tweak spacings through the whole system

Sounds good. And, let's be realistic about what we can feasibly accomplish before MozFest, keeping enough time for QA.

**Comment by alanmoo** [comment]
It sounds like some engineering tickets need to be filed, but I'm not clear exactly what they are/what the final work is, beyond literally just switching the news and people sections. @taisdesouzalessa can you comment with a list of tickets to be filed?

**Comment by xmatthewx** [comment]
@alanmoo - rebalance the homepage is all in this epic: https://github.com/mozilla/network/issues/786

@kristinashu - will handle any implementation tickets related to hero along with other UI alignment in this epic: https://github.com/mozilla/network/issues/582

I'm going to close this. Please re-open if this is a mistake.
