### ISSUE TITLE
Move Network Leaders component down on the homepage

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#793]
@xmatthewx commented on [Tue Sep 26 2017](https://github.com/mozilla/network-pulse/issues/705)

Move the Network leaders block to lower on the homepage. Below News/Latest and above Get Involved.

**Comment by taisdesouzalessa** [comment]
Mockups posted here: https://github.com/mozilla/network/issues/791#issuecomment-333688967

**Comment by gvn** [comment]
@taisdesouzalessa I'm unclear on what the final direction is based on #791. I see several variations.

Can you point me to the final comp?

**Comment by taisdesouzalessa** [comment]
@gvn based on the discussion we had [here](https://github.com/mozilla/network/issues/791#issuecomment-333699733) we are not changing the hero image for now. So those mockups don't apply.

This ticket's request is to move the Network leaders block to lower on the homepage (below News/Latest and above Get Involved). No other changes required. Is that clear or still confusing? I can do a quick mockup if it helps.

**Comment by gvn** [comment]
Ok that makes sense. I was confused by your link above to mockups...

**Comment by taisdesouzalessa** [comment]
Yep, I can see how it is confusing - I should have updated this page as well with the decisions we made on that thread...

**Comment by xmatthewx** [comment]
looks good on staging!
