### ISSUE TITLE
columbia journalism review news item has red glyph

### ISSUE THREAD

**Issue by gvn** [mozilla/network#796]
Should be monochrome to match other glyphs:

See:

<img width="928" alt="screen shot 2017-09-26 at 11 58 24 am" src="https://user-images.githubusercontent.com/206379/30878666-275c9846-a2b2-11e7-9a36-b0cd8abf0c7b.png">

**Comment by gvn** [comment]
Note: glyphs are managed via CMS.

CC @xmatthewx @hannahkane to delegate...

**Comment by xmatthewx** [comment]
Thanks @gvn. Are those other icons broken or just absent? If absent, I'll file a separate ticket to address our fallback.

**Comment by xmatthewx** [comment]
@taisdesouzalessa can you help prep a monochrome icon?

**Comment by taisdesouzalessa** [comment]
I wonder if we could create a process to ask authors to always submit the logos to us first so we can make it monochromatic for them (we do have it in the documentation but maybe it is not very scannable). Or in a long-term maybe have a filter in css?

**Comment by taisdesouzalessa** [comment]
Here is the logo:
![favicon-152](https://user-images.githubusercontent.com/22157921/30928391-62f73ca8-a370-11e7-8591-2b1a6b308ad4.png)

I tried to replace it via CMS in the production site but I run into a bug (unless I am missing something): filed it here #800

**Comment by taisdesouzalessa** [comment]
> Are those other icons broken or just absent? If absent, I'll file a separate ticket to address our fallback.

@xmatthewx @gvn the icon's path is broken on prod.
<img width="454" alt="image" src="https://user-images.githubusercontent.com/22157921/30929361-21d4f8c0-a373-11e7-899e-afabfe5be85d.png">


@alanmoo made a fix on staging and now we can see them on staging (not in prod):
<img width="857" alt="image" src="https://user-images.githubusercontent.com/22157921/30929421-5a268dd8-a373-11e7-9053-74aecf234c7d.png">

**Comment by gvn** [comment]
There are a lot of missing glyphs right now which shouldn't normally show up as broken images, but there's a bug where they're being emitted by the CMS as a incomplete/broken link (it's being fixed).

**Comment by taisdesouzalessa** [comment]
Thanks for the context here, @gvn 
I will open a ticket to design the missing glyphs. Closing this ticket since this issue is solved. Feel free to reopen if necessary :).
