### ISSUE TITLE
Gather requirements for CRM data collection

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#8]
Goal of site is to gain new members for the Network, and track them in the CRM so we can build relationships. 

The site will include typical GA tracking. Hopefully we can build in some goals and funnels for a better look at people's experience and our success. This planning should be coordinated with CRM work so they complement each other.

cc @arlissc

**Comment by xmatthewx** [comment]
Some initial thoughts just to break the ice:

For the CRM, I anticipate that we do a few things: 
 - We will gather email addresses for a mailing list. Low barrier entry. This will happen via simple form on the site. You'll see an example in the middle of the homepage. We should have a way to identify the site/page and campaign-ID of someone who joins like this. That's my educated guess. Not an expert.
 - Sometimes, a user will click a featured CTA that takes them to a different site (ex: Teachable, NSF challenge mini-site). We should track that when possible, but I'm guessing that's tricky and not MVP for launch. If we can just capture site/page/campaign wherever they do sign-up, we should be good for now. 
 - For these list joiners, we will need to plan engagement via email. Becoming a highly engaged "Member" will be a process.
 - Lastly, we will also have a more detailed Join form. This could ask for things like Affiliation or Issue interest area. This is a higher barrier to entry. Or even a pledge or some sort. Exact definition of membership is TBD from the other parts of the org.

**Comment by arlissc** [comment]
Thanks @xmatthewx  for starting this issue.

**Minimum required data to be collected:**
- First name 
- Last name
- Email

**Nice to Have:**
- Twitter ID
- GitHub ID
- Location (city minimum required, country would be great)
- Affiliation

Would like to start discussions around how/where the data will be captured and stored and in what format.  Happy to start a discussion around this.

**Comment by gvn** [comment]
@arlissc Any updates on schema for this JSON or service endpoint to push it to?

**Comment by arlissc** [comment]
@gvn - besides the new basket ID - what additional information do you need ?

**Comment by gvn** [comment]
I honestly don't know as I haven't done a Salesforce integration before. I'm assuming there's a REST API that we send this data to when someone submits the form.

If that's correct, then I need:

- REST API endpoint URL (and documentation)
- Schema for JSON (assuming it's JSON...) to be pushed to the endpoint

**Comment by xmatthewx** [comment]
@alanmoo - is this blocked from your perspective? Need anything from @arlissc?

**Comment by gvn** [comment]
Related to #15
