### ISSUE TITLE
Make Heroku pipelines work again

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network#805]
Now that we've got our static pages built in JSX, we can almost go back to Heroku pipelines for deployment instead of multiple git branches.

The one key problem I see is that we've got env variables (specifically `NETWORK_API_DOMAIN`) baked into the built JS files, so promoting from staging to production would result in the wrong endpoint being used.

Let's figure out how to extract that so we align our deploy process with other projects.

Requirement: We should still be able to change the API being used for the purposes of testing different data sets.

**Comment by alanmoo** [comment]
tl;dr of a Slack conversation:

>I suggested grabbing `window.location.host` and defining it as the global variable once so that anywhere it's needed can just grab that variable. If we need to test it locally, it's simply changing `window.location.host` to the name of the domain you want. However, this requires that you remember not to commit this change.

>@gvn suggested using an XHR to the API side to figure out what endpoint to hit. My concern with this is that it could introduce another roundtrip to render a single page. Gavin's suggestion is that we resolve this by caching aggressively.

Does that sound right?

**Comment by gvn** [comment]
Yep. I am suggesting a route that returns a whitelist of env properties. Something like `/api/env`.

I think we should try this first and see if perf is affected in any significant way. If so we could explore caching either via HTTP or as a cookie with a fairly short expiration.

**Comment by gvn** [comment]
Pipeline is working!
