### ISSUE TITLE
Organize a way to sync about future news that will be posted on the site

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#812]
hey @KevZawacki and @Sydette I was wondering if we could connect to collectively find a way in which design can support the News section of the Network site. 

This work is broken down in 2 parts:
1. Immediate action: the current broken links are in progress of being fixed (if there are no links, the text should be on the left) but a quick fix for now would be for me to manually add the glyphs so all news (at least in the home page) have logos. Also, I can provide an image for the featured item but I would need your help to choose one that fits better. I can post them here and get your thoughts.

2. Planning the future: I would like to have your help to figure out how we can best support you (with images/logos) in your future News needs. We could brainstorm it together. Maybe a meeting? Let me know.

Here is a screenshot of the current state of this section, for reference:
<img width="1235" alt="image" src="https://user-images.githubusercontent.com/22157921/31139433-61559cae-a826-11e7-9ede-51501a346a13.png">

cc: @hannahkane @xmatthewx

**Comment by KevZawacki** [comment]
Hi @taisdesouzalessa & @Sydette. Happy to brainstorm here. (But if you'd prefer a meeting, that's fine too.)

I worry about designers spending too much time creating logos. There are so many news articles about us from so many sources... that's a lot of work. Do we feel the logos are necessary? 

Re: choosing an image for the featured news item... good question. A screenshot of the article would probably look strange, right? If we're only updating that image once a week or so, I can help determine art on a case-by-case basis. Perhaps something from Flickr that's CC.

**Comment by taisdesouzalessa** [comment]
> Do we feel the logos are necessary?

For now, I think that having the logos whenever possible (in the News page) is useful because we don't have any filter on this page so the logos help our audience to quickly scan the publications if they are looking for a specific one. Visually, I also think that it adds interest in a page full of text.  It's not bad if we don't have some logos, but at least the major ones would be cool, in my opinion. 

@sabrinang - curious about your thoughts here, since you worked on the majority those glyphs in the past.

I can file a ticket to see if, in the future, we could automate the collection of those logos via CMS (Gavin had some ideas on it). 

> choosing an image for the featured news item... good question. A screenshot of the article would probably look strange, right? If we're only updating that image once a week or so, I can help determine art on a case-by-case basis. Perhaps something from Flickr that's CC.

I think an image would be more eye-catching than a screenshot of the article (that may be a bit confusing). Love the idea of Flickr (CC licensed pictures). There is also Unsplash, also free to use ([here is the license](https://unsplash.com/license)).

**Comment by KevZawacki** [comment]
@taisdesouzalessa Sounds good! Feel free to message me when you're seeking a new image for a featured news item; I can help track something down.

**Comment by taisdesouzalessa** [comment]
Thanks @KevZawacki! I think every featured news item should have an image so they stand out and bring attention to it. I'll add a paragraph about it on the "[Network Site User Guide](https://docs.google.com/a/mozilla.com/document/d/1WGWhfUY2mrQQGm-idP137S4CWdcdizL-UXI6DI_2QeU/edit?usp=sharing)". For now - I am wondering if you or @Sydette have some suggestions of an image for the current featured News item: 
<img width="588" alt="image" src="https://user-images.githubusercontent.com/22157921/31189177-26ee9784-a8ec-11e7-856e-47922071d3be.png">


Also, is there a calendar of future posts so maybe we could provide the assets you need in advance? Do you think having the assets in advance would be useful to your team? Any other ideas on how we can collaborate on those are welcome :).

**Comment by KevZawacki** [comment]
Hi @taisdesouzalessa,

For the current featured item, how about [this photo from the Coral website](http://coralproject.net/research.html):

![learnmore-lg](https://user-images.githubusercontent.com/11045250/31193328-c9aef05c-a911-11e7-8ce5-a3e0a0179047.jpg)

And, @Sydette would know better than I if there's a calendar.

**Comment by taisdesouzalessa** [comment]
Great image @KevZawacki! Thanks for that. I just found an issue with adding images that aren't videos (I filed the bug for that).

I'll just wait for the fix to happen before I upload this image, ok? In any case here is the preview of the final result (just imagine it without the play button).

<img width="653" alt="image" src="https://user-images.githubusercontent.com/22157921/31203474-0ade32e0-a91c-11e7-975d-975c21ad9cab.png">

I'll connect with Sydette about a calendar! Thanks :)

**Comment by taisdesouzalessa** [comment]
Closing this ticket. News broken links are fixed :). The play button fix has its own ticket. Screenshot of the current state: 
<img width="1187" alt="image" src="https://user-images.githubusercontent.com/22157921/31299607-1ac3de1a-aaa4-11e7-8068-a69fba473690.png">
Action item: Taís will connect with Sydette to check on editorial calendar and discuss the need for future logos.
