### ISSUE TITLE
Automate glyphs

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#814]
Our News site has many logos from many different publications:
https://network.mozilla.org/news/

This ticket is to investigate the possibility to make the inclusion of the glyphs automatic somehow (if not the whole process, is there a part of it than could be automatized?). Currently we manually update each glyph: 1. we find them, 2. we convert them to grey, 3. we upload them to the CMS.

**Comment by gvn** [comment]
Completely automating it is going to be super time consuming, but we can easily add a grayscale filter via CSS to make that part easier.

**Comment by gvn** [comment]
Also, bear in mind that soon missing glyphs will just result in left aligned header text instead of a broken image, so getting every single glyph in will be less crucial.

We could also explore a default glyph...

**Comment by xmatthewx** [comment]
Cool. I think we can keep this in the backlog. Maybe as help-wanted. Left alignment will definitely improve things. A default glyph seems like 80% of the solution with 1/10th the work.

**Comment by gvn** [comment]
Left align is back on prod!

**Comment by taisdesouzalessa** [comment]
Since the left alignment is implemented  I feel we can close this ticket. Feel free to reopen if you disagree.
