### ISSUE TITLE
Migrate domain name to foundation.mozilla.org

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network#815]
Beyond the production and staging server names, what other work is required as part of this? Would this be a good time to rename the heroku app too?

**Comment by alanmoo** [comment]
@xmatthewx @jessevondoom Just to confirm: we don't need any design/logo changes to implement this, correct?

**Comment by xmatthewx** [comment]
I think we're good to go, no design/copy changes required. I will file a ticket to review copy/links within the site, but that shoudn't be a blocker. Let's...

 - [ ] set up a redirect from network to foundation

...since we probably won't announce this change.

**Comment by alanmoo** [comment]
Yup. @cadecairos will be tracking this in the devops repo, crosslink to come. We spoke about a plan yesterday.

**Comment by cadecairos** [comment]
I enabled `network.mofostaging.net` to `foundation.mofostaging.net` (without redirect) and captured the actions that I took (these steps apply to production):

1. Add `foundation.mozilla.org` to `ALLOWED_HOSTS`, `ASSET_DOMAIN`, `CORS_WHITELIST`, `NETWORK_SITE_URL` 
2. Add `foundation.mofostaging.net` as a domain to network-api-production
3. Add `https://foundation.mofostaging.net` as an authorized javascript origin in the Google OAuth settings
4. Add `https://foundation.mofostaging.net/soc/complete/google-oauth2/` as a callback url in the Google OAuth settings
5. Add CNAME `foundation.mozilla.org.herokudns.com.` to `foundation.mozilla.org.`
6. Once foundation.mozilla.org resolves, run a build
7. Test.

So, now staging now can serve up both sites.

For the redirect, I propose we ship a patch once we have both domains set up, that will redirect to the primary domain if it's serving a request for another domain. This way we can keep using lets encrypt certs on Heroku for secure redirects.

**Comment by cadecairos** [comment]
Bug filed for `foundation.mozilla.org` cname: https://bugzilla.mozilla.org/show_bug.cgi?id=1409104

**Comment by xmatthewx** [comment]
and... analytics!

**Comment by cadecairos** [comment]
Filter added to the production analytics view.

**Comment by alanmoo** [comment]
Can we close this?
