### ISSUE TITLE
Latest from the Network section: persistent play button

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#818]
Issue: in our "Latest from the Network" section the play button is persistent when we have no images in the featured item.

<img width="1007" alt="image" src="https://user-images.githubusercontent.com/22157921/31200683-c42139f2-a910-11e7-9ac9-b9a976dc3560.png">

There are 2 use cases where this button shouldn't be there:
1. When there is no image
2. When the featured news article isn't a video and the author uses an image to illustrate the featured item.

**Comment by taisdesouzalessa** [comment]
In the case showed above, the video box was unchecked:
<img width="834" alt="image" src="https://user-images.githubusercontent.com/22157921/31241541-0023a1bc-a9b9-11e7-82a5-cfbd6d7a5163.png">

**Comment by xmatthewx** [comment]
checkbox works like a charm. closing.
