### ISSUE TITLE
 Implement nav ui alignment

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network#820]
From alignment work in mozilla/network#582 and to align better with new brand, mozilla.org, Network site, and IRH sites.

https://redpen.io/ygc29beb3e61e39afb

<img width="1022" alt="screen shot 2017-10-05 at 10 13 42 am" src="https://user-images.githubusercontent.com/1068783/31240638-2ee66e1a-a9b6-11e7-992e-a81308078c21.png">

### Updates include:
- keep logo the same
- show menu items (pull out from hamburger)
- update menu items Open Sans Bold 16px (can use Nunito instead of Open Sans)
- keep signup CTA the same
- hover state for nav items and Username is black underline 2px high
- keep total nav bar height the same (88px)

### Mobile:
- similar to now
- move hamburger icon and close icon to the right
- reversed menu icon [Menu.svg.zip](https://github.com/mozilla/network/files/1364119/Menu.svg.zip)

<img width="970" alt="screen shot 2017-10-06 at 4 37 15 pm" src="https://user-images.githubusercontent.com/1068783/31302197-acadc308-aab4-11e7-957b-1d6bed88fda0.png">

cc @gvn

**Comment by kristinashu** [comment]
The menu items look just a little too tight next to each other. Could you please add an extra couple px between each menu item? 

Example:
![screen-shot-2017-10-17-at-8 31 24-am](https://user-images.githubusercontent.com/1068783/31674391-90acfe66-b316-11e7-972e-a5f09680c656.png)

Otherwise, everything else looks great!

**Comment by gvn** [comment]
What would you like the spacing to be exactly?

**Comment by kristinashu** [comment]
If it's 18px now, then please increase it to 28px (that might be @2x).

**Comment by gvn** [comment]
Changes are up on staging to verify: https://network.mofostaging.net/

**Comment by kristinashu** [comment]
The space between nav items looks good but please make the space between the logo and the first nav item the same as between individual items (ie make the blue box the same as the pink ones).

![screen-shot-2017-10-19-at-4 32 48-pm](https://user-images.githubusercontent.com/1068783/31798952-e2ff859a-b4eb-11e7-9b3c-81c57f37c7e7.png)

**Comment by gvn** [comment]
Changes are up on staging to verify: https://network.mofostaging.net/

**Comment by kristinashu** [comment]
Perfecto!
