### ISSUE TITLE
Add excerpt text to news articles on homepage

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#821]
**Task:** 
To add a few lines for either a summary or editorial commentary. The goal: provide more context on stories and guidance to visitors.

**Here are the specs:**
1. JPEG with the final look of this section (I did this mockup on the browser so it is following the already implemented rules):
<img width="832" alt="image" src="https://user-images.githubusercontent.com/22157921/31199842-8c1c8be0-a90d-11e7-950a-b089602734bf.png">

2. Character count (max): 146

3. For spacing between date and text excerpt, I just added a `<p></p>` after the date, so the spacing is what we already have there (16px - yellow part of the image below)
<img width="373" alt="image" src="https://user-images.githubusercontent.com/22157921/31200045-3e78ca56-a90e-11e7-96e5-eb3a1dd648e8.png">

**Comment by taisdesouzalessa** [comment]
For what I understood (correct me if I am wrong), we are limiting the character once the page is published, correct? So in theory, an editor could add as much copy as they want and it would add an ellipsis once the page is rendered.

What I had in mind when I designed the page was that the limit would be set in the CMS for the editors so they could write a short piece of copy (with the limit of 146 characters). In that scenario, the character count of A is the same as B because the stories could be interchangeable and no ellipsis would be required.

<img width="728" alt="image" src="https://user-images.githubusercontent.com/22157921/31456818-c1d07dd4-ae6f-11e7-84f6-2a8db73056ab.png">

If we are not implementing this now into the CMS due to complexities, I would suggest we either:
1. State the limit of characters in copy only via CMS (via helper text) to try to avoid the ellipsis and be clear that they should add a summary (without a forced limit people may still exceed it...we could talk to the main editors about it and add it to our doc as well):
<img width="808" alt="image" src="https://user-images.githubusercontent.com/22157921/31457640-32e50632-ae72-11e7-885b-da22ceec25c6.png">

2. Keep the ellipsis but add in the helper text that they should add the first paragraph of the article instead of a summary.
<img width="856" alt="image" src="https://user-images.githubusercontent.com/22157921/31458077-b985f132-ae73-11e7-83e8-a3b98827dae6.png">

When we have ellipsis (or other treatments such as fading), users expect a continuity of the copy so once they click on the article, the expectation is that the copy will be the same as they were previously reading (as showed in this example from Pulse):
<img width="723" alt="image" src="https://user-images.githubusercontent.com/22157921/31458260-69fc3d46-ae74-11e7-9cca-059ccf20cbc4.png">

Mixing both ellipsis and summary will be confusing for the end users. 

I find the solution 1 the most appropriate because I think the purpose of the summary is to bring attention to the story (which the first paragraph of an article may not do very well).

Hope this explanation is clear, if not, we can always chat!

@xmatthewx - please let me know your thoughts on it.
@alanmoo - those are my comments after I checked this feature. Let me know what you think as well. 

I apologize for the long post, I couldn't make it shorter :)

**Comment by alanmoo** [comment]
This makes sense. The ellipsis is the quickest way to achieve a description, as it required no back-end work. I think the approach we take depends on this: Do we want the extra text to be a summary or an excerpt? Let's not spend a lot of time hashing this out, as there are bigger fish to fry right now.

**Comment by taisdesouzalessa** [comment]
I think the summary makes more sense since it quickly captures the essence of a story and it is more likely to make the users go check it out. Curious about others think, though.

**Comment by xmatthewx** [comment]
@taisdesouzalessa you can check with Sydette and Jesse as stakeholders. We might want a new clean ticket for implementation after all has been figured out.

**Comment by taisdesouzalessa** [comment]
Talked to Sydette and Jesse via Slack. They want the text to be a summary, so authors have more control over the messaging. 
Option 1 seems to make sense then, at least to me. We could not limit the character counting (since we are not able to do it via CMS for now) to guarantee the full text will be displayed (no ellipsis required) and encourage authors to keep it around 146 via helper text.

**Comment by alanmoo** [comment]
Ok, I can open a pull request on this real quick. How about this: Helper text says `A short summary of the article (around 146 characters)`, but field is actually limited to 200 characters?

**Comment by taisdesouzalessa** [comment]
I think it is a great idea, Alan!

**Comment by xmatthewx** [comment]
looks good on staging! both frontend and back.
