### ISSUE TITLE
Implement section divider ui alignment

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network#822]
From alignment work in mozilla/network#582 and to align better with new brand, mozilla.org, Network site, and IRH sites.

Comp https://redpen.io/ygc29beb3e61e39afb

<img width="1021" alt="screen shot 2017-10-05 at 10 46 23 am" src="https://user-images.githubusercontent.com/1068783/31242194-1c1e3aa6-a9bb-11e7-949e-4ff70ac3d6ce.png">

Update dashed divider to gradient + highlight text. Note that sometimes the divider is gradient + highlight text and sometimes it is only the highlight text (no gradient)([example](https://redpen.io/tw35abb62b45df306b)).

- gradient colors are same as header banner (from #3DFEFD to #B7D43F), 4px in height
- 30px vertical space between gradient and text
- text is Zilla Slab Highlight 25px with 40px of black before text starts

Related to Pulse nav update https://github.com/mozilla/network-pulse/issues/731

cc @gvn

**Comment by kristinashu** [comment]
Sweet! Looks good except the dividers at top of the Landing page and also the Upcoming page look a little too close to the banner image.

Example:
![screen-shot-2017-10-17-at-8 40 56-am](https://user-images.githubusercontent.com/1068783/31674924-044d766a-b318-11e7-86e4-ec9d40397f21.png)

Please increase the the gap from what I think is 30px to 50px.

Padding on all the other dividers (example: 'Network Leaders' and 'Get Involved' lower down on the Landing page) look good.

**Comment by kristinashu** [comment]
Sorry, one more thing... can you add the selected state? So if I'm on the projects page then "Projects" should be underlined (like the hover state). It seems to be there on narrow screens but not desktop.

**Comment by gvn** [comment]
Changes are up on staging to verify: https://network.mofostaging.net/

**Comment by kristinashu** [comment]
Awesome!
