### ISSUE TITLE
Implement home page feature box alignment 

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network#823]
From alignment work in mozilla/network#582 and to align better with new brand, mozilla.org, Network site, and IRH sites.

Update Get Involved feature box layout to look more like News feature box layout.

### News on production:
<img width="504" alt="screen shot 2017-10-05 at 10 59 29 am" src="https://user-images.githubusercontent.com/1068783/31242648-79cb773a-a9bc-11e7-9200-8328a4505f58.png">

### Get Involved on production: 
<img width="511" alt="screen shot 2017-10-05 at 10 59 22 am" src="https://user-images.githubusercontent.com/1068783/31242647-79beec7c-a9bc-11e7-9b2a-2488f784a435.png">

### To do: 
We want this to look more like News on production site so please update Get Involved by:
- remove grey background box
- remove grey drop shadow on image
- add white overlapping box
- update image ratio to match image in News

cc @gvn

**Comment by xmatthewx** [comment]
This all looks great on staging to me, but I'll let @kristinashu verify this, #820, and #822.

**Comment by kristinashu** [comment]
Looks excellent!
