### ISSUE TITLE
Review site to update links and copy for new subdomain 

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#829]
We will soon shift the site URL from network.mozilla.org to foundation.mozilla.org.

Let's do a quick review of the site to identify any links or copy that require an update. Let's timebox this to an hour or two.

Note: 
 - logo and home link to root "/", so no update is required. 
 - links to network subdomain will redirect to foundation, so we don't need to worry about missing minor links  on opportunity pages. 

a pad to gather notes: https://public.etherpad-mozilla.org/p/foundation-site-url-updates

**Comment by taisdesouzalessa** [comment]
Added my notes on the Etherpad. Found only email address and copy issues. No link issues found.

**Comment by xmatthewx** [comment]
Wow, thanks @taisdesouzalessa  for the thorough notes. I'll file a ticket regarding the email address. And I will pass the etherpad along to Sydette to figure out what copy needs to evolve.  Sound good?

**Comment by taisdesouzalessa** [comment]
@xmatthewx I just added 1 more line to the Etherpad (line 8). It just occurred to me that I forgot to check 1 thing about the links...
