### ISSUE TITLE
Favicon!

### ISSUE THREAD

**Issue by gvn** [mozilla/network#83]
We need a Favicon designed for the site.

**Comment by sabrinang** [comment]
<img width="1093" alt="screen shot 2017-02-20 at 9 41 19 am" src="https://cloud.githubusercontent.com/assets/2492510/23136255/c6370f40-f750-11e6-8c65-2b5ff91cf0d8.png">
All mozilla properties are using the updated m for the favicon and documentation is on of the bottom of the [brand guide](https://mozilla.ninja/our-logo)

Favicon files are located here: https://mozilla.ninja/s/Moz_Favicon_Logos.zip
<img width="862" alt="screen shot 2017-02-20 at 9 56 26 am" src="https://cloud.githubusercontent.com/assets/2492510/23136723/e5543c8e-f752-11e6-963c-ab98d586cded.png">

Let's go with "One-color-black" (we can change to colour in the future when we finalize a brand colour for the network).
