### ISSUE TITLE
DUE MARCH 3: Content for "Fellowships" 

### ISSUE THREAD

**Issue by hannahkane** [mozilla/network#84]
Needed:
 * Short blurb for homepage feature card (see [mockup](https://projects.invisionapp.com/share/ZJ9YTAGEA#/screens/216715355))
 * Copy for interstitial page (look at [Health Report](https://projects.invisionapp.com/share/ZJ9YTAGEA#/screens/216715361) page as an example of layout)
 * CTA content and link to external page

**Comment by hannahkane** [comment]
@vanessarhinesmith and @auremoser - assigning this to you. Are you the right people?

**Comment by auremoser** [comment]
Yep @hannahkane , I think so, we can loop people in on the doc.

May I ask where the current CTA for "Join the Network" leads? I think ours should be the same CTA as other pages for the launch; ie "join the network to learn more." But I'm not sure the architecture of that "join" form and whether or not it will allow a user to specify what they are most interested in (fellowships, partner opportunities) etcet. I don't want to assume it will do something that it doesn't.

**Comment by hannahkane** [comment]
@xmatthewx should correct me if I'm wrong here, but I believe the "Join the Network" CTA will add someone to the general Network list, but tag them based on the page they arrived via. So, the CTA should be Fellowships-specific, so that we can confidently tag them as interested.

**Comment by xmatthewx** [comment]
Yep. 

Here's the flow in case any of it is confusing: 
 - Person visits homepage
 - Sees a "card" that features fellowships (image, short phrase)
 - Taps card
 - Page opens with some info and a Join form (similar to the [health report page](https://projects.invisionapp.com/share/ZJ9YTAGEA#/screens/216715361))
 - Person reads stuff. They might leave page to view more fellow info. Ideally they Join and submit their email address. 
 - When they join, we'll know that they did it from this page, and they will be tagged in CRM so we can engage with them specifically about fellowships. 

We can customize the Join header and statement next to the form for your purpose. Something similar but better than: "Join the network. Be the first to learn about fellowships and other opportunities."  

Two notes: 
 - Think of a mix of things we might offer. Doesn't need to be about FELLOWSHIPS. For example: See PERSON X's amazing Project Foo to learn more about our Network's fellowships.
 - 1st draft doesn't need to polished. We should get feedback from Kevin/Paul/Will and others who are thinking about messaging and engagement.  

Sorry for such a long comment. Ooops.

**Comment by hannahkane** [comment]
hey @vanessarhinesmith and @auremoser - do you have an update on this? Thanks!

**Comment by auremoser** [comment]
Hi all, sorry for the delay here, things have been pretty busy. 

Here's a [Google Doc with content suggestions](https://docs.google.com/a/mozilla.com/document/d/1TPs2OKTtow4rVj8R8n0Lqy7tlP4Q18h3vTMBG6j4yoM/edit?usp=sharing).

Took a stab at the content you itemized above, everyone else on this thread feel free to edit/annotate as you see fit for appropriate messaging. You should all have permissions.

cc/ @vanessarhinesmith @stephwright

Have a great weekend.

**Comment by hannahkane** [comment]
Thanks, @auremoser. I think this copy looks excellent. @xmatthewx - do you have an opinion on the issue raised in the doc about linking off-site? I don't think that's unprecedented. I believe we do that on both the Internet Health and the Trainings interstitials, right?

**Comment by hannahkane** [comment]
I'm going to close this, since work has moved on in other tickets.
