### ISSUE TITLE
Create route that exposes whitelisted env vars as JSON object

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network#843]
1. A route handler, maybe `/environment`?
2. We can have it serve the same variables we output in `build-env.js`
3. accepts GET requests, response type "application/json"
4. Ensure it only renders whitelisted vars.

**Comment by cadecairos** [comment]
@patjouk Here's how I think this can be accomplished:

1. Add a `views.py` file to `/network-api/app/networkapi/` which contains a custom view class that uses `django.http.JsonResponse` to render a dict as a json payload. here are some helpful doc links: [base views](https://docs.djangoproject.com/en/1.10/ref/class-based-views/base/#view), [JsonResponse](https://docs.djangoproject.com/en/1.11/ref/request-response/#jsonresponse-objects)
2. Add the route (`/environment.json`) to `/network-api/app/networkapi/urls.py`. 
3. Add the specific variables that we want to send in `/network-api/app/networkapi/settings.py`. see [here](https://github.com/mozilla/network/blob/77922244c71065c571f567fddb5a140fbc9d19fd/network-api/app/networkapi/settings.py#L24-L49), and find somewhere to add in a "frontend" section, where you load the values from the OS environment (using `VARIABLE = env('VARIABLE')`)

**Comment by cadecairos** [comment]
There might also be a simpler way to do this in Django Rest Framework - feel free to investigate that avenue - I only looked up pure django solutions.
