### ISSUE TITLE
Bootstrap error message

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#85]
@gvn I was wondering if there is a default way we treat error handling in Bootstrap. Ex: does a tooltip show up? Does an inline text show up after the field?

Scenario: if user doesn't check the box accepting the Privacy Notice, the form can't be submitted. here is what we have in the mockup so far:

<img width="1037" alt="screen shot 2017-02-21 at 2 51 38 pm" src="https://cloud.githubusercontent.com/assets/22157921/23188918/678133e0-f845-11e6-86fc-802438f63429.png">

If there is a default way please let me know and I'll add it to the mockups, adding our style on top of that. 

cc: @sabrinang

**Comment by gvn** [comment]
There's no prescribed way to handle errors, but Bootstrap does have a "Alert" component:

https://v4-alpha.getbootstrap.com/components/alerts/

(We haven't come up with a specific style for this in `mofo-bootstrap` yet.)

**Comment by sabrinang** [comment]
Some ideas around error states:
<img width="820" alt="screen shot 2017-02-22 at 12 00 28 pm" src="https://cloud.githubusercontent.com/assets/2492510/23229819/8d3a4426-f8f6-11e6-9ca6-3943ac8ee121.png">

**Comment by taisdesouzalessa** [comment]
Thanks for the input here! Based on this discussion, here is the application of the error message in the interface:

DESKTOP:
![error-desktop](https://cloud.githubusercontent.com/assets/22157921/23236992/485ebe58-f910-11e6-9101-e038de0b9a94.gif)

MOBILE:
![error-mobile](https://cloud.githubusercontent.com/assets/22157921/23236994/49f71666-f910-11e6-9e98-df11af4d8af9.gif)

I implemented them in the prototypes as well - to see it in action, click on the "Join Us" form in the home page without checking the box.

**Comment by xmatthewx** [comment]
This direction looks great. I propose that we let @gvn run with this, come back to us if he identifies any gaps.

**Comment by alanmoo** [comment]
Turns out bootstrap does have some validation. https://v4-alpha.getbootstrap.com/components/forms/#examples. There's also some browser-level validation that we can get for free, though its support may not be completely there across browsers. I'll poke at this and see what I get.

**Comment by alanmoo** [comment]
MVP taken care of for launch in #126. Unassigning for now.

**Comment by kristinashu** [comment]
I think we can close this but please reopen if you think it is still needed.
