### ISSUE TITLE
Fellowships page: Research and benchmarks

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#855]
**Description:**
Research existing pages in order to have an overview of the existing work, ask questions that surface from it in the main doc and also take a quick look at some benchmarks to collect new ideas and inspiration.

**Current web properties:**
https://science.mozilla.org/programs/fellowships
https://advocacy.mozilla.org/en-US/open-web-fellows/fellows2017
https://network.mozilla.org/opportunity/2017-tech-policy-fellows/
(Note: we have an additional Fellowship area - Media Fellows - that currently has no online home)

**Comment by taisdesouzalessa** [comment]
Here is the [document](https://docs.google.com/a/mozilla.com/document/d/1TgBEok6QrS7xIxU0qaUccJRzzuSXOS1omkvaOKtztLo/edit?usp=sharing) that lists of existing items of the current sites and a quick benchmark. 

As I looked through the existing sites I found it useful to write down their structure so I could pay attention to the information architecture and other elements that could be reused in the new site. I think we have many cool things there (highlighted in bold).

In the benchmarks section, I focused on structure and organization of content. The goal was to quickly learn what others are doing and gather some ideas about ways to organize our information.

Any ideas and suggestions? @xmatthewx  @hannahkane

**Comment by hannahkane** [comment]
This is very helpful, @taisdesouzalessa. A question this surfaces for me is whether Pulse profiles will be adequate for the depth of information we might want to convey about Fellows? 

cc @xmatthewx @jessevondoom

**Comment by xmatthewx** [comment]
What types of info are thinking? We do plan to extend profiles to include a space for story engine interview. Not yet implemented of course. This could be made flexible for free form content. And... I'd be hesitant to add too much content that will likely grow stale. I'd rather link out to blog posts, about-me pages, and other social profiles.

**Comment by xmatthewx** [comment]
What types of info are thinking? We do plan to extend profiles to include a space for story engine interview. Not yet implemented of course. This could be made flexible for free form content. And... I'd be hesitant to add too much content that will likely grow stale. I'd rather link out to blog posts, about-me pages, and other social profiles.

**Comment by taisdesouzalessa** [comment]
@hannahkane, I am curious about what you mean about the depth of information as well, could you give me an example? 

What I had in mind was a short paragraph for each Fellow (following the model we already have) and link to external sources if people want to learn more, as Matthew suggested. 

I think once we start building the wireframes we will have a clearer picture of what type of information we want and where it should come from.

**Comment by hannahkane** [comment]
@taisdesouzalessa - I think we can probably close this ticket and move on to wireframes. What do you think?

**Comment by taisdesouzalessa** [comment]
Good idea @hannahkane - closing!
