### ISSUE TITLE
Add Participation Guidelines

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#87]
Mozfest footer links to participation guidelines: https://mozillafestival.org/guidelines

Could be a good idea to do something similar on this site.  @hannahkane - curious what you think. Would you do this the same way as on MozFest? Does it make sense in this context?

**Comment by hannahkane** [comment]
Interesting idea. Would it be for interacting on the site (not too many opportunities to do that, at least initially, right?) Or would it be about real-world interactions?

**Comment by hannahkane** [comment]
@edrushka has recommended we make use of the [official set of community guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) that Mozilla developed in conjunction with the community. 

@xmatthewx wonders if we should adapt these and host a separate version specifically for the network.

Thoughts? @ldecoursy @Lottarao @chrislarry33 - anyone else who might have an opinion?

**Comment by hannahkane** [comment]
I'll start! My opinion is that it's potentially confusing to have two different sets of guidelines, so I'd stick to the official Mozilla set. What do other's think? 

I'm not sure who to tag, but I'm going to go with @chrislarry33 @Lottarao @KevZawacki

**Comment by KevZawacki** [comment]
@hannahkane Agreed. I think we should stick with the official Mozilla set. 

Only potential tweak is revising: "If you believe you’re experiencing practices which don’t meet the terms outlined above, please contact inclusion@mozilla.com." 

Not sure we want to be de facto mediators for any and all Network disagreements.

**Comment by hannahkane** [comment]
@KevZawacki - so, are you suggesting we host our own version of the guidelines, with the tweak, rather than linking to the general moz guidelines?

**Comment by KevZawacki** [comment]
@hannahkane Hm. If the tweak means building out a whole new section of the Network Site... let's just link to the existing guidelines.

**Comment by hannahkane** [comment]
Thanks, @KevZawacki.

Closing in lieu of implementation ticket #235
