### ISSUE TITLE
Remove Leadership from title and MLN acronym 

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#88]
Site title is currently Mozilla Leadership Network.
https://github.com/mozilla/network/search?utf8=%E2%9C%93&q=mln

Putting this in a future milestone to address after we land the final name. 

The rationale: We use the word Leadership internally, and inherited the acronym MLN from the mozilla learning network. We'll move away from both. Externally, we've found that the word Leadership is often ambiguous and exclusive. It's also implied that a network will be lead by leaders. MLN and other acronyms don't transmit info to audience who haven't been initiated.

**Comment by hannahkane** [comment]
@xmatthewx - who is responsible for unblocking this ticket?

**Comment by xmatthewx** [comment]
assigning this to me 😄.

**Comment by hannahkane** [comment]
Can we close this?
