### ISSUE TITLE
Copy review before launch

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#89]
Let's review copy for typos and other oopsies. Gather all the little things to fix in this issue. File bigger changes to a page in its own ticket. 

Note: copy will change. Not yet ready for a full review. I'll remove this note when it is.

**Comment by hannahkane** [comment]
@xmatthewx - is this likely to happen this week, or should it be next week? Can we start this process now? Can we identify pages that aren't going to change and assign them to people to review? (I can be a reviewer.)

**Comment by hannahkane** [comment]
I'm going to close this, since it's covered in the QA ticket.
