### ISSUE TITLE
Facebook share refers to "Network"

### ISSUE THREAD

**Issue by gvn** [mozilla/network#892]
This is what a share on FB will look like:

<img width="370" alt="screen shot 2017-11-07 at 9 03 04 am" src="https://user-images.githubusercontent.com/206379/32506850-83ef9988-c39a-11e7-813c-41de8c34ea52.png">

I'm assuming we should update the title and description to "Foundation" instead of "Network"? @xmatthewx @jessevondoom

**Comment by jessevondoom** [comment]
Let's do something simple:

Mozilla Foundation — Home
Mozilla is fueling a movement for a healthy Internet. See how a network of dedicated leaders and activists are working for a better Internet for all, connecting us to each other and to a better future.
