### ISSUE TITLE
Home Page Iteration - opportunities box

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#92]
**Context:**
Staff gave feedback about offering easy action to the audience. Currently the look and feel of our offerings space (in the home page) is very refined. It gives an idea that action is complicated and it is a big deal to take part of it.

**Actions:**
• do a simple wireframe of what are 3 formats for a “Feature activity/action” box could look like. 
Ideas: 2 polished vs 1 polished plus 2 bullets vs 3 bullets with more explanatory text. 

@hannahkane @xmatthewx @sabrinang

**Comment by taisdesouzalessa** [comment]
Iterations are here - **from slide 12 on**
https://docs.google.com/a/mozilla.com/presentation/d/1xSsiegCWf9e0H5kO-DWrBlHGYj4LU4zIKLewwByvdF0/edit?usp=sharing

**Comment by taisdesouzalessa** [comment]
After team discussion via InVision we decided to move on to a more refined version of proposals 1 , 2 and 3.2.

**Comment by taisdesouzalessa** [comment]
We decided to proceed with 2 options for further investigation:
- proposal 1 [Comp here](https://invis.io/ZJ9YTAGEA#/221865370_Home_Page_-_Offerings_V1)
- proposal 3.2 [Comp here](https://invis.io/ZJ9YTAGEA#/221865372_-_Home_Page_-_Offerings_V3_-)

ACTION ITEM:
- Taís to explore proposal 1 based on the feedback that the boxes looked related to each other. Suggestions from the team: iterate on a merge of 1+3 (promo box from the left, take action box on right) / make each box 50% of the page.

**Comment by taisdesouzalessa** [comment]
Explorations on proposal 1:

[Comp here](https://invis.io/ZJ9YTAGEA#/221908121_-_Home_Page_-_Offerings_V1-2_-)
<img width="498" alt="screen shot 2017-03-03 at 3 02 52 pm" src="https://cloud.githubusercontent.com/assets/22157921/23572228/801b9848-0022-11e7-89fa-bf1f43153951.png">

____

[Comp here](https://invis.io/ZJ9YTAGEA#/221908122_-_Home_Page_-_Offerings_V1-3_-)
<img width="489" alt="screen shot 2017-03-03 at 3 03 01 pm" src="https://cloud.githubusercontent.com/assets/22157921/23572232/829e20f4-0022-11e7-8b3e-9970f594734c.png">

** Image is just a placeholder. We will work on the image once direction is decided.**

Here are the options, based on our meeting today @hannahkane @xmatthewx @sabrinang

**Comment by xmatthewx** [comment]
I like the first option. I think it answer's the concern @hannahkane shared... as designed, I don't think these secondary actions feel like sub-task on the primary item. They feel separate to me. What do you think @hannahkane?

I think we can reduce the phrase to just "Other opportunities ~~to take action:~~"

**Comment by hannahkane** [comment]
Agree on both of your points, @xmatthewx.

I like this iteration.

**Comment by taisdesouzalessa** [comment]
Closing this ticket, merged it into a new one.
