### ISSUE TITLE
Information about staff creating new pages

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/network#93]
Branches off from this issue: https://github.com/mozilla/network/issues/42#issuecomment-281413815

We're trying to understand what the data/requirements might look like and how we would incorporate that into our CMS design.

A couple of questions we have about the non-bespoke pages:
- Which categories will these landing pages fall under? (offerings, news, etc.) Will some of these landing pages not fall under any specific category?
- How will navigation work for these landing pages? If an author creates a landing page that is independent from any of the main nav categories, how are they linked in the front-end / how are they made discoverable?
- What is the current format/structure of these landing pages? What kind of content will authors use (text, images, etc.)?

cc @xmatthewx 

@wex, @cadecairos @gvn anything to add to the above?

**Comment by hannahkane** [comment]
If answers are still needed, here's my best effort:

Gideon's question: Which categories will these landing pages fall under? 

Hannah's best attempt to answer: I believe the non-bespoke pages are limited to the "offerings" pages. There are other elements of structured data (people, news), but they aren't pages themselves.

Q: How will navigation work for these landing pages? If an author creates a landing page that is independent from any of the main nav categories, how are they linked in the front-end / how are they made discoverable?

A: The landing pages should all be within a path like /opportunities/new-page. Our current plan is to feature three of these at a time from the home page. Probably warrants a follow-up discussion to determine whether/how they're accessible when they're not in the current featured opportunities.

Q: What is the current format/structure of these landing pages? What kind of content will authors use (text, images, etc.)?
A: I believe this has been answered elsewhere, but let me know if not. (They look like [this](https://network.mofostaging.net/opportunity/training/).)

**Comment by hannahkane** [comment]
@gideonthomas - is more information needed? Can we close this ticket?

**Comment by xmatthewx** [comment]
thanks @hannahkane 

> What is the current format/structure of these landing pages? What kind of content will authors use (text, images, etc.)?

Authors should be able to:
 - Set page Title 
 - Set page Header
 - Add page content 
   - use basic html to format and style the copy (p, a, img, h2, ui, li, etc)
   - embed things like a youtube video. We can start with raw html and not worry wysiwyg at this stage
   - use inline styles if they want to get fancy 
 - Toggle to include sign-up form. If true:
   - Set form header string
   - Set form description string

**Comment by gideonthomas** [comment]
I think this might be useful for @Pomax too, so pinging him here. Thanks @hannahkane and @xmatthewx

**Comment by gvn** [comment]
For page content does Django CMS give us the option to use TinyMCE (or something similar) to edit a string?

Most of what @xmatthewx is outlining above is structured data. Page content is the exception.

**Comment by Pomax** [comment]
Mezzanine (a CMS on Django, but not Django-CMS, which is an actual project too =D) lets you define fields as being a TinyMCE content field.

**Comment by Pomax** [comment]
For the purposes of prototyping, I've filed https://github.com/mozilla/coss/issues/98 as an implementation test issue over on the CoSS repository (because that's where Mezzanine prototyping code currently lives)

**Comment by xmatthewx** [comment]
matthew to file any follow needed.

**Comment by xmatthewx** [comment]
this work is largely done. follow up conversations happening in other tickets.
