### ISSUE TITLE
Fix Github permissions

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/network#94]
Add mofo-staffonly and mofo-admin-staffonly to the contributor list with the appropriate permissions.

cc @gvn maybe?

**Comment by gvn** [comment]
I just added `mofo-admin-staffonly` with write access.

**Comment by gideonthomas** [comment]
any particular reason why?

Generally we do admin access for `mofo-admin-staffonly` and write access for `mofo-staffonly`

**Comment by cadecairos** [comment]
I've updated the permissions.
