### ISSUE TITLE
Refactor current Join Us as generic container

### ISSUE THREAD

**Issue by gvn** [mozilla/network#96]
@xmatthewx mentioned that we may want to retain the current Join Us UI (clicking the top nav button to trigger a pop out) as a container for general announcements. Join Us is currently being redesigned as a standalone page.

We can look into refactoring this to be enabled via a feature flag in the .env.

Putting this in the backlog for now.

**Comment by gvn** [comment]
CC: @alanmoo FYI

**Comment by gvn** [comment]
@xmatthewx Should we close this?

**Comment by xmatthewx** [comment]
I think yes. This ship has sailed.
