### ISSUE TITLE
URLs for Landing Pages

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#98]
Landing Pages will serve our ~~Offerings~~ Opportunities and, in the future, incoming traffic from Advocacy, Fellows etc.

@hannahkane proposes this URL structure. Looks good to me.

/opportunity/foobar
/opportunity/ → redirect home (for now)

**Comment by gvn** [comment]
@cadecairos How do we want to handle redirects given our hosting?

**Comment by hannahkane** [comment]
Is this still blocked?

**Comment by gvn** [comment]
Still waiting on an answer. @cadecairos any thoughts on my q above?

**Comment by cadecairos** [comment]
We can fairly easily use S3 redirect rules to send `/opportunity` and `/opportunity/doesnotexist` to the homepage

**Comment by gvn** [comment]
Cool, can you set that up?

**Comment by gvn** [comment]
Blocked pending discovery of how Mezzanine handles routes.

**Comment by cadecairos** [comment]
My plan here is to have someone duplicate the existing landingpages in mezzanine, and then we update the CDN to proxy requests to mezzanine.

- [X] Land 'landingpages' on staging
- [ ] Land 'landingpages' on production
- [ ] add existing pages to mezzanine as 'landingpage' contenttypes
- [ ] update the Cloudfront distribution so that `/opportunity` proxies to mezzanine

**Comment by xmatthewx** [comment]
@cadecairos – team suggests you add this redirect while working other related things today....

**Comment by alanmoo** [comment]
@cadecairos most of this is done, just the redirect at /opportunity/ that doesn't...redirect, right? It shows the homepage but the URL remains.

**Comment by cadecairos** [comment]
> @cadecairos most of this is done, just the redirect at /opportunity/ that doesn't...redirect, right? It shows the homepage but the URL remains.

This is done.

I used Cloudfront behaviours and S3 Redirect rules to implement the desired redirection.
